### ISSUE TITLE
Compilation failure  Building NVCC (Device) object CMakeFiles/cugraph.dir/src/cugraph_generated_grmat.cu.o

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cugraph#1]
I'm really keen to trying this as I use graphs extensively in my work. I've already implemented a simple GPU accelerated library using Numba, to use with Rapids, and would like to compare.

Unfortunately, the compile failed at the make stage due to missing header file:

```
[ 11%] Building NVCC (Device) object CMakeFiles/cugraph.dir/src/cugraph_generated_grmat.cu.o
/home/john/conda/cugraph/src/grmat.cu:35:10: fatal error: gdf/gdf.h: No such file or directory
 #include <gdf/gdf.h>
          ^~~~~~~~~~~
compilation terminated.
CMake Error at cugraph_generated_grmat.cu.o.cmake:219 (message):
  Error generating
  /home/john/conda/cugraph/build/CMakeFiles/cugraph.dir/src/./cugraph_generated_grmat.cu.o
```
I did also try
```
conda activate cugraph_dev
```
rather than 
```
conda activate
```
In the README, as thae former activates the (base) environment.

**Comment by dantegd** [comment]
It seems that that file is looking at the older version of the `cuDF` headers, I believe now it should read `cuDF.h` or `types.h` depending on what is trying to be included. CC @afender
