### ISSUE TITLE
[ENH] rename types and make them consistent

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1015]
- [ ] `VT, ET, WT` should be `vertex_t, edge_t, weight_t`, consider adding `result_t` as needed.
- [ ] consistently use `vertex, edge, graph` terminology instead of `node, link, network` in code and doc

**Comment by BradReesWork** [comment]
@afender are you adding an issue to address updating all the files?  Or is this just a note that we need to be consistent?

**Comment by afender** [comment]
It's more of a main tracker note as we agreed on applying the boy scoot rule for this effort.

**Comment by BradReesWork** [comment]
this basically says to follow the boy-scout rule.  Without a list of sub-tasks the EPIC really since able to be tracked.  Closing
