### ISSUE TITLE
[ENH] Consistent python formatting tool and configuration

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1016]
We should all use the same to avoid lengthy format changes between authors and facilitate reviews.

Initiated by https://github.com/rapidsai/cugraph/pull/963#discussion_r457526932

**Comment by BradReesWork** [comment]
@afender this sounds more like a documentation request rather than an feature.enhancement

**Comment by BradReesWork** [comment]
We are going to follow the boy scout rule (https://www.matheus.ro/2017/12/11/clean-code-boy-scout-rule/) for updating variable names®

**Comment by afender** [comment]
This is not really related to documentation or variable names.

This is more about the python formatting tool and configuration. In the past, we had PRs auto-editing hundreds of lines (like #963) because we don't have a common formating tool or configuration. So I think we should:
- [ ] agree on one like `Black` that I think Chuck is using too
- [ ] have all non-default settings (if any) published on the repo 
- [ ] run auto formating on all files

**Comment by kkraus14** [comment]
cuDF uses a combination of `Black`, `flake8`, and `isort` for automatic formatting / linting of Python code. If possible I'd suggest following what cuDF has set up so we can maintain consistent for RAPIDS libraries. We have plans to centralize the configuration but haven't had the spare cycles to do so for now.

**Comment by rlratzel** [comment]
Another checklist item for this issue should be:
- [ ] update `CONTRIBUTING.md`, like [cuDF has done](https://github.com/rapidsai/cudf/blob/branch-0.17/CONTRIBUTING.md#code-formatting).

**Comment by afender** [comment]
Closing after the last release discussion. The reformating problem has not shown up since then and everyone uses black or does the changes manually to comply with flake8.
