### ISSUE TITLE
[FEA] SNMG PageRank : Python tasks 

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#102]
The existing multi GPU PageRank code is currently in this fork/branch: https://github.com/afender/cugraph/tree/multi_pagerank. 

The following tasks have been identified

**System improvements**
- [x] Fix the conda env incompatibility for dask-cudf+cugraph in cugraph_dev env
- [x] Organize files properly under `dask/` directory rather than root directory
- [x] Add a new setup.py to be able to build and import dask-cugraph which should allow the following:
     - [x] Download and install dask-cudf automatically (in cugraph_dev env)
     - [x] Automatically point to your local cluster.json for `test_dask_cugraph.py` 
     - [x] Remove the need for the  `export PYTHONPATH=...` step.
- [x] Create a readme.md with instructions under `cugraph/dask`
- [x] Clean up the dask-cugraph python code

**Testing improvements**
- [ ] Add a test on larger data instead of using the small hardcoded one
- [x] Verify that dask-mpi does the expected MPI Rank<->GPU mapping (may need Corey's help for that)

**Comment by afender** [comment]
You can run `test_dask_cugraph.py` by doing the following:

(1) Build cugraph:
- Get the latest version of `multi_pagerank` branch and update the `cugraph_dev` conda env.
- Get the latest rmm . Currently :  `git checkout bab520d`
- Clean *all* previous build files and build cuGraph following the readme (build the python part too)

(2) Install dask-cudf in cugraph_dev env:
```
git clone https://github.com/rapidsai/dask-cudf
cd dask-cudf
pip install .
```
(optional) `pytest` : you should see some tests running.

(3) Run dask-cugraph test:
- `dask-scheduler --scheduler-file cluster.json`
- `mpirun -np 2 dask-mpi --no-nanny --nthreads 2 --no-scheduler --scheduler-file cluster.json`
- update `test_dask_cugraph.py` to point to your local directory
- `export PYTHONPATH=your_path_to_the_dir_of_dask_cugraph:$PYTHONPATH`
- `python test_dask_cugraph.py`

**Comment by afender** [comment]
I was able to verify that each MPI rank has its own PID and CUDA device in the C++ scope when called from `python test_dask_cugraph.py`.
Left code to print that when verbose mode is ON:
```
PID: 15267 - rank: 0 - dev: 0
PID: 15268 - rank: 1 - dev: 1
```

**Comment by Iroy30** [comment]
Added a setup.py to be able to build and import dask_cugraph, which installs dask-cudf as well and removes need to add PYTHONPATH. Cleaned up the desk_cugraph code. Further restructuring maybe needed.

**Comment by afender** [comment]
The dask-mpi-cugraph experimental solution has been integrated in PR #134 under dask-cugraph-beta branch. It still has limitations and known issues on large cases.
