### ISSUE TITLE
[FEA] SNMG PageRank : Benchmarking tasks

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#103]
The existing multi GPU PageRank code is currently in this fork/branch: https://github.com/afender/cugraph/tree/multi_pagerank.

- [x] Generate HiBench graphs for 1, 4, 8 and 16 GPUs (big data, giagantic and "even bigger" sizes for each). 
       [alternative] we can give a try to the "repartition" function of dask-cudf part after verifying that we can rely on this feature on multiple GPUs with dask-mpi.
- [x] check that the Notebook under `cugraph/python` is working 
- [x] Improve documentation and user experience in the Notebook
- [x] Add consistent performance output across dask/python/C++. We need to know the time of each step (total pipeline, sort, max, python call total, C++ call total, C++ coo2csr, C++ Pagerank). Write this in csv format so we can draw charts directly. Display these times in the notebook.
- [x] triple-check the dask-cudf sort -> found problems on larger cases
- [x] deploy https://github.com/afender/cugraph/tree/multi_pagerank on a DGX and run on the previously generated HiBench data.
- [ ] Record the memory requirement of the Bigdata size and identify the largest graph we can handle on the DGX2 with this implementation. Generate edge list files for a graph of this size.
- [ ] Gather HiBench results

**Comment by afender** [comment]
@seunghwak : timers are now in the cpp code returning in csv format on a single line. 

Define `MPR_BENCH` to enable it. When enabled, this is visible in the terminal output including at the dask_cugraph scope so you can add other timers to this same csv line. 

For reference, the format is :
```
coo2csr,min_pr_spmv,max_pr_spmv,min_pr_comms,max_pr_comms,min_pr_transfers,max_pr_transfers,total_csr_pagerank,total_cpp,
```

**Comment by seunghwak** [comment]
Regarding "triple-check the dask-cudf sort"

dask-cudf.sort_values_binned() function

properly sorts data based on the primary key and binning is working but this is not a stable sort (does not preserve the original order among the values with a same primary key).

Also, memory footprint (on CPU side) becomes very large (to process 3 GB input graph in ASCII format, it goes as high as 30 GB) and sorting data of this size takes minutes.

**Comment by seunghwak** [comment]
Regarding 
"check that the Notebook under cugraph/python is working"
 "Improve documentation and user experience in the Notebook"

Updated the notebook file (python/notebooks/dask_mpi_pagerank_demo.ipynb) and it does what the corresponding python script does (dask/test_dask_cugraph_pagerank.py, fails with the same error message inside dask_cugraph.mg_pagerank()).

**Comment by afender** [comment]
>dask/test_dask_cugraph_pagerank.py, fails with the same error message inside dask_cugraph.mg_pagerank()

@seunghwak what error message do you get inside `dask_cugraph.mg_pagerank()`? Is `test_dask_cugraph.py` failing for you?

**Comment by seunghwak** [comment]
test_dask_cugraph.py works.

in _get_mg_info
    worker = parse_host_port(first(workers))
  File "/home/seunghwak/Program/anaconda3/envs/pagerank_demo/lib/python3.7/site-packages/toolz/itertoolz.py", line 368, in first

It seems like this happened even before starting actual pagerank and happened during parsing Dask workers... Let me take a little more look.

Full Error Message:
(pagerank_demo) seunghwak@seunghwak-linux:~/RAPIDS/pagerank_demo_cugraph/dask$ python test_dask_cugraph_pagerank.py 
Initializing.
Read Input Data.
Sort Input Data.
Compute PageRank.
Traceback (most recent call last):
  File "test_dask_cugraph_pagerank.py", line 55, in <module>
    pr = dcg.mg_pagerank(dgdf)
  File "/home/seunghwak/RAPIDS/pagerank_demo_cugraph/dask/dask_cugraph/pagerank.py", line 37, in mg_pagerank
    gpu_futures = _get_mg_info(X_df)
  File "/home/seunghwak/RAPIDS/pagerank_demo_cugraph/dask/dask_cugraph/pagerank.py", line 70, in _get_mg_info
    worker = parse_host_port(first(workers))
  File "/home/seunghwak/Program/anaconda3/envs/pagerank_demo/lib/python3.7/site-packages/toolz/itertoolz.py", line 368, in first
    return next(iter(seq))
StopIteration

**Comment by afender** [comment]
Ok please work with Ishika to identify where the problem is. This should be related to how the pipeline work in the notebook as `test_dask_cugraph.py` successfully calls the operation that is causing issues here.

I had a look at the notebook, the part on how to launch dask scheduler and workers is a big paragraph that has a lot of test and code mixed (unless it doesn't display properly on my machine, I attached a screenshot). It is not really a high priority but I'll leave the box unchecked at the end so that we remember to clarify it later. 
<img width="876" alt="screen shot 2019-03-06 at 6 59 45 pm" src="https://user-images.githubusercontent.com/45606510/53924647-7ebf5b80-4042-11e9-8c36-ef5e2f52ab9b.png">

**Comment by afender** [comment]
Benchmark on HiBench input is done. 

The SNMG Pagerank code based on PRBench has been integrated in dask-cugraph-beta branch in PR #134. It still has known issues.
