### ISSUE TITLE
[FIX] Katz centrality test on asymmetric directed graph produces different results than NetX

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1042]
When the `email-EU-core.csv` dataset is used in the python katz centrality test (`python/cugraph/tests/test_katz_centrality.py`), cugraph and NetX produce a different set of top-10 vertices and the test fails.

The test failure can be reproduced using a much smaller dataset of just 11 vertices:
```
0 1 1.0
1 2 1.0
2 3 1.0
2 4 1.0
2 5 1.0
5 6 1.0
5 7 1.0
5 8 1.0
8 9 1.0
8 10 1.0
```
and a debug print shows the differences:
```
sorted by top 10 for nx_katz
     cu_katz  vertex   nx_katz
9   0.000000       9  0.310307
10  0.000000      10  0.310307
6   0.000000       6  0.310080
7   0.000000       7  0.310080
8   0.327174       8  0.310080
3   0.000000       3  0.309170
4   0.000000       4  0.309170
5   0.572554       5  0.309170
2   0.633900       2  0.305533
1   0.322062       1  0.290984
sorted by top 10 for cu_katz
    cu_katz  vertex   nx_katz
2  0.633900       2  0.305533
5  0.572554       5  0.309170
8  0.327174       8  0.310080
1  0.322062       1  0.290984
0  0.244102       0  0.232787
3  0.000000       3  0.309170
4  0.000000       4  0.309170
6  0.000000       6  0.310080
7  0.000000       7  0.310080
9  0.000000       9  0.310307
FAILED
```

**Comment by seunghwak** [comment]
I think we can revisit this problem once the pattern accelerator API PR is merged (https://github.com/rapidsai/cugraph/pull/838/files#diff-96caec535db6a41418a5a555e0109f90, hopefully before the end of the 0.16 release).

IIRC, the current cuGraph Katz Centrality is based on Hornet which adopts a different math than NetworkX. The new implementation based on the pattern accelerator API more faithfully follows the NetworkX, so the difference should be minimal.

**Comment by BradReesWork** [comment]
The latest code does a much better job are matching Nx results.  For the `email-EU-core.csv` dataset, on an Undirected graph, the top 10 exactly match.  The top 20 has a pair of vertices id different order (90%) match.

For a directed graph, we by default compute the out-edge Katz centrality while NetworkX compute the in-edge Katz centrality.  By first calling NetworkX Gnx.reverse() to flip the edges, the out-edge Katz can be computed which yields the same results

**Comment by BradReesWork** [comment]
We need to document this

**Comment by seunghwak** [comment]
Our python SG katz centrality calls the legacy version of Katz Centrality. The new version runs the same algorithm as NetworkX and the results should match. We should update python SG katz to call the new version.
