### ISSUE TITLE
[FIX] Triangle counting test on asymmetric directed graph produces different results than NetX

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1043]
When the `email-EU-core.csv` dataset is used in the python triangle counting test (`python/cugraph/tests/test_triangle_count.py`), cugraph and NetX produce a different number of counted triangles and edge vals.

A debug print of the counts returned by both implementations for the above dataset shows the difference:
```
cu count: 367140, nx count: 316383
```

**Comment by pgera** [comment]
I'm seeing some issues with symmetric graphs too. At least tcount_b2b() seems to have issues. From my limited testing, tcount_wrp() appears to be producing the correct output. Test case: com-orkut, which should have 627,584,181 triangles [1] (or times 3 in case of cugraph). I can get this number if use tcount_wrp, not tcount_b2b, which is what is selected based on the avg. degree. Another test that fails is that graph permutations should return the same output, which is also currently broken for tcount_b2b.

[1]: https://ieeexplore.ieee.org/document/8000612

**Comment by rlratzel** [comment]
NOTE: triangle counting is being refactored to use a new graph primitive, which could result in this issue getting resolved.
cc @seunghwak @BradReesWork

**Comment by seunghwak** [comment]
The new triangle counting works only on undirected graphs, and it will throw an exception instead of returning an inaccurate result.

**Comment by seunghwak** [comment]
And I am not sure NetworkX really supports triangle counting on directed graphs.

See
```
@not_implemented_for("directed")
```
https://github.com/networkx/networkx/blob/58b63cb57cd1747c23611ee0b46991a5be2db751/networkx/algorithms/cluster.py#L19

And
```
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edge(1,2)
>>> G.add_edge(2,3)
>>> G.add_edge(3,1)
>>> nx.triangles(G)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seunghwak/Program/anaconda/envs/cuda115-cugraph/lib/python3.8/site-packages/networkx/utils/decorators.py", line 816, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 3, in argmap_triangles_1
  File "/home/seunghwak/Program/anaconda/envs/cuda115-cugraph/lib/python3.8/site-packages/networkx/utils/decorators.py", line 86, in _not_implemented_for
    raise nx.NetworkXNotImplemented(errmsg)
networkx.exception.NetworkXNotImplemented: not implemented for directed type

**Comment by seunghwak** [comment]
To support triangle counting on directed graphs, we should define what triangles mean in directed graph first.

Should we consider only a->b, b->c, c->a or is a->b, a->c, b->c also a triangle?

**Comment by BradReesWork** [comment]
Re-evaluate after #2671

**Comment by BradReesWork** [comment]
The triangle counting algorithm was update in a cuGraph release and now produces the same answer as NetworkX
