### ISSUE TITLE
[FIX] Asymmetric directed graph input causes NetX call to fail in test_core_number test

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1045]
Adding `email-EU-core.csv` to the set of inputs to the `test_core_number` test causes NetworkX to raise an exception which fails the test:
```
E           networkx.exception.NetworkXError: Input graph has self loops which is not permitted; Consider using G.remove_edges_from(nx.selfloop_edges(G)).
```

**Comment by BradReesWork** [comment]
NetworkX core number does not support graphs with self loops.  That is not a cuGraph issue to fix
