### ISSUE TITLE
[FIX] Asymmetric directed graph input causes NetX call to fail in test_k_core DiGraph test

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1046]
Adding `email-EU-core.csv` to the set of inputs to the `test_k_core.py::test_core_number_DiGraph` test causes NetworkX to raise an exception which fails the test:
```
E           networkx.exception.NetworkXError: Input graph has self loops which is not permitted; Consider using G.remove_edges_from(nx.selfloop_edges(G)).
```

**Comment by BradReesWork** [comment]
NetworkX Core Number does not support graphs with self loop.  Need to select a different dataset.  This is a valid Nx error
