### ISSUE TITLE
[ENH] MNMG Renumbering including sort optimization

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1048]
in support of 2D partitioning.
Support |V| > 2 billion

**Comment by seunghwak** [comment]
It will be great if you can test this implementation with the dataset in http://webdatacommons.org/hyperlinkgraph/

http://webdatacommons.org/hyperlinkgraph/2012-08/download.html#toc0

The above link has preprocessed Common Crawl Data (the original raw data can be found form https://commoncrawl.org/). Sometime in the future, it will be great if we can demonstrate the entire pipeline starting from raw data using cuDF + cuGraph.

**Comment by BradReesWork** [comment]
closed by PR #1081
