### ISSUE TITLE
[ENH] Update CMake to use FetchContent

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1075]
Scrambling to get cuda11 working in 0.15 resulted in adding FetchContent to get CUB and THRUST from git instead of using the version in the cuda library.

FetchContent is an alternative to ExternalProject with the advantage that the content is downloaded at configuration time instead of at build time.  The FetchContent approach was borrowed from cudf.

Several internet articles suggest NOT mixing FetchContent with ExternalProject.  It would be helpful to evaluate the best approach and either migrate everything to FetchContent or migrate everything to ExternalProject.

As an alternative, cuCollections suggests in their README using https://github.com/TheLartians/CPM.cmake, which is a wrapper around FetchContent that might make things easier.

**Comment by BradReesWork** [comment]
closed by #1367
