### ISSUE TITLE
[ENH] Restructure clustering software

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1092]
The Louvain, Leiden and ECG code all share components.  The current configuration of the C++ code is awkward.  We should restructure the software to move common pieces into separate files so that the files aren't calling things defined in other algorithms.

This could also improve some of the templating awkwardness.

**Comment by afender** [comment]
We could also use consistent terminology and select between `clustering`, `partitioning`, and `community detection ` both for code and public doc.
