### ISSUE TITLE
[ENH] Document which algorithms work on which graph types and formats

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1095]
We have inconsistent documentation about which algorithms work on which graph types (e.g. directed, undirected, with self-loops, with multi-edge, etc).  Some of the algorithms properly raise exceptions when the wrong type is presented.

This problem is about to get worse for MNMG since the graph data structure (CSR-like or CSC-like) will be much more expensive to construct.

We should identify a good way to document the behavior of the graph algorithm implementations against different graph types and structures, and make sure that at the python layer all checks are documented and evaluated correctly.

**Comment by ChuckHastings** [comment]
Relative priority of this may shift.  Focus in 0.16 will be on undirected Graph, so perhaps this can be deferred until we look at the other graph types.

**Comment by BradReesWork** [comment]
OBE until new graph classes are finished
