### ISSUE TITLE
[QST] Does cugraph.Graph.sets for bipartite graphs partitions in a consistent order?

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [rapidsai/cugraph#1099]
I'm attempting to use the bipartite graph functionality provided in `cugraph` version `0.15` (but not in `0.14`) and have questions about whether or not `cugraph.Graph.sets` returns the partitions in the same order on different calls. 

I was looking at the [implementation of `cugraph.Graph.sets`](https://github.com/rapidsai/cugraph/blob/branch-0.15/python/cugraph/structure/graph.py#L267), and it looks like the order that the partitions of a bipartite graph get returned in depends on the order of in which `self._nodes.keys()` returns the partition labels. My understanding is that Python's `dict.keys()` doesn't guarantee that the keys are returned in a consistent order. Since the graph is bipartite, this may not be a problem in practice if the size of `self._nodes` is approximately 2 since `dict.keys()` will most likely but not guaranteed to consistently return keys in the same order. 

Is it guaranteed that `cugraph.Graph.sets` will return the partitions in the same order for the bipartite graph case? If not, would there be a way of getting the labels for the partitions? A workaround would be to use the multipartite functionality even when we only have a bipartite graph so that `cugraph.Graph.sets` returns a `dict` with the partition labels. 

It's likely that I'm misunderstanding something. 

I would be happy to explore this problem on my own in order to find a demonstrable example of where this concern shows a problem as soon as `cugraph` version `0.15` is available on `conda-forge`.

**Comment by Iroy30** [comment]
@paul-tqh-nguyen If I understand correctly, you are concerned regarding the consistency of the order in which the bipartite sets are returned in multiple calls. Starting from python 3.6, the dict preserves the order of insertion. So, dict.keys() will return the partition labels as inserted, being consistent on multiple calls. Hopefully that answers your question.

**Comment by paul-tqh-nguyen** [comment]
Yes, that does answer my question completely! Thank you for getting back to me.
