### ISSUE TITLE
[ENH] `cugraph` code quality improvement

### ISSUE THREAD

**Issue by aschaffer** [rapidsai/cugraph#1107]
This issue will be used to track code quality in `cugraph` 0.16. Work on this will span more than one PR. 
Some more immediate fixes are:

(1.) Replace all raw pointers by more informative `device_ptr<>`, `device_vector<>`, or `std::vector<>`, `host_vector<>`;

Wherever raw pointers are passed to thrust algos, `device_ptr<>` can be passed instead from both host and device callers.
#
# Example:
#
```
rmm::device_buffer frontier(n_bytes);
thrust::device_ptr<T> d_frontier_ptr{static_cast<T>(frontier.data())};
//...
// call thrust algo directly on device_ptr:
//
thrust::fill(d_frontier_ptr, d_frontier_ptr + n_bytes/sizeof(T), 0);
```

(2.) Replace custom loops by transforms(), etc.

(3.) insert `rmm::exec_policy(stream)->on(stream)` execution policy in all algorithms; 

(4.) Use `const` qualifiers to explicitly separate input from output parameters in functions;

(This list is not yet exhaustive, more things will be added to be addressed).

**Comment by aschaffer** [comment]
> 
> 
> This may not apply to .hpp files (for non-owning cases and to interface with python). To get data owned by python in cuDF DataFrame and/or Series, we may still need to resort to raw pointers.

Okay, so we will _not_ be following `cudf`'s approach here of passing: 
(a) `column_view`'s and returning `std::unique_ptr<column>`; 
or, 
(b) passing `table_view`'s and returning `std::unique_ptr<table>`

Right? It's okay, I just need us to agree how drastically we want to change our code. If we want to keep an API that takes raw pointers for the sake of not touching the Python API, then that's fine, I just need to understand what drives the changes we want or don't want to do in our code.

**Comment by BradReesWork** [comment]
closing since this should be a general thing and there are no defined subtasks
