### ISSUE TITLE
[QST] Does cugraph support graphs with larger than GPU memory

### ISSUE THREAD

**Issue by msharmavikram** [rapidsai/cugraph#1128]
I have a few graphs consuming about 40-80GB in binary representation (only edges). I would like to run some graph analytics applications on these graphs. I am new to cugraph and wondering if my V100-32GB GPU would be able to run with cugraph or do I have to make changes to cugraph to enable unified memory or zero-copy memory? 

(also reading from prior discussed PRs https://github.com/rapidsai/cugraph/issues/955 , I see changes required to enable int64 or uint64 data types. I am using cugraph master branch and I believe these fixes are in-place. correct me if wrong.)

**Comment by kaatish** [comment]
Hi, please take a look at the notebook written by @afender [here](https://github.com/rapidsai/cugraph/blob/branch-0.16/notebooks/demo/uvm.ipynb). Using unified memory with cugraph should be possible unless I am mistaken. Having said that you should be aware that there could be a few intermediate steps required to preprocess your graph which could require more combined memory than that taken by the graph.

**Comment by msharmavikram** [comment]
Thanks for the response. I am more interested in the C++ code. As long as C++ supports it, I am all good. 

I am interested in running following algos on a large graph: betweenness, ktruss, spectral clustering, triangle counting, BFS, CC, SSSP, pagerank, and overlap similarity

**Comment by BradReesWork** [comment]
@msharmavikram as @kaatish mentioned, you can use unified memory to scale beyond the memory limitation of a single GPU. All the algorithm you mentioned will run with Unified memory.
