### ISSUE TITLE
[QST] Any way to run on Kepler or Maxwell GPUs?

### ISSUE THREAD

**Issue by arvindshmicrosoft** [rapidsai/cugraph#1130]
Hello! I did read the notes that cuGraph needs Pascal or above. However, given Kepler and Maxwell GPU availability is still higher than Pascal / Volta or Turing, it would be great from an adoption point of view to allow running with lower CUDA compute capability (of course with caveats around newer features like memory oversubscription etc. not being available). A quick test on a K80 reveals the below error:

```
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
```

Is anything possible? By building from source etc.?

**Comment by BradReesWork** [comment]
@arvindshmicrosoft the code leverage features found in the newer GPUs.  
The joy of open-source is that you can download the source, modify the build scripts, and give it a try. but there are function calls that might need to be refactored as well.

**Comment by arvindshmicrosoft** [comment]
Thank you @BradReesWork . I am prepared to do that - if you have any hints around where I should be looking to check for the compute capability specific items, that would be a bonus.

As further background, I was experimenting with this on Azure and later on Collab. In the case of Collab, you randomly get assigned a GPU SKU, so sometimes you get lucky and get a P100 or later. Most of the time (based on my limited tests) I was unlucky and got a K80, in which case the out-of-box samples fail to load an appropriate kernel as I mentioned originally. So adoption-wise, having options which would work on Kepler would be fantastic.

**Comment by BradReesWork** [comment]
@arvindshmicrosoft not really.  take a look at the cuSignal build script since that package covers more arch types.
