### ISSUE TITLE
[ENH] Triangle counting implementation is loose on types

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1140]
The Triangle Counting implementation is inconsistent on how it uses types.  It sometimes uses signed types and sometimes uses unsigned types.  It largely ignores the vertex_t and edge_t defined by the graph.

This manifests itself as an irritating compiler warning message about type conversion:

```warning: invalid narrowing conversion from "int" to "unsigned long"```

**Comment by BradReesWork** [comment]
being closed.  We are redoing TC which will drop the need for this change
