### ISSUE TITLE
[ENH] Remove from_cudf or form_dask_cudf references in methods

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cugraph#1141]
**Describe the solution you'd like**
Hi!

I have noticed that some methods contain the data type within the method name.

- from_cudf_adjlist(offset_col, index_col[, …])
- from_cudf_edgelist(input_df[, source, …]) 
- from_dask_cudf_edgelist(input_ddf[, source, …]) 

I'd propose a different to remove cudf and dask_cudf references in the method name, ending something like this:

- from_adjlist(offset_col, index_col[, …])
- from_edgelist(input_df[, source, …]) 
- from_edgelist(input_ddf[, source, …]) 

I think the data type could be inferred from the parameter passed, and that would allow keeping the method name while adding new data types support to those methods, like pandas, numpy, cupy, dask...

Hope it helps!

Regards,
Miguel

**Comment by BradReesWork** [comment]
@miguelusque This is a great suggestion and in-line with where we are going.  The plan is to start supporting more data types and dropping the type name from the function name will both simplify the function name and reduce having a function per type.

**Comment by BradReesWork** [comment]
Agree that generic function should be added.   But the old function with data type names ( from_pandas...) need to be retained for API compatibility with Nx and other frameworks.
