### ISSUE TITLE
[BUG] cuGraph functions not compatible with NetworkX functions

### ISSUE THREAD

**Issue by ericmjl** [rapidsai/cugraph#1143]
**Describe the bug**

Today, I test-drove cuGraph with the thought that I could drop-in replace it for NetworkX.

This minimal example failed:

```python
import cugraph as nx

G = nx.Graph()

G.add_node("a")
```

It appears that the NetworkX class methods are not fully supported yet, which means I'm still not able to `import cugraph as nx` confidently.

I think a NetworkX user would want the ability to to manipulate the graph node-by-node. Yes, this doesn't follow a "vectorized" way of working, which is what GPUs are intended to be used for, but being able to directly manipulate the graph is super important for building confidence in using a graph library.

**Comment by datametrician** [comment]
But you can do that in networkx. I think we should be clearer that cuGraph is really meant for the algorithms not every graph function. 
If you adding a bunch of nodes serially I would say use networkx and when you’re ready to do pagerank or BFS or some other algo copy the data to the GPU which is relatively fast.

**Comment by ericmjl** [comment]
@datametrician thanks for the clarification - yes, this needs to be made much clearer in the docs, then.

Is there a technical difficulty in reimplementing the flexible NetworkX graph data model on GPUs? I'm not very well-versed in GPU programming, but from @quasiben I heard NVIDIA engineers are pretty good at solving this class of "oh we thought GPUs aren't good for this" kind of problems.

**Comment by ericmjl** [comment]
Following up on a Twitter backdoor thread that I had with @datametrician.

Looks like my expectations were incorrect about cuGraph - that this is intended to be an accelerated graph algorithms library, and not a drop-in replacement for NetworkX, can I confirm this with the rest of the team?

The starting point for my seemingly trivial example is actually deeper than it might seem. The ability to manipulate a graph on-the-fly is super important for interacting with graphs. And as someone who is a seasoned NetworkX user, I came in to cuGraph expecting to be able to use cuGraph graphs the way I use NetworkX graphs too, like adding nodes and edges on-the-fly and the likes. `import cugraph as nx` and then instantiating graphs on-the-fly and manipulating them would help with transferring knowledge for everyone that I teach NetworkX to. But if simply _accelerated algorithms_ is the goal, then that's totally cool! :smile:. In that case, maintaining compatibility with NetworkX _graph objects_ would help a lot with the case for using cugraph.

I test-drove exactly that point, and in the spirit of putting up reproducible examples, you can see a [gist](https://gist.github.com/ericmjl/d34d0e1a018add97fa7621f9fcfc657f) that I wrote. 

It's clear to me that cuGraph expects a bunch of data structure API calls that aren't present on NetworkX graphs. That's cool, they probably exist only in cuGraph for a good reason, or at least for historical reasons, someone had to make some decision somewhere. However, not being able to pass in a NetworkX graph into a cuGraph function induces an activation barrier to using cuGraph's functions.

To get around that, I also tried constructing cuGraph objects from NetworkX objects by manually constructing the edge list. In the gist, I have one suggested function that can naively convert NetworkX graphs into cuGraph objects, which would allow cuGraph functions to accept NetworkX graphs. (That function probably needs some work though.)

**Comment by seunghwak** [comment]
Thank you very much for writing this, and

We may not add a single vertex or a single edge to the GPU graph data structure, but we can store graph updates in a buffer and execute bulk insertions and deletions (adding one vertex or one edge has comparable computational cost to adding multiple vertices and edges at once).

I think we can make this buffering invisible to end-users.

We have discussed this internally several times and supporting bulk insertions/deletions is in our long-term roadmap (we have other higher priority tasks at this moment). @BradReesWork can comment more about our plan.

**Comment by datametrician** [comment]
I've synced with @BradReesWork this morning.
Accepting NetworkX graphs is going on our roadmap.
The goal should be anytime a networkx user calls an algorithm for starters (potentially could expand in the future), they can just replace that call with cuGraph and it works or sends a message saying not supported use networkx (no code change).

**Comment by BradReesWork** [comment]
@ericmjl   Thank you for positing, and kudos on using datasets from Moreno in your notebooks.  I think too many folks don’t appreciate all the foundational work that he did.  

cuGraph is working towards better NetworkX compatibility, and every release we get closer.  
The one area where we still have a long way to go is captured in your statement: “_I think a NetworkX user would want the ability to to manipulate the graph node-by-node_”.  That disconnect, IMHO, stems from our initial focus being on scale.  Adding and manipulating individual nodes starts becoming problematic as the number of nodes explodes into the millions and billions.  However, we do need a way to bounce between macro scale analytics and micro scale – for instance, once a smaller subgraph is extracted.  

This release will include the ability for cuGraph to accept NetworkX graph objects.  From there we will start thinking about how to better handle adding and manipulating single nodes and edges.  

Please continue to submit issues so that we can get better.
