### ISSUE TITLE
[ENH] [Testing] DATASETS_UNDIRECTED points to files that store edges in both directions

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1160]
DATASETS_UNDIRECTED points to files with directed edges in both directions: https://github.com/rapidsai/cugraph/blob/84df6353f888899c7873b0f7ac5336d5a306a0c3/datasets/karate.csv#L79

We should use files that contain undirected edges (ie. where there is not necessarily a `v -> u` stored in the file for each ` u->v` ) and let cugraph deal with it to properly test the `Graph` structure path.

**Comment by BradReesWork** [comment]
All test datafile, and the complete test framework, will be redone over the next few releases.  
This issue is already captured in that refactoring tasks
