### ISSUE TITLE
[ENH] depth limits on BFS and SSSP

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1171]
Limit the depth of the search in traversals like in NX

**Comment by seunghwak** [comment]
See

https://github.com/rapidsai/cugraph/blob/branch-0.16/cpp/src/experimental/bfs.cu#L173
https://github.com/rapidsai/cugraph/blob/branch-0.16/cpp/src/experimental/sssp.cu#L249

This will be done once we use the pattern accelerator based version for both SG & MG, I think this will happen in the next release after performance & memory footprint tuning.

**Comment by BradReesWork** [comment]
PR #1532 addressed the BFS portion of this issue
