### ISSUE TITLE
[FEA] Travelling Salesman Problem (TSP) and/or Hamiltonian path

### ISSUE THREAD

**Issue by jannisborn** [rapidsai/cugraph#1185]
**Is your feature request related to a problem? Please describe.**
Is there any plan to integrate NP algorithms like finding Hamiltonian paths or solving the TSP?

**Describe the solution you'd like**
A function that you can call with an undirected, possibly weighted graph and a starting node that returns the solution to the TSP.

**Additional context**
`networkx` implementation of TSP is pretty slow, so this would be a great feature, I think.

**Comment by BradReesWork** [comment]
@jannisborn TSP is on the roadmap for roughly the January 2021 release.  We have been doing a lot of research in that areas and are now ready to make it available.  

Hamiltonian paths is something that we have discussed but has not made it onto the roadmap for a specific release

**Comment by jannisborn** [comment]
@BradReesWork that sounds fantastic!
for the TSP, I think it would be great if an option would be included to, unlike the original TSP, **_not_** return to the source node. This would be identical to finding the shortest Hamiltonian path for a given source node. 
Otherwise thanks a lot for the great work! Loooking forward to the 2021 release and please feel free to close if applicable.

**Comment by BradReesWork** [comment]
@jannisborn breaking your feature request into two part - TSP will be in the current 0.18 release that we are workign on.   Hamilton paths a little later

**Comment by BradReesWork** [comment]
closed by #1360
