### ISSUE TITLE
[FEA] MG test infra on Prometheus

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1203]
We need to better automate MG testing

Please take a look at https://github.com/rapidsai/cuml/issues/1896

Running the tests checking correctness is the top priority (`python/cugraph/tests/dask/*`).
Then we should also take care of #1085

**Comment by rlratzel** [comment]
Similar to [cuML](https://github.com/rapidsai/cuml/issues/1896#issuecomment-662509200), code is available [here](https://gitlab-master.nvidia.com/rratzel/cugraph-testing/-/tree/main).
