### ISSUE TITLE
[ENH] Replace the legacy graph class with the new graph class.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#1207]
We currently have both the legacy & new experimental graph classes.

https://github.com/rapidsai/cugraph/blob/branch-0.16/cpp/include/graph.hpp
https://github.com/rapidsai/cugraph/blob/branch-0.16/cpp/include/experimental/graph.hpp

The old graph classes need to be replaced to remove redundancy in our code-base.

The new graph class provides accesses to offsets, indices, and weights arrays to support this transition.

**Comment by BradReesWork** [comment]
OBE
