### ISSUE TITLE
[FEA] MG renumbering in CUDA

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1215]
We currently leverage python and (dask)cudf for renumbering. 
While this has a number of advantages, this prevents doing specific optimizations that would enable support for bigger input.
This is currently the MG scalability bottleneck

### Scope
- Memory efficiency: the goal is to be as close to optimal as possible. Scale is the top priority.
- Feature: String and random numeric IDs. Note : string resolution mechanic should probably remain at python level to leverage cudf (one option is to map them to integer and pass these to c++ renumbering). 
- Performance: faster than the python layer version and faster than analytics like Pagerank.

**Comment by BradReesWork** [comment]
closed by #1268
