### ISSUE TITLE
[ENH] null values

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1218]
The null value concept ([as seen in cudf](https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html#Null-Handling-in-UDFs)) is not supported in cuGraph. 

Support for null values should be added in the future. 
We would most likely have a policy for handling null values in `from_cudf_edge_list` at the time it loads the df to create a graph.

**Comment by BradReesWork** [comment]
duplicated in #1372 which is schedule in 21.12
