### ISSUE TITLE
[FEA] Label propagation graph primitive patterns

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1225]
The current implementation of graph primitives doesn't cover that.
Label propagation is a recurring pattern for analytics going from Louvain to MST.

**Comment by antonyscerri** [comment]
Hi

I'm curious about this ability. I was looking for something similar to networkx's networkx.algorithms.node_classification.hmn.harmonic_function for propagating labels. It doesnt look like RAPIDS currently has anything like this out of the box, and as of now i'm unclear if there is anything which can easily be used to build a user defined process (message passing, map reduce, sparse matrix) directly on top of existing functionality. The closest may be to attempt a user defined function with cuDF. 

Any pointers to suitable entry points (or some existing feature i've overlooked) to creating something like this without the need to write a lower level cugraph implementation.

Thanks

**Comment by BradReesWork** [comment]
closing - work is being picked up under a new issue
