### ISSUE TITLE
[BUG] Graph object has no attribute add_edge_list

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cugraph#1231]
**Describe the bug**
Graph object has no attribute add_edge_list

**Steps/Code to reproduce bug**
From an example provided in the documentation of cugraph.structure.symmetrize.symmetrize(). Also, `add_adj_list()` no longer exists but still in the docs.

```
src, dst, val = cugraph.symmetrize(edges['source'], edges['target'], edges['value'])
G = cugraph.Graph()
G.add_edge_list(src, dst, val)
```

**Expected behavior**
Edges are created from 3 lists

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuGraph install: Docker
   - latest from rapids-nightly, v 0.16

**Comment by BradReesWork** [comment]
All references to "add_edge_list" from been dropped from documentation
