### ISSUE TITLE
Many to Many Dijkstra, Map Matching etc. [QST]

### ISSUE THREAD

**Issue by karatemir** [rapidsai/cugraph#1283]
I am currently using pgRouting/Postgis for Map Matching purposes and pretty much the computational bottleneck is the many-to-many Dijkstra routing between candidate road segments. 

I thought about using CuGraph/CuSpatial as an accelerated alternative and some quick search led me to [this](https://portal.opengeospatial.org/files/?artifact_id=90339) presentation from 2019. Here it is stated that Map Matching/Dijkstra/Routing is considered as functionalities to be implemented in 2020. I haven't found much about these functionalities anywhere else. I would be grateful if any of you guys can point me towards relevant info. Also is it possible to do many-to-many shortest-path search as of now?

**Comment by afender** [comment]
Hi @karatemir,
Thanks for your question. At the moment the way to do this is to call an SSSP for each source. This is not optimal, but if you have multiple GPUs you may consider distributing the work like in the batched betweenness centrality feature https://docs.rapids.ai/api/cugraph/nightly/dask-cugraph.html#batch-processing
We also have a more efficient native ASSP feature on the long term road map: #329

**Comment by mickvanhulst-TomTom** [comment]
My apologies if you prefer separate issue creation, but I was wondering if anything has changed in the meantime related to the roadmap for map matching and routing.

Would be great to understand if anything related to map matching, Dijkstra, and/or routing is currently on the roadmap.
