### ISSUE TITLE
[QST] Support for BFS Predecessors

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cugraph#1300]
Hey all. I tried using cugraph this week for the first time. For fun I've been trying to work through [Advent of Code](https://adventofcode.com/) this year but [trying to do as much computation as possible on the GPU](https://github.com/jacobtomlinson/advent-of-gpu-code-2020). The challenges in AoC are not especially performance bound, so using a GPU is generally overkill. But this has been a fun learning experience so far.

[Yesterday's challenge](https://adventofcode.com/2020/day/7) was a graph problem. I'm not hugely familiar with solving graph problems in Python (or at all really) so I saw this as a fun opportunity to look into `networkx` and `cugraph`.

The first part involved creating a digraph and then for a given node you had to find all of the possible start nodes from which you could traverse to that node.

For [my solution](https://github.com/jacobtomlinson/advent-of-gpu-code-2020/blob/main/solutions/07/07%20Solution.ipynb) I used `nx.bfs_predecessors`. However I was unable to find an equivalent method in `cugraph`. So I was curious whether this kind of thing would be possible in `cugraph`.

The second part of the challenge involved starting from a specific point and traversing all the way to the extremeties multiplying the edge weights as you went. I ended up implementing this as a recursive Python function which traversed the `networkx` data structure. But again I was curious whether I would be able to do this in `cugraph`.

**Comment by afender** [comment]
Hi @jacobtomlinson,

The BFS implementation in cuGraph returns predecessors natively (so does SSSP). More information on this in the doc : https://docs.rapids.ai/api/cugraph/nightly/api.html#module-cugraph.traversal.bfs
Basically, you should find` df[‘predecessor’] `   in the returned dataframe. It contains, for each i’th position in the column, the vertex ID immediately preceding the vertex at position `i` in the ‘vertex’ column. 

We should probably add a `bfs_predecessors` wrapper on top of our API that redirects to this feature for Nx users. I created an issue for that : #1301


Regarding traversing while multiplying, this is something that can be done with our graph primitives at the CUDA level at the moment but this API is not yet exposed in python. Related issues are : #1210 #1211. 

Hope that helps and please let me know if you have further questions

**Comment by jacobtomlinson** [comment]
Thanks @afender that's really helpful! I'll close this out as everything is now covered in #1301, #1210 and #1211.
