### ISSUE TITLE
[QST] Calculate all possible paths between two points

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cugraph#1309]
Another graph problem came up in Advent of Code. This time I need to calculate all paths between two points of a digraph.  Specifically, I need to count the number of paths between two points.

I was able to do this in networkx with [`nx.all_simple_paths`](https://networkx.org/documentation/networkx-1.9/reference/generated/networkx.algorithms.simple_paths.all_simple_paths.html#networkx.algorithms.simple_paths.all_simple_paths) but after reading the cugraph docs couldn't find a similar method. How would I be able to achieve the same thing?

This would be especially useful in cugraph because it is super slow in networkx.

**Comment by afender** [comment]
Hi @jacobtomlinson 

Thanks for your question. While we currently don't have a direct API for all paths between two vertices, you should be able to identify a number of paths by running BFS samples.

I am not surprised that Nx takes a lot of time for this because the theoretical complexity and memory footprint are fundamentally very large for this problem. It would be helpful to know more about the context and which data science workflow requires this.

**Comment by jacobtomlinson** [comment]
Thanks for getting back to me @afender.

All of the problems in AoC are toy problems. Mostly targeted at learning.

[This specific problem](https://adventofcode.com/2020/day/10) gives you a list of ~100 nodes each connected end to end, so there is only one route through. It then tells you some nodes can be skipped, therefore there are additional edges which bypass some nodes.

The solution asks you to count the number of possible paths through this graph.

I'm guessing that there is a mathmatical way to calculate this without having to generate each route, because as you say the complexity and footprint of this is large and does not scale.

However I was curious whether this problem could be brute forced with a GPU.

**Comment by afender** [comment]
Thanks for the information! 

> I was curious whether this problem could be brute forced with a GPU.

Yes, it can. One way to do this is to leverage CUDA streams and execute concurrent SSSP with different sources within a GPU. On top of that, P GPUs could be leveraged to handle V/P sources on each one independently.

**Comment by BradReesWork** [comment]
@jacobtomlinson I am marking this question as closed and adding development of the nx.all_simple_paths  functionality to out roadmap

**Comment by jacobtomlinson** [comment]
Sounds great thanks @BradReesWork
