### ISSUE TITLE
[DOC] describing how to use the cugraph C/C++ API 

### ISSUE THREAD

**Issue by nodrogluap** [rapidsai/cugraph#1317]
Following up on [this Twitter thread](https://twitter.com/YYCist/status/1339391573528756232).

It would be nice to have a doc describing how to use the cugraph C/C++ API directly with some basic examples, as the doxygen pages are not all that didactic.  For example, I have an existing [C++ CUDA program](https://github.com/nodrogluap/OpenDBA) that potentially produces a large distance matrix, and I'd like to apply the ECG algorithm to it. It's not abundantly clear how to format the data (other than it's Apache Arrow based AFAIK) and how to parameterize the cugraph ECG function call.

Also, in trying to follow the [KISS](https://en.wikipedia.org/wiki/KISS_principle) principal, I'd like to know the minimal environment (including SM version and external library dependencies) required to compile against and run cugraph, if I'm not using the Python layer at all.

**Comment by BradReesWork** [comment]
@nodrogluap this is a focus for cuGraph over the next few releases.  You should start seeing incremental improvements

**Comment by BradReesWork** [comment]
being dropped and replaced by an issue to create a training class on how to use C/C++
