### ISSUE TITLE
[FEA] Large scale RMAT graph generator

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1329]
We need a distributed graph generator to facilitate MG testing and benchmarking. 
Data needs to be passed as dask cudf edge list.
It should be RMAT and comply with Graph500 Specs
Leveraging GPUs would be ideal.

**Comment by BradReesWork** [comment]
Argument suggestions:
- Number of vertices or Scale factor (power of 2)
- Number of edges or branching factor

-RMAT a parameter (default: 0.45)
    Probability of an edge falling into the A partition in the R-MAT model.

-RMAT b parameter (default: 0.22)
    Probability of an edge falling into the B partition in the R-MAT model.

-RMAT c parameter (default: 0.22)
    Probability of an edge falling into the C partition in the R-MAT model.

- Number of GPUs 
   can be used to per-partition the data

**Comment by seunghwak** [comment]
> Argument suggestions:
> 
> -RMAT a parameter (default: 0.45)
> Probability of an edge falling into the A partition in the R-MAT model.
> 
> -RMAT b parameter (default: 0.22)
> Probability of an edge falling into the B partition in the R-MAT model.
> 
> -RMAT c parameter (default: 0.22)
> Probability of an edge falling into the C partition in the R-MAT model.

Graph 500 uses 
A = 0.57 | B = 0.19
C = 0.19 | D = 1-(A+B+C) = 0.05 (http://graph500.org/?page_id=12)
and should we better set default values based on the Graph 500 specs?

**Comment by seunghwak** [comment]
This issue will be addressed in PR #1401 & #1411
