### ISSUE TITLE
[ENH] Retire legacy SG PageRank and replace with the latest version

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1331]
There has been a growing number of requests for weights support #1313 and bug reports in the legacy version #1330.
Exposing the new PageRank would address both issues.

- [ ] Verify performance
- [ ] Upgrade bindings 
- [ ] Upgrade doc to account for the new features
- [ ] Delete the old version

**Comment by BradReesWork** [comment]
closed by #1330 and #1332
