### ISSUE TITLE
[FEA] Add option to Jaccard to support 2-hop comparisons

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#136]
Currently Jaccard only compute a score if the vertices are connected by an edge.  However there are analytics user cases where the user wants to find similarities between unconnected vertices (max is 2-hops).  Computing the 2-hop comparison can be computationally expensive, therefore having it as an option might be preferred.

**Comment by jwyles** [comment]
In NetworkX they take as an argument a list of vertex pairs to compute the Jaccard similarity for. Perhaps doing the same would be more versatile than an option for 2-hop comparisons. It also is easier to implement that way.

**Comment by jwyles** [comment]
Please assign this to me. I am going to start working on it.
