### ISSUE TITLE
[QST] Min cost flow

### ISSUE THREAD

**Issue by brianchmiel** [rapidsai/cugraph#1366]
Ask a question that could be converted into a feature or enhancement
Hi, is cuGraph plan to support min cost flow ?

**Comment by BradReesWork** [comment]
We have not considered Min-cost Flows.   We have Traveling Salesman (TSP) coming out this release and then being enhanced over the year to provide CVRPTW.  

We have MaxFlow on the roadmap via work from UC Davis on Gunrock.

If you create an feature request we will work it into teh schedule.

**Comment by BradReesWork** [comment]
Adding Min Cost to the roadmap and closing this issue
