### ISSUE TITLE
[ENH] Update cudf groupby calls to explicitly set the sort option

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1371]
A potentially breaking cudf change was recently merged and cugraph should be updated to explicitly set the `sort` option so we don't rely on a default behavior that may be different than what we're expecting.

See https://github.com/rapidsai/cudf/pull/7180 for details about the change.

The request here is to simply add a `sort=True` option to all groupby calls that **do not** already specify a `sort` behavior.

In addition, @ChuckHastings mentioned:

> we may want to flag those to go back later and see if sort=True is necessary.  It would be faster without the sort.  Or we could preemptively try setting sort=False in each of those places to see if it will work.

**Comment by BradReesWork** [comment]
PR #1375 did an exploration of current code and showed that there is no assumption that results needed to be in sorted order,  Therefore, this issue is not needed and being closed
