### ISSUE TITLE
[FEA] Benchmark SG analytics

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#138]
All the Single-GPU analytics in version 0.6 should be benchamrked

- [ ] BFS 
- [x] Jaccard Similarity
- [ ] Weighted Jaccard
- [x] Louvain Example
- [x] Page Rank
- [ ] Spectral Clustering - Balanced Cut
- [ ] Spectral Clustering - Modularity
- [ ] Single Source Shortest Path

**Comment by afender** [comment]
I started a python script in cugraph-team Drive to facilitate benchmarking: https://drive.google.com/open?id=1nIoL6ORhbvf2qzvEdvj-nW-OCCdPmpUJ  

It is best to have issues #163, #164 and #167 fixed before proceeding to the benchmark.

Here is how to use the script:
```
usage: cugraph_time.py [-h] [--file_type FILE_TYPE] [--algo ALGO]
                       [--damping_factor DAMPING_FACTOR] [--max_iter MAX_ITER]
                       [--tolerence TOLERENCE] [--source SOURCE]
                       [--auto_csr AUTO_CSR]
                       file

CuGraph benchmark script.

positional arguments:
  file                  Path to the input file

optional arguments:
  -h, --help            show this help message and exit
  --file_type FILE_TYPE
                        Input file type : csv or mtx. If csv, cuDF reader is
                        used (set for [src dest] pairs separated by a tab). If
                        mtx, Scipy reder is used (slow but supports weights).
                        Default is mtx.
  --algo ALGO           Algorithm to run : pagerank, bfs, sssp, jaccard,
                        louvain, all. Default is all
  --damping_factor DAMPING_FACTOR
                        Damping factor for pagerank algo. Default is 0.85
  --max_iter MAX_ITER   Maximum number of iteration for any iterative algo.
                        Default is 100
  --tolerence TOLERENCE
                        Tolerence for any approximation algo. Default is 1e-5
  --source SOURCE       Source for bfs or sssp. Default is 0
  --auto_csr AUTO_CSR   Automatically do the csr and transposed
                        transformations. Default is 0, switch to another value
                        to enable

```

It currently supports pagerank, bfs, sssp, jaccard, louvain. If needed, other algorithms can be added in just a few line following the exact same path.

**Comment by afender** [comment]
By using this script and the released cugraph 0.6 packages, the benchmark team should be able to run on any desired configurations and inputs.

**Comment by BradReesWork** [comment]
I have been working on benchmarking notebooks that processes several networks and produces a bar chart of speedup.  Currently is only compares cuGraph against NetworkX.  I plan on expanding that.

**Comment by BradReesWork** [comment]
This issues is going to roll over to the next release cycle
