### ISSUE TITLE
[EPIC] Existing Algorithms using Primitives and Supporting MNMG

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1381]
All existing algorithms should be migrated to using Graph Primitives and the legacy versions retired.  
- [ ] **Subgraph Extraction**
  - [x] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Degree and weight sum**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **EgoNet**
  - [x] using GP
  - [x] Legacy retired
  - [ ] supporting MNMG
- [ ] **Katz**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **Betweenness Centrality**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Edge Betweenness Centrality**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Louvain**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **Leiden**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **ECG**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Spectral**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **TC**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **K-Truss**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **WCC**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **SCC**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **K-Core**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Core Number**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **PageRank**
  - [x] using GP
  - [x] Legacy retired
  - [x] supporting MNMG
- [ ] **Personal PageRank**
  - [x] using GP
  - [x] Legacy retired
  - [x] supporting MNMG
- [ ] **Jaccard**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **Overlap Similarity**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG
- [ ] **BFS**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **SSSP**
  - [x] using GP
  - [ ] Legacy retired
  - [x] supporting MNMG
- [ ] **MST**
  - [ ] using GP
  - [ ] Legacy retired
  - [ ] supporting MNMG

**Comment by afender** [comment]
Added egonet and subgraph extraction.
Created separate issues for R-MAT and Coarsening since they are new features to add the python API.
