### ISSUE TITLE
[FEA] balanced triads | Heider

### ISSUE THREAD

**Issue by geoHeil** [rapidsai/cugraph#1393]
So far an algorithm to calculate balanced triads (as defined by Heider) does not (yet) seem to be part of cugraph. 
https://neo4j.com/docs/graph-algorithms/current/labs-algorithms/balanced-triads/

Am I overlooking something? Would there be an easy way to retrofit them? 
Otherwise: I guess this might be a feature request in a new version of cugraph.

**Comment by BradReesWork** [comment]
@geoHeil I really like balanced triads, but it currently is not on the roadmap - most things only make it on the roadmap when someone asks for it.   I will evaluate how hard the feature is and work it into the plan

**Comment by ChuckHastings** [comment]
It would make sense to consider this algorithm when we work on the triangle counting primitives later this year.
