### ISSUE TITLE
[FEA][NV] Add helper functions in Python API

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#14]
Load adjacency list

and 

Add/delete :
- transposed adjacency list
- adjacency list

This is already implemented in the C++ API, just needs python bindings and simple tests.

**Comment by jwyles** [comment]
Please assign this to me. I am starting to work on it.

**Comment by afender** [comment]
@jwyles, iirc @Iroy30 added part of it along with Jaccard feature. You should sync-up together.

**Comment by jwyles** [comment]
Yes, I believe most of it has been added. Some of the methods don't have active tests though. I think that most of what's to be done will be figuring out the tests.

**Comment by jwyles** [comment]
@afender Do we want to have a method to add the transposed adjacency list to a graph (by wrapping the user provided columns in a view)? It doesn't seem like that would be necessary.

**Comment by afender** [comment]
> @afender Do we want to have a method to add the transposed adjacency list to a graph (by wrapping the user provided columns in a view)? It doesn't seem like that would be necessary.

I agree that it is not necessary for now. What is really important is to be able to create it from the user's edge list (and we already have that iirc).
