### ISSUE TITLE
[BUG] traveling_salesperson route returned does not include all vertices

### ISSUE THREAD

**Issue by SchultzC** [rapidsai/cugraph#1410]
**Describe the bug**
cugraph 0.18 traveling_salesperson returns a route and a cost.  The cost appears correct but the route does not show all vertex ids in the output.

**Steps/Code to reproduce bug**
```python
sample_points = cudf.DataFrame({"vertex":[101,102,103,104],"x":[1,2,3,4],"y":[1,2,3,4]})
print(sample_points)
route, cost = cugraph.traversal.traveling_salesperson(sample_points, restarts=10, beam_search=False, nstart=101, k=1, verbose=True)
print("Route: \n{}".format(route))
print("\nCost:\n{}".format(cost))
```

**Expected behavior**
All vertex ids should be included in the route output.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuGraph install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
docker pull rapidsai/rapidsai-core-nightly:0.18-cuda11.0-runtime-ubuntu18.04-py3.8
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-core-nightly:0.18-cuda11.0-runtime-ubuntu18.04-py3.8

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 27430205b703b35d17bd17810212a981a32a790d (grafted, HEAD, tag: branch-0.18-latest, origin/branch-0.18, origin/HEAD, branch-0.18)
     Author: Hugo Linsenmaier <hlinsenmaier@gmail.com>
     Date:   Thu Feb 11 06:17:38 2021 -0800
     
     Add SG TSP (#1360)
     
     This PR implements an approximated solution to the Traveling Salesperson Problem (TSP).
     The algorithm is exposed under ```traversal``` through a Python API taking 2D pos as input and returning a route.
     This PR relies on RAFT KNN: https://github.com/rapidsai/raft/pull/126
     Solves: https://github.com/rapidsai/cugraph/issues/1185
     
     Authors:
     - Hugo Linsenmaier (@hlinsen)
     
     Approvers:
     - AJ Schmidt (@ajschmidt8)
     - Brad Rees (@BradReesWork)
     - Rick Ratzel (@rlratzel)
     - Alex Fender (@afender)
     - Andrei Schaffer (@aschaffer)
     
     URL: https://github.com/rapidsai/cugraph/pull/1360
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux ivb100 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Feb 16 19:28:21 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla T4            On   | 00000000:04:00.0 Off |                    0 |
     | N/A   43C    P0    26W /  70W |    958MiB / 15109MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla T4            On   | 00000000:05:00.0 Off |                    0 |
     | N/A   37C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:         x86_64
     CPU op-mode(s):       32-bit, 64-bit
     Byte Order:           Little Endian
     CPU(s):               40
     On-line CPU(s) list:  0-19
     Off-line CPU(s) list: 20-39
     Thread(s) per core:   1
     Core(s) per socket:   10
     Socket(s):            2
     NUMA node(s):         2
     Vendor ID:            GenuineIntel
     CPU family:           6
     Model:                62
     Model name:           Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
     Stepping:             4
     CPU MHz:              3334.167
     CPU max MHz:          3600.0000
     CPU min MHz:          1200.0000
     BogoMIPS:             6000.31
     Virtualization:       VT-x
     L1d cache:            32K
     L1i cache:            32K
     L2 cache:             256K
     L3 cache:             25600K
     NUMA node0 CPU(s):    0-9
     NUMA node1 CPU(s):    10-19
     Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear
     
     ***CMake***
     
     ***g++***
     
     ***nvcc***
     
     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.8.6
     
     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 : /opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
     aiobotocore               1.2.1              pyhd8ed1ab_0    conda-forge
     aiohttp                   3.7.3            py38h497a2fe_1    conda-forge
     aioitertools              0.7.1              pyhd8ed1ab_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
     arrow-cpp                 1.0.1           py38h2934018_29_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-cal                 0.4.5                h2ff795d_6    conda-forge
     aws-c-common              0.4.67               h7f98852_0    conda-forge
     aws-c-event-stream        0.2.6                h4285e0c_4    conda-forge
     aws-c-io                  0.8.3                h3b39b8c_1    conda-forge
     aws-checksums             0.1.11               h3b39b8c_1    conda-forge
     aws-sdk-cpp               1.8.138              h9e0957a_1    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     blas                      2.14                   openblas    conda-forge
     bleach                    3.3.0              pyh44b312d_0    conda-forge
     bokeh                     2.2.3            py38h578d9bd_0    conda-forge
     boost                     1.72.0           py38h1e42940_1    conda-forge
     boost-cpp                 1.72.0               h9d3c048_4    conda-forge
     botocore                  1.19.52            pyhd8ed1ab_0    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     cairo                     1.16.0            h7979940_1007    conda-forge
     certifi                   2020.12.5        py38h578d9bd_1    conda-forge
     cffi                      1.14.4           py38ha65f79e_1    conda-forge
     cfitsio                   3.470                h2e3daa1_7    conda-forge
     chardet                   3.0.4           py38h924ce5b_1008    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
     cryptography              3.4.4            py38h3e25421_0    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.0a210215   cuda_11.0_py38_gd3f5add210_251    rapidsai-nightly
     cudf_kafka                0.18.0a210215   py38_gd3f5add210_251    rapidsai-nightly
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cugraph                   0.18.0a210215   py38_g27430205_297    rapidsai-nightly
     cuml                      0.18.0a210215   cuda11.0_py38_g3fc458fec_127    rapidsai-nightly
     cupy                      8.0.0            py38hb7c6141_0    rapidsai-nightly
     curl                      7.71.1               he644dc0_8    conda-forge
     cusignal                  0.18.0a210216   py37_g803aa6b_29    rapidsai-nightly
     cuspatial                 0.18.0a210215   py38_g3045c48_21    rapidsai-nightly
     custreamz                 0.18.0a210215   py38_gd3f5add210_251    rapidsai-nightly
     cuxfilter                 0.18.0a210215   py38_gc6e0946_64    rapidsai-nightly
     cycler                    0.10.0                     py_2    conda-forge
     cyrus-sasl                2.1.27               h3274739_1    conda-forge
     cython                    0.29.21          py38h709712a_2    conda-forge
     cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
     dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
     dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
     dask-cuda                 0.18.0a210216           py38_61    rapidsai-nightly
     dask-cudf                 0.18.0a210215   py38_gd3f5add210_251    rapidsai-nightly
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         4.0.1              pyhd8ed1ab_0    conda-forge
     dask-ml                   1.8.0              pyhd8ed1ab_0    conda-forge
     datashader                0.11.1             pyh9f0ad1d_0    conda-forge
     datashape                 0.5.4                      py_1    conda-forge
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2021.2.0         py38h578d9bd_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     expat                     2.2.10               h9c3ff4c_0    conda-forge
     fa2                       0.3.5            py38h1e0a361_0    conda-forge
     faiss-proc                1.0.0                      cuda    conda-forge
     fastavro                  1.3.2            py38h497a2fe_0    conda-forge
     fastrlock                 0.5              py38h709712a_2    conda-forge
     filterpy                  1.4.5                      py_1    conda-forge
     fiona                     1.8.18           py38h37fbd03_0    conda-forge
     fontconfig                2.13.1            hba837de_1004    conda-forge
     freetype                  2.10.4               h0708190_1    conda-forge
     freexl                    1.0.5             h516909a_1002    conda-forge
     fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
     gdal                      3.1.4            py38h25844d8_3    conda-forge
     geopandas                 0.8.1                      py_0    conda-forge
     geos                      3.8.1                he1b5a44_0    conda-forge
     geotiff                   1.6.0                h5d11630_3    conda-forge
     gettext                   0.19.8.1          h0b5b191_1005    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.1                h36c2ea0_2    conda-forge
     git                       2.30.1          pl5320h014a29a_0    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gpuci-tools               0.2.1                        15    gpuci
     grpc-cpp                  1.35.0               h146f9af_0    conda-forge
     hdf4                      4.2.13            h10796ff_1004    conda-forge
     hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     holoviews                 1.14.1             pyhd3deb0d_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     importlib-metadata        3.4.0            py38h578d9bd_0    conda-forge
     importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.4.2            py38h81c977d_0    conda-forge
     ipython                   7.15.0           py38h32f6830_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
     jedi                      0.17.2           py38h578d9bd_1    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
     joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     json-c                    0.13.1            hbfbb72e_1002    conda-forge
     json5                     0.9.5              pyh9f0ad1d_0    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter-server-proxy      1.6.0              pyhd8ed1ab_0    conda-forge
     jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
     jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
     jupyterlab                2.1.5                      py_0    conda-forge
     jupyterlab-nvdashboard    0.5.0a200819               py_0    rapidsai-nightly
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     jupyterlab_server         1.2.0                      py_0    conda-forge
     jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
     kealib                    1.4.14               he4dc956_1    conda-forge
     kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.12                 hddcbb42_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.18.0a210215   cuda11.0_gd3f5add210_251    rapidsai-nightly
     libcudf_kafka             0.18.0a210215   gd3f5add210_251    rapidsai-nightly
     libcugraph                0.18.0a210215   cuda11.0_g27430205_297    rapidsai-nightly
     libcuml                   0.18.0a210215   cuda11.0_g3fc458fec_127    rapidsai-nightly
     libcumlprims              0.18.0a210211   cuda11.0_gff080f3_0    rapidsai-nightly
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libcuspatial              0.18.0a210215   cuda11.0_g3045c48_21    rapidsai-nightly
     libdap4                   3.20.6               hd7c4107_1    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libfaiss                  1.6.3           h328c4c8_3_cuda    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
     libgcrypt                 1.8.7                h36c2ea0_0    conda-forge
     libgdal                   3.1.4                h96b6e7a_3    conda-forge
     libgfortran-ng            7.5.0               h14aa051_18    conda-forge
     libgfortran4              7.5.0               h14aa051_18    conda-forge
     libglib                   2.66.7               h1f3bc88_0    conda-forge
     libgomp                   9.3.0               h2828fa1_18    conda-forge
     libgpg-error              1.41                 h9c3ff4c_0    conda-forge
     libgsasl                  1.8.0                         2    conda-forge
     libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     libkml                    1.3.0             hd79254b_1012    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     liblapacke                3.8.0               14_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libntlm                   1.4               h7f98852_1002    conda-forge
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libpq                     12.3                 h255efa7_3    conda-forge
     libprotobuf               3.14.0               h780b84a_0    conda-forge
     librdkafka                1.5.3                hc49e61c_1    conda-forge
     librmm                    0.18.0a210216   cuda11.0_g14eb3c7_34    rapidsai-nightly
     librttopo                 1.1.0                hb271727_4    conda-forge
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
     libspatialite             5.0.1                h6ec7341_0    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.2.0                hdc55705_0    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuuid                   2.32.1            h7f98852_1000    conda-forge
     libuv                     1.40.0               h7f98852_0    conda-forge
     libwebp                   1.2.0                h3452ae3_0    conda-forge
     libwebp-base              1.2.0                h7f98852_0    conda-forge
     libxcb                    1.13              h7f98852_1003    conda-forge
     libxgboost                1.3.3dev.rapidsai0.18      cuda11.0_0    rapidsai-nightly
     libxml2                   2.9.10               h72842e0_3    conda-forge
     llvmlite                  0.35.0           py38h4630a5e_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py38h497a2fe_3    conda-forge
     matplotlib-base           3.3.4            py38h0efea84_0    conda-forge
     mistune                   0.8.4           py38h497a2fe_1003    conda-forge
     more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
     multidict                 5.1.0            py38h497a2fe_1    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     nbclient                  0.5.2              pyhd8ed1ab_0    conda-forge
     nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
     nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
     networkx                  2.5                        py_0    conda-forge
     nodejs                    15.3.0               h92b4a50_1    conda-forge
     notebook                  6.2.0            py38h578d9bd_0    conda-forge
     numba                     0.52.0           py38h51da96c_0    conda-forge
     numpy                     1.20.1           py38h18fd61f_0    conda-forge
     nvtx                      0.2.3            py38h497a2fe_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openjpeg                  2.4.0                hf7af979_0    conda-forge
     openssl                   1.1.1i               h7f98852_0    conda-forge
     orc                       1.6.7                h7950760_0    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.1.5            py38h51da96c_0    conda-forge
     pandoc                    2.11.4               h7f98852_0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     panel                     0.10.3             pyhd8ed1ab_0    conda-forge
     param                     1.10.1             pyhd3deb0d_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.44                 he1b5a44_0    conda-forge
     perl                      5.32.0               h36c2ea0_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.1.0            py38ha0e1e83_2    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     pixman                    0.40.0               h36c2ea0_0    conda-forge
     pluggy                    0.13.1           py38h578d9bd_4    conda-forge
     poppler                   0.89.0               h2de54a5_5    conda-forge
     poppler-data              0.4.10                        0    conda-forge
     postgresql                12.3                 hc2f5b80_3    conda-forge
     proj                      7.1.1                h966b41f_3    conda-forge
     prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
     prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
     protobuf                  3.14.0           py38h709712a_1    conda-forge
     psutil                    5.8.0            py38h497a2fe_1    conda-forge
     pthread-stubs             0.4               h36c2ea0_1001    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     py-xgboost                1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai-nightly
     pyarrow                   1.0.1           py38hf66eee4_29_cuda    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyct                      0.4.6                      py_0    conda-forge
     pyct-core                 0.4.6                      py_0    conda-forge
     pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
     pyee                      7.0.4              pyh9f0ad1d_0    conda-forge
     pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
     pynndescent               0.5.2              pyh44b312d_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyppeteer                 0.2.2                      py_1    conda-forge
     pyproj                    2.6.1.post1      py38h56787f0_3    conda-forge
     pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
     pysocks                   1.7.1            py38h578d9bd_3    conda-forge
     pytest                    6.2.2            py38h578d9bd_0    conda-forge
     python                    3.8.6           hffdb5ce_5_cpython    conda-forge
     python-confluent-kafka    1.5.0            py38h1e0a361_0    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
     pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
     pyzmq                     22.0.1           py38h3d7ac18_0    conda-forge
     rapids                    0.18.0a210216   cuda11.0_py38_g38e245e_216    rapidsai-nightly
     rapids-xgboost            0.18.0a210216   cuda11.0_py38_g38e245e_216    rapidsai-nightly
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     requests                  2.25.1             pyhd3deb0d_0    conda-forge
     rmm                       0.18.0a210215   cuda_11.0_py38_g14eb3c7_34    rapidsai-nightly
     rtree                     0.9.7            py38h02d302b_1    conda-forge
     s2n                       0.10.26              h9b69904_0    conda-forge
     s3fs                      0.5.2              pyhd8ed1ab_0    conda-forge
     scikit-learn              0.23.1           py38h3a94b23_0    conda-forge
     scipy                     1.5.3            py38h828c644_0    conda-forge
     seaborn                   0.11.1               hd8ed1ab_1    conda-forge
     seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py38h578d9bd_3    conda-forge
     shapely                   1.7.1            py38ha11d057_1    conda-forge
     simpervisor               0.4                pyhd8ed1ab_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     statsmodels               0.12.2           py38h5c078b8_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     tbb                       2020.2               h4bd325d_3    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.2            py38h578d9bd_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     tiledb                    2.2.3                h91fcb0e_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py38h497a2fe_1    conda-forge
     tqdm                      4.56.2             pyhd8ed1ab_0    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     treelite                  1.0.0            py38hd08a91b_0    conda-forge
     treelite-runtime          1.0.0                    pypi_0    pypi
     typing-extensions         3.7.4.3                       0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     tzcode                    2021a                h7f98852_0    conda-forge
     ucx                       1.9.0+gcd9efd3       cuda11.0_0    rapidsai-nightly
     ucx-proc                  1.0.0                       gpu    rapidsai-nightly
     ucx-py                    0.18.0a210215   py38_gcd9efd3_19    rapidsai-nightly
     umap-learn                0.5.1            py38h578d9bd_0    conda-forge
     urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websockets                8.1              py38h497a2fe_3    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
     wrapt                     1.12.1           py38h497a2fe_3    conda-forge
     xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
     xerces-c                  3.2.3                h9d8b166_2    conda-forge
     xgboost                   1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai-nightly
     xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.12               h516909a_0    conda-forge
     xorg-libxau               1.0.9                h7f98852_0    conda-forge
     xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
     xorg-xproto               7.0.31            h7f98852_1007    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     yarl                      1.6.3            py38h497a2fe_1    conda-forge
     zeromq                    4.3.4                h9c3ff4c_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.8                ha95c52a_1    conda-forge
     
</pre></details>

**Comment by BradReesWork** [comment]
@SchultzC thanks for posting this bug.  we are looking into it
