### ISSUE TITLE
[FEA] Bindings for multi source BFS

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1462]
Add bindings for #1457 

In addition, the python layer responsibility is to :
- call feasibility check and redirect to the appropriate implementation path #1460
- call the graph consolidation #1459
- renumber and concatenate sources in a single DF 
- call multi-source traversal and potentially uses #1461 if relevant

**Comment by rlratzel** [comment]
closed after merging #1591 and #1804
