### ISSUE TITLE
[BUG] COO to CSR conversion does not capture isolated vertices (libcugraph)

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1479]
When converting a COO to CSR using `coo_to_csr()` or `view()` (still need to determine which or if either), isolated vertices are dropped.  The following C++ gtest code snippet demonstrates (from PR #1475 ):

```
size_t nrows = 3;

std::vector<IndexT> cooRowInd{0, 0, 1};
std::vector<IndexT> cooColInd{0, 1, 0};

size_t nnz = cooRowInd.size();

EXPECT_EQ(nnz, cooColInd.size());

// Note: there seems to be a BUG in coo_to_csr() or view()
// COO format doesn't account for isolated vertices;
cugraph::GraphCOOView<int, int, float> G_coo(&cooRowInd[0], &cooColInd[0], nullptr, nrows, nnz);
auto G_unique = cugraph::coo_to_csr(G_coo);
cugraph::GraphCSRView<int, int, float> G = G_unique->view();
  
size_t num_vertices = G.number_of_vertices;
size_t num_edges    = G.number_of_edges;
  
EXPECT_EQ(num_vertices, nrows); //fails when G was constructed from COO
EXPECT_EQ(num_edges, nnz);
```

**Comment by afender** [comment]
@rlratzel Looking at the example, did you mean self-loops instead of isolated vertices?

**Comment by ChuckHastings** [comment]
This is only an issue with the legacy graph, and only affects things if you call coo_to_csr on a graph that has isolated vertices at the end (as I describe above).  Isolated vertices that are less than the maximum vertex id in the data will be represented perfectly fine.

The new graph has a different approach which would not see this error.

Do we want to fix the legacy graph or just live with this limitation?

**Comment by BradReesWork** [comment]
Since the legacy graph is slowly being dropped, let's live with the limitation and push to get everything migrated over
