### ISSUE TITLE
[ENH] Refactor C++ include directory

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1491]
To better match the rest of RAPIDS, the structure of include should be "cpp/include/cugraph"

create a new directory structure and move existing files

**Comment by seunghwak** [comment]
A related question is whether to include files under include/cugraph as

#include <file_name>
or
#include <cugraph/file_name>

It seems like the latter is common patterns within RAPIDS, so we may follow that convention.
