### ISSUE TITLE
[ENH] Create a wrapper file for cuco::static_map

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#1496]
**Describe the solution you'd like**
cuco::static_map is implemented in a header to support different template types. However, we're mainly using this for "vertex_t to vertex" or "vertex to float or double" look-ups.

There is basically little need to recompile this in every place we use as this increases compile time and also the final binary size.

If we create a separate wrapper taking pointers with explicit instantiations for the types we use, I think we can cut both compile time and binary size.

**Comment by ChuckHastings** [comment]
We could also potentially eliminate our Pascal issue if we hide the `cuco::static_map` entirely from the API to the wrapper.  Our uses of `cuco::static_map` entirely revolve around taking a set of key/value pairs and creating an efficient structure to look up values given a key.  If we created an API that hid the implementation, we could provide for Pascal and earlier an option for just doing `sort_by_key` and `lower_bound` (or something like that) to provide the same functionality.

It might also be that in some circumstances the `sort_by_key`/`lower_bound` technique might be more efficient than the hash table.  Doing this might make it easier to swap implementations around.

**Comment by ChuckHastings** [comment]
Going to close this one.  Our initial uses of `cuco::static_map` lent themselves to a wrapper.  The latest code in the primitives does not really allow for that.

When we refactor things to separate the primitives from the algorithms we can address whether to do something like this for some of the use cases.
