### ISSUE TITLE
[BUG] Rapids Docker container 0.18 refresh causes 'import cugraph' to return: cannot import name 'stringify_path' from 'dask.bytes.core'.

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cugraph#1501]
**Describe the bug**
An update to Docker image **rapidsai/rapidsai:0.18-cuda11.0-runtime-ubuntu20.04-py3.8** pushed at around 7:30PM GMT on 31 March 2021 has an error in cugraph:

```import cugraph```

results in 

```cannot import name 'stringify_path' from 'dask.bytes.core'```

I also observed that a version of the container pushed 10 hours earlier also had this error.

I was running a version, with same tag, which I pulled 3 weeks ago, which works fine.

![image](https://user-images.githubusercontent.com/8914493/113317192-09004980-9307-11eb-8c07-990964983360.png)

**Steps/Code to reproduce bug**

My server looks for new container pushes and automatically updates although backs up previous pull.

Running existing code containing ```import cugraph``` caused the error.

Any of the cugraph example workbooks will show this error in the affected containers.

**Expected behavior**

The original RAPIDS 0.18 Docker container did not have this issue, only this update.

**Environment overview (please complete the following information)**

 - Environment location: Bare metal
 - Method of cuGraph install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
  
```docker pull rapidsai/rapidsai:0.18-cuda11.0-runtime-ubuntu20.04-py3.8```

```docker run --gpus all --name rapids0.18 --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 -v /data/john:/data/ -v /srv/data/john:/output/ -v /home/john/Source/Notebooks:/rapids/notebooks/work -v /mnt:/mnt rapidsai/rapidsai:0.18-cuda11.0-runtime-ubuntu20.04-py3.8```

**Comment by rlratzel** [comment]
Hi @MurrayData ,
I'll take a look at this issue, and I may be able to provide instructions on how to update your container to fix this. Changing the image itself to properly fix the problem will require our Ops team to get involved as they're the ones that maintain the Dockerfiles, do the builds and uploads, etc.  Assuming I can find a series of steps you can do to fix this, would that be acceptable in the short term?

**Comment by rlratzel** [comment]
@MurrayData - I pulled that image and was able to see the same `ImportError` you did when importing cugraph.  I noticed the image was built with a 0.18 `dask_cudf`, but the latest `dask` packages, which appear to be incompatible.  After I downgraded `dask`, I was able to successfully import `cugraph`:
```
$ docker run --gpus all --name rapids0.18 --rm -it rapidsai/rapidsai:0.18-cuda11.0-runtime-ubuntu20.04-py3.8
...

(rapids) root@f27dcbb5314a:/rapids# python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cugraph
...
ImportError: cannot import name 'stringify_path' from 'dask.bytes.core' (/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/bytes/core.py)
>>>

(rapids) root@f27dcbb5314a:/rapids# conda install -y dask=2020.12
...

(rapids) root@f27dcbb5314a:/rapids# python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cugraph
>>>
```
so if you're able to run:
```
conda install -y dask=2020.12
```
I believe this will allow you to import the rapids libraries that are affected (which includes cugraph).

Note: you _may_ need to restart jupyterlab for the dask downgrade to be seen (I haven't verified this yet).  If so, you can stop and start jupyterlab from the command line by using the commands in these scripts: [stop-jupyter.sh](https://github.com/rapidsai/docker/blob/branch-0.19/context/stop-jupyter.sh) and [start-jupyter.sh](https://github.com/rapidsai/docker/blob/branch-0.19/context/start-jupyter.sh) 

I'm also inquiring about how to update the image on DockerHub so those steps aren't needed longer-term.

**Comment by rlratzel** [comment]
**update:** a better suggestion than _downgrading_ `dask` is to _upgrade_ `cudf` and `dask-cudf` to the latest patch release for 0.18.  Just replace the suggested conda command above with this one:
```
conda install -y dask=0.18.1 dask-cudf=0.18.1
```
and all other steps remain the same.

I believe @dillon-cullinan in the RAPIDS Ops team is actively working on making this change in their Dockerfile and building & publishing an updated image.

**Comment by MurrayData** [comment]
> Hi @MurrayData ,
> I'll take a look at this issue, and I may be able to provide instructions on how to update your container to fix this. Changing the image itself to properly fix the problem will require our Ops team to get involved as they're the ones that maintain the Dockerfiles, do the builds and uploads, etc. Assuming I can find a series of steps you can do to fix this, would that be acceptable in the short term?

Thanks, for now I've reverted to previous stable version of the 0.18 container. My pull script automatically saves each image version =, with data stamp, so allows reversion even if the tags are the same.

**Comment by ajschmidt8** [comment]
Hi @MurrayData, thanks for opening this issue. I'm on the RAPIDS Ops team and will be working on fixing this today.

**Comment by ajschmidt8** [comment]
@MurrayData, we fixed the underlying issue and pushed new containers a little while ago. From my local testing, it seems that this has resolved the `import cugraph` error that you initially experienced. Please let me know if these updated containers are working okay for you.

**Comment by rlratzel** [comment]
> @MurrayData, we fixed the underlying issue and pushed new containers a little while ago. From my local testing, it seems that this has resolved the `import cugraph` error that you initially experienced. Please let me know if these updated containers are working okay for you.

@ajschmidt8 - just confirming that I pulled the latest image and all versions looked right, and I was able to `import cugraph` in python without errors.  Thanks!

**Comment by MurrayData** [comment]
All working fine now, thank you.
