### ISSUE TITLE
[ENH] Integer weights support in get_traversed_cost

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1519]
Issue created for this: https://github.com/rapidsai/cugraph/pull/1376#discussion_r604441536

This function needs to be translated into MG, it still only works for legacy algorithms.  When we convert to MG we can make sure that integer weight support is included.

**Comment by ChuckHastings** [comment]
C++ code supports integer weights.

We need to explore from a python level what should be supported.  Going to close this until there's a motivating use case in python.
