### ISSUE TITLE
[ENH] Link prediction on directed graphs

### ISSUE THREAD

**Issue by eburling** [rapidsai/cugraph#1530]
It would be useful to allow for link prediction on directed graphs, e.g. kNN graphs where a pair of nodes can have 0, 1, or 2 edges between them.

```python
import cuml
import cudf
import cugraph
import cupy as cp

n_samples = 10000
n_features = 20
centers = 5
n_neighbors = 10

X, _ = cuml.make_blobs(n_samples=n_samples,
                       n_features=n_features,
                       centers=centers)
X = cudf.DataFrame.from_records(X)

# Use n_neighbors + 1 to account for self index
model = cuml.neighbors.NearestNeighbors(n_neighbors=n_neighbors+1)

model.fit(X)

idx = model.kneighbors(X, return_distance=False)

# Drop self index
idx.drop(columns=0,inplace=True)

n_nonzero = n_neighbors * X.shape[0]

indptr = cp.arange(0, n_nonzero + 1, n_neighbors)

G = cugraph.Graph()
G.from_cudf_adjlist(indptr, idx.values.ravel(), None)
cugraph.jaccard(G)
```

I would rather like to to be able to run `cugraph.jaccard(G.to_directed())` to capture the directions of the kNN graph, since the answers given by `cugraph.jaccard(G)` above differ from the jaccard coefficients that can be calculated from the rows of `idx`:

```python
ref = 0
query = idx.iloc[0][1]
s = len((set(idx.iloc[ref].values.get())).intersection(set(idx.iloc[query].values.get())))
s / (2 * n_neighbors - s)
```

I tried working around this with the latest `cuml` nightly build, which includes the function `sparse_pairwise_distances`, but the output is a dense matrix, which is too memory hungry to scale for large graphs.

```python
from cupy.sparse import csr_matrix
from cuml.metrics import sparse_pairwise_distances

weight = cp.ones(n_nonzero)
csr = csr_matrix((weight, idx.values.ravel(), indptr),
                    shape=(X.shape[0], X.shape[0]))
j = csr_matrix(1 - sparse_pairwise_distances(csr, metric='jaccard'))
```

Thanks very much for your consideration! I love the library and am spreading the RAPIDS gospel to all of my computational biology colleagues.

**Comment by hlinsen** [comment]
Hi @eburling,
Thanks for your suggestion! We will look into possible solutions to accelerate that path and add it to our roadmap for future releases.

**Comment by BradReesWork** [comment]
this should all work now
