### ISSUE TITLE
[ENH] Migrate CMakeLists files to use CPM

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1539]
Discussed this with @dantegd - cuDF and cuML are moving to CPM, cuGraph should do the same for consistency and the benefit of added functionality:
* ability to use preinstalled dependencies or download and build from source
* better support for CUDA, GPU arches, etc. (I think?)
* be up-to-date with the community's expectations
* be able to copy patterns from other RAPIDS repos
* addresses tech debt related to `FetchContent` calls that use commit hashes (eg. cuHornet), which have mistakenly used `GIT_SHALLOW` and broken builds when dependencies update their latest hash. (see https://github.com/rapidsai/cugraph/pull/1535 )

**Comment by dantegd** [comment]
Linking #1585

**Comment by ChuckHastings** [comment]
This is OBE.  We migrated everything to use the rapids-make mechanism.

**Comment by dantegd** [comment]
@ChuckHastings for curiosity, what does OBE mean? A quick google search gives me `Order of the British Empire` so that would be quite a status for the issue 😛

**Comment by ChuckHastings** [comment]
OBE = "Overcome By Events".  We didn't intentionally do something to address this request, however other changes have made doing something for this issue unnecessary.
