### ISSUE TITLE
[FEA] Automate CHANGELOG.md updates

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#154]
**Is your feature request related to a problem? Please describe.**
Engineers have to manually update the CHANGELOG.md.  This is not a reliable way to keep it updated. "Missing changelog update" is probably the most common problem found during reviews. Then the developer has to re-work the PR. This is a waste of development time

**Describe the solution you'd like**
This could be automated by copying the PR title in a new line in the changelog each time a PR is merged.

**Describe alternatives you've considered**
We could also publish the `git log` at each release.

**Task List**
Work with Inter ops / CI / cugraph teams to make this happen

**Comment by afender** [comment]
@Iroy30 please get the ball rolling on this issue. Not sure if this is something we should do inside cugraph or if this can be done at RAPIDS level. 

+cc @rlratzel and @dantegd for visibility in case this is something you have been looking at for Rapids already.

**Comment by karthikeyann** [comment]
*Suggestion:* `git log` would work if there is only single commit or all the commit has the same commit message. If there are multiple commits and/or different commit messages, then the changelog check could fail and developer can re-work the PR. 
is it possible for CI to add its own commit to PR after running checks?
