### ISSUE TITLE
[BUG] Tests expect /datasets to be writable

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cugraph#156]
The tests untar data into `/datasets` but this may not be feasible on all systems. Can this be updated to use relative paths from the either the test directory or the project root?

**Comment by seunghwak** [comment]
I think this is related to https://github.com/rapidsai/cugraph/issues/79

I think the test team may better decide a policy on placing test data, then, enforce the policy to every RAPIDS project.

**Comment by afender** [comment]
Closing as duplicate of #79

**Comment by afender** [comment]
This should be addressed at the same time as #79 (dup #171)
We need a single policy across RAPIDS for where the test data should be and how it should be provided to tests (cc @rlratzel ).
