### ISSUE TITLE
[BUG] MG katz_centrality requires the optional `alpha` param to converge

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1584]
@Iroy30 discovered that the MG `katz_centrality` calls require the `alpha` parameter to complete, and without it, an uncaught exception is thrown from C++ stating the algo failed to converge.

A workaround for benchmarking is to compute the `alpha` parameter in code prior to the `katz_centrality` call and pass it in.  This does not fix the bug (currently considered a bug since the alpha param is currently optional), but it unblocks benchmarks.  One issue with computing `alpha` for large distributed graphs is that a distributed `Graph` object does not support the `degree()` method required for computing `alpha` (`1/(max_degree+1)`), so a different approach would be required.  We'll need to weigh fixing the bug vs. applying a workaround in the short-term.

**Comment by ChuckHastings** [comment]
I believe this is fundamentally a python issue (correct?).  The C++ API for `katz_centrality` requires alpha to be provided.

There is a C++ function on the graph_view that returns the maximum in degree (or out degree).  Do we need to do anything to help expose this or can @Iroy30 make the necessary changes?

**Comment by BradReesWork** [comment]
According to the docs, this has been fixed
