### ISSUE TITLE
[BUG] MG Louvain call crashes with a cuda error

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1586]
Calling MG Louvain is currently crashing with an uncaught `cudaErrorInvalidValue` exception (see screenshot).
This is occurring with both RMAT-generated and existing hibench CSV file inputs.

![image](https://user-images.githubusercontent.com/3039903/117510536-dd99fb80-af51-11eb-8e17-08fa39401fdf.png)

**Comment by seunghwak** [comment]
Are we symmetrizing R-mat graph? AFAIK, Louvain expects undirected graph (so the input edge list should be symmetric).
