### ISSUE TITLE
[BUG] Invalid start vertex for MG BFS and MG SSSP result in unclear exception

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1587]
An invalid start vertex results in a misleading exception that appears as a cugraph bug:

![image](https://user-images.githubusercontent.com/3039903/117511311-1b4b5400-af53-11eb-9822-0b02844945db.png)

The SG version is somewhat better:

![image](https://user-images.githubusercontent.com/3039903/117511361-31591480-af53-11eb-9d67-ef72dcac5beb.png)

but is still misleading because, for instance in the error above, the start vertex was `0` but was not a valid vertex for that graph.

**Comment by ChuckHastings** [comment]
I assume this is a python-only change?  If the python code validated the a valid vertex was used then I believe the C code will do the right thing.

If you would like a C++ code change as well, please create a separate issue for the C++ team and identify what you would like the C++ behavior to be in this situation.

**Comment by alexbarghi-nv** [comment]
My proposed fix is to validate the start vertex and return a ValueError if invalid, using `G.has_node(start)`
![image](https://user-images.githubusercontent.com/105237337/167863965-5ff7841e-48bb-4f02-8f35-5426744fd6ae.png)

However, the returned dataframe still contains invalid vertices (see below) even when called correctly.  This shouldn't affect the results for the correct vertices but shouldn't we remove the invalid vertices before returning the results to the user?

![image](https://user-images.githubusercontent.com/105237337/167864497-670c6549-052d-4255-8090-27053ee95793.png)

**Comment by ChuckHastings** [comment]
The python documentation for BFS and SSSP reflect that vertices that are unreachable from the source will have maximum distance and a predecessor of -1.  So I believe what you are seeing is consistent with the documentation.

Whether we want to change the definition of the API to improve the user experience (giving them a smaller result with only the relevant data) is a reasonable question.  I would leave that to @rlratzel to evaluate.
