### ISSUE TITLE
[QST] Java API

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cugraph#16]
I am interested in generating Java API, can someone identify what are core API files, so I just focus on whats important?

**Comment by afender** [comment]
C++ API: [include](https://github.com/rapidsai/cugraph/tree/master/include) directory.
Python API: [python](https://github.com/rapidsai/cugraph/tree/master/python) directory (you can also check the python API [doc](https://github.com/rapidsai/cugraph/tree/master/docs) to have an overview of what's exposed).
This is still work in progress.

**Comment by archenroot** [comment]
@afender - I will wait some time, I see lot of changes here emerging, so don't want to spend time with remapping all the time to sync with latest version... 

Q: Do you please some release I can bind JNI mapping to, or should I just at some time link it to git commit ID?

**Comment by BradReesWork** [comment]
Marking this question as closed.
Each RAPIDS release will be frozen while we move onto the next release.  Critical bug fixes (hot patches) can be done when needed.  So a JNI wrapper could be done around a release for testing

It might be better to wait until version 1.0 is release at which time the API should be stable
