### ISSUE TITLE
[ENH] Selectively enable MG C++ testing outputs for non-root processes

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#1616]
**Describe the solution you'd like**
We previously disabled all the outputs from non-root processes in MG C++ testing and this will be undone in https://github.com/rapidsai/cugraph/pull/1615 as this disables useful error messages as well.

We need a more sophisticated mechanism to disable only redundant test progress messages in long run.

We can investigate https://github.com/LLNL/gtest-mpi-listener or write our custom listeners for this purpose.

**Comment by ChuckHastings** [comment]
Closed.  Workaround in @seunghwak comment above.
