### ISSUE TITLE
[BUG] WSL 2

### ISSUE THREAD

**Issue by IdanM75** [rapidsai/cugraph#1618]
I wish I could use cuGraph to be used over window WSL 2 system.  
Today there is not support for running RAPIDS algorithms over windows WSL 2.
This feature will unlock a new world of opportunities to developers who has CUDA GPUs and Windows based OS.

**Comment by afender** [comment]
Hi @IdanM75, thanks for your feedback. 
RAPIDS is looking into WSL, in fact, we just published a blog post that may be of interest to you https://medium.com/rapids-ai/running-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux-c5cbb2c56e04
Let us know if you encounter a specific issue related to cuGraph and WSL.

**Comment by IdanM75** [comment]
Hey @afender!
First, thank you for replying.
I opened this issue after discussion in Slack where I have been told that there is no support yet on windows WSL 2, that you are working on it and to open this issue here.
I have already read those articles, mainly the [NVIDIA guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html).
The reason from the first place that I contact you is because I tired to use RAPIDS on WSL 2 and docker on top of my windows 10 PC, but every time I got the following exception from the function calls like sssp, betweenness, and from_cudf_edgelist:
`RuntimeError: CUDA error at: _deps/cuco-src/include/cuco/detail/static_map.inl74: cudaErrorInvalidDevice invalid device ordinal`

**Comment by afender** [comment]
Thank you for your patience. Seems like there is a bug involving cuco, one of cuGraph's dependencies. While we are working on WSL it's not fully tested or officially supported yet. Your feedback is very helpful to help us get there. We will update the status of this Github issue as we validate/fix WSL support.

**Comment by afender** [comment]
+cc @ChuckHastings, @seunghwak

**Comment by IdanM75** [comment]
Thank you all, 
I will wait and check for updates.
If there is something I can do and help let me know.
Have nice week.

**Comment by ChuckHastings** [comment]
Can you provide details of what GPU you are running this on?

**Comment by IdanM75** [comment]
NVIDIA GeForce RTX 2060 SUPER

**Comment by bganesh11** [comment]
If it helps, an update: I updated to Rapids 21.10 on WSL2 and it seems that the error appearing with Louvain (and Leiden) is resolved, and I was able to run both using WSL2. Thanks!
