### ISSUE TITLE
[BUG] Managed memory hangs 

### ISSUE THREAD

**Issue by antonyscerri** [rapidsai/cugraph#1635]
Hi

Before i go creating a bug thought i'd just check. I did some work Nov 2020 using 0.16 and used cuGraph to load a graph with 1.7B edges and run page rank. Picking things up now with 0.19 release i'm running into problems simply loading the graph. I'm using he same machine and environment i simply created a new conda env with the latest using:

- conda create -n rapids-0.19 -c rapidsai -c nvidia -c conda-forge     rapids=0.19 python=3.7 cudatoolkit=10.2

The problem i'm facing is that after loading the edges into a cudf initialising the DiGraph using G.from_cudf_edgelist. The machine has a single 16GB GPU, and i'm using:

- cudf.set_allocator("managed")

But the call to from_cudf_edgelist just doesn't finish. I've left it going for an hour, and both CPU usage @ 100% and GPU usage, however GPU memory usage doesn't get above 800MB. With 0.16 the graph construction took milliseconds. I've tried using a smaller edge list (440M) and it took 1.5s. Trying 880M edges failed to finish after several minutes, where as 660M edges takes about 6s, 750M took 10s, 800M took 27s.

Looked through release notes and for any obvious changes but havent come across anything, anyone have any idea what this might be being caused by, i'm thinking something to do with the unified memory maybe?

Thanks

Tony

**Comment by antonyscerri** [comment]
I've now tried installing 0.18 and it too didnt work. I then went back to 0.16 and it worked (after dropping dask back to 2.30.1 as it installed 2021.5.0 by default which didnt work alongside the other lib versions. So seems like between 0.16 and 0.18 (or one of the other required packages which dont appear to have fixed versions) something has changed to cause this issue.

**Comment by afender** [comment]
Thanks for letting us know. Looking into it!

**Comment by afender** [comment]
I realized you are using `cudf.set_allocator("managed")`,  but have you tried `rmm.reinitialize(managed=True)` to activate managed memory instead? 
Calling `rmm.reinitialize` before any cudf or cugraph calls and should have the desired effect. 
`rmm.reinitialize()` provides an easy way to initialize RMM with specific memory resource options, see help(rmm.reinitialize) for full details.
There's a [notebook](https://github.com/rapidsai/cugraph/blob/branch-21.06/notebooks/demo/uvm.ipynb) and a [blog](https://medium.com/rapids-ai/tackling-large-graphs-with-rapids-cugraph-and-unified-virtual-memory-b5b69a065d4) showing a managed memory example in cuGraph if that helps.

**Comment by antonyscerri** [comment]
i will try that now, when i used 0.16 initially i picked up on the cudf approach to handling the larger graphs, i hadnt spotted this rmm one :)

**Comment by antonyscerri** [comment]
Ok so i switched out:

`cudf.set_allocator("managed")
`
For:

```
rmm.reinitialize(managed_memory=True)
assert(rmm.is_initialized())
```
It's been running for at least 5 minutes on the step (G.from_cudf_edgelist, on a newly created DiGraph object). So at least compared to the nearest instant action in 0.16 it did not help.

**Comment by antonyscerri** [comment]
BTW I mentioned in the initial post that the GPU memory wasn't going above 800MB or so. I've been running some other code using 0.19 working on a cuDF implementation, I noticed there too the GPU memory (reported from nvidia-smi) against the python process doesn't go above 1GB, but the overall GPU memory usage is reporting a lot more being used as I would have expected (there is no other process than the python job listed). This is unlike using something like pytorch where all the gpu memory usage is recorded against the python process.

**Comment by antonyscerri** [comment]
I checked on the rmm.reinitialize vs cudf.set_allocator, seems the various libraries have helper functions that do a similar thing which all end up calling rmm.reinitialize.

**Comment by afender** [comment]
Thank you for your patience @antonyscerri. I was able to reproduce the issue with the 21.06 nightly version as well. Unified memory is an important feature that we should support. I updated the flags on the issue.

**Comment by antonyscerri** [comment]
Thanks for the update. I've also run into what might be the same issue, using cuDF. I went back and tried it with the 0.16 release and I see a similar behaviour where it works to a point and then appears to hang. In this case all I was doing was essentially doing a node degree calculation with a dataframe with a src and dst column with node ids and doing a basic group by  on the src column with built in count aggregation. As I add more rows (edges) it again gets to the point it stops. If its the same root cause then i would think something underlying the pagerank algorithm i originally saw this with changed after the 0.16 release which exhibited the same problem.

**Comment by BradReesWork** [comment]
I have tested this and updated out RMM notebook.  I do not see a hang, but it does get very slow as the size of data get much larger than GPU memory

**Comment by Ankitkurani1997** [comment]
@BradReesWork @afender 
I am trying to use cugraph and cudf with rmm.reinitialize set to managed_memory=True

Following is the code snippet

```
import rmm  
rmm.reinitialize(managed_memory=True)
import cudf
import cugraph
import time

cdf = cudf.read_csv("datasets/twitter-2010.csv", delimiter=' ', names=['src', 'dst'])
G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(cdf, source='src', destination='dst', renumber=False)
```

Using unified virtual memory 
with gpu memory of 22GB and main memory of 377GB
dataset size :- 26GB on disk 
GPU :- Tesla P40

The process for making the edgelist gets stuck or hangs, 
as it has 1.47 billion edges, 

I can process 1 billlion edges in few mins but 1.47 billion edges seems to be  not working?

Is there a reason for such behavious

I waited for more than 24 hrs but the process is not stopping

@antonyscerri did you find any work around for this issue?

I am using Rapids 22.06 version and CUDA version is 11.0
