### ISSUE TITLE
[BUG] segfault when values array is not set

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#164]
**Describe the bug**
Segfault in Louvain when the value array is not set. Currently, the user has to manually fill a column with `1.0` and attach it to the graph in order to run on unweighted graphs.
==> This also applies to spectral clustering
**To Reproduce**
Remove values from the input graph in the test.

**Expected behavior**
Python bindings should provide an array of `ones` to the C++ API when they don't already exist in the input graph.

**Comment by Iroy30** [comment]
can be closed

**Comment by afender** [comment]
done after #193
