### ISSUE TITLE
[QST] Make the precision of the Hungarian algorithm controllable

### ISSUE THREAD

**Issue by SILI1994** [rapidsai/cugraph#1645]
Hi! Is there any way to manually control the precision of the Hungarian algorithm?  I checked the [RAFT library](https://github.com/rapidsai/raft/blob/a6f3e75938f4c4b607eadc4da05af4adf183b7e4/cpp/include/raft/lap/lap_kernels.cuh#L63) and it is currently fixed to 1e-6. I found this value not accurate enough for large-size dense assignment problems.

**Comment by ChuckHastings** [comment]
There is no way, short of changing the code, to modify that parameter.  We could consider exposing that as a configurable parameter.  How large a problem are you running?  What is the range of values in your assignment problem?

**Comment by SILI1994** [comment]
I personally would appreciate it if this precision is configurable in python API. My problem is of sizes more than 10k*10k with ranges 0-2. So the current 1e-6 precision is not enough for me.
