### ISSUE TITLE
[ENH] Hungarian algorithm for rectangular matrix

### ISSUE THREAD

**Issue by SILI1994** [rapidsai/cugraph#1646]
**Describe the solution you'd like**
Hi! I found that the current implementation of the Hungarian algorithm [does not support rectangular cost matrices](https://github.com/rapidsai/cugraph/blob/637c13947fb443d42985a62a7ec904066b267224/cpp/src/linear_assignment/hungarian.cu#L47). This problem is easy to solve by adding dummy rows/columns to the cost matrix without modifying the Hungarian algorithm itself. For example:

**Describe alternatives you've considered**
```python
import numpy as np
from scipy.optimize import linear_sum_assignment

if __name__ == '__main__':

    # A rectangular cost matrix
    cost = np.random.rand(10, 15)
    true_size = min(cost.shape)

    # solve for the rectangular LAP
    r1, c1 = linear_sum_assignment(cost)

    # add in dummy rows to make rectangular matrix square
    dummy = cost.max() * np.ones((cost.shape[1] - cost.shape[0], cost.shape[1]))
    cost_new = np.concatenate((cost, dummy), axis=0)
    r2, c2 = linear_sum_assignment(cost_new)
    r2, c2 = r2[:true_size], c2[:true_size]

    print(c1)
    print(c2)


```

**Comment by ChuckHastings** [comment]
I assume, from your problem description above, that you are accessing the Hungarian algorithm from python.

It would be relatively easy to update the python as you suggest to convert the rectangular matrix to a square matrix.  Is this sufficient for your needs, or do we need to explore having the C++ code directly support a rectangular matrix?

**Comment by SILI1994** [comment]
Yeah, I am accessing it via python. This is just a suggestion and I personally think doing it in python is enough since this operation is not time-consuming.
