### ISSUE TITLE
[FEA] Degree for all nodes.

### ISSUE THREAD

**Issue by benedekrozemberczki** [rapidsai/cugraph#1678]
**Is your feature request related to a problem? Please describe.**
I would like to have a function that returns the degree of every node (possibly in and out).

**Describe the solution you'd like**
A function that takes a cugraph and returns a cudf.

**Describe alternatives you've considered**
Based on my understanding there is no easy way to do this.

**Comment by ChuckHastings** [comment]
I believe the functionality you desire is already present.  I assume that you are accessing cugraph via python (I can revisit this answer if you are accessing cugraph a different way, but please give an example of constructing your graph if it is not in python).

This unit test https://github.com/rapidsai/cugraph/blob/d01da40f0a436289bdb922f5804a7e1e7d6ed3dd/python/cugraph/tests/test_graph.py#L473

Tests the functionality of a method on the graph object called `degrees`.  This method returns a data frame containing the in degree and out degree of each vertex.  You can also call the function `in_degree` or `out_degree` if you only want the degree in a particular direction.

**Comment by benedekrozemberczki** [comment]
Lovely! Thank you for the quick answer!
