### ISSUE TITLE
[BUG] cugraph's column data become invalid if cudf dataframe objects are deleted or garbage collected.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#168]
**Describe the bug**
cuGraph's python class Graph creates a graph instance from cudf dataframe objects which hold graph data in column arrays. The Graph class currently uses C++ struct gdf_graph internally and passes pointers to the column arrays' data to a gdf_graph instance. However, this C++ struct gdf_graph does not participate in python's reference counting based garbage collection, and when the cudf dataframe objects are deleted or garbage collected, the memories assigned to the column arrays get reclaimed (python has no idea these memories are still used by C++); the pointers to the column arrays (in C++ struct gdf_graph) are no longer valid.

**To Reproduce**
Accessing invalid memory locations can lead to undefined behaviors.

**Expected behavior**
cuGraph instances should participate in python's reference counting in garbage collection for column arrays. cudf provides python class Column. If we use this Column to store column arrays, this problem problem gets solved. This maximizes code reuse as well and this is better software engineering practice in general than recreating our own solution.

The Column class provides the copy function with input parameter deep(=True). If deep is set to False, this performs shallow copy and shares memory similar to the current cuGraph implementation. If deep is set to True, deep copy is performed and creates an independent copy.

**Comment by afender** [comment]
closing after PR #190
