### ISSUE TITLE
[QST] where is NCCL cmake configuration file???

### ISSUE THREAD

**Issue by beew** [rapidsai/cugraph#1684]
I am trying to build cugraph from source but cmake  keeps complaining that it cannot find nccl. I have put the nccl libs in /usr/local/cuda/lib64 (and the header files in /usr/local/cuda/include) following Nvidia's installation guide. 

cugraph is looking for a nccl cmake config file but there is no such a thing in the tar ball I downloaded from Nvidia, there is a .pc file, I have copied it to /usr/local/cuda/pkconfig but cugraph doesn't like it, still demanding cmake config.

Where is this file??

cuda 11.0, nccl-2.9.8, OS Ubuntu 20.04 Linux,  cugraph 21.06.00

**Comment by rlratzel** [comment]
Hi @beew , sorry for the delay.

As you noticed, NCCL does not include a cmake configuration, however, the cugraph build should be working around that by generating one as part of the build process [here](https://github.com/rapidsai/cugraph/blob/9bcfa146103a4d17803da9b7605c3368c9558e51/cpp/cmake/thirdparty/get_nccl.cmake#L27).  Can you provide the error message(s) you're seeing so we can get a better idea of how to debug?
