### ISSUE TITLE
[FEA] cuGraph needs to provide an option to deep copy cudf dataframe objects when creating a cugraph instance

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#170]
**Is your feature request related to a problem? Please describe.**
cuGraph creates a graph from cudf dataframe objects which store graph data in column arrays. A created cuGraph instance shares the memory locations with cudf dataframe objects. If cudf dataframe objects are modified, the cugraph instance's data get changed as well. This behavior is not always desirable.

Pandas dataframe provide an option to create a new instance by either deep copying or shallow copying (https://stackoverflow.com/questions/44993846/pandas-dataframe-mutability). cuGraph needs to provide this option as well.

**Describe the solution you'd like**
cudf class Column already provides the copy function with input parameter deep. This issue may better be addressed together with https://github.com/rapidsai/cugraph/issues/168

**Task List**
1. First solve https://github.com/rapidsai/cugraph/issues/168
2. Then, update cugraph's API similar to that of Pandas and properly set the input parameter deep in creating column arrays.

**Comment by afender** [comment]
CuGraph still needs to be able to reuse cuDF's memory directly without a copy. This should remain the default behavior.

**Comment by seunghwak** [comment]
Got it, and copy is set to False by default in Pandas as well (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html). So I think we should set copy to False by default as well.

**Comment by afender** [comment]
Closing after #190
