### ISSUE TITLE
[BUG] test_mg_pagerank fails with RuntimeError

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#1714]
test_mg_pagerank returns the following RuntimeError for `PERSONALIZATION_PERC=50` when using 3, 4, 5, 6, 7 and 8 GPUs on DGX18

`distributed.worker - WARNING - Compute Failed
Function:  call_pagerank
args:      (b'4\x15\xae\xd9Z\x1cA\xb4\x9e\x0f-\xf1IwH\xfd', [   dst  src
0   18    1
1   21   13
2   19   13
3   18   13
4   18   17
5   18    5
6   18    6
7   18   11
8   18    8
9   18   14], 34, 156, 0     0
0     0
1     2
2     9
3    14
4    20
5    26
6    30
7    34
dtype: int32, [0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 6, 0, 0, 0, 4], 0.85, 100, 1e-06, Empty DataFrame
Columns: [vertex, values]
Index: [], None)
kwargs:    {}
Exception: RuntimeError('cuGraph failure at file=/jnke/PR_4/cugraph/cpp/src/experimental/graph.cu line=267: Invalid input argument: edgelists[] have out-of-range values.\nObtained 33 stack frames\n#0 in /jnke/PR_4/cugraph/python/cugraph/community/louvain_wrapper.cpython-38-x86_64-linux-gnu.so(_ZN4raft9exception18collect_call_stackEv+0x4e) [0x7f3eb427b0fe]\n#1 in /opt/conda/envs/rapids/lib/libcugraph.so(_ZN7cugraph11logic_errorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xcd) [0x7f3e54a98f0d]\n#2 in /opt/conda/envs/rapids/lib/libcugraph.so(_ZN7cugraph12experimental7graph_tIiifLb1ELb1EvEC1ERKN4raft8handle_tERKSt6vectorINS0_10edgelist_tIiifEESaIS9_EERKNS0_11partition_tIiEEiiNS0_18graph_properties_tERKSt8optionalIS7_IiSaIiEEEb+0x7d7) [0x7f3e5507e307]\n#3 in /opt/conda/envs/rapids/lib/libcugraph.so(_ZN7cugraph6cython6detail12create_graphIiifLb1ELb1ELPv0EEESt10unique_ptrINS_12experimental7graph_tIT_T0_T1_XT2_EXT3_EvEESt14default_deleteISA_EERKN4raft8handle_tERKNS0_17graph_container_tE+0x3e5) [0x7f3e54ae4a05]\n#4 in /opt/conda/envs/rapids/lib/libcugraph.so(_ZN7cugraph6cython13call_pagerankIifEEvRKN4raft8handle_tERKNS0_17graph_container_tEPT_PT0_S9_SA_SC_ddlb+0x580) [0x7f3e54ae9730]\n#5 in /jnke/PR_4/cugraph/python/cugraph/dask/link_analysis/mg_pagerank_wrapper.cpython-38-x86_64-linux-gnu.so(+0x4105b) [0x7f3e6c42905b]\n#6 in /opt/conda/envs/rapids/bin/python(PyCFunction_Call+0x54) [0x55ca54c4b914]\n#7 in /opt/conda/envs/rapids/bin/python(_PyObject_MakeTpCall+0x31e) [0x55ca54c4eebe]\n#8 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x7203) [0x55ca54cf2893]\n#9 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#10 in /opt/conda/envs/rapids/bin/python(PyObject_Call+0x5e) [0x55ca54c3db6e]\n#11 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x21bf) [0x55ca54ced84f]\n#12 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#13 in /opt/conda/envs/rapids/bin/python(PyObject_Call+0x5e) [0x55ca54c3db6e]\n#14 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x21bf) [0x55ca54ced84f]\n#15 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#16 in /opt/conda/envs/rapids/bin/python(+0x1333b4) [0x55ca54c4f3b4]\n#17 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x62ba) [0x55ca54cf194a]\n#18 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#19 in /opt/conda/envs/rapids/bin/python(PyObject_Call+0x5e) [0x55ca54c3db6e]\n#20 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x21bf) [0x55ca54ced84f]\n#21 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#22 in /opt/conda/envs/rapids/bin/python(+0x1333b4) [0x55ca54c4f3b4]\n#23 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0x62ba) [0x55ca54cf194a]\n#24 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#25 in /opt/conda/envs/rapids/bin/python(_PyEval_EvalFrameDefault+0xa63) [0x55ca54cec0f3]\n#26 in /opt/conda/envs/rapids/bin/python(_PyFunction_Vectorcall+0x1a6) [0x55ca54cd3646]\n#27 in /opt/conda/envs/rapids/bin/python(+0x1b7ed1) [0x55ca54cd3ed1]\n#28 in /opt/conda/envs/rapids/bin/python(PyObject_Call+0x5e) [0x55ca54c3db6e]\n#29 in /opt/conda/envs/rapids/bin/python(+0x255639) [0x55ca54d71639]\n#30 in /opt/conda/envs/rapids/bin/python(+0x1ee9c4) [0x55ca54d0a9c4]\n#31 in /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f3f280b16db]\n#32 in /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f3f2742d71f]\n')`

**Comment by BradReesWork** [comment]
closing by PR 1764 that has been merged
