### ISSUE TITLE
[BUG] gpuCIv2/cugraph/gpu and gpuCIv2/cugraph/prb/cugraph-prb fail

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#173]
**Describe the bug**
gpuCIv2/cugraph/gpu and gpuCIv2/cugraph/prb/cugraph-prb fail. It seems that cuda pkg version is 10.0 which conflicts with the nvgraph library which accesses 9.2. 

Ishika found that this seems like a recent change because for PR #165 (https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCIv2%2Fcugraph%2Fprb%2Fcugraph-gpu-build/detail/cugraph-gpu-build/39/pipeline) line 79 has cuda version 9.2 and it builds correctly. 

**To Reproduce**
rerun cugraph build/tests on the platform

**Expected behavior**
Expected to pass

**Screenshots**
https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/gpuCIv2%2Fcugraph%2Fprb%2Fcugraph-gpu-build/detail/cugraph-gpu-build/48/pipeline

**Comment by afender** [comment]
cc @Iroy30 and @raydouglass

**Comment by raydouglass** [comment]
This was fixed by this commit: https://github.com/rapidsai/cugraph/commit/4d30dfa93c0971982d223a01fdd7ee231dc60598
