### ISSUE TITLE
[ENH] Clearer `None` warnings during chained use

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cugraph#1733]
**Scenario motivating the issue**
When (incorrectly) attempting to use the API in a pipeline (`cugraph.Graph().add_edges(...).louvain()..`), I hit some hard to decipher error messages. These mostly came down to deep internal messages due to passing in `None`, which was getting passed in because imperative commands are non-chainable so they return `None` instead of `G`, and I missed that.

**Describe the solution you'd like**
Methods should have a `None` check, at least for the `G` position

**Describe alternatives you've considered**
I was also thinking about how to make the library more compositional
- The naive solution would be to make methods return `G`
- ... but that will be confusing. There is value in keeping side-effect operations clearly imperative via `None` returns, as otherwise folks may mutate data they think immutable
- Some libraries like pandas try to track this -- `G' = G.effect()` and mark `G'` as a view of a stateful obj, so `G'.effect()` can give a warning that it is unsafe
- While others go truly functional, which would change the side-effecting methods to functional... which is a deeper change

So I figured, at least for interim, going compositional will be hard. So instead, should make it easier to tell users that they shouldn't be going compositional. So, a `is None` check on the `G` position would go far.

cc @BradReesWork

**Comment by BradReesWork** [comment]
@lmeyerov I am trying to come up with a good solution to the problem posed.  We would just echo back the graph, but as you stated, that might lead developers to believe that the return is different (mutated).  A `Graph` is a stateful python class that adheres closer to  object-oriented programming than functional.  The problem that you mention is that we do mix our models

**Comment by lmeyerov** [comment]
Yeah -- I think long-term it's smart to go functional, and agree that near-term tricky to clearly do both. 

The immediate issue is a rocky experience for new + intermittent users for the current API, which is a much easier hill to climb :) There are probably 20-50 top-level `cugraph.some_method(G, ...)` calls, so an intermediate fix is:

1. runtime type contract check, at least for G position <- best cost/reward ratio?

```python
def some_method(G):
  assert_type(G, cugraph.Graph, 'Method expected parameter G of type cugraph.Graph but received %s', type(G))
  ...
```

or even

```python
@assert_G
def some_method(G):
  ...
```

2. `typing` annotations on the signature. Good for docs, and some IDE users, but probably not remote IDE ones <-- may already be there, and if not, seems best for py3.7+, which is a judgement call..

```python
def some_method(G: cugraph.Graph, ...) -> None`
```

**Comment by BradReesWork** [comment]
We are going to address this issue in the upcoming NetworkX compatibility module.   That module will allow us to better wrap existing function so that we can provide pipelining.  

I am going to mark this issue as closed but add the pi0pelining feature as a requirement on the module
