### ISSUE TITLE
[BUG] Pagerank errors on float64 weights

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cugraph#1737]
**Describe the bug**
Pagerank throws a misleading exn about requiring positive weights when weights are a `float64` series (`df.assign(ew=1.0)`), and the error goes away when cast to `float32`

It's fine if `float32` is required, but should improve the error message to a dtype error

**Steps/Code to reproduce bug**

```python
import cudf, cugraph, pandas as pd
fb_df = (
    pd.read_csv(
        'https://raw.githubusercontent.com/graphistry/pygraphistry/master/demos/data/facebook_combined.txt',
        sep=' ')
    .rename(columns={'0': 's', '1': 'd'})
)
fb_df['ew'] = 1.0
fb_gdf = cudf.DataFrame(fb_df)
G = cugraph.Graph()
G.from_cudf_edgelist(
            fb_gdf,
            source='s',
            destination='d',
            edge_attr='ew',
            renumber=True)
pagerank_df = cugraph.pagerank(G)
```
=>

```
cuGraph failure at file=../src/experimental/pagerank.cu line=110: Invalid input argument: input graph should have postive edge weights.
```

**Expected behavior**
Pagerank computed or a clear error about requiring `float32` dtype

**Environment overview (please complete the following information)**

conda 0.19 / docker / pascal

**Comment by ChuckHastings** [comment]
This looks like a python issue.  I notice that `df['pagerank']` is hard-coded to `np.float32` instead of matching the type of weights.  The mismatch of types would likely confuse the C++ code.

**Comment by jnke2016** [comment]
Yes . @kaatish mentioned it 2 days ago. I am pushing a fix for that in a bit
