### ISSUE TITLE
[FEA] [SNMG PageRank] SNMG Degree

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#175]
**Is your feature request related to a problem? Please describe.**
SNMG PagerRank needs an SNMG function that compute the degree of each vertex. 

**Describe the solution you'd like**

1.  **Input** 
- An array of size E (32-bit ints) where each GPU has a chunk of this array. In the pagerank case, this is the “destination” array. Vertex Ids are 0-based indexed.
- The number of vertices

2. **Output** 
- An array of size V (32-bit ints): each GPU has the full array containing the degree of all vertices 

3. **Implementation**
Each GPU can use the existing degree kernel in cuGraph to get the degree based on the local information it has. 
Then, all local results need to be reconciled. This should be done in a P2P way rather than gather/broadcast as we should assume that a single GPU doesn’t have enough memory to gather the data of every GPU. I am thinking about a reduction three for that but there might be other options.

4. **Generalize**
The solution above describes what is needed for pagerank case but we should expose a more general function that does like #188 / #210. 

Needs OpenMp and NVlink technologies.
32-bit is needed but the code should be templated to allow 64bit offsets in the future

**Task List**
- [x] CUDA Implementation 
- [x] Tests : verify the result by comparing to the single GPU version
- [x] API : this feature needs to be exposed in cugraph's API following the same API as the single GPU one. In addition, this needs to interact well with other SNMG PageRank functions.

**Comment by jwyles** [comment]
The current python API has the degree calculation as a method of the Graph object, Are we going to have a distributed graph object for this to work on, or are we going to use a different API?

**Comment by afender** [comment]
For the C++ API I think we can just get `gdf_columns` and partition offsets (like in snmg spmv). This is very flexible and allows to build any python API on top of it. 

For python, we don't have a multi-GPU graph object yet. We need to have a discussion on the API. This issue is really about the cuda part (python work is tracked in #179)
