### ISSUE TITLE
[FEA] Weak Connected Components

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#180]
We need to take connected components out of cuML and move it into cugraph

This needs to be exposed in cugraph in C++ and Python API. Tested and documented.

The first step is to identify if there are any missing pieces or if we can just transfer code, tests, and bindings directly.

**Comment by BradReesWork** [comment]
How cuML is storing and processing data might be as an edge list which limits graph sizes.  Andrei will continue working with Corey on issue

**Comment by jakirkham** [comment]
What other ways would you envision storing and working with data?

Part of my reason for asking is image processing leverages [connected component labeling]( https://en.wikipedia.org/wiki/Connected-component_labeling ) to cluster pixels into objects based on connectivity. I don't know if this in scope at all for this issue or repo, but thought I'd raise the use case to see if it is of interest.

**Comment by afender** [comment]
> What other ways would you envision storing and working with data?

adjacency list (CSR matrix) representation needs less memory and has more options for vectorization. It is a tradeoff because this format is less flexible.

As for image processing, it may work depending on the properties of the graph you have. I'd recommend giving it a try when it is ready. What solutions are you using/considering currently?

**Comment by afender** [comment]
Addressed as part of #331. Please remember to add "close < issue_number >"  in PRs when applicable
