### ISSUE TITLE
[DOC] RMAT generator API example code is not formatted correctly

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1828]
The example python code is not formatted correctly:
https://docs.rapids.ai/api/cugraph/stable/api.html#module-cugraph.generators

cc @ChuckHastings

**Comment by ChuckHastings** [comment]
Same as #1807 ?

**Comment by rlratzel** [comment]
> Same as #1807 ?

Yep, sorry about the duplicate.
