### ISSUE TITLE
[BUG] cpp/src/cugraph.cu compiler wanrings.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#184]
**Describe the bug**
Compiling cpp/src/cugraph.cu produces the following compiler warnings.

/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu: In lambda function:
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_invalid’ not handled in switch [-Wswitch]
     switch(col->dtype){
        ^
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_INT16’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_INT64’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_DATE32’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_DATE64’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_TIMESTAMP’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_CATEGORY’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘GDF_STRING’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:407:8: warning: enumeration value ‘N_GDF_TYPES’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu: In lambda function:
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_invalid’ not handled in switch [-Wswitch]
     switch(col->dtype){
        ^
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_INT16’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_INT64’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_DATE32’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_DATE64’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_TIMESTAMP’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_CATEGORY’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘GDF_STRING’ not handled in switch [-Wswitch]
/home/seunghwak/RAPIDS/cugraph/cpp/src/cugraph.cu:439:8: warning: enumeration value ‘N_GDF_TYPES’ not handled in switch [-Wswitch]

**Comment by jwyles** [comment]
I will start working on this. Please assign to me.
