### ISSUE TITLE
[QST] Compatibility with PyTorch > 1.8 (CUDA) 

### ISSUE THREAD

**Issue by JulianKu** [rapidsai/cugraph#1861]
I would like to use cugraph together with a recent `PyTorch` version (for use of `PyTorch Geometric`). However, I find no way of installing both in a conda environment.
[Official PyTorch Geometric conda releases](https://anaconda.org/pyg/pyg) exist for PyTorch 1.8 and 1.9 (with CUDA 10.2 or 11.1 for PyTorch 1.9 and additionally CUDA 10.1 for PyTorch 1.8).
The problem is that there is no rapids version working with either of these CUDA versions. conda packages for `rapids` only work with CUDA 11.0 and 11.2 (not 11.1).

Is there a reason why rapids is not available for any CUDA version that is supported by recent PyTorch versions (>1.8)?

**Comment by BradReesWork** [comment]
@JulianKu CUDA 11 introduce a new comparability feature, so you should be able to sure the 11.2 version of RAPIDS on a 11.1 version of CUDA

**Comment by wangxiaoyunNV** [comment]
Hi @JulianKu 
I am wondering how you set up the environment with conda? Did you try to create a Rapids conda env, and then install pytorch inside of this env?  Or did you used container? Conda env+ install pytorch inside the env should work.
https://rapids.ai/start.html

Best,
Xiaoyun

**Comment by JulianKu** [comment]
Hi @BradReesWork and @wangxiaoyunNV ,
thank you for your fast responses.

So far, I have tried multiple configurations to set up rapids together with pytorch (all of them are conda, so no container).
I tried setting up the rapids environment as described on [https://rapids.ai/start.html](https://rapids.ai/start.html), i.e.
`conda create -n rapids-pytorch -c rapidsai -c nvidia -c conda-forge \
    rapids=21.08 python=3.8 cudatoolkit=11.2`
When I try to install PyTorch afterwards with `conda install pytorch=1.9 -c pytorch`, I get problems because conda pytorch requires `cudatoolkit >=11.1,<11.2` (same goes for `pytorch=1.8`).

On the other hand, when I try to set up the rapids environment with cudatoolkit=11.1, I either get an error that rapids requires cudatoolkit=11.2 (for python 3.8) or cudatoolkit=11.0 (for python 3.7). So no success there.

The other way around, I create a pytorch environment first with
`conda create -n rapids-pytorch -c pytorch -c nvidia -c conda-forge \
    pytorch python=3.8 cudatoolkit=11.1`
(`cudatoolkit=11.0` and `cudatoolkit=11.2` would not work as they would only install pytorch for cpu)
Then, I try to install rapids with `conda install -c rapidsai -c conda-forge rapids=21.08`
which somehow gives me an error as now rapids requires `cudatoolkit >=11.4.0,<11.5.0a0`.

I also tried setting up both upon creation of the environment with no versions specified for rapids and pytorch, i.e.
`conda create -n rapids-pytorch -c rapidsai -c pytorch -c nvidia -c conda-forge rapids pytorch python=3.8 cudatoolkit=11.1`
but this only resolves for rapids=0.0.1 (pytorch set to 1.9).
With versions specified for rapids and/or pytorch, I get the same errors as in the separated setups described above.

**Comment by wangxiaoyunNV** [comment]
We use the same ubuntu version, but a different driver version, I use 460.91.03. I will follow up with our container people to see why there are conflicts. And if there are any performance issues, for example, cugraph runs slow in some functions please also let me know.

Thank you!

**Comment by JulianKu** [comment]
I already thought so...
Problem is that I need PyTorch >= 1.8 to be able to use a recent version of [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/). 
But then I'll simply need to wait for PyTorch supporting CUDA >= 11.2 and figure it out somehow else in the meantime.

Thanks again for your efforts!
