### ISSUE TITLE
[FEA] Expose a degree function (snsg)

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#188]
We need to expose a function to compute the degree of all vertices. It should allow computing in_degree, out_degree, and in+out degree. 

The following kernel accepts indices and returns the number of occurrences of all vertices:
https://github.com/rapidsai/cugraph/blob/a389189d1637dd2b6610043f1e2b9713a19be4f2/cpp/src/graph_utils.cuh#L300

Subtasks checklist for python:

- [ ]  Python bindings and API (may include some adjustments of the C++/CUDA part)
- [ ]  Pytest testing against NetworkX
- [ ]  Documentation
- [ ]  Validate everything in Jenkins

**Comment by Iroy30** [comment]
can be closed?

**Comment by afender** [comment]
Yes, closing after #210
