### ISSUE TITLE
[BUG][NV]Small improvements of existing python bindings

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#19]
- Change PageRank to be 32bits (and update the test)
- Add gdf error check
- Remove .h files in python directory
- Put general helper functions outside of Pagerank file/folder
- Change transpose behaviour so that it can be called multiple times without returning an error

**Comment by Iroy30** [comment]
PR #15

**Comment by afender** [comment]
Addressed _"Change transpose behaviour so that it can be called multiple times without returning an error"_ in dd04503 (PR #20)

**Comment by afender** [comment]
Closing. Addressed in PR #15 and #20
