### ISSUE TITLE
[FEA] Add `doctest` coverage to CI scripts

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1904]
cuGraph code examples in docstrings  need to be tested on a regular basis to ensure they're correct, not only because users rely on docstrings in the APIs, but also because the examples in docstrings are included in the generated online help docs.

This is mostly a placeholder issue at the moment, and more details will be included in a later update.

cc @bdice

**Comment by BradReesWork** [comment]
closed
