### ISSUE TITLE
Need to update calls to cuDF `Series` ctors when calling with a `Buffer` type

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1908]
https://github.com/rapidsai/cudf/pull/9370 changed support for how`Series` object are to be constructed with `Buffer` objects.

For instance, this example is no longer supported:
```
import numpy as np
import cudf

tmp = cudf.Series([1, 2, 3])
print(tmp);

buffer = cudf.core.buffer.Buffer(tmp.data)
tmp2 = cudf.Series(data=buffer, dtype=np.dtype("int32"))
print(tmp2)
```

The supported pattern is now:
```
...
buffer = cudf.core.buffer.Buffer(tmp.data)
col = cudf.core.column.build_column(buffer, dtype=np.dtype("int32"))
tmp2 = cudf.Series._from_data({SERIES_NAME: col})
```

cc @ChuckHastings @vyasr

**Comment by vyasr** [comment]
OK sounds good @rlratzel I don't know if we necessarily need to have a dedicated conversation for this, that's up to you (perhaps after you've planned more of your refactoring). I'll keep alerting you (and marking relevant PRs) as we make further internal changes in cuDF that may impact you.
