### ISSUE TITLE
[FEA] Extend induced_subgraph for MNMG

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#1910]
**Is your feature request related to a problem? Please describe.**
Induced subgraph extraction code currently does not support MNMG.
https://github.com/rapidsai/cugraph/blob/branch-21.12/cpp/src/structure/induced_subgraph_impl.cuh#L119

**Describe the solution you'd like**
Needs to be updated to support MNMG.

**Comment by ChuckHastings** [comment]
Superseded by #2502
