### ISSUE TITLE
[FEA] MNMG triangle counting.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#1912]
**Is your feature request related to a problem? Please describe.**
We need a triangle enumeration/counting mechanism.

We should be able to count triangles for every vertex (e.g. to implement clustering coefficient) AND/OR edge (e.g. to implement K-truss) AND/OR enumerate triangles (requiring memory large enough to store the entire set of triangles only if a caller requests to enumerate triangles as well).

**Describe the solution you'd like**
#1909 & #1911 will be a pre-requisite for this.

1)  We first keep the edges that are only in 2-core & from the lower degree vertex to the higher degree vertex. We can do this using #1909 & #1911 

2) After 1), there are two competing approaches. One is to find intersection on the source & destination vertices' neighbors, and the second is to iterate over wedges created by picking a vertex and a pair of vertices from the vertex's neighbor list and querying the existence of the edge between the pair. Need to evaluate their pros & cons in the context of cuGraph.

**Comment by ChuckHastings** [comment]
C++ definition and implementation addressed by #2233 and #2253
C API definition addressed by #2271

C API implementation TBD

**Comment by ChuckHastings** [comment]
C API implementation in #2302
