### ISSUE TITLE
[BUG] nvLouvain API gave wrong results

### ISSUE THREAD

**Issue by tianhaox** [rapidsai/cugraph#197]
**Describe the bug**
The nvLouvain API gave wrong results under branch 0.7 (This API will crash under branch 0.6/master). 

**To Reproduce**
1. Code:
```
src_list = [7,2,3,1,4,5,6,1]
dst_list = [2,3,1,4,5,6,4,0]
# cugraph
src = cudf.Series(src_list)
dst = cudf.Series(dst_list)
G = cugraph.Graph()
G.add_edge_list(src,dst,None)
cu_parts, cu_mod = cugraph.nvLouvain(G)

# nx
Gnx = nx.Graph()
Gnx.add_edges_from(list(zip(src_list, dst_list)))
nx_parts = community.best_partition(Gnx)

# compare
cu_map = {0: 0}
for i in range(len(cu_parts)):
    cu_map[cu_parts['vertex'][i]] = cu_parts['partition'][i]
cu_mod_nx = community.modularity(cu_map, Gnx)
nx_mod = community.modularity(nx_parts, Gnx)
#
print("cu_mod_nx: %f,  nx_mod: %f"%(cu_mod_nx, nx_mod))
```

**Expected behavior**
Should give same results as that given by community.best_partition (cu_mod_nx=nx_mod)

**Screenshots**
cu_mod_nx -> 0，nx_mod ->0.398438

**Desktop (please complete the following information):**
 - OS: Ubuntu16.04
 - Version cudf0.6+cugraph0.7(build from source)

**Additional context**

**Comment by BradReesWork** [comment]
The identified bug is a well know resolution issue with Modularity against small graphs.  There is a similar issue with very large graphs.  The algorithm works as specified in the Louvain paper.  We are looking at providing additional analytics based on newer extensions to Louvain/Modularity that address the known issues
