### ISSUE TITLE
why import cugraph not working in kaggle?

### ISSUE THREAD

**Issue by SouAdr01** [rapidsai/cugraph#1972]
I need to use cugraph in kaggle forthat i install rapids with this code:

    import sys
!cp ../input/rapids/rapids.21.06 /opt/conda/envs/rapids.tar.gz
!cd /opt/conda/envs/ && tar -xzvf rapids.tar.gz > /dev/null
sys.path = ["/opt/conda/envs/rapids/lib/python3.7/site-packages"] + sys.path
sys.path = ["/opt/conda/envs/rapids/lib/python3.7"] + sys.path
sys.path = ["/opt/conda/envs/rapids/lib"] + sys.path 
!cp /opt/conda/envs/rapids/lib/libxgboost.so /opt/conda/lib/

then,
conda install -c nvidia -c rapidsai -c numba -c conda-forge cugraph cudatoolkit=11.4

but cugraph not installed, usually i have this error:
 ModuleNotFoundError                       Traceback (most recent call last) /tmp/ipykernel_241/370751810.py in <module>
----> 1 import cugraph

ModuleNotFoundError: No module named 'cugraph'

**Comment by rlratzel** [comment]
Hi @SouAdr01 , can you provide the following:
* Any messages from the output of the `conda install` command you used that indicate if cugraph was or was not installed successfully.
* The conda environment you're installing to. Based on the code you're using to update `sys.path`, it seems like it's assumed to be installed in the `rapids` environment, but we should confirm this.
* The conda environment you've activated when you run the code that produces the `ModuleNotFoundError`. We should confirm that the conda environment cugraph is installed to is being used for the code you're running.

@taureandyernv - I'm not familiar with kaggle, so do you have any suggestions on how to debug this? I suspect this may be specific to kaggle.

**Comment by BradReesWork** [comment]
Did you try


conda install -c rapidsai -c nvidia -c conda-forge cugraph=21.10 python=3.7 cudatoolkit=11.4

I do not see the cugraph version number in your description

**Comment by taureandyernv** [comment]
@SouAdr01 , Kaggle only has cudf and cuml installed on its kernel.  you will need to manually install cugraph and any other RAPIDS library with this, run as code, in your kaggle notebook:

```
!conda install -y -c rapidsai -c nvidia -c conda-forge cugraph=21.08 python=3.7 cudatoolkit=11.0
```

In the future, as Kaggle updates the default RAPIDS version, you will need to change the `21.08` to the current version that is being run in the Kaggle kernel.  They may also update their CUDA toolkit and python versions.  You can quickly find out what versions are installed by running this in your cell:

```
!conda list | grep -E 'cudatoolkit|cudf|python'
```

You will get an output like this (shortened for clarity on what to look for):
```
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      21.08.03        cuda_11.0_py37_ge4313b6a1e_0    rapidsai
python                    3.7.10          hb7a2778_101_cpython    conda-forge
```
For RAPIDS (cudf), cuda toolkit,  and python, you only need `<x>.<y>` for the install parameters.  discard the other numbers after the second `.`
e.g: `<x>.<y>`, becomes `21.08`.

You can also ask Kaggle to include cugraph in their kernel :).

**Comment by rlratzel** [comment]
@SouAdr01 - I'll close this with the assumption that @taureandyernv 's suggestion solved the problem.  We can re-open this issue if you're still having the same problem.
