### ISSUE TITLE
[FEA] flake8 for cython

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#199]
**Is your feature request related to a problem? Please describe.**
cuGraph currently runs flake8 on python files. We need to run flake8 for cython files as well to improve code base consistency.

**Describe the solution you'd like**
We may see some false positives if we run flake8 on cython files, and it seems like we are not the first to have this problem. The following link sounds like a good starting point.

https://sgoel.org/posts/setting-up-flake8-for-cython/

**Comment by dantegd** [comment]
I literally was writing the same issue for cuML right now. Actually there are quite a few related projects that already have a cython pep8 style that skip a number of rules, for example pyarrow: https://github.com/apache/arrow/blob/master/python/.flake8.cython

**Comment by raydouglass** [comment]
The style checks are controlled by this script: https://github.com/rapidsai/cugraph/blob/branch-0.7/ci/checks/style.sh

Should be straight forward to add a flake8 config and update the flake8 call in that script.

**Comment by seunghwak** [comment]
rapidsai/cudf
[REVIEW] Add isort, black, and cython flake8 to the style checker, fix existing style issues 
https://github.com/rapidsai/cudf/pull/2307

We should bring this to cuGraph as well.

**Comment by kkraus14** [comment]
@seunghwak if you need any help with the implementation just let me know, this was fun 😅

**Comment by seunghwak** [comment]
@BradReesWork Why does this issue get closed? If this issue has not been addressed, shouldn't we better move this to the restructuring phase?
