### ISSUE TITLE
[DOC] The html help for `multi_source_bfs` is not present in the online docs

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2012]
`cugraph.multi_source_bfs` has a docstring, but it is not showing in the online docs.  It should be present under `traversal` with `bfs` : https://docs.rapids.ai/api/cugraph/stable/api_docs/traversal.html

**Comment by rewaza** [comment]
Hello, is this feature implemented? I'm receiving an error:

>>> import cugraph
>>> import cudf
>>> import pandas as pd
>>> from datetime import datetime

>>> s_time = datetime.now()
>>> dfs = pd.read_csv("/nodes/small.csv")
>>> data = {'source': [1,1,3,2],
...         'target': [7,5,7,6]}
>>> rcdf = pd.DataFrame(data)
>>> cuda_g = cudf.DataFrame.from_pandas(dfs)
>>> cuda_nc = cudf.DataFrame.from_pandas(rcdf)
>>> G = cugraph.Graph()
>>> G.from_cudf_edgelist(cuda_g, source='source', destination='target', edge_attr='cost')
>>> sources = set(rcdf.iloc[:, 1])
>>> def msources(s):
...     gr = cugraph.multi_source_bfs(G, s)
...     print(gr[0])
... 
>>> msources(sources)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in msources
  File "/home/c2f/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/cugraph/traversal/ms_bfs.py", line 249, in multi_source_bfs
    raise NotImplementedError(
NotImplementedError: concurrent_bfs is coming soon! Please up vote the github issue 1465             to help us prioritize
