### ISSUE TITLE
[QST] Is multi_source_bfs implemented in nightly (22.02) version or in stable (21.12) version?

### ISSUE THREAD

**Issue by rewaza** [rapidsai/cugraph#2018]
I was looking for an efficient way to get all pairs short paths from graphs. According to this [post](https://stackoverflow.com/questions/70632337/how-to-accelerate-finding-all-pairs-shortest-path-with-gpu-using-rapids-cugraph) multi_source_bfs function should work but I'm receiving an error: line 249, in multi_source_bfs raise NotImplementedError(NotImplementedError: concurrent_bfs is coming soon! Please up vote the github issue 1465 to help us prioritize) Is this feature implemented in nightly (22.02) version or in stable (21.12) version? 

Here's an example of my code:
>>> import cugraph
>>> import cudf
>>> import pandas as pd
>>> from datetime import datetime
>>> s_time = datetime.now()
>>> dfs = pd.read_csv("/xxx/small.csv")
>>> data = {'source': [1,1,3,2],
...         'target': [7,5,7,6]}
>>> rcdf = pd.DataFrame(data)
>>> cuda_g = cudf.DataFrame.from_pandas(dfs)
>>> cuda_nc = cudf.DataFrame.from_pandas(rcdf)
>>> G = cugraph.Graph()
>>> G.from_cudf_edgelist(cuda_g, source='source', destination='target', edge_attr='cost')
>>> sources = set(rcdf.iloc[:, 1])
>>> def msources(s):
...     gr = cugraph.multi_source_bfs(G, s)
...     print(gr[0])
>>> msources({1,2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in msources
  File "/xxx/anaconda3/envs/rapids-22.02/lib/python3.8/site-packages/cugraph/traversal/ms_bfs.py", line 249, in multi_source_bfs
    raise NotImplementedError(
NotImplementedError: concurrent_bfs is coming soon! Please up vote the github issue 1465             to help us prioritize

Thank you!

**Comment by BradReesWork** [comment]
Currently there is no easy way to get all pair shortest path.   We are planning on implementing a version of that and are hoping that we can squeeze it into this years roadmap.  The multi-seed bfs/sssp code assume one seed per component.  If you have a small graph, you can replicate the data into a number of disjoint components and then do one seed per component and rebuild the all-paths answer

**Comment by ChuckHastings** [comment]
Based on latest road map discussion this will not be addressed until later in 2023.
