### ISSUE TITLE
[BUG] online html docs for `hypergraph` are missing

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2022]
The [section on Graph classes](https://docs.rapids.ai/api/cugraph/stable/api_docs/structure.html) in the online docs does not appear to include [hypergraph](https://github.com/rapidsai/cugraph/blob/branch-22.02/python/cugraph/cugraph/structure/hypergraph.py).

cc @bryevdv

**Comment by betochimas** [comment]
PR #2014 addressed this and it's been in the online documentation since the end of 22.02
