### ISSUE TITLE
[ENH] Add MG HITS to the cugraph Python API

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2026]
The `libcugraph` C++ library now supports multi-GPU HITS.  The `cugraph` and `pylibcugraph` python APIs needs to be extended to provide an API to use this.
- [ ] Need C API updated to include HITS and MG HITS (attn: @ChuckHastings)
- [ ] Add HITS APIs (and tests) to `pylibcugraph` that call C APIs
- [ ] Add HITS APIs (and tests) to `cugraph` that call `pylibcugraph` APIs
- [ ] Add docstrings and examples

**Comment by ChuckHastings** [comment]
Depends on #2091 and #2092
