### ISSUE TITLE
[BUG] Remove cudatoolkit from conda env

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#205]
Our current python tests require to do `conda install cudatoolkit`. This is requiered bu numba. This is a source of conflict with the cuda toolkit already installed on the machine which is used by all other parts of the project.

Notice that cuDF doesn't have this dependency.

When the conda installed cuda toolkit is missing, the following error shows up:
`numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found.`

It seems that one possible fix is to set :
```
NUMBAPRO_NVVM=<path to cudatoolkit>/cuda/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE=<path to cudatoolkit>/cuda/nvvm/libdevice/
```

**Comment by Iroy30** [comment]
there is a way to incorporate it into the environment after the environment creation. Running a one time bash script for setting the necessary variables in activate.d and deactivate.d ensures the environment sets them whenever it is activated.

**Comment by BradReesWork** [comment]
Waiting to see how cuDF addressing the issue

**Comment by afender** [comment]
@Iroy30  I just talked to Dante. It seems cuML addressed it. They set the proper NUMBA variables in the .profile of the shell (same as cuDF)

**Comment by afender** [comment]
conda's cudatoolkit became a dependency of all rapids projects. closing.
