### ISSUE TITLE
[ENH] Add `node2vec` API to cugraph

### ISSUE THREAD

**Issue by betochimas** [rapidsai/cugraph#2058]
node2vec has been implemented in libcugraph, in the C++ library. The task is to add the API to `pylibcugraph` and `cugraph`, as well as writing tests and writing clear documentation for these node2vec methods

- [x] Add initial set of unit tests in `cugraph` for desired cugraph node2vec API
- [x] Write initial implementation in cugraph for `node2vec`, which either calls stubbed-out `pylibcugraph.node2vec()` or hardcodes fake data.
- [x] Add initial set of unit tests in `pylibcugraph`. These will be written to exercise the requirements of the `cugraph.node2vec()` implementation.
- [x] Write initial implementation in pylibcugraph for `node2vec`, which either calls a stubbed-out `node2vec` C API or hardcodes fake data.
- [x] Review https://github.com/rapidsai/cugraph/pull/2059
- [x] `cugraph.node2vec()` docstring
- [x] `pylibcugraph.node2vec()` docstring

**Comment by rlratzel** [comment]
still waiting for #2093 to be merged
