### ISSUE TITLE
[ENH] Add Bipartite graph generation option to R-MAT

### ISSUE THREAD

**Issue by mughetto** [rapidsai/cugraph#2075]
Sec 3.5 of the R-MAT paper (https://www.cs.cmu.edu/~christos/PUBLICATIONS/siam04.pdf) documents an option for generating a bipartite graph by specifying the number of node on each dimension. 

As far as I can tell this is not doable with the current implementation (that assumes square adjacency).

Is it something that could be easily added?

**Comment by BradReesWork** [comment]
@mughetto we can do that.  We plan to be expanding the number of generators and options.  I will work this into our roadmap

**Comment by mughetto** [comment]
Great to hear! Looking forward to it!

**Comment by BradReesWork** [comment]
@rlratzel time to get Python wrappers

**Comment by ChuckHastings** [comment]
@rlratzel @BradReesWork - Created an epic to track this along with some companion stories.  Please review.

**Comment by BradReesWork** [comment]
Being tracked under this new Epic:  https://github.com/rapidsai/cugraph/issues/2075
