### ISSUE TITLE
[DOC]notebooks/link_analysis/HITS.ipynb 

### ISSUE THREAD

**Issue by einzigsue** [rapidsai/cugraph#2079]
## Report incorrect documentation

**Location of incorrect documentation**
notebooks/link_analysis/HITS.ipynb 

**Describe the problems or issues found in the documentation**
the vertex with the highest hub/authority score is 34, but vertex 33 is shaded in green in the figure.

**Comment by acostadon** [comment]
image fixed in PR 2106. Not yet merged as of 3/7
