### ISSUE TITLE
[BUG] Pagerank fail

### ISSUE THREAD

**Issue by eunaeuna** [rapidsai/cugraph#208]
**Describe the bug**
The pagerank computation all failed in 6 systems in the cluster (P100 and V100 w/ 16GB or 32GB memory) only on "kron_g500-logn21.mtx" graph

**To Reproduce**
Run pagerank as below:
python cugraph_time.py /home/zronaghi/GrAPL/gunrock-psg/dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --file_type mtx --algo pagerank --damping_factor 0.85 --max_iter 50 --tolerence 1e-2 > result/pr/pr_kron_g500-logn21.txt

N/A

N/A

kron_g500-logn21
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  reduce failed to synchronize: an illegal memory access was encountered
./run_pr_cugraph.sh: line 12: 39556 Aborted                 python cugraph_time.py /home/zronaghi/GrAPL/gunrock-psg/dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --file_type mtx --algo pagerank --damping_factor 0.85 --max_iter 50 --tolerence 1e-2 > result/pr/pr_kron_g500-logn21.txt

**Expected behavior**
Finishes the computation and shows the pagerank processing time

**Screenshots**
Showing error message above and exiting.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by afender** [comment]
Results and err logs : https://drive.google.com/drive/folders/156084GTPu9VzIwwxbUAtzzJ02GWKsdXE

**Comment by jwyles** [comment]
I am working on this, please assign to me.

**Comment by jwyles** [comment]
Traced this error down to a bug in cub::DeviceSpmv::CsrMV. The bug has been reported to cub already: https://github.com/NVlabs/cub/issues/139.

**Comment by eunaeuna** [comment]
Thank you for the update.
Can I have a schedule for this error fix?

Sent from my iPhone

On Apr 18, 2019, at 5:44 PM, jwyles <notifications@github.com<mailto:notifications@github.com>> wrote:


Traced this error down to a bug in cub::DeviceSpmv::CsrMV. The bug has been reported to cub already: NVlabs/cub#139<https://github.com/NVlabs/cub/issues/139>.

**Comment by jwyles** [comment]
It's going to depend on the cub folks getting the bug fixed.

**Comment by BradReesWork** [comment]
PR submitted to cub - waiting on new cub version

**Comment by BradReesWork** [comment]
I downloaded the data files from https://sparse.tamu.edu/MM/DIMACS10/kron_g500-logn21.tar.gz

M = mmread(datafile).asfptype()

gdf = cudf.DataFrame()
gdf['src'] = M.row
gdf['dst'] = M.col

G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='src', destination='dst')
df = cugraph.pagerank(G)

All runs with no issue

**Comment by BradReesWork** [comment]
Once CUB updates their code, we will re-examine this issue
