### ISSUE TITLE
[BUG] Tests with nx objects calling "to_scipy_sparse_array" fail

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#2103]
All tests with `nx `objects calling `to_scipy_sparse_array` are failing with the following error: `AttributeError: module 'scipy.sparse' has no attribute 'coo_array'`

Suggestions:
was this call deprecated ?
Are submodules not automatically imported by `scipy`?

**Comment by jnke2016** [comment]
I am not able to reproduce this error locally.

**Comment by rlratzel** [comment]
closed by this PR: https://github.com/rapidsai/integration/pull/439
