### ISSUE TITLE
[FEA] NetworkX API matching - PageRank

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#212]
The goal is to have a NetworkX style API for graph analytics.   

For PageRank there are a few minor changes.
* NetworkX sets some values in the PageRank call rather than the Graph call
https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank.html#networkx.algorithms.link_analysis.pagerank_alg.pagerank

Task:
- [ ] tolerance should be `tol` 

This will need to be updated once we have personalized pagerank

**Comment by afender** [comment]
I think this was addressed as part of #300. 
@kaatish can you double check if the API match?

**Comment by kaatish** [comment]
The networkX API is as follows :
`pagerank(G, alpha=0.85, personalization=None, max_iter=100, tol=1e-06, nstart=None, weight='weight', dangling=None)`
whereas cugraph is :
`pagerank(G,alpha=0.85, personalization=None, max_iter=100, tol=1.0e-5, nstart=None)`

We are missing the last two parameters but everything else matches networkX style.
