### ISSUE TITLE
[EPIC]  Initial GaaS 

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2141]
- [ ] Initial Version (#2210)
    - [ ] Create Cluster
    - [ ] Load Data
    - [ ] Create Graph 
    - [ ] Run MNMG Neighborhood Sampling
    - [ ] Create client class

**Comment by rlratzel** [comment]
@BradReesWork I just created an issue for the items we want in 22.06 release for this, and ended up covering just about everything in this EPIC.  Should we close this issue, or keep it to track tasks for GaaS beyond the initial implementation?

**Comment by rlratzel** [comment]
Tracking this work [here](https://github.com/rapidsai/GaaS/issues/2) instead.
