### ISSUE TITLE
[EPIC]  Data Masking

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2143]
We want to be able to mask (hide) portion of the graph that is then ignored in processing.  This is useful for heterogeneous graph and time windows 

- [ ] **22.06** Approach defined #2104  
- [ ] 22.10 Neighborhood Sampling  #2161 
- [ ] Egonet
- [ ] Random Walk
- [ ] Node2Vec
- [ ] Louvain
- [ ] BFS
- [ ] SSSP
- [ ] WCC
- [ ] SCC

**Comment by seunghwak** [comment]
Related to https://github.com/rapidsai/cugraph/issues/2104

**Comment by kingmesal** [comment]
Duplicate
