### ISSUE TITLE
[QST] Graph() initialization failed in cugraph

### ISSUE THREAD

**Issue by kampores** [rapidsai/cugraph#216]
Code(Tested in Colab):
!pip install cugraph
import cugraph
g=cugraph.Graph()

Errmsg:
Collecting cugraph
  Downloading https://files.pythonhosted.org/packages/95/33/ccab877191ccdf155af377fe285546eb84bff365f91dc469597a96d9b12b/cugraph-0.6.0-cp36-cp36m-manylinux1_x86_64.whl (8.8MB)
    100% |████████████████████████████████| 8.8MB 3.4MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from cugraph) (1.14.6)
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from cugraph) (0.29.6)
Installing collected packages: cugraph
Successfully installed cugraph-0.6.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-caf380924198> in <module>()
      1 get_ipython().system('pip install cugraph')
      2 import cugraph
----> 3 g=cugraph.Graph()

AttributeError: module 'cugraph' has no attribute 'Graph'

Question:

Hello, I am a cugraph user. I created a Graph () function according to the cugraph manual(https://docs.rapids.ai/api/cugraph/stable/), but an error occurs. How do I fix it?

**Comment by kampores** [comment]
I installed anaconda with Josh's help and fixed the error. However, because there is a 'community' package that can be installed with pip alone, it is not satisfactory because you need to configure it with the Anaconda + pip system. I hope I can install cugraph with pip alone.

**Comment by BradReesWork** [comment]
Since PIP is being dropped and since cuGraph is being better integrated into the conda package, and docker container.  This issue should be resolved.  
However, the issue will be tested going forwards
