### ISSUE TITLE
[ENH] MNMG K-Core

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2168]
Enhance K-Core to be MNMG 

Code across all libraries

- [ ] libcugraph
- [ ] libcugraph_c
- [ ] pylibcugraph
- [ ] cugraph

**Comment by seunghwak** [comment]
libcugraph part is complete (https://github.com/rapidsai/cugraph/blob/branch-22.04/cpp/include/cugraph/algorithms.hpp#L1533).

**Comment by rlratzel** [comment]
This is closed by #2731 and #2933
