### ISSUE TITLE
[DOC] Number of vertices count inconsistent in Overlap Similarity Notebook

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/cugraph#2173]
## Report incorrect documentation

**Location of incorrect documentation**
[notebook
](https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/link_prediction/Overlap-Similarity.ipynb)
**Describe the problems or issues found in the documentation**

"The test graph has only 34 vertices, so why is the Graph listing 35?" But its listing 34.

![Screenshot from 2022-03-29 13-46-39](https://user-images.githubusercontent.com/625946/160673465-dea63219-7fe7-486e-8eb9-f6bb97a5c766.png)

**Suggested fix for documentation**
Remove note if this has been changed.

**Comment by BradReesWork** [comment]
@mmccarty great catch.  that is an old comment before we fully implemented renumbering.  back then we just padded the data.  I'm updating the notebook text
