### ISSUE TITLE
[BUG] Notebook data sources are no longer public?

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/cugraph#2175]
**Describe the bug**
Notebooks are failing because they cannot access the data source.

- [cugraph/notebooks/demo/mn_louvain.ipynb](https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/demo/mg_louvain.ipynb)
- [cugraph/notebooks/demo/mg_pagerank.ipynb](https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/demo/mg_pagerank.ipynb)
- [cugraph/notebooks/demo/uvm.ipynb](https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/demo/uvm.ipynb)

**Steps/Code to reproduce bug**
Running the second code cell results in the following...
```
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
```

**Expected behavior**
The notebooks assumes the file is public.

**Comment by charlesbluca** [comment]
I am able to access the Twitter dataset in [cugraph/notebooks/demo/uvm.ipynb](https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/demo/uvm.ipynb), but not the Hollywood dataset used in the other notebooks

**Comment by betochimas** [comment]
Hi, we're working on reproducing this error. Could you provide us with some further details about how you ran the cells? Examples: Was this on a lab machine? Within or without the company network?

**Comment by mmccarty** [comment]
I'm running them on my local workstation off the VPN. Same as any user would.

**Comment by mmccarty** [comment]
I retested and am no longer able to reproduce the issue. Thanks all. Closing
