### ISSUE TITLE
[DOC] Incorrect number of unique IP addresses reported in Renumber-2.ipynb

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/cugraph#2178]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/cugraph/blob/branch-22.04/notebooks/structure/Renumber-2.ipynb

**Describe the problems or issues found in the documentation**
The notebooks concludes with "we can now see that there are only 50 unique IP addresses in the dataset", but the results seem to imply that there are actually 52?

![image](https://user-images.githubusercontent.com/20627856/160917225-d22a3d12-94f6-41f2-82ab-5c193c043f65.png)

**Suggested fix for documentation**
Update this conclusion to match the actual number of unique IP addresses

**Comment by oorliu** [comment]
It looks like the correct number of unique values is, in fact, 52! This will be updated accordingly in the documentation, and there will be an extra few lines of code to verify that this is the case (using CuPy).

**Comment by rlratzel** [comment]
closed by #2335
