### ISSUE TITLE
[FEA] : support weights in betweenness centrality

### ISSUE THREAD

**Issue by duccioa** [rapidsai/cugraph#2186]
Hello,
Is there a plan to support `weight` in `cugraph.centrality.betweenness_centrality.betweenness_centrality` for weighted graphs ?

I am not sure I have the skills to contribute but I would love to try. What are the main reasons it hasn't been implemented, yet ?

Thank you very much.

Duccio

**Comment by ChuckHastings** [comment]
Please track our development and provide any other comments/feedback in the linked issue.
