### ISSUE TITLE
[BUG] Failure when running MG algos on very small datasets

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#2196]
Our MG implementation assumes that each workers has a partition, which is unlikely to occur for very small datasets and a large number of GPUs

**Steps/Code to reproduce bug**
Run MG Neighborhood sampling with 3+ GPUs on the `small_tree.csv` datasets

**Comment by seunghwak** [comment]
Does this happen with C++ benchmarking as well? (This shouldn't but if you can produce this in MG C++ testing, please let me know). Our MG C++ implementation assumes that each process has partition(s) but partitions can have no vertex/edge.

**Comment by jnke2016** [comment]
@seunghwak . This bug is on the python side and I am fixing this. But I might have uncovered another bug seems to be C/C++ related where I get this error
`Exception: "RuntimeError('non-success value returned from uniform_nbr_sample: CUGRAPH_UNKNOWN_ERROR')"`

I will provide more updates about this.
