### ISSUE TITLE
[BUG] MG Louvain Notebook Fails Due to CommsClosedError

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cugraph#2198]
**Describe the bug**
Running the mg_louvain notebook fails due to a CommsClosedError

**Steps/Code to reproduce bug**
Running the mg_louvain demo notebook on centOS 7, cuda 11.2, python 3.8 in a fresh kernal with no other kernals running fails with this error: `CommClosedError: in <TCP (closed) Scheduler Broadcast local=tcp://127.0.0.1:36246 remote=tcp://127.0.0.1:35425>: Stream is closed
2022-04-06 19:23:43,467 - distributed.nanny - WARNING - Restarting worker`

**Expected behavior**
Demo should run without this error or user intervention in the docker container. 

**Environment overview (please complete the following information)**
 - Environment location:  Docker
 - Method of cuGraph install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

`docker pull rapidsai/rapidsai-core-nightly:22.04-cuda11.2-runtime-centos7-py3.8`

`docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786     -v ~/extra:/rapids/notebooks/extra rapidsai/rapidsai-core-nightly:22.04-cuda11.2-runtime-centos7-py3.8`

**Comment by BradReesWork** [comment]
fixed by PR #3558
