### ISSUE TITLE
[FEA] Proposed change to pylibcugraph organizational structure

### ISSUE THREAD

**Issue by betochimas** [rapidsai/cugraph#2200]
Right now, all of the different software stacks of cuGraph have recently gone through redesigns, but the newest stack, pylibcugraph, is growing at a fast pace compared to what it was just a few months ago. As the gap between number of offered algorithms shrinks between libcugraph/cugraph and pylibcugraph, there is a need to discuss how to classify the currently offered algorithms. 

cuGraph's structure can be condensed into 3 categories of algorithms, shown below.
```
cugraph
- dask (MNMG)
- experimental (for features not yet ready for full release)
- centrality, community, components, cores, layout, linear_assignment, link_analysis, link_prediction, sampling, structure, traversal, tree
```
The latter category resembles networkX, which is important for maximizing networkX compatibility on the user side. However, pylibcugraph only has components and experimental, despite having algorithms like node2vec, pagerank, sssp. As pylibcugraph algorithms are moved out of experimental, they will need to appear in the online documentation.

For the current pylibcugraph algorithms (including those in EXPERIMENTAL), a proposed structure could be:

```
pylibcugraph
- connectivity
    - _connectivity
- centrality
    - hits
    - pagerank
- structure
    - graphs
    - graph_props
    - resource_handle
 - sampling
     - node2vec
     - uniform_neighborhood_sampling
```

This change would make pylibcugraph more resemble cugraph, although it would also make it less resemble libcugraph_c. Perhaps developers from the different stacks could comment?

**Comment by rlratzel** [comment]
We will likely not do this, at least not anytime soon, so I'm going to close this with the intention of re-opening it if we decide otherwise.
