### ISSUE TITLE
node2vec converts start_vertices from py list of numbers to cudf.Series incorrectly

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2229]
node2vec allows the `start_vertices` to be passed in as a python list of numbers and will automatically create a cudf.Series from them. However, it then checks that the Series dtype is int32, which is is not, and then raises an exception:

```
>>> start_vertices = [0, 2]
>>> paths, weights, path_sizes = cugraph.node2vec(G, start_vertices, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cugraph-22.6.0a0+g1e46f7b-py3.8-linux-x86_64.egg/cugraph/sampling/node2vec.py", line 114, in node2vec
    raise ValueError(f"'start_vertices' must have int32 values, \
ValueError: 'start_vertices' must have int32 values, got: int64
```

**Comment by qitianliang** [comment]
I have come across something like this. when I perform `random_walk` function in version 22.02, and I found cugraph accept int16 cudf to build edges properly. However, when pass start_vertices a python int list, it raise an dtype error. I  rebuild the cugraph from int32 dtype , and it works properly. you can check if it is like this.
