### ISSUE TITLE
[BUG] Conda environment has pip-installed dependencies, but doesn't depend on pip

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#225]
https://github.com/rapidsai/cudf/issues/1401

Just adding -pip in the .yml files fix this, but we may better wait till cudf folks fix this and copy what they did to maintain consistency with cudf.

Besides this, in cugraph_nightly(_cuda10).yml
```
  1 name: cugraph_0.6
```
This name does not sound right, should better be something like cugraph_nightly.

And cudf folks name the .yml file for CUDA 9.2 with _cuda9.2.yml. We don't add this to the .yml files for CUDA 9.2. We may consider renaming to better match cudf (if we do this, we need to update README.md to reflect this change as well).

**Comment by afender** [comment]
closed via #256
