### ISSUE TITLE
setup.py files reference old paths, need cleanup

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2265]
https://github.com/rapidsai/cugraph/blob/bc2242007c4b114733ca32fec68985d38bedddc9/python/pylibcugraph/setup.py#L111
is referencing `"../../thirdparty/cub"` which no longer exists. There may be others, and the `setup.py` files are in need of general cleanup.

**Comment by jarmak-nv** [comment]
@rlratzel was this resolved by [#2378](https://github.com/rapidsai/cugraph/pull/2378) ?
