### ISSUE TITLE
[BUG] Cmake build of libcugraph fails -- cugraph-ops missing.

### ISSUE THREAD

**Issue by atabou** [rapidsai/cugraph#2280]
**Describe the bug**

It seems like the cmake script is not finding the required configuration files:
- cugraph-opsConfig.cmake
- cugraph-ops-Config.cmake

**Steps/Code to reproduce bug**
- Clone the repo
- Create `build` directory and cd into it
- Create install directory `testbuild` 
- Run `cmake .. -DCMAKE_INSTALL_PREFIX="$HOME/Downloads/cugraph/cpp/build/testbuild"`

**Expected behavior**

cudagraph-ops should be included in the repo, or the SOURCEBUILD.md should make it clearer where to get cudagraph-ops from. 

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuGraph install: source

**Environment details**

**Additional context**

```
CMake Error at build/_deps/rapids-cmake-src/rapids-cmake/find/package.cmake:89 (find_package):
  By not providing "Findcugraph-ops.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "cugraph-ops", but CMake did not find one.

  Could not find a package configuration file provided by "cugraph-ops" with
  any of the following names:

    cugraph-opsConfig.cmake
    cugraph-ops-config.cmake

  Add the installation prefix of "cugraph-ops" to CMAKE_PREFIX_PATH or set
  "cugraph-ops_DIR" to a directory containing one of the above files.  If
  "cugraph-ops" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  cmake/thirdparty/get_libcugraphops.cmake:24 (rapids_find_package)
  cmake/thirdparty/get_libcugraphops.cmake:35 (find_and_configure_cugraph_ops)
  CMakeLists.txt:152 (include)
```

**Comment by BradReesWork** [comment]
@atabou we are aware of the issue.  I recent cMake change broke the build process.   I work-around is to use an older version of cugraph-ops
   **conda install -c rapidsai-nightly libcugraphops=22.06.00a220517=cuda11_g09cdeaa_35**

we are working to have this resolved

**Comment by BradReesWork** [comment]
We have a PR to fix the issue in review

**Comment by atabou** [comment]
Hello @BradReesWork, thank you for your help!

I ended up using conda to download libcugraph as there were other missing dependencies during the compilation process. I then manually moved the libraries and header files I needed from their location in the anaconda directory to an appropriate location.

It would also be nice if we were able to not use conda to download libcugraph. I know that the cmake file is going to be fixed, but would you consider adding libcugraph to a package manager for use with `apt` or `pacman`? That way, by running `pacman -S libcugraph` it would download all the so and h files to the regular lib and include directories, or maybe even somewhere on the cuda or nvcc path.

**Comment by benjha** [comment]
Hi @BradReesWork,

I am compiling from source cugraph for ppc64le (Summit) and have the same compilation error.

Is libcugraphops closed source or there is a public repo.  from where I can build it from source ?

Thanks,
