### ISSUE TITLE
Not being able to install cugraph with conda

### ISSUE THREAD

**Issue by DyumanAditya** [rapidsai/cugraph#2352]
Hi,
The conda installation process mentioned in the main README file does not work for me. I cannot reproduce the error because I've installed it successfully in the next step:

When I install cugraph in the following way, there are no errors:
```
conda install -y -c rapidsai -c nvidia -c conda-forge cugraph=22.06 python=3.8 cudatoolkit=11.5
```

But when I try to import cugraph, I get the following errors:
```
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cugraph
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInitGlobal'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
[2]    29254 segmentation fault (core dumped)  python3
```

How can I fix this to be able to import cugraph?

**Comment by BradReesWork** [comment]
@jnke2016 any insight into this error?

**Comment by jnke2016** [comment]
Hi @DyumanAditya ,
I ran you command and I was able to import cuGraph successfully. Can you try again please? If you still have the issue we can debug it further to see if you are missing `libcuda.so`

**Comment by rlratzel** [comment]
Closing this issue.  @DyumanAditya - please re-open if you still have a problem and let us know if you have a missing `libcuda.so`.
