### ISSUE TITLE
[QST] ArangoDB - cuGraph

### ISSUE THREAD

**Issue by aMahanna** [rapidsai/cugraph#2376]
Hi there, [ArangoDB](https://github.com/arangodb/arangodb) is currently maintaining a cuGraph adapter that allows developers to convert their ArangoDB graphs to cuGraph, and vice versa.

We are curious to know whether this would be worth listing somewhere as a cuGraph-powered project, or even as a blog post.

Would this be of interest?

https://github.com/arangoml/cugraph-adapter

**Comment by BradReesWork** [comment]
ah, yes that is something on my todo list - which I'm hoping to get to this release
