### ISSUE TITLE
[FEA][NV] Add Python bindings for SSSP

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#24]
I already implemented the CUDA/C++ part to access nvgraph features using cugraph graph structure and SSSP wrapper in [src/plugin/nvgraph/nvgraph_gdf.cu](https://github.com/rapidsai/cugraph/blob/master/src/plugin/nvgraph/nvgraph_gdf.cu). The task consist in adding python bindings for `gdf_error gdf_sssp_nvgraph`

Subtasks checklist:

- [ ]  Python bindings and API (may include some adjustments of the C++/CUDA part)
- [ ]  Pytest testing against NetworkX
- [ ]  Documentation
     - [ ]  Doxygen (C++)
     - [ ]  Sphinx (Python)
     - [ ]  python code example
- [ ]  Check headers and licenses
- [ ]  Validate everything in Jenkins

**Comment by archenroot** [comment]
as for other graph algos I will do Java binding

**Comment by afender** [comment]
Closing after merging : Fea python bindings sssp #44
