### ISSUE TITLE
[FEA] Property Graph API to get `ntypes` and `etypes`  from the PropertyGraph

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2423]
**Describe the solution you'd like and any additional context**

Property Graph API to provide properties for `vertex types` and `edge types`  from the PropertyGraph .  

```python
pg.vtypes  (Returns a cudf.Series corresponding to the unique vertex types)
```

```python

pg.etypes (Returns a cudf.Series corresponding to the  unique edge types)
```

**Comment by eriknw** [comment]
Why is a `Series` object preferred?  Could the return type be a Python set?

**Comment by VibhuJawa** [comment]
> Why is a `Series` object preferred? Could the return type be a Python set?

No preference of a `Series` object , Any python iterable that can be smoothly transformed into a list of strings works.

**Comment by eriknw** [comment]
This is implemented by https://github.com/rapidsai/cugraph/pull/2434, which has been merged.  Sorry, I forgot to link.

Spelling: `pg.vertex_types` and `pg.edge_types` properties.

**Comment by jarmak-nv** [comment]
Hey @eriknw just wanted to confirm this was entirely completed in #2434 before I close it. Thanks!

**Comment by eriknw** [comment]
Yes, it is entirely completed.  Close away!
