### ISSUE TITLE
[BUG] Investigate hash size in renumbering

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#243]
`hash_size` is hardcoded to be `8191`.

We should do more experiment and try to have some heuristics to set it automatically based on the input. This impact performance by over 2x

See https://github.com/rapidsai/cugraph/pull/234#discussion_r278213508

**Comment by ChuckHastings** [comment]
Recommend pushing this out to 0.9.  I don't think that we should do this evaluation until #61 is completed as the optimal hash size for integer types might be different from the optimal hash size for non-integer types.

**Comment by ChuckHastings** [comment]
Suggest putting this in blocked state as well.  Not really worth doing this until #61 is completed as the characteristics of doing this with strings will be totally different.

**Comment by BradReesWork** [comment]
Closing this issue and opening a feature request to make the Hash Size a function argument
