### ISSUE TITLE
[FEA] Optimize cugraph.uniform_neighbor_sample 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2433]
**Describe the solution you'd like and any additional context**

We should optimize `cugraph.uniform_neighbor_sample`.   

```python
import cudf
import cugraph

df = cudf.read_parquet('/datasets/graph_nn/ogbn_products.parquet')
G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(df,source='src',destination='dst',edge_attr='weight')
batch = G.nodes()[0:4096]
```

```python
%%timeit 

sampled_g_cugraph = cugraph.uniform_neighbor_sample(G,
                                     start_list=batch,
                                     fanout_vals=[10],
                                     with_replacement=False
```
```
332 ms ± 847
```

Expected Performance :  I would expect the performance to be around `8-9x` better.  More details in internal thread.

**Comment by VibhuJawa** [comment]
Will be fixed by https://github.com/rapidsai/cugraph/pull/2394

**Comment by kingmesal** [comment]
@seunghwak Can you confirm if this is complete? Does anything else need to occur to close this?

**Comment by seunghwak** [comment]
https://github.com/rapidsai/cugraph/pull/3269 might be related to this issue no other issue tracking uniform neighbor sampling performance.

**Comment by kingmesal** [comment]
@VibhuJawa can you confirm whether or not #3269 fixes your issue?

**Comment by VibhuJawa** [comment]
Lets close this issue. https://github.com/rapidsai/cugraph/pull/3269 fixed most things
