### ISSUE TITLE
[BENCH] Benchmark Jaccard's performance issue after recent changes

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#245]
When computing all weights ( including 2 hops) cuGraph is not faster than Nx. We need to identify the performance bottleneck and find out how to make Jaccard faster for this use case.

**Comment by ChuckHastings** [comment]
Are we certain that this is true?  How did we measure this?

I recently discovered (by code inspection of networkx) that networkx's Jaccard implementation does lazy computation of the similarity.  So the time spent calling nx.jaccard_coefficient itself **only** includes the time required to construct a lazy iterator.  The real time spent computing nx.jaccard_coefficient would include populating a pandas frame with all of the results.  It seems like that should explode for even a small graph.

**Comment by BradReesWork** [comment]
Dropping this issues.  The Jaccard code is slated to be complexly redone in 0.17 for MNMG at which time it should also be update to better address 2-hop comparisons and performance
