### ISSUE TITLE
[BUG] Extract subgraph on pg creates an undirected graph

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2457]
**Describe the bug**

Extract subgraph on a PG creates an undirected graph instead of directed one

**Steps/Code to reproduce bug**

```python
import cugraph
import cudf
from cugraph.experimental import PropertyGraph

# create PG
df = cudf.DataFrame({'src':[1,2], 'dst':[2,3]})
pg = PropertyGraph()
pg.add_edge_data(df, vertex_col_names=['src','dst'])

# extract subgraph
graph = pg.extract_subgraph()
```
```python
print(graph.directed)

False
```

```python

print(graph.edges())

   src  dst
0    2    3
1    1    2
```

**Expected behavior**

I would expect a directed graph. 

**Additional context**
This means that i cant use this extracted subgraph for sampling in GNN pipe-lines. 

CC: @rlratzel , @alexbarghi-nv

**Comment by eriknw** [comment]
Try `graph = pg.extract_subgraph(cugraph.DiGraph)`.  The first argument to `extract_subgraph` is `create_using=cugraph.Graph`.

Do you think the default should be `cugraph.DiGraph`?

**Comment by rlratzel** [comment]
(oops, Erik beat me to it)

**Comment by rlratzel** [comment]
> Try `graph = pg.extract_subgraph(cugraph.DiGraph)`. The first argument to `extract_subgraph` is `create_using=cugraph.Graph`.

FYI, `cugraph.DiGraph` is deprecated in favor of the `directed=True` arg to the `cugraph.Graph()` ctor.

> Do you think the default should be `cugraph.DiGraph`?

This is a good question, IOW, should we default to returning directed graphs if `create_using` isn't specified?

**Comment by VibhuJawa** [comment]
Closing in favor of https://github.com/rapidsai/cugraph/issues/2459 . Thanks guys .
