### ISSUE TITLE
[FEA] Remove code that uses `PropertyGraph` debug/internal attrs from `gnn` modules

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2480]
There are several `FIXME`s in https://github.com/rapidsai/cugraph/pull/2450 related to removing access to the `PropertyGraph._vertex_prop_dataframe` and `PropertyGraph._edge_prop_dataframe` which should be addressed.

**Comment by VibhuJawa** [comment]
Closing in favor of https://github.com/rapidsai/graph_dl/issues/39
