### ISSUE TITLE
[FEA] MNMG Leiden

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#2481]
Implement MNMG Leiden.

We have an SG implementation, although it does not accurately compute the Leiden clustering algorithm.  The new implementation should be primitive based and more accurately reflect the serial implementations.

Tasks:
- [ ] Implement in Python
- [ ] Define PLC (pylibcugraph) API
- [ ] Define C API
- [ ] Define C++ API
- [ ] Implement algorithm
- [ ] Define C++ unit tests
- [ ] Define C unit tests
- [ ] Define Python unit tests
- [ ] Delete legacy implementation

**Comment by kingmesal** [comment]
closing - tracked by [#3276](https://github.com/rapidsai/cugraph/issues/3276)
