### ISSUE TITLE
[QST]Why does the Triangle Counting only support the total number of triangle 

### ISSUE THREAD

**Issue by cfangplus** [rapidsai/cugraph#2488]
Unlike NetworkX, the triangle counting algorithm simply return the total number of triangle and not the number per vertex.
Why and When could it support the number per vertex, thx.

**Comment by seunghwak** [comment]
We have a C++ triangle count function and this function supports per vertex triangle counts (https://github.com/rapidsai/cugraph/blob/branch-22.08/cpp/include/cugraph/algorithms.hpp#L1674).

We need to update our python API to call this one instead of the legacy triangle count implementation.

**Comment by acostadon** [comment]
The python API now cuGraph now supports per vertex triangle counts.
It is currently in our experimental area but will be moved out in 22.10. 
see:
https://github.com/rapidsai/cugraph/blob/branch-22.10/notebooks/algorithms/community/Triangle-Counting.ipynb

for an example notebook.
