### ISSUE TITLE
Set up automated SG/MG/MNMG (based on scale and coverage type) PG tests and benchmarks

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2526]
This will be needed for both the small and large-scale graph support in PG, and to ensure design changes produce the expected results (functional and performance) as early as possible.  Larger scale MNMG testing for PG in particular is needed for ensuring PG can support GNN use cases, and since some smaller-scale tests are already present in the nightly MNMG test suite.

The high-level idea is we need something in place to easily run to validate designs for both small (for quick turnaround) and large (to stress test) scale, where the developer can easily run different test types as part of their personal development process.  At the moment, all we have are small-scale unit tests in the cugraph repo.  These tests should also be able to be added to a nightly test run (such as the nightly MNMG tests) to produce a more comprehensive report.

This task does not prescribe a particular test infrastructure, so even pytest tests are acceptable if they meet the needs (in fact, pytest would be preferred since there's already a lot of familiarity and test infra for those).

One aspect of this task also involves getting access, understanding the job scheduling software, and several other aspects, all of which can be time consuming. Doing this first allows us to focus on development of larger-scale MNMG PG support easier.

**Comment by BradReesWork** [comment]
ties in with #2566
