### ISSUE TITLE
Run release 22.08 benchmark notebook

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2528]
The 22.08 release notebook needs to be done to capture official benchmark data.

- create a new 22.08 folder under 
https://nvidia.sharepoint.com/:f:/s/cugraph_team/Ep29cEW_dxdIhFu9JUwI95QB7nbInBa6QkZGL04Rn_DIQg?e=67wYqh

- copy the last slide deck over
- update slides with 22.08 material and benchmark numbers

**Comment by acostadon** [comment]
Need to change Triangle algorithm to call new implementation in experimental.
Needs to be run on Ampere or later GPU.
