### ISSUE TITLE
[FEA] MNMG Random Walks

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#2551]
Implement MNMG Random Walks.  We have an SG implementation, but it will not translate to MNMG.  We should be able to think about Random Walks as a special case of neighborhood sampling.

- [ ] Python implementation
- [ ] Define PLC (pylibcugraph) API
- [ ] Define C API
- [ ] Define C++ API
- [ ] Implement algorithm
- [ ] Define C++ unit tests
- [ ] Define C unit tests
- [ ] Define Python unit tests
- [ ] Delete legacy implementation

**Comment by kingmesal** [comment]
#3277 tracks this work
