### ISSUE TITLE
[FEA] Leiden C++ implementation  

### ISSUE THREAD

**Issue by naimnv** [rapidsai/cugraph#2564]
**Describe the solution you'd like and any additional context**

To avoid badly connected communities, we would like to implement Leiden method. To way it is done -

1. Find partition of the vertices as it's done in Lovain implementation
2. Refine the partition to avoid merging weakly connected sub-communities in a community
3. Merge refined graph according to partition find in refinement phase

---
_For Developers below this line_

  - [] Code passes CI
  - [] Code uses Graph Primitives
  - [] Code in C++/CUDA layer
  - [] Code in C layer
  - [] Code in pylibcugraph Python layer
  - [] Code in cugraph Python layer
  - [] Documentation
  - [] Test cases at each layer (for MG tests, a note in the PR description indicating the new/existing MG tests were run and passed)

**Comment by ChuckHastings** [comment]
Implemented in 23.08
