### ISSUE TITLE
Get the data generator from JoC and create test data

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2566]
reach out to JoC team and obtain their heterogeneous data generator.

Other option:
https://github.com/Nanthini10/synthetic-data

Then create test datasets 

- 1M edges
- 10M edges
- 100M edges
- 1,000M edges

**Comment by BradReesWork** [comment]
the https://github.com/Nanthini10/synthetic-data code downloads different synthetic datasets.   Those are useful for testing but not for large test cases

**Comment by rlratzel** [comment]
closing and moved to internal task tracker
