### ISSUE TITLE
Create new primitive to replace `gather_one_hop`

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#2600]
In addition to random sampling, the neighborhood sampling code supports a feature (when fanout for a level is set to -1) to retrieve all neighbors of vertices encountered at that point in the sampling.

The current implementation uses a method named `gather_one_hop`, which has some issues related to how it handles the hyper-sparse areas in an MG graph.

Create a new primitive that will provide that functionality (given a set of vertices, return the set of edges that depart from that vertex).

**Comment by BradReesWork** [comment]
closed by #2623
