### ISSUE TITLE
[FEA] degree_centrality and betweenness_centrality with cugraph.dask

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cugraph#2605]
Implementing `degree_centrality` and `betweenness_centrality` for larger Graphs that needs to scaled onto more than 1 GPUs.
Please help us providing any workarounds to utilize these for larger graphs is possible.

**Comment by mlahir1** [comment]
degree_centrality is straight fwd, that should not be a problem. can achieve this with couple of groupby aggs.

**Comment by ChuckHastings** [comment]
Betweenness Centrality is underway.  I expect this will be included in version 23.02.

@jnke2016, we should explore whether we have sufficient capability in the python API to efficiently compute degree centrality.  We could add a C API to compute degree centrality if the current capabilities and the dask calls that might be required are inefficient.

**Comment by ChuckHastings** [comment]
Vertex Betweenness Centrality will be implemented as part of 23.02.
