### ISSUE TITLE
cugraph uses a cudf API in a way that will be unsupported in a future release, user sees Warning

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2619]
```
/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/dataframe.py:1064: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
```
The user in this case did not set an edge weight, but it is unknown if that is related or not.  Regardless, this warning should not be seen and it likely means cugraph is now using cudf incorrectly and that at some future time we will break.

cc @ChuckHastings

**Comment by VibhuJawa** [comment]
Closed by https://github.com/rapidsai/cudf/pull/11761
