### ISSUE TITLE
Testing on Hopper

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#2658]
**Describe the solution you'd like and any additional context**
Run the C++ and python `cuGraph` tests on Hopper(SG and MG configuration)

Tested on the most recent image available below

`gitlab-master.nvidia.com:5005/pataylor/dlfw/rapids-dlfw:22.08-test-cuda11.8-ubuntu20.04-linux-amd64 /bin/bash`

---
_For Developers below this line_

  - [X] Python SG tests (**PASSED**)
  - [X] Python MG tests (**PASSED**)
  - [X] C++ SG tests (**PASSED**)
  - [X] C++ MG tests (`MG_GATHER_ONE_HOP_TEST` and `MG_GATHER_UTILS_TEST` **FAILED** but are ignored for now until the new primitives are ready.

**Comment by rlratzel** [comment]
Testing is considered complete.
