### ISSUE TITLE
[BUG] update CI for new nvgraph version location 

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#266]
As discussed in https://github.com/rapidsai/cugraph/pull/194#issuecomment-486789449 ,Nvgraph now lives inside cugraph repository and is built along with it. This version contains fixes and improvements so we cannot keep using the gitlab code and the existing version of the anaconda package (https://anaconda.org/nvidia/nvgraph) of nvgraph. 

For 0.7 there are two possible solutions:
1. deploy the new nvgraph library and headers as part of cugraph package and remove nvgraph from cugraph's dependency list. 
2. upgrade nvgraph package on https://anaconda.org/nvidia/nvgraph using the nvgraph version that is in cugraph. 

In the future, there will be two nvgraph versions. Solution (2) will be needed for the legacy nvgraph verison and we will need solution (1) for the verison used in cugraph untill the codes are completely merged.

**Comment by raydouglass** [comment]
@afender Looking at `cpp/CMakeLists.txt` in configures/builds nvgraph (from `cpp/nvgraph`). That cmake is used by `conda/recipes/libcugraph` so the resulting `libcugraph` conda package has `libnvgraph_rapids.so`. 

Effectively nvgraph is being packaged with libcugraph.

So it sounds like the solution is to remove the dependencies on `nvgraph` from the conda recipes and build scripts. Does that sounds right?


> In the future, there will be two nvgraph versions.

Not sure what you mean by this.

**Comment by afender** [comment]
> so the resulting libcugraph conda package has libnvgraph_rapids.so.

Excellent!

> So it sounds like the solution is to remove the dependencies on nvgraph from the conda recipes and build scripts. Does that sounds right?

Sounds good to me.

> In the future, there will be two nvgraph versions.
>> Not sure what you mean by this.

Nothing to worry about now, it's just a heads up, there will be : 
- the legacy version in what is currently called `graph-oss` repo, this one should be deployed using https://anaconda.org/nvidia/nvgraph.
- the cugrpah version from `cpp/nvgraph` that should be deployed as part of cuGraph

**Comment by raydouglass** [comment]
Great! I opened a PR to address this. https://github.com/rapidsai/cugraph/pull/271
