### ISSUE TITLE
[QST] Build a network based on stochastic_block_model by cuGraph

### ISSUE THREAD

**Issue by pp850110** [rapidsai/cugraph#2681]
Ask a question
By using NetworkX, the code will be like this:
`G=nx.stochastic_block_model(1000, 0.2)`
Is it possible to build a network based on stochastic_block_model by cuGraph?
If it is possible, any instruction to plot by cuGraph?

**Comment by seunghwak** [comment]
We currently does not support graph generation with the stochastic block model. Could you submit a feature request issue for this? Then, we can plan on implementing a graph generator with the stochastic block model.

**Comment by pp850110** [comment]
> We currently does not support graph generation with the stochastic block model. Could you submit a feature request issue for this? Then, we can plan on implementing a graph generator with the stochastic block model.

Many thanks for your suggestion. I will reference this question in the request.
