### ISSUE TITLE
[FEA][NV] I/O : support edge lists using any numerical identifier as vertex label

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#27]
Currently, sources and destinations must be 32-bit integers in the range [0, V-1].
We need to support 64-bit integers without range.

**Comment by afender** [comment]
The CUDA part has been addressed by Chuck in PR#38. 
Next step is integration in python bindings and CAPI.

**Comment by afender** [comment]
The next PR should also add changes for RMM compatibility: 
1. #include <rmm_utils.h>
2. replace `cudaMalloc/free` by `ALLOC_MANAGED_TRY / ALLOC_FREE_TRY`

**Comment by ChuckHastings** [comment]
PR #234 adds a python interface for integer lookups.  I believe this completes this issue.

**Comment by afender** [comment]
We need to add documentation in the python API.
I understand you have a notebook already, correct?. If so, it would be great to add it to the notebook repo.

**Comment by ChuckHastings** [comment]
PR #247 adds python interface.

https://github.com/rapidsai/notebooks/pull/127 adds the notebook to the notebook repo.
