### ISSUE TITLE
[FEA] Handle Missing Property Values

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#2710]
Currently, vertices that do not have a value for a particular property have a default value of `NA`.  This is problematic for two reasons:

1. Determining which property keys are valid for which vertices requires a full dataframe search.
2. If the user just wants to input a default value so they can run their network (which is a common use case), calling the basic `fillna` exposes implementation details as they have to access the vertex dataframe to do so.

**Comment by BradReesWork** [comment]
I think we need to add an API for setting the NA value, similar to cuDF `fillna`
see  - https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.DataFrame.fillna.html#cudf.DataFrame.fillna

**Comment by BradReesWork** [comment]
@alexbarghi-nv we have two options

(1) your are required to call "fillna" at data load time
(2) we create a 'fillna' method that can be called at anytime after the graph is created but before a function call

**Comment by rlratzel** [comment]
PG currently has fillna() methods, but this is still open for adding better docs and tests
