### ISSUE TITLE
[BUG] install Rapid framework with AWS CLUSTER VIA DASK: `Mismatched versions found`

### ISSUE THREAD

**Issue by parkerzf** [rapidsai/cugraph#2734]
**Describe the bug**
Follow the instruction on https://rapids.ai/cloud.html#aws, section AWS CLUSTER VIA DASK, I get the Mismatched versions found error. Is this deployment approach outdated? 

**Steps/Code to reproduce bug**
Client node: `p3.2xlarge`, installed rapid framework using the latest docker command:
```cmd
docker pull rapidsai/rapidsai-dev:22.08-cuda11.5-devel-ubuntu20.04-py3.9
docker run --gpus all --rm -it \
    --shm-size=1g --ulimit memlock=-1 \
    -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-dev:22.08-cuda11.5-devel-ubuntu20.04-py3.9
```

ECS cluster: 1 instance `p3.2xlarge`, all the steps are correct and the cluster is created successfully. However, with following code it shows the error:

```
from dask.distributed import Client
client = Client(cluster)

import dask, cudf, dask_cudf
ddf = dask.datasets.timeseries()
gdf = ddf.map_partitions(cudf.from_pandas)
gdf.groupby(‘name’).id.count().compute().head()
```

Error:
```
CancelledError: ('getitem-fe751d5251afed463bc49ee3f67eabe0', 0)/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/client.py:1274: VersionMismatchWarning: Mismatched versions found

+-------------+----------------+----------------+----------------+
| Package     | client         | scheduler      | workers        |
+-------------+----------------+----------------+----------------+
| blosc       | MISSING        | None           | None           |
| cloudpickle | 2.1.0          | 1.6.0          | 1.6.0          |
| dask        | 2022.7.1       | 2021.04.0      | 2021.04.0      |
| distributed | 2022.7.1       | 2021.04.0      | 2021.04.0      |
| lz4         | 4.0.0          | None           | None           |
| msgpack     | 1.0.4          | 1.0.2          | 1.0.2          |
| numpy       | 1.22.4         | 1.20.2         | 1.20.2         |
| pandas      | 1.4.3          | MISSING        | MISSING        |
| python      | 3.9.13.final.0 | 3.7.10.final.0 | 3.7.10.final.0 |
| toolz       | 0.12.0         | 0.11.1         | 0.11.1         |
+-------------+----------------+----------------+----------------+
Notes:
-  msgpack: Variation is ok, as long as everything is above 0.6
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
  ```

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: AWS
 - Method of cuGraph install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
```cmd
docker pull rapidsai/rapidsai-dev:22.08-cuda11.5-devel-ubuntu20.04-py3.9
docker run --gpus all --rm -it \
    --shm-size=1g --ulimit memlock=-1 \
    -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-dev:22.08-cuda11.5-devel-ubuntu20.04-py3.9
```

**Comment by taureandyernv** [comment]
@mmccarty , I know you're revamping the cloud docs, so do we have any updates to the aws cluster with dask instructions @parkerzf mentioned?  Everything works fine with a LocalCUDA Cluster
```
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
client = Client(cluster)

import dask, cudf, dask_cudf
ddf = dask.datasets.timeseries()
gdf = ddf.map_partitions(cudf.from_pandas)
gdf.groupby('name').id.count().compute().head()
```

**Comment by parkerzf** [comment]
> @mmccarty , I know you're revamping the cloud docs, so do we have any updates to the aws cluster with dask instructions @parkerzf mentioned? Everything works fine with a LocalCUDA Cluster
> 
> ```
> from dask.distributed import Client, wait
> from dask_cuda import LocalCUDACluster
> 
> cluster = LocalCUDACluster()
> client = Client(cluster)
> 
> import dask, cudf, dask_cudf
> ddf = dask.datasets.timeseries()
> gdf = ddf.map_partitions(cudf.from_pandas)
> gdf.groupby('name').id.count().compute().head()
> ```

Thanks! Indeed it is working fine with LocalCUDACluster because no version mismatched issue.

**Comment by mmccarty** [comment]
cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Ah I had replied over on https://github.com/rapidsai/cudf/issues/11766. Given that this is a duplicate issue I recommend we close this one out.

**Comment by parkerzf** [comment]
> Ah I had replied over on [rapidsai/cudf#11766](https://github.com/rapidsai/cudf/issues/11766). Given that this is a duplicate issue I recommend we close this one out.

Thanks for the reply. close this one.
