### ISSUE TITLE
Update Python code to support pipelining of functions

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2735]
**Describe the solution you'd like and any additional context**
There are a number of functions that currently prevent function pipelining since the function returns None.   
Update functions to always return an object 

Note: [This](https://stackoverflow.com/questions/73826904/cugraph-create-nonetype/73830932?noredirect=1#comment130391020_73830932) is a related SO question

**Comment by rlratzel** [comment]
Perhaps we should reopen [this issue](https://github.com/rapidsai/cugraph/issues/1733) instead, especially since it has more discussion about the impact of this on the library's API as a whole.
