### ISSUE TITLE
[RFC] Throw exception before fully removing deprecated APIs

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2743]
We should throw an informative exception for deprecated APIs for 1+ release cycles instead of fully changing/removing them.  Then, fully change/remove them after 1+ release cycle.  So the new procedure will be:

1) Add deprecation warning for 1+ release cycle
2) Raise exception stating the API is now removed, include instructions on an alternate API if appropriate for 1+ release cycle
3) Fully remove the deprecated API and exception

For experimental APIs:
1) Add experimental API which includes warning that its experimental and could change/go away
2) Promote API to stable, change warning on experimental version saying it is no longer experimental and the stable version should be used (but allow the user to keep using the experimental version) for 1+ release
3) Raise exception for the experimental version saying they must use the stable version for 1+ release
4) Fully remove the experimental version and the exception

In addition to the above, we should also have pytest treat warnings as errors (may need a pytest plugin for that since I don't see an option)

cc @eriknw @jnke2016

**Comment by BradReesWork** [comment]
@acostadon the outcome of this discussion should be captured in our docs
