### ISSUE TITLE
[DOC] Define, prioritize How-to Pages for Users.

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#2767]
The goal of this task is to sketch out a doc that outlines what the how-to pages should look like and what needs to be done

#Define a set of valuable how-to documents for new users of cuGraph.
Prioritize them.
Create issues for them.

**Comment by BradReesWork** [comment]
The goal should be to create a Tutorial / How-to collection of static pages:


## Tutoial
- The different Graph types
  - how to create
  - how to transform
- Property Graphs
- cugraph-service
  - how-to
- Algorithms

**Comment by BradReesWork** [comment]
page under "cugraph_team -> documents -> Design -> New_Design.docx"
