### ISSUE TITLE
cugraph wheel/pip builds include test runs which are failing

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2781]
There were several test failures as part of building wheels for cugraph - output is [here](https://github.com/rapidsai/cugraph/actions/runs/3192366121/jobs/5211608816), traceback for the initial error starts [here](https://github.com/rapidsai/cugraph/actions/runs/3192366121/jobs/5211608816#step:7:2918).

It appeared as if almost all the SG test pass until about the last few, then they all start failing/erroring after that, including all the MGs. 

One suspicion is that the first failure put a device or the environment in a bad state somehow, causing all the other tests after that to fail/error.  The failure also seemed to occur in a call to `cudf.read_csv()`, which is unlikely to have a problem since the cuDF tests passed.

Here are instructions:
```
# The instructions below assume Python 3.8 and CUDA 11.5 but you should be able to tweak those
# However you choose to have CUDA installed should be fine, if you want it in the env you can add it to the command below

# Create env
conda create -c conda-forge -n test_rapids_wheels python=3.8 cuda numpy scipy networkx python-louvain cupy-cuda115 (assuming cuda 11.5)
conda activate test_rapids_wheels
pip install git+https://github.com/rapidsai/asvdb.git@main && pip install git+https://github.com/vyasr/benchmark.git@versioned_rmm_req#subdirectory=rapids_pytest_benchmark

# Install all the other wheels 
pip install -i https://pypi.k8s.rapids.ai/simple/ rmm-cu11 cudf-cu11 dask-cudf-cu11 raft-dask-cu11 pylibraft-cu11 pylibcugraph-cu11

# Download and install the built cugraph wheel (I picked one of the latest artifacts)
curl -O https://downloads.rapids.ai/ci/cugraph/pull-request/2747/bc71f0e/cugraph_wheel_python_cugraph_38%2039_x86_64.tar.gz
tar -xzf cugraph_wheel_python_cugraph_38\ 39_x86_64.tar.gz
pip install cugraph_cu11-22.10.0a0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

# To run the tests, probably easiest to clone the repo and run from there
git clone git@github.com:rapidsai/cugraph.git
RAPIDS_DATASET_ROOT_DIR=`pwd`/cugraph/datasets
cd cugraph/python/cugraph/cugraph/tests
pytest .
```

cc @vyasr

**Comment by vyasr** [comment]
[Here's the log of one of the failed runs](https://pipelines.actions.githubusercontent.com/serviceHosts/d6c198dc-6df8-474f-baf8-466706a59d3b/_apis/pipelines/1/runs/10934/signedlogcontent/77?urlExpires=2022-10-06T15%3A38%3A04.3885521Z&urlSigningMethod=HMACV1&urlSignature=BZkzzV6Hctd6C4HPXjVtXEzPm2y2HnacwIPUpjU57uE%3D).

**Comment by vyasr** [comment]
I've resolved a number of upstream errors and the new runs show a smaller set of errors. [Here's an updated run](https://github.com/rapidsai/cugraph/actions/runs/3227101202/jobs/5284480954).
