### ISSUE TITLE
[BUG]Adding data to same nodes twice in a PG results in incorrect __vertex_prop_dataframe 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2793]
**Describe the bug**
If i add data to the same nodes twice , we end up with incorrect number of rows and incorrect state of PG `__vertex_prop_dataframe` which causes a bunch of errors downstream.  

**Steps/Code to reproduce bug**
```python
import cugraph
from cugraph.experimental import PropertyGraph
import cudf

def add_node_a(pg):
    v_df =  cudf.DataFrame({'node_ids':[0,1,2]})
    pg.add_vertex_data(v_df, vertex_col_name='node_ids', type_name='a')

    feat_df =  cudf.DataFrame({'node_ids':[0,1,2], 'data':[10,20,30]})
    pg.add_vertex_data(feat_df, vertex_col_name='node_ids', type_name='a')

def add_node_b(pg):
    v_df =  cudf.DataFrame({'node_ids':[3,4,5]})
    pg.add_vertex_data(v_df, vertex_col_name='node_ids', type_name='b')

    feat_df =  cudf.DataFrame({'node_ids':[3,4,5], 'data':[10,20,30]})
    pg.add_vertex_data(feat_df, vertex_col_name='node_ids', type_name='b')
    
pg = PropertyGraph()
add_node_a(pg)
add_node_b(pg)
pg.get_num_vertices('b')
```
```
  | _TYPE_ | data
-- | -- | --
a | 10
a | 20
a | 30
b | <NA>
b | <NA>
b | <NA>
b | 10
b | 2
b | 30
```

```python
pg.get_num_vertices('b')
6
```
**Expected behavior**
```
3
```

**Environment details**
Please run and paste the output of the `cugraph/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
This will probably block https://github.com/rapidsai/dgl/pull/16

CC: @eriknw , @rlratzel , @alexbarghi-nv , @BradReesWork

**Comment by eriknw** [comment]
I see the intent here--thanks for the good example.  To my knowledge, PropertyGraph has never handled this properly.

We'll probably need to use `fillna` or `combine_first` (`combine_first` isn't in `cudf` though).

See WIP in #2796 where I ask several questions regarding implementation and behavior in code comments.
