### ISSUE TITLE
[BUG] Can not add data to the same edges twice

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2794]
**Describe the bug**
Adding data to the same edges twice results in duplicated rows.  This prevents me adding features to an existing edge in PG. 
```python
import cugraph
import cudf
from cugraph.experimental import PropertyGraph


df_1 =  cudf.DataFrame({'src': [0,1],
                      'dst': [1,2],
                      'feat_1':[10,20]
                     })


df_2 =  cudf.DataFrame({'src': [0,1],
                       'dst': [1,2],
                       'feat_2':[0.5,0.2]
                     })

pg = PropertyGraph()
pg.add_edge_data(df_1, ['src','dst'], type_name="a")
pg.add_edge_data(df_2, ['src','dst'], type_name="a")
pg._EXPERIMENTAL__PropertyGraph__edge_prop_dataframe
```

```python
	_SRC_	_DST_	_TYPE_	feat_1	feat_2
_EDGE_ID_					
0	0	1	a	10	<NA>
1	1	2	a	20	<NA>
2	0	1	a	<NA>	0.5
3	1	2	a	<NA>	0.2
```

**Expected behavior**
I would expect that we add it to the existing rows.  

```python
	_SRC_	_DST_	_TYPE_	feat_1	feat_2
_EDGE_ID_					
0	0	1	a	10	0.5
1	1	2	a	20	0.2

```

CC: @eriknw , @rlratzel , @alexbarghi-nv , @BradReesWork

**Comment by eriknw** [comment]
The current version of your example behaves as expected.  Adding new edge data is assumed to be new edges.  If you want to _update_ values of existing edges, you need to provide your own edge ids (and if you do, you'll see the incorrect behavior you are illustrating).

Do you want edges to be unique by src, dst, and type?  Should we add a new method to _update_ edge data?
