### ISSUE TITLE
[BUG][CI] RuntimeError: NVRTC error: NVRTC_ERROR_INVALID_OPTION

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cugraph#280]
There is a failure in gpuCI on cuda9.2-ubuntu18.04-py37 only.

This must be addressed for the v0.7 release.

Full output here: https://gpuci.gpuopenanalytics.com/view/rapids-branch-gpu-matrix/job/gpuCI/job/cugraph/job/branches/job/cugraph-gpu-matrix-branch-0.7/CC_VERSION=7,CUDA=9.2,LINUX_VERSION=ubuntu18.04,PYTHON=3.7/3/console

**Comment by ChuckHastings** [comment]
Does this error recur?  I cannot get it to reproduce - and it doesn't make sense.  I tried the following steps on my linux workstation and everything worked correctly:

`
git clone git@github.com:rapidsai/cugraph.git
cd cugraph
git checkout branch-0.7
git submodule update --init --recursive
bash ci/local/build.sh -i gpuci/rapidsai-base:cuda9.2-ubuntu18.04-gcc7-py3.7
`

**Comment by raydouglass** [comment]
Turns out this was the result of cuda 9.2 on T4s which is not supported.
