### ISSUE TITLE
Improve handling when passing a transposed graph into algos that dont expect one.

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#2806]
When a transposed graph is passed into an algorithm like triangle_count it returns an error that the graph must be undirected even when the graph is undirected.

**Expected behavior**
Should either return an error clearly stating the graph should not be transposed or handle it.

**Environment overview (please complete the following information)**
 - Environment location: bare-metal workstation with A6000, cuGraph 22.12 branch 10/13/2022
 - Method of cuGraph install: [conda, Docker, or from source] from source

**Environment details**
Please run and paste the output of the `cugraph/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

```
G = cugraph.Graph()
g.from_cudf_edglist(gdf, src="src", dst="dst", store_transposed=True)

cugraph.triangle_count(G)
```

**Comment by ChuckHastings** [comment]
This was corrected by #2898

I have retested and this works correctly now.
