### ISSUE TITLE
[FIX] conda recipies missing packages for Dataset API

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2811]
**Describe the bug**
when running test_datsets it crashes with a 

pytest -v tests/test_dataset.py 

```
ImportError: HTTPFileSystem requires "requests" and "aiohttp" to be installed
```

**Comment by nv-rliu** [comment]
The packages (`requests`, `aiohttp`) that were missing when this bug first arose are now included in the most recent conda recipe file: `all_cuda-120_arch-x86_64.yaml`

When running the Dataset unit tests in this conda environment, the error no longer occurs. 

Logs from my run on dgx18:
```
$ pytest -k tests/utils/test_dataset.py

>>> ...
>>> tests/utils/test_dataset.py::test_create_using[dataset1] PASSED [ 93%]
tests/utils/test_dataset.py::test_create_using[dataset2] PASSED [ 95%]
tests/utils/test_dataset.py::test_ctor_with_datafile PASSED     [ 97%]
tests/utils/test_dataset.py::test_unload PASSED                 [100%]

========================== warnings summary ===========================
../../../../miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/pylibcugraph/utilities/api_tools.py:133: 15 warnings
cugraph/tests/utils/test_dataset.py: 8 warnings
  /home/nfs/ralphl/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/pylibcugraph/utilities/api_tools.py:133: DeprecationWarning: NoneDataset has been promoted out of experimental. Use the non-experimental version instead, as this one will be removed in a future release.
    warnings.warn(warning_msg, DeprecationWarning)

cugraph/tests/utils/test_dataset.py: 53 warnings
  /home/nfs/ralphl/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/pylibcugraph/utilities/api_tools.py:150: DeprecationWarning: Noneset_download_dir has been promoted out of experimental. Use the non-experimental version instead, as this one will be removed in a future release.
    warnings.warn(warning_msg, DeprecationWarning)

cugraph/tests/utils/test_dataset.py::test_env_var
cugraph/tests/utils/test_dataset.py::test_home_dir
cugraph/tests/utils/test_dataset.py::test_set_download_dir
  /home/nfs/ralphl/miniconda3/envs/cugraph_dev/lib/python3.10/site-packages/pylibcugraph/utilities/api_tools.py:150: DeprecationWarning: Noneget_download_dir has been promoted out of experimental. Use the non-experimental version instead, as this one will be removed in a future release.
    warnings.warn(warning_msg, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================== 44 passed, 79 warnings in 13.13s ===================
```

This issue can be closed.

**Comment by bdice** [comment]
@rlratzel `meta.yaml` should only contain hard dependencies of the package, not including dependencies used only to test. If you need to generate an environment with testing dependencies, that should be done with a dev environment like `all_cuda-120_arch-x86_64.yaml` or by generating an environment with only test dependencies as we do in CI:

https://github.com/rapidsai/cugraph/blob/a3bb1fbfdfa5087a60d1cf64a803f152756e1935/ci/test_python.sh#L9-L12

**Comment by bdice** [comment]
If you need to install testing dependencies with pip, you can install `cugraph-cu12[test]` and it will also fetch the test dependencies: https://github.com/rapidsai/cugraph/blob/a3bb1fbfdfa5087a60d1cf64a803f152756e1935/python/cugraph/pyproject.toml#L51-L66

**Comment by rlratzel** [comment]
@bdice - since this originates from a call to ` df = cudf.read_csv(url)` in the dataset.py module, I'm assuming it implies `requests` and `aiohttp` are soft dependencies of cudf and we should be adding these to cugraph...or, are they **not** intended to be soft dependencies of cudf and these should be added as hard deps of cudf?

**Comment by bdice** [comment]
These are _soft_ dependencies for cudf, cudf won't force their installation (to keep cudf's dependency footprint minimal). The errors indicate pretty clearly what packages are needed, and it is perfectly fine with me for cugraph to list these as hard dependencies. However, the actual dependency you want to list for cugraph might be a bit more complicated by fsspec: https://github.com/rapidsai/cugraph/pull/3781#discussion_r1297592634
