### ISSUE TITLE
Create "getting started" doc with code examples for cugraph_service

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2830]
A "getting started" doc with code examples for cugraph_service is needed for various users and groups trying to include cugraph_service into their projects.
- [ ] Check and possibly expand the current `README.md` in cugraph_service to ensure it can be used for this purpose
- [ ] Ensure APIs, dask launcher scripts, etc. are working in the context of the examples provided in the README

**Comment by rlratzel** [comment]
cc @oyilmaz-nvidia

**Comment by acostadon** [comment]
Requirements here have been rolled into #3018
