### ISSUE TITLE
[BUG]: cuGraph does not build from source. 

### ISSUE THREAD

**Issue by ccoulombe** [rapidsai/cugraph#2892]
### Version

22.12

### Which installation method(s) does this occur on?

From source, not conda

### Describe the bug.

cuGraph does not build from source with `bash build.sh`.
```
  Could not find a package configuration file provided by "cugraph-ops"
  (requested version 22.12.00) with any of the following names:

    cugraph-opsConfig.cmake
    cugraph-ops-config.cmake
```
It is missing `cugraph-ops` and conda is not an option.

Both #2280 and #2231 had the same issue, but it is still an issue.

### Minimum reproducible example

```shell
git clone https://github.com/rapidsai/cugraph.git
cd cugraph
bash build.sh
```

### Relevant log output

```shell
Could not find a package configuration file provided by "cugraph-ops"
  (requested version 22.12.00) with any of the following names:

    cugraph-opsConfig.cmake
    cugraph-ops-config.cmake
```

### Other/Misc.

Where can one find `cugraph-ops`? If it is a closed source, can `cugraph-ops` be set to off by default instead?

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jnke2016** [comment]
Hi @ccoulombe, 
Thank you for raising this up. Before we debug this further, can you do `conda list libcugraphops` to verify thatyou have `cugraph-ops` installed?

**Comment by rlratzel** [comment]
Hi @ccoulombe , `cugraph-ops` is an optional closed-source package that's used by certain sampling algorithms.  It can be installed using conda, but if conda is not an option then the binaries will need to be downloaded and installed another way (I think we have support for `pip` for that package, but I would need to get you the details).

If you don't need support for every sampling algorithm, then you can still build cugraph without it.  If you add `-DUSE_CUGRAPH_OPS=OFF` to the cmake call in the build.sh script [here](https://github.com/rapidsai/cugraph/blob/7387fbcdaaa9c6ed4bbfd41a874203be6ee1b70b/build.sh#L228-L237), you'll be able to build and run cugraph without cugraph-ops.

I've also created an issue to address this problem which you can track [here](https://github.com/rapidsai/cugraph/issues/2902).

**Comment by ccoulombe** [comment]
@rlratzel Thanks! 

I did search for the library, on PyPI and elsewhere, without luck.

Indeed, that's what I ended up doing : compiling without `cugraph-ops` by patching the build script.
I could do a PR if you are not already working on it.

Cheers!

**Comment by rlratzel** [comment]
Glad to hear you got it working @ccoulombe .  Thanks for offering to submit a PR, but I had one started and just submitted it [here](https://github.com/rapidsai/cugraph/pull/2904), which should auto-close this issue when merged.
