### ISSUE TITLE
[ENH] CSV test input instead of MTX at C++ level

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#294]
This will better reflect cugraph's e2e use cases. It will also be faster. mmio is an old CPU C code that has several warnings. 

- [ ] convert `mtx` files to `csv` with the python script in `python/utils`
- [ ] upgrade C++ tests: replace mmio by cuDF csv reader
- [ ] update amazon s3 with the new input (syncup with Ray)

**Comment by BradReesWork** [comment]
If you use the skiprows feature of read_csv you can load the mtx files

**Comment by BradReesWork** [comment]
this has been addressed.  There is utility function to convert to CSV
