### ISSUE TITLE
[FEA] Integrate snmg sort in cugraph

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#295]
- [ ] The content of https://github.com/ogreen/cugraph/blob/fea-ext-cusort/cpp/include/cusort/sort.cuh should be added to `cugraph/cpp/src/`

- [ ] Tests should be implemented in `cugraph/cpp/src/test`. They should compare against the output of the existing naive C++ implementation for a couple of datasets.

**Comment by afender** [comment]
The MG Coo2Csr feature made it in 0.8 without the global MG sort step.

**Comment by ChuckHastings** [comment]
Is integration into SNMG coo2csr to close this issue, or should that be a separate issue?

**Comment by afender** [comment]
We went with another solution for coo2csr. this is not necessary to close this issue.
