### ISSUE TITLE
[QST]:  Why the page-rank scores differs from actual google page-rank algorithm ? 

### ISSUE THREAD

**Issue by Manoj-red-hat** [rapidsai/cugraph#2950]
### What is your question?

Consider below data Data

```
v_vertices={2,3,4,5};
v_src={3,5};
v_dst={5,3};
```
Google Page-Rank
![Screenshot from 2022-11-17 11-35-00](https://user-images.githubusercontent.com/5130287/202369087-c73a87c5-fa9f-4686-8c98-b15a7dffa6e4.png)

Damping factor =0.85 

```
Default PageRank : 
PR(2) = 1
PR(3) = 1
PR(4) = 1
PR(5) = 1

Iteration 1
PR(2) = (1-d)
PR(2) = 0.150 = 0.150

PR(3) = (1-d) + d(PR(5)/C(5))
PR(3) = 0.150 + 0.85(1.000/1) = 1.000

PR(4) = (1-d)
PR(4) = 0.150 = 0.150

PR(5) = (1-d) + d(PR(3)/C(3))
PR(5) = 0.150 + 0.85(1.000/1) = 1.000

Iteration 2 
PR(2) = (1-d)
PR(2) = 0.150 = 0.150

PR(3) = (1-d) + d(PR(5)/C(5))
PR(3) = 0.150 + 0.85(1.000/1) = 1.000

PR(4) = (1-d)
PR(4) = 0.150 = 0.150

PR(5) = (1-d) + d(PR(3)/C(3))
PR(5) = 0.150 + 0.85(1.000/1) = 1.000
```

On 2nd iteration it converges, so ideally page-rank by default google algo is
```
PR(2) = 0.150
PR(3) = 1.000
PR(4) = 0.150
PR(5) = 1.000
```

If I run above dataset  via cu-graph, I get  

```
PR(2) =0.575
PR(3) =1.425
PR(4) = 0.575
PR(5) = 1.425
```
Unable to understand which formula you are using ?

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by Manoj-red-hat** [comment]
FYI .. @ChuckHastings

**Comment by Manoj-red-hat** [comment]
FYI @BradReesWork

**Comment by Manoj-red-hat** [comment]
@ChuckHastings 

Using C++

Calling 
```
    std::vector<vertex_t> v_vertices={2,3,4,5};
    std::vector<vertex_t> v_src={3,5};
    std::vector<vertex_t> v_dst={5,3};
    auto res = cuda_func(v_vertices, v_src, v_dst,1,0.85,0.9);
```

Below wrapper function I am using 
```
std::pair<std::vector<vertex_t>,std::vector<float>> cuda_func(const std::vector<vertex_t> &v_vertices,const std::vector<vertex_t> &v_src, const std::vector<vertex_t> &v_dst,int max_itr,float alpha,float epsilon) {
    AutoProfiler T("GPU_PAGERANK");
    AutoProfiler *T1=new AutoProfiler("Raft handle creation");
    raft::handle_t handle;
    delete T1;
    T1=new AutoProfiler("thrust_host_to_device");
    rmm::device_uvector<vertex_t> d_vertices_srcs(v_vertices.size(), handle.get_stream());
    raft::update_device(d_vertices_srcs.data(), v_vertices.data(), v_vertices.size(), handle.get_stream());

    rmm::device_uvector<vertex_t> d_edgelist_srcs(v_src.size(), handle.get_stream());
    raft::update_device(d_edgelist_srcs.data(), v_src.data(), v_src.size(), handle.get_stream());

    rmm::device_uvector<vertex_t> d_edgelist_dst(v_dst.size(), handle.get_stream());
    raft::update_device(d_edgelist_dst.data(), v_dst.data(), v_dst.size(), handle.get_stream());
    RAFT_CUDA_TRY(cudaDeviceSynchronize());
    delete T1;

    T1=new AutoProfiler("Graph creation");
    cugraph::graph_t<vertex_t, edge_t, weight_t, true, false> graph(handle);
    std::optional<rmm::device_uvector<vertex_t>> renumber_map{std::nullopt};
    RAFT_CUDA_TRY(cudaDeviceSynchronize());
    std::tie(graph, std::ignore, renumber_map) = cugraph::
    create_graph_from_edgelist<vertex_t, edge_t, weight_t, int32_t, true, false>(
            handle,
            std::optional<rmm::device_uvector<vertex_t>>(std::move(d_vertices_srcs)),
            std::move(d_edgelist_srcs),
            std::move(d_edgelist_dst),
            std::nullopt,
            std::nullopt,
            cugraph::graph_properties_t{false, false},
            true);
    RAFT_CUDA_TRY(cudaDeviceSynchronize());
    delete T1;
    T1=new AutoProfiler("device_sync");
    auto graph_view = graph.view();
    std::cout << "No. of vertices " << graph_view.number_of_vertices() << std::endl;
    std::cout << "No. of edges " << graph_view.number_of_edges() << std::endl;
    rmm::device_uvector<result_t> pageranks_v(graph_view.number_of_vertices(), handle.get_stream());
    std::cout << "Result elements " << pageranks_v.size() << std::endl;
    RAFT_CUDA_TRY(cudaDeviceSynchronize());
    delete T1;
    T1=new AutoProfiler("PG RANK");
    cugraph::pagerank<vertex_t, edge_t, weight_t, result_t, false>(
            handle,
            graph_view,
            std::nullopt,
            std::nullopt,
            std::nullopt,
            std::nullopt,
            pageranks_v.data(),
            alpha,
            epsilon,
            max_itr,
            false,
            false);
    RAFT_CUDA_TRY(cudaDeviceSynchronize());
    delete T1;
    T1=new AutoProfiler("output");
    auto pageranks= to_host(handle,pageranks_v);
    auto mapping= to_host(handle,renumber_map.value());
    delete T1;
    return std::make_pair(mapping,pageranks);
}
```

**Comment by Manoj-red-hat** [comment]
Thanks @BradReesWork for explanation, I am going to test it on [Network Dataset](https://snap.stanford.edu/data/as-skitter.html)

**[Background]**

 I am trying to figure out if I can accelerate Spark Graphx or some other graph database using GPUs.

Need to see how it behaves in below cases

case 1) single node : graph can be cached in GPU
case 2) single node : graph can not be  cached in GPU
case 3) multi-node node : graph can not be  cached in GPU
case 4) multi-node node : graph can be  cached in partial-GPUs (2 node cluster : node 1 GPU cache 50% graph and node 2 GPU cache remains 50% graph)

**Comment by seunghwak** [comment]
>auto res = cuda_func(v_vertices, v_src, v_dst,1,0.85,0.9);

@Manoj-red-hat If I am not mistaken, you set max iter to 1 and epsilon to 0.9, is this intentional? If I set the values to the default, I got (0.15/2.3, 1.0/2.3, 0.15/2.3, 1.0/2.3); the value you're expecting after normalization.

And in your step by step calculation, I think you missed the contribution of 0 out-degree vertices. If a vertex has no outgoing edges, they make a random jump. So, the sum of PageRank values of the 0 out-degree vertices (dangling_sum in the C++ code https://github.com/rapidsai/cugraph/blob/branch-22.12/cpp/src/link_analysis/pagerank_impl.cuh#L236) should be considered in the math.

dangling_sum * damping_factor / # vertices (assuming no personalization vector) should be added to consider this.

If you factor this in, more than one iteration will be necessary for convergence.

**Comment by seunghwak** [comment]
So, the equation you posted is only correct under the assumption that 0 out-degree vertices are assumed to be connected with every vertex.

**Comment by Manoj-red-hat** [comment]
Thanks @seunghwak , you are absolutely right I missed dangling sum.

I tried to build libcugraph with custom printouts anyways that's didn't work raise [2974](https://github.com/rapidsai/cugraph/issues/2974) for that.

I extracted all page-rank impl dependencies from project and create a sub project which works fine and able to understand the entire algorithm. 

Thanks once again
