### ISSUE TITLE
[QST]: cosine similarity in libcugraph

### ISSUE THREAD

**Issue by Manoj-red-hat** [rapidsai/cugraph#2979]
### What is your question?

Do we have any plan to add cosine similarity algorithm ?

As a part of link prediction 

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by acostadon** [comment]
It is not in our current schedule but we will look into it and provide more information about when/if an implementation might occur.

Cosine similarly is in cuML.

**Comment by acostadon** [comment]
This is being tracked in a new feature request
https://github.com/rapidsai/cugraph/issues/2993
