### ISSUE TITLE
[FIX]: Always use PyTorch in CuGraphStore

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#2995]
### Version

23.02

### Which installation method(s) does this occur on?

Docker, Conda, Pip, Source

### Describe the bug.

Since `cugraph-pyg` will have a hard dependency on PyG once version 2.2 is released, `CuGraphStore` should always assume PyTorch is available and always use it.  The "backend" property should also be removed since it is no longer relevant.

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by kingmesal** [comment]
Status update? @alexbarghi-nv

**Comment by alexbarghi-nv** [comment]
This is planned for 23.04
