### ISSUE TITLE
[DOC]: Create an MG notebook on centrality/similarity

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3015]
### How would you describe the priority of this documentation request

High

### Describe the future/missing documentation

Customer has asked for a notebook to demonstrate centrality and similarty algorithms on Multi-GPU 

### Where have you looked?

https://github.com/rapidsai/cugraph/tree/branch-23.02/notebooks/algorithms
https://github.com/rapidsai/cugraph/tree/branch-23.02/notebooks/demo

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by BradReesWork** [comment]
duplicate of #2669
