### ISSUE TITLE
[FIX]: Update cugraph_dev_cuda11.6 environment 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#3037]
### Version

23.02

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

We need to update  cugraph_dev_cuda11.6 environment  to match 23.02 .

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
should be covered in https://github.com/rapidsai/cugraph/pull/3131
