### ISSUE TITLE
[FEA] Add __version__ attribute

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cugraph#304]
**Is your feature request related to a problem? Please describe.**
Hi!

I have tried to double check current cugraph version in my container by running the following code:

```
import cugraph
print(cugraph.__version__)
```

It returns the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-39ef4ed12d29> in <module>
      1 import cugraph
      2 
----> 3 print(cugraph.__version__)

AttributeError: module 'cugraph' has no attribute '__version__'
```

**Describe the solution you'd like**
cudf, cuml, dask_cudf, dask_cudf already implement '\_\_version\_\_' attribute.

It would be great if cugraph could also implement it.

Hope it helps!

Regards,
Miguel

**Comment by afender** [comment]
Hi Miguel, 

Good catch and thanks for letting us know! This will be addressed in the next release.

Have a great day,
Alex
