### ISSUE TITLE
[FEA]: Enable RMM PyTorch allocator  for cugraph_dgl 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#3043]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem this feature solves

We should enable RMM PyTorch allocator  for cugraph_dgl by default for Pytorch. This should prevent memory issues as well as enable speedups (2-3x) when using POOL .

RMM PR: https://github.com/rapidsai/rmm/pull/1168

### Describe your ideal solution

NA

### Additional context

We will probably need to do the same for PYG

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by alexbarghi-nv** [comment]
Done for now, this works on single GPU but we do not want to always have it enabled.
