### ISSUE TITLE
[FEA]: Address warnings and issues in notebooks and tests

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3068]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

Running notebooks, including in CI, is generating a number of warning messages that should be addressed

- [ ] cugraph/tests/test_louvain.py::test_louvain_csr_graph[False]

- [ ]   /opt/conda/envs/test/lib/python3.9/site-packages/cupy/sparse/__init__.py:17: DeprecationWarning: cupy.sparse is deprecated. Use cupyx.scipy.sparse instead.
    warnings.warn(msg, DeprecationWarning)

- [ ] cugraph/tests/test_betweenness_centrality.py: 144 warnings

- [ ]   /__w/cugraph/cugraph/python/cugraph/cugraph/tests/test_betweenness_centrality.py:163: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    sources = random.sample(Gnx.nodes(), k)

- [ ] cugraph/tests/test_bfs.py: 26 warnings
  /__w/cugraph/cugraph/python/cugraph/cugraph/tests/test_bfs.py:280: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    start_vertex = random.sample(Gnx.nodes(), 1)[0]

- [ ] cugraph/tests/test_bfs.py: 10 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/traversal/bfs.py:108: DeprecationWarning: This function is deprecated in favor of cupy.from_dlpack
    distances = cp.fromDlpack(sorted_df["distance"].to_dlpack())

- [ ] cugraph/tests/test_bfs.py: 10 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/traversal/bfs.py:109: DeprecationWarning: This function is deprecated in favor of cupy.from_dlpack
    preds = cp.fromDlpack(sorted_df["predecessor"].to_dlpack())

- [ ] cugraph/tests/test_compat_pr.py: 23 warnings

cugraph/tests/test_pagerank.py: 90 warnings
  /opt/conda/envs/test/lib/python3.9/site-packages/networkx/algorithms/link_analysis/pagerank_alg.py:108: DeprecationWarning: networkx.pagerank_scipy is deprecated and will be removed in NetworkX 3.0, use networkx.pagerank instead.
    return pagerank_scipy(

- [ ] cugraph/tests/test_connectivity.py: 14 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/components/connectivity.py:91: DeprecationWarning: This function is deprecated in favor of cupy.from_dlpack
    labels = cp.fromDlpack(sorted_df["labels"].to_dlpack())

- [ ] cugraph/tests/test_convert_matrix.py::test_from_to_numpy[graph_file2]

  /opt/conda/envs/test/lib/python3.9/site-packages/networkx/convert_matrix.py:579: DeprecationWarning: to_numpy_matrix is deprecated and will be removed in NetworkX 3.0.
  Use to_numpy_array instead, e.g. np.asmatrix(to_numpy_array(G, **kwargs))
    warnings.warn(

- [ ]  cugraph/tests/test_convert_matrix.py::test_from_to_numpy[graph_file2]

  /opt/conda/envs/test/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return matrix(data, dtype=dtype, copy=False)

 

- [ ] cugraph/tests/test_convert_matrix.py::test_from_to_numpy[graph_file2]

  /opt/conda/envs/test/lib/python3.9/site-packages/networkx/convert_matrix.py:687: DeprecationWarning: from_numpy_matrix is deprecated and will be removed in NetworkX 3.0.
  Use from_numpy_array instead, e.g. from_numpy_array(A, **kwargs)
    warnings.warn(

- [ ] cugraph/tests/test_property_graph.py: 130 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/pylibcugraph/utilities/api_tools.py:67: PendingDeprecationWarning: NonePropertyGraph is experimental and will change or be removed in a future release.
    warnings.warn(warning_msg, PendingDeprecationWarning)

 

- [ ] cugraph/tests/test_jaccard.py::test_weighted_exp_jaccard

  /opt/conda/envs/test/lib/python3.9/site-packages/pylibcugraph/utilities/api_tools.py:88: PendingDeprecationWarning: Nonejaccard is experimental and will change or be removed in a future release.
    warnings.warn(warning_msg, PendingDeprecationWarning)

 

- [ ] cugraph/tests/test_random_walks.py: 18 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/sampling/random_walks.py:105: PendingDeprecationWarning: Coalesced path results is deprecated and will no longer be supported in the next releases. only padded paths will be returned instead
    warnings.warn(warning_msg, PendingDeprecationWarning)

 

- [ ] cugraph/tests/test_random_walks.py: 12 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/sampling/random_walks.py:160: PendingDeprecationWarning: The 'max_depth' is relative to the number of vertices and will be deprecated in the next release. For non legacy result type, it is relative to the number of edges which will only be supported.
    warnings.warn(warning_msg, PendingDeprecationWarning)

 

- [ ] cugraph/tests/test_edge_betweenness_centrality.py: 72 warnings

  /__w/cugraph/cugraph/python/cugraph/cugraph/tests/test_edge_betweenness_centrality.py:165: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    sources = random.sample(Gnx.nodes(), k)

- [ ] cugraph/tests/test_edge_betweenness_centrality.py: 48 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/networkx/algorithms/centrality/betweenness.py:225: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    nodes = seed.sample(G.nodes(), k)

- [ ] cugraph/tests/test_graph.py::test_consolidation[graph_file0]

  /opt/conda/envs/test/lib/python3.9/site-packages/tornado/ioloop.py:350: DeprecationWarning: make_current is deprecated; start the event loop first
    self.make_current()

- [ ]  cugraph/tests/test_hungarian.py::test_hungarian[500-500-10000]

  /__w/cugraph/cugraph/python/cugraph/cugraph/tests/test_hungarian.py:63: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    v1, g, m = create_random_bipartite(v1_size, v2_size, weight_limit, np.float)

- [x] cugraph/tests/test_sssp.py: 10 warnings

  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/traversal/sssp.py:112: DeprecationWarning: This function is deprecated in favor of cupy.from_dlpack
    cp.fromDlpack(sorted_df["distance"].to_dlpack()),

- [x] cugraph/tests/test_paths.py: 6 warnings

cugraph/tests/test_sssp.py: 10 warnings
  /opt/conda/envs/test/lib/python3.9/site-packages/cugraph/traversal/sssp.py:113: DeprecationWarning: This function is deprecated in favor of cupy.from_dlpack
    cp.fromDlpack(sorted_df["predecessor"].to_dlpack()),

### Describe your ideal solution

Go through all the notebook and examine the warning message and deterime if the can be addressed 

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by BradReesWork** [comment]
PR #3126 addresses the Dlpack warnings

**Comment by acostadon** [comment]
This issue is outdated but notebook warnings persist. Need to create an Epic and add warnings that are currently active.
