### ISSUE TITLE
[QST]: Saving cugraph object

### ISSUE THREAD

**Issue by acjones27** [rapidsai/cugraph#3114]
### What is your question?

Hi, 

I was wondering if anyone knows how to save a Graph object after it's been created? I'm creating a large DiGraph (1.7 billion edges), so I would preferably like to save the output once it has been created. Is this possible? I looked into pickle and joblib but got errors "cannot pickle 'socket' object" and "TypeError: cannot pickle 'TaskStepMethWrapper' object", respectively

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by BradReesWork** [comment]
You can get the edge data from the graph, which is a cuDF DataFrame and then use the save features offered bu cuDF.   
cuDF support saving as CSV, Parquet, JSON, or ORC.  https://docs.rapids.ai/api/cudf/stable/user_guide/io.html

**Comment by acjones27** [comment]
Hi @BradReesWork, thanks for the suggestion. Could you be more specific about the edge data? Do you mean the edgelist? If so, wouldn't I still have to rebuild the graph from scratch each time? Also, I already have the edge data since that's how I built the graph to begin with so I guess it's the same thing (apologies if I'm missing something)
