### ISSUE TITLE
[FEA] Update UCX Dockerfile to Include Build Packages

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3122]
The current Dockerfile for building an environment with the latest version of UCX, required for properly benchmarking MG+UCX code, does not have the packages needed to build cugraph.  This makes testing more difficult as the necessary packages have to be installed, which could result in conflicts, etc.  The current Dockerfile should be updated to already include these packages so benchmarking can be performed on a development version of cugraph easily.

**Comment by rlratzel** [comment]
For reference: https://github.com/rapidsai/cugraph/blob/9c41ece4f1ecd54fd558ead99a794e90ff1ab3f2/benchmarks/shared/build_cugraph_ucx/cugraph_ucx.dockerfile
