### ISSUE TITLE
[DOC]: weakly_connected_components says that input graph can be directed but the code suggests otherwise

### ISSUE THREAD

**Issue by acjones27** [rapidsai/cugraph#3133]
### How would you describe the priority of this documentation request

High

### Please provide a link or source to the relevant docs

https://docs.rapids.ai/api/cugraph/stable/api_docs/api/cugraph.weakly_connected_components.html

### Describe the problems in the documentation

The documentation for weakly_connected_components suggests that

> If using a graph object, the graph can be either directed or undirected where an undirected edge is represented by a directed edge in both directions

I am passing in a graph of type `<cugraph.structure.graph_classes.Graph object>` and `G.is_directed()` is `True`, but I still get the error 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/rapids-22.12-new/lib/python3.9/site-packages/cugraph/components/connectivity.py", line 188, in weakly_connected_components
    raise ValueError("input graph must be undirected")
ValueError: input graph must be undirected
```

And the code also quite clearly checks this https://github.com/rapidsai/cugraph/blob/2ae4b61aeabb6e9233e4d236ba83e649cd59b28a/python/cugraph/cugraph/components/connectivity.py#L187

In this case, I guess the documentation is incorrect unless I'm missing something?

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by ChuckHastings** [comment]
The documentation is incorrect.  The Weakly Connected Components implementation relies on the fact that the underlying graph is symmetric.

The python documentation should be updated to reflect this.  C++ documentation already reflects this limitation.

**Comment by BradReesWork** [comment]
@acostadon - please convert this to an issue and get Docs updated
