### ISSUE TITLE
[BUG]: 'from_cudf_adjlist' still does not work after last fix

### ISSUE THREAD

**Issue by Intron7** [rapidsai/cugraph#3182]
### Version

22.12

### Describe the bug.

The bug #3016 was fixed for the conda version. However it's still present in the pypi realse of 22.12.

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by Intron7** [comment]
Yes that's perfect. I knew that it was fixed for 22.12 so I wanted to let you know about the error in the pip version.

**Comment by rlratzel** [comment]
Thank you @Intron7 , we appreciate you taking the time to create this issue and letting us know.  Thanks for confirming it's okay to close and closing it too.
