### ISSUE TITLE
[QST]: multi-GPU dask cluster setup

### ISSUE THREAD

**Issue by wence-** [rapidsai/cugraph#3187]
### What is your question?

Since #3082, multi-GPU tests attempt to start workers on devices 1 and 2 by default (rather than 0 and 1), since `cugraph.dask.common.start_dask_client`

https://github.com/rapidsai/cugraph/blob/5c021fb21230f256abf723a977aaecc24a315bf7/python/cugraph/cugraph/dask/common/mg_utils.py#L104-L117

Has a (deliberate?) off-by-one in selecting the relevant devices.

In contrast, the previous usage (from `cugraph.testing.mgutils.start_dask_client`) would usually pass `dask_worker_devices=None` to `LocalCUDACluster`, which results in selecting all the devices on the system (indexed from zero).

https://github.com/rapidsai/cugraph/blob/5c021fb21230f256abf723a977aaecc24a315bf7/python/cugraph/cugraph/testing/mg_utils.py#L59-L64

This seems like it is just a bug, but might have been done deliberately?
### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by wence-** [comment]
Given discussion in #3189, this _is_ deliberate, so I'd be happy to close.

**Comment by VibhuJawa** [comment]
Yup this is deliberate to allow client process to do stuff like training. Closing this.
