### ISSUE TITLE
[DOC]: Build From Source Page has wrong file name in conda env

### ISSUE THREAD

**Issue by GregorySchwing** [rapidsai/cugraph#3203]
### How would you describe the priority of this documentation request

Low (would be nice)

### Please provide a link or source to the relevant docs

https://github.com/rapidsai/cugraph/blob/branch-23.02/readme_pages/SOURCEBUILD.md

### Describe the problems in the documentation

conda env create --name cugraph_dev --file conda/environments/all_cuda-118_arch-x86_64.yaml

should be 

conda env create --name cugraph_dev --file conda/environments/all_cuda-115_arch-x86_64.yaml

as of 
commit 5bf1f4473c5cc2355eb7c8fd860d55aa9ea4ddc8 (HEAD -> branch-23.02, origin/branch-23.02, origin/HEAD)
Author: Rick Ratzel <3039903+rlratzel@users.noreply.github.com>
Date:   Fri Jan 6 17:07:21 2023 -0600
__

### (Optional) Propose a correction

replace 
conda env create --name cugraph_dev --file conda/environments/all_cuda-118_arch-x86_64.yaml

with 

conda env create --name cugraph_dev --file conda/environments/all_cuda-115_arch-x86_64.yaml

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
Hi @GregorySchwing , the latest versions of these docs in [branch-23.02](https://github.com/rapidsai/cugraph/tree/branch-23.02) (the current default branch) only have a conda env file named [all_cuda-118_arch-x86_64.yaml](https://github.com/rapidsai/cugraph/tree/branch-23.02/conda/environments), which matches the file name in the current [SOURCEBUILD.md](https://github.com/rapidsai/cugraph/blob/branch-23.02/readme_pages/SOURCEBUILD.md)
```
# create the conda environment (assuming in base `cugraph` directory)

# for CUDA 11.5
conda env create --name cugraph_dev --file conda/environments/all_cuda-118_arch-x86_64.yaml
```

However, I do see that the comment still says "CUDA 11.5", which could be confusing. Perhaps this issue should be for correcting the comment and not the `conda env create` command?

**Comment by GregorySchwing** [comment]
I had to pull the repo to get the latest changes.  The last commit I had was from  Date: Fri Jan 6 17:07:21 2023 -0600.
The conda env file was updated 5 days ago in commit 5c021fb21230f256abf723a977aaecc24a315bf7.
