### ISSUE TITLE
[FEA]: Add MG DASK edgelist and graph support to Datasets API

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3218]
The DataSets class should include some datasets that require MG.

* Identify datasets
* Add to Datasets

**Comment by huiyuxie** [comment]
Hi! I'm interested in implementing this feature. It has not yet been assigned and I'd like to take on this.

Here is what I plan to do:
1. Add `get_mg_edgelist()` function to [Dataset API](https://github.com/rapidsai/cugraph/blob/branch-23.12/python/cugraph/cugraph/datasets/dataset.py), which returns an `Edgelist` by invoking `dask_cudf.read_csv()`.
2. Add `get_mg_graph()` function to [Dataset API](https://github.com/rapidsai/cugraph/blob/branch-23.12/python/cugraph/cugraph/datasets/dataset.py), which returns a `Graph` object by invoking `Graph.from_dask_cudf_edgelist()`.
3. Test above new functions through adding `test_get_mg_edgelist()` and `test_get_mg_graph()` to the [test_dataset file](https://github.com/rapidsai/cugraph/blob/branch-23.12/python/cugraph/cugraph/tests/utils/test_dataset.py).

Then the use case will be:
```python
from cugraph.datasets import karate
E = karate.get_mg_edgelist()
G = karate.get_mg_graph()
```

I'm not quite sure if the above would satisfy these two requirements.: (1) Identify datasets and (2) Add to Datasets. Should I add more functions? For example, determining if a dataset requires MG handling based on its size, or tagging the dataset metadata (.yaml file) to indicate the need for MG processing, and then proceed with MG? 

I will set up the multiple GPU EC2 instance on AWS to implement this feature and probably create a PR within the following two weeks. Any feedback or suggestions would be appreciated! I will check them here in my spare time :)

**Comment by huiyuxie** [comment]
There are more tasks to consider:
4. Add `__download_csv_mg()` and `download_all_mg()` to [Dataset API](https://github.com/rapidsai/cugraph/blob/branch-23.12/python/cugraph/cugraph/datasets/dataset.py) to read .csv file via MG.
5. Test above new functions in the [test_dataset file](https://github.com/rapidsai/cugraph/blob/branch-23.12/python/cugraph/cugraph/tests/utils/test_dataset.py).
