### ISSUE TITLE
[FEA] Common code formatting checking across C++ code

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#326]
Clang format is being added to other Rapids projects. Motivations are clearly described in cudf and cuml issues below and they also apply to cuGraph :
rapidsai/cudf#540
https://github.com/rapidsai/cuml/issues/560

cuML proposed the following solution :
rapidsai/cuml#616

**Comment by codereport** [comment]
Hi @BradReesWork, I am in the process of wrapping this up for cuDF. I can set it up for cuGraph as well. Feel free to assign me.
