### ISSUE TITLE
[FEA]:  MG Testing should use datasets that requier more than 1 GPU

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3282]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem this feature solves

The current set of MG test use a dataset that is too small,  it is even small for SG testing.  
The datasets need to be over 200 million edges, 1 billion edges and larger preferred

Nothing smaller than the cyber.csv , Twitter dataset should be mandatory.

The issues is that we are not uncovering DASK and other issues when using trivial datasets.  Testing MG on a dataset with 2K edges is pointless

### Describe your ideal solution

Create a MG dataset that every MG test uses.
Update all test to use the new dataset 

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by rlratzel** [comment]
Related: #3540 adds MG benchmarks that use RMAT-generated datasets that scale with the number of GPUs.
