### ISSUE TITLE
[BUG] CSV Import Error

### ISSUE THREAD

**Issue by nbucklin** [rapidsai/cugraph#330]
**Describe the bug**
It's not clear to me if CSV import is enabled or not. I can see this was discussed in #233 & #219 but I can't tell what the outcome was. When trying to use `cugraph` on a graph generated from a CSV file and `cudf` dataframe I get this error: `GDFError: b'GDF_UNSUPPORTED_DTYPE'`. When using `mmread` for a MTX file `cugraph` works fine

**To Reproduce**
```
df_cd = cudf.read_csv('/path/polbooks.csv',sep= ' ',header=None,names=['src','dst','weight'])
G = cugraph.Graph()
G.add_edge_list(df_cd['src'],df_cd['dst'],None)
out = cugraph.pagerank(G)
>> GDFError: b'GDF_UNSUPPORTED_DTYPE'
```

**Expected behavior**
Loading graph from `cudf` dataframe works the same as loading from MTX file.

**Desktop (please complete the following information):**
 - OS: Debian 9 (Google Cloud)

**Comment by afender** [comment]
Thank you for reaching out about this issue.

`add_edge_list` supports only int32 type. The best way to address this in your example is by explicitly telling the CSV reader to use int32 type by adding `dtype=['int32', 'int32', 'float32']`. 

I was able to find your dataset [here](https://www.cise.ufl.edu/research/sparse/matrices/Newman/polbooks.html) in mtx format and converted it using our [mtx2csv](https://github.com/rapidsai/cugraph/blob/branch-0.8/python/utils/mtx2csv.py) converter. Then, the following code succeeded : 

```
import cudf
import cugraph
from librmm_cffi import librmm as rmm
from librmm_cffi import librmm_config as rmm_cfg

df_cd = cudf.read_csv('polbooks.csv',sep= ' ',header=None,dtype=['int32', 'int32', 'float32'], names=['src','dst'])
G = cugraph.Graph()
G.add_edge_list(df_cd['src'],df_cd['dst'],None)
df = cugraph.pagerank(G)
print(df['pagerank'])
```

Notice that this dataset does not seem to have weights and the PageRank algorithm does not use this column so the "weight" column may be safely dropped.

cuGraph documentation and input checking will be improved my next PR and I will make sure to better capture this use case. Finally, when the input is already stored on the device as int64 or strings, cugraph can translate this representation in int32. This feature is called `renumber`.

I hope this is useful to you and please let us know if you encounter any other problems using cuGraph.

**Comment by nbucklin** [comment]
Thanks for your help. Just tried it out and the `dtype` method worked. Thanks!

**Comment by afender** [comment]
Glad to hear that! I'm closing the issue.
