### ISSUE TITLE
[QST]: cugraph-ops

### ISSUE THREAD

**Issue by black6816** [rapidsai/cugraph#3301]
### What is your question?

Hi, Alls.

I can't find cugraph-ops repo, isn't it an open source repo?

<img width="620" alt="image" src="https://user-images.githubusercontent.com/29648796/221531651-07e3ca8e-8ae3-4238-ac73-2c452ade454d.png">

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by BradReesWork** [comment]
@black6816 cugraph-ops is a closed-source effort, so the repo is not publicly open
