### ISSUE TITLE
End-to-End MNMG Example Notebook for cugraph-dgl and cugraph-pyg with Dask

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3315]
Should have notebooks for cugraph-dgl and cugraph-pyg that demonstrate how to run end-to-end training on MNMG using Dask and the bulk sampler.

**Comment by VibhuJawa** [comment]
We have these present for  DGL here. 
https://github.com/rapidsai/cugraph/blob/branch-23.04/python/cugraph-dgl/examples/muti_trainer_MG_example/workflow.py

Todo left: 
Add model training bits for MNMG dask (we only have until dataloading), which got slipped by me in last release. 

We have one for PyG here: 
https://github.com/rapidsai/cugraph/blob/branch-23.04/python/cugraph-pyg/cugraph_pyg/examples/graph_sage_mg.py

Which i think is complete.

**Comment by rlratzel** [comment]
3 points applied to 23.06, 3 points to be applied to 23.08

**Comment by VibhuJawa** [comment]
PR up for closing this https://github.com/rapidsai/cugraph/pull/3603
