### ISSUE TITLE
[BUG]: Many test failures in cugraph-dgl with DGL 1.0 

### ISSUE THREAD

**Issue by chang-l** [rapidsai/cugraph#3320]
### Version

23.02

### Which installation method(s) does this occur on?

Source

### Describe the bug.

Within cugraph-dgl, the use of DGL dataloader API is inconsistent to DGL 1.0 and it can fail many tests under `cugraph-dgl/tests` if the latest DGL is installed . For example, when using `dgl.dataloading.create_tensorized_dataset` like below:
https://github.com/rapidsai/cugraph/blob/8539b88d48e3377f85e2146435018c8d16d17ceb/python/cugraph-dgl/cugraph_dgl/dataloading/dataloader.py#L144-L151
the latest DGL 1.0 added an additional arg `use_shared_memory` to `create_tensorized_dataset()` in 1.0 release, i.e., https://github.com/dmlc/dgl/blob/1.0.x/python/dgl/dataloading/dataloader.py#L554-L555 ([ref PR](https://github.com/dmlc/dgl/pull/4497))

We may need to either fix the issue or inform users that 23.02 only supports DGL up to 0.9...

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by VibhuJawa** [comment]
So, I pushed a fix for this after the 23.02 release with [cugraph/pull/3291/](https://github.com/rapidsai/cugraph/pull/3291/files#diff-90e104d897a4c013ed2a0277850b6ca609e86605dccf38da479b6a066c5e45fe)

What is the best way for you to use a patch ?

**Comment by chang-l** [comment]
Thanks. 
I am wondering can this fix be cherry-picked into the latest release (23.02)?

**Comment by TristonC** [comment]
We need it into RAPIDS 23.02.

**Comment by VibhuJawa** [comment]
@chang-l , Did cherry picking fix things for you ? The fix for this is all ready in .

**Comment by VibhuJawa** [comment]
@rlratzel , Can you provide guidance on how to merge stuff into `23.02 ` ? I am not sure if that is a possibility for us

**Comment by chang-l** [comment]
@VibhuJawa  Yes, your fix in [cugraph/pull/3291/](https://github.com/rapidsai/cugraph/pull/3291/files#diff-90e104d897a4c013ed2a0277850b6ca609e86605dccf38da479b6a066c5e45fe) works. It seems only in devel branch (23.04), right?

**Comment by VibhuJawa** [comment]
@kingmesal communicated that there wont be patched release so closing this. Please open this if this understanding is incorrect.
