### ISSUE TITLE
[QST]: Support for different quality functions for Leiden

### ISSUE THREAD

**Issue by lvxhnat** [rapidsai/cugraph#3328]
### What is your question?

Is there anyway for me to set a user defined quality function? I wish to define Leiden to optimise using the Constant Potts Model (CPM), but at the moment, does not seem to take in any parameters that allow me to do so.

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by BradReesWork** [comment]
Currently no.  But having either a collection of quality functions or even  a User Define Function (UDF) would be a good extension to what we have.

CC:  @ChuckHastings @naimnv

**Comment by ChuckHastings** [comment]
We have been actively working on providing a new modularity-based implementation of Leiden that we expect will be much better.  We can definitely explore adding CPM to Leiden as a follow-on to this work.  I believe the refactoring of Leiden will make this a very tractable problem.

If we want to explore a UDF, we probably need to have a bigger design conversation.  There are some optimizations in the code that might make it a bit complex to support a UDF (specifically, it might be necessary to break the UDF up into pieces in a way that might not be obvious to the developer).  But we can explore some of those ideas as we look at expanding to add CPM.

**Comment by BradReesWork** [comment]
New feature request created:  https://github.com/rapidsai/cugraph/issues/3471
