### ISSUE TITLE
DataSets: Move out of Experimental

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3359]
Move the class out of experimental

**Comment by rlratzel** [comment]
We also need to remember to use the ["promoted" deprecation util](https://github.com/rapidsai/cugraph/blob/dca4d4c365b62ac813f697eb49fea41a6b58d3f1/python/cugraph/cugraph/utilities/api_tools.py#L23) so we don't break anyone currently using `cugraph.experimental.datasets`

**Comment by nv-rliu** [comment]
PR #3680 addresses this issue. 

Status update for promoting the Datasets API
- Users can now import stable datasets objects from `cugraph.datasets`
- Experimental warning wrappers have been added to the deprecated version of datasets
- `test_dataset.py` will now verify that an experimental dataset object will raise a `DeprecationWarning` upon use
- `test_dataset.py` also verifies that the Graph object has the same properties (vertices, edges) as the metadata file used to create it
- The location of the dataset batches have been migrated from `cugraph/experimental/datasets` to `cugraph/testing`
- Redundant and unnecessary batches have been removed or localized to specific unit tests
- The remaining batches now use an improved naming scheme
- `cugraph` doc-strings, notebooks, and unit tests have been updated to use stable Datasets
- The URLs for the metadata (eg `karate.yaml`) now point to data files hosted in a permanent S3 location
