### ISSUE TITLE
[DOC]: BLOG on cugraph-pyg and cugraph-dgl

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3364]
### How would you describe the priority of this documentation request

High

### Describe the future/missing documentation

Create a BLOG on how to use cugraph-pyg and/or cugrapg-dgl

### Where have you looked?

N/A

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by alexbarghi-nv** [comment]
Both blogs have no been published, waiting on marketing to give the go ahead to promote the DGL blog.
