### ISSUE TITLE
Data Masking - Create requirements and design documentation

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3397]
Create Requirements and design documentation for data masking.

**Comment by seunghwak** [comment]
I will interpret this as identifying the required tasks to finish vertex/edge masking, so we can create issues.

* Define a wrapper class to store vertex property values.
  - We currently uses a simple 1D array to store vertex property values assuming that the vertex IDs assigned to each GPU are consecutive integers. This no longer holds with vertex masking.
  - Similar to storing edge/edge src/edge dst property values, we need to create a class to store vertex property values and abstract out the complexities related to vertex masking.
* Packed Bool support for edge property values
 - Ready-for-review (https://github.com/rapidsai/cugraph/pull/3482)
* Update graph utility functions to support vertex & edge maksing
 - e.g. coarsen_graph, decompress_edgelist, select_random_vertices, ...
* Update all the primitives to support vertex & edge masking
* Check all the algorithms are working with vertex & edge masking.
 - We need to update C++ test suites to include vertex & edge masking
 - Remove the user level code written assuming that local vertex partition range is contiguous integers (all these should be hided inside the wrapper class to store vertex property values).
* Define the behavior of the classes to store vertex/edge/edge src/edge dst property values when masks are updated.
 - Unmasked vertex/edge may have invalid/outdated values.
 - Need to think about how this will be extended with vertex/edge insertions/deletions.

**Comment by ChuckHastings** [comment]
I updated the tracking epic to include the new items in the list above.  Going to consider this design task complete with the above comments.
