### ISSUE TITLE
cugraph.dask.common.input_utils.get_distributed_data Drops Column Names

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3420]
While investigating a bug involving concatenation of cudf series objects in `cugraph.dask.uniform_neighbor_sample`, another bug was found where after calling `get_distributed_data`, the column names of the returned dask future were removed.  For some reason, calling `merge` instead of `concat` before `get_distributed_data` did not produce this bug.

```
s1 = ...
s2 = ...
df = dask_cudf.concat([s1, s2], axis=1)

ddf = get_distributed_data(ddf)
wait(ddf)
ddf = ddf.worker_to_parts

print(ddf[0][0].result().columns)
```
Expected:
```
["s1", "s2"]
```

Actual:
```
Int64Index([0, 1])
```

**Comment by rlratzel** [comment]
This should be combined with another story for removing get_distributed_data.

**Comment by rlratzel** [comment]
@alexbarghi-nv mentioned we're removing `cugraph.dask.common.input_utils.get_distributed_data`, which should resolve this issue.

**Comment by alexbarghi-nv** [comment]
Issue no longer relevant
