### ISSUE TITLE
Edgelist Returned from dataset.get_edgelist() is global

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3421]
Currently, when calling `get_edgelist()`, a global edgelist is returned.  This causes issues when performing operations such as:
```
df_unweighted = datasets.karate.get_edgelist()
df.drop('wgt', axis=1, inplace=True)
...
df_weighted = datasets.karate.get_edgelist()
print(df_weighted)
```
Expected:
```
src  dst  wgt
...
```

Actual:
```
src  dst
...
```

To fix this issue, datasets should return a copy of the global edgelist so the edgelist can be used in multiple places without affecting the original object.

**Comment by rlratzel** [comment]
We can also address this with documentation stating that a reference is being returned and that the caller should make a copy if needed. This makes it more of a documentation bug.
