### ISSUE TITLE
cugraph-pyg and cugraph-dgl performance blog

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3437]
* Two blogs, one on cugraph-dgl performance and one on cugraph-pyg performance
* depends on benchmark story

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/graph_dl/issues/168
```

**Comment by VibhuJawa** [comment]
Dont have edit permissions so adding a comment:
Depends upon:

1. https://github.com/rapidsai/cugraph/issues/3440
2. https://github.com/rapidsai/cugraph/issues/3439
3. https://github.com/rapidsai/graph_dl/issues/172

**Comment by alexbarghi-nv** [comment]
Probably deferred to November
