### ISSUE TITLE
cugraph-dgl getting started blog

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3438]
* scope is: examples, writing blog, reviews, etc.
* No initial benchmark numbers ("numbers and perf coming soon")
    Include getting started scripts
    ensure marketing sign-off
    includes cugraph-ops coverage

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by rlratzel** [comment]
Need to include Alex R.

**Comment by rlratzel** [comment]
This was started in 23.06, may need to determine if there are any points to apply to 23.08

**Comment by rlratzel** [comment]
link to blog to review: https://docs.google.com/document/d/1NMlIRZePH8hCnbBkLTArLw5H-InseOI8z73usk1mpuY/edit#heading=h.bdbpyzlbhsxp

**Comment by BradReesWork** [comment]
BLOG is live:  https://nvda.ws/45WeWVi
