### ISSUE TITLE
efficient cugraph graph creation (runtime and memory)

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3439]
* leveraging the profile data Joseph acquired in 23.04 #3310 
* look into various ownership options
* currently, there's significant duplication of data - est. 4X memory
* add scale testing [include table of num GPUs vs. num edges/scale]

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Research and prototype decorator that uses dask features for memory profiling
```

**Comment by VibhuJawa** [comment]
Related issue from  @jolorunyomi  https://github.com/rapidsai/cugraph/issues/3310

**Comment by VibhuJawa** [comment]
Related issue to add: https://github.com/rapidsai/cugraph/issues/2769

**Comment by VibhuJawa** [comment]
Probably related issue: https://github.com/rapidsai/graph_dl/issues/155 (CC: @alexbarghi-nv )

**Comment by VibhuJawa** [comment]
Linked issue: 
https://github.com/rapidsai/graph_dl/issues/187

**Comment by rlratzel** [comment]
@jnke2016 - could use benchmark data on graph creation

**Comment by rlratzel** [comment]
Profile data is [here](https://github.com/rapidsai/graph_dl/issues/187#issuecomment-1513371888).

**Comment by rlratzel** [comment]
related: https://github.com/rapidsai/cugraph/issues/3541
