### ISSUE TITLE
[BUG] weakly_connected_components(G, connect_type = CUGRAPH_WEAK) should not take connect_type

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#344]
**Describe the bug**

    connect_type : cugraph_cc_t
      Weak (CUGRAPH_WEAK), or Strong (CUGRAPH_STRONG) (not implemented, yet)

weakly_connected_compnents(G, connect_type=CUGRAPH_STRONG) does not make sense. In this case, do we get weakly connected components or strongly connected components? The function name already implies that this will compute weakly connected components.

**Comment by Iroy30** [comment]
Can be closed
