### ISSUE TITLE
[BUG]: MNMG tests failing on later version of NCCL (>2.11.4.1)

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#3478]
### Version

23.04

### Which installation method(s) does this occur on?

Docker, Conda, Source

### Describe the bug.

All our MNMG runs fail when running on 32+ GPU with nccl>2.11.4.1. This impact all the algos.

### Minimum reproducible example

```shell
Run any MNMG algo on 32+ GPUs
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
Notes (20230411)
* still need a minimal reproducer
* will need a 32+ GPU cluster to reproduce
* RAFT related

**Comment by rlratzel** [comment]
5 points remaining for 23.08
