### ISSUE TITLE
Update Graph creation API (add_cudf_edgelist) to allow for individual edge ID/type/weight specifications

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3486]
`Graph.add_cudf_edgelist()` should add the ability for users to specify only one or several of edge types/IDs/weights. 

At the moment, users can specify only weights, or weights and type and ID, but they cannot, for example, specify only ID and types.

If a user wants only IDs and types, they must specify weight too, which wastes memory since weights would be allocated but unused.

**Comment by alexbarghi-nv** [comment]
# Option 1
G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(
  source='src',
  destination='dst',
  edge_attr=['w','etp','attr1','attr2']
 )
 
 G.set_edge_type('etp')
 G.set_edge_weight('w')
 G.set_edge_id('attr2')
 
 # Option 2 (would allow either edge_attr or weight/edge_id/edge_type, throw exception if both provided)
 # User can specify only the edge properties they need.
 G = cugraph.Graph(directed=True)
 G.from_cudf_edgelist(
  source='src',
  destination='dst',
  weight='w',
  edge_id='attr1',
  edge_type='etp'
 )

**Comment by alexbarghi-nv** [comment]
Decided to go with option 2 after discussion
