### ISSUE TITLE
Profile Sampling Calls

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3543]
Profile MG sampling calls to understand memory and compute usage during the call.  Create a chart documenting the expected vs. actual memory usage similar to what was done for graph creation.  Create a list of required improvements/changes based on any performance issues found with sampling.

**Comment by rlratzel** [comment]
@alexbarghi-nv can you update this when you get chance.

**Comment by alexbarghi-nv** [comment]
This was done in June.
