### ISSUE TITLE
Convert SG and MG PyG Examples to Notebooks

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3593]
We have been asked by the RAPIDS team to convert the PyG example scripts (`graph_sage_sg.py` and `graph_sage_mg.py`) to Jupyter notebooks in order to better align with user expectations.

**Comment by rlratzel** [comment]
Do we need to make sure these run and pass the CI notebook test runs, or are we going to use the "skip test" magic comment?  If they need to run as tests (which seems like a good idea), then we'll need to make sure `ci/test_notebooks.sh` or more likely `dependencies.yaml` includes the right dependencies.

**Comment by rlratzel** [comment]
offline discussion: we agreed that running these new notebooks in CI would be a good idea.

**Comment by alexbarghi-nv** [comment]
Not planned; we are not converting the examples to notebooks.
