### ISSUE TITLE
[QST]: Number of cluster varies greatly on hardware infrastructure Leiden runs on

### ISSUE THREAD

**Issue by lvxhnat** [rapidsai/cugraph#3624]
### What is your question?

I am currently running the Leiden algorithm on 2 locations:
(1) Vertex AI Workbench - Machine Specs: n1-standard-4 (4 vCPUs, 15 GB RAM) GPU NVIDIA T4 x 1
(2) Vertex AI Pipeline, which uses KubeFlow underlying to autoscale based on T4 GPUs as well

I am mainly using (1) for development and (2) for serving the graph model in a production environment. 

```python 
G: cugraph.Graph = cugraph.Graph()

G.from_cudf_edgelist(
        df[["source", "target", "weight"]],
        source="source",
        destination="target",
        edge_attr="weight",
        store_transposed=True,
)

partition_df, _ = cugraph.leiden(
        graph,
        max_iter=50_000,
        resolution=0.8,
)
```

Running this piece of code generates 10-11 partitions consistently across 10 separate runs on enviroment (1) but 43-44 partitions in (2). Similarly, calculating modularity scores with the following code 

```python
cugraph.analyzeClustering_modularity(
        graph,
        n_clusters=partition_df["partition"].nunique(),
        clustering=partition_df,
        vertex_col_name="vertex",
        cluster_col_name="partition",
    )
```

also seems to show a doubling in modularity scores for the results generated in (2) compared to (1). 

I am curious as to the reason why this is happening (does KubeFlow's autoscaling affect the results?)

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by ChuckHastings** [comment]
Can you provide cugraph versions?  Are you using the same version of cugraph on both systems?  We recently made changes to both the Leiden implementation and the spectral functions (which `analyzeClustering_modularity` calls).  So if you have different versions you might see some differences.  Understanding which versions will help in this analysis.

**Comment by ChuckHastings** [comment]
@lvxhnat - we're going to close this issue.  The Leiden implementation has been upgraded in version 23.08 of cugraph.  I expect that you will get a correct answer if you are using version 23.08 or later.

If you continue to have issues, please reopen the issue and add version details and perhaps a small graph that demonstrates your problem so that we can reproduce the issue.

**Comment by naimnv** [comment]
Hi,
We had some bug fix and hopefully it should be resolved now.
![image](https://github.com/rapidsai/cugraph/assets/110031745/774ce046-78b7-457a-9bf8-35ce7cb80972)
