### ISSUE TITLE
[QST]: Precision when creating graphs (Memory usage)

### ISSUE THREAD

**Issue by dierop** [rapidsai/cugraph#3630]
### What is your question?

I am actually creating a Graph with hundreds of millions of edges. For that, I am using the function "from_dask_cudf_edgelist" so as to distribute the data between GPUs.
But I am not sure if Cugraph uses single or double precision floating point when it creates the graph (well I am not even sure how it works internally or whether this makes sense).
So does someone knows if there is some kind of parameter or configuration for this? In the end, I am just trying to reduce the GPUs usage of memory (So other suggestions would be welcomed... I added _legacy_renum_only=True_ as I saw it would help with issues with OOM)

Thanks :)

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by VibhuJawa** [comment]
@dierop , Can you report the version of cugraph you are using. We have improved the memory footprint by a factor of 2x in this latest 23.06 release.  Can you try against that ?

**Comment by rlratzel** [comment]
@dierop, have you had a chance to try the latest nightly version of cugraph which contains the enhancements @VibhuJawa mentioned above?  If you're still seeing OOM issues, then we can debug further.

**Comment by ChuckHastings** [comment]
One other observation: you control much of the memory allocation (indirectly).  The columns that you pass for defining the vertex ids will be of a type (int32 or int64).  The vertex structures in the graph will mirror that choice.

If you create a weighted graph, the weights will either be float or double, the weight structures in the graph will mirror that choice.

The only internal memory choice that cugraph makes is to define the `edge_t` (think the offsets array in a CSR) based on how many edges you have.  If you have 32-bit vertex ids and less than 2^32-1 edges the `edge_t` will be a 32-bit integer.  If larger than 2^32 then it will be a 64-bit integer.

**Comment by rlratzel** [comment]
@dierop - we're just wondering if you had a chance to look at our responses above and if the latest version addresses your OOM issue.

I'll close this but feel free to re-open it if you still have problems.
