### ISSUE TITLE
[ENH] Move `datasets` API from experimental to stable

### ISSUE THREAD

**Issue by nv-rliu** [rapidsai/cugraph#3675]
- Promote `datasets` API by copying `cugraph.experimental.datasets` to `cugraph.datasets`
- Add deprecation warning to `cugraph.experimental.datasets`

Follow-up: update docs, notebooks, and tests to use the stable version of the API.

**Comment by rlratzel** [comment]
This was completed when https://github.com/rapidsai/cugraph/pull/3712 was merged
