### ISSUE TITLE
[ENH]: Update docstring and example for edge betweenness centrality

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#3679]
### How would you describe the priority of this documentation request

Medium

### Please provide a link or source to the relevant docs

https://github.com/rapidsai/cugraph/blob/branch-23.08/python/cugraph/cugraph/centrality/betweenness_centrality.py

### Describe the problems in the documentation

A new implementation of edge betweenness centrality following the PLC path is available. Update the docstring and examples accordingly

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
closed by #3672
