### ISSUE TITLE
[BUG] PLC Data is Not Being Cleaned Up Correctly

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3682]
In `uniform_neighbor_sample` and other algorithms, it is sometimes necessary to manually call `release()` on the future containing output from pylibcugraph.  In theory, once the reference count of the object goes to 0, it should automatically be cleaned up, but that does not appear to be happening.  This could break users relying on our dask API, especially those who use code paths we may be less familiar with.

**Comment by VibhuJawa** [comment]
Related issue from @jnke2016 : https://github.com/rapidsai/cugraph/issues/2657

**Comment by alexbarghi-nv** [comment]
Resolved by #2657
