### ISSUE TITLE
Cannot fetch "cugraph-ops" when build form source

### ISSUE THREAD

**Issue by TaoShCh** [rapidsai/cugraph#3722]
### Version

23.08

### Describe the bug.

I am trying to build cugraph from source code, when execute
```
$ ./build.sh libcugraph
...
[1/9] Performing download step (git clone) for 'cugraph-ops-populate'
Cloning into 'cugraph-ops-src'...
Permission denied (publickey).
```
error occurred:
```
Failed to clone repository: 'git@github.com:rapidsai/cugraph-ops.git'
```
and I found this repository unreachable. Is this path incorrect or do you set "cugraph-ops" private?

Thanks!

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by BradReesWork** [comment]
cugraph-ops is a closed-source repo.   You have uncovered a bug in our build process that we do need to address.

**Comment by rlratzel** [comment]
Hi @TaoShCh , our build scripts will attempt to download the sources and build cugraph-ops from source if the correct version was not found in the build environment.  Do you have cugraph-ops installed in your build environment?  If you're using `conda` you should be able to run `conda list libcugraphops` to see which version is available.  Can you confirm if `libcugraphops` is installed and what version it is along with what version of cugraph you're trying to build?

**Comment by pknowles** [comment]
I just hit this issue when following [source_build.md](https://github.com/rapidsai/cugraph/blob/branch-23.10/docs/cugraph/source/installation/source_build.md#build-and-install-the-ccuda-libcugraph-library)'s *Build and Install the C++/CUDA libcugraph Library*.

Env:
- cuda toolkit 12
- Fedora 37

```bash
git clone git@github.com:rapidsai/cugraph.git
mkdir cugraph/cpp/build
cd cugraph/cpp/build
cmake ..
```

```
...
[ 11%] Creating directories for 'cugraph-ops-populate'
[ 22%] Performing download step (git clone) for 'cugraph-ops-populate'
Cloning into 'cugraph-ops-src'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can the docs include `libcugraphops` as a dependency, have cmake attempt to find it and then point to the docs if its not found?

**Comment by rlratzel** [comment]
> Can the docs include libcugraphops as a dependency, have cmake attempt to find it and then point to the docs if its not found?

Yes I think that's a good idea.

I have the doc updates in [this PR](https://github.com/rapidsai/cugraph/pull/3893), but I'm going to put the updates to the cmake files in a separate PR for now while I look into the best way to output the message.  [Here](https://github.com/rapidsai/cugraph/issues/3892)'s the issue for that.
