### ISSUE TITLE
[BUG] Fix CONTRIBUTING.md with new steps to build python package, currently pytest fails 

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cugraph#376]
**Describe the bug**
pytest fails with the following error message

`ImportError: cannot import name 'louvain_wrapper' from 'cugraph.community' (/home/rgsl/Project/cugraph/python/cugraph/community/__init__.py)`

**To Reproduce**
Pull latest code and build it from scratch

**Screenshots**
![image](https://user-images.githubusercontent.com/42624703/61002300-dfc7aa80-a326-11e9-9f62-e65b82591b90.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)

**Solution**
Under cugraph/python 
`python setup.py clean --all; python setup.py build_ext --inplace; python setup.py install`

CONTRIBUTING.md needs to be updated with this step.

**Comment by afender** [comment]
What are the alternatives?

I would prefer to stick to the current `python setup.py` instead of this long command line.

What is creating the need for this? I see that cudf does not need it : https://github.com/rapidsai/cudf/blob/branch-0.9/CONTRIBUTING.md

**Comment by seunghwak** [comment]
This is what cudf does

$ cd $CUDF_HOME/python/cudf
$ python setup.py build_ext --inplace
$ python setup.py install

and with the update fixing https://github.com/rapidsai/cugraph/issues/146, we need

python setup.py build_ext --inplace similar to cudf & cuml. I will update the documentation about the added step (python setup.y build_ext --inplace)  taking cudf's CONTRIBUTING.md (https://github.com/rapidsai/cudf/blob/branch-0.9/CONTRIBUTING.md) as a reference.
