### ISSUE TITLE
[BUG]: `cugraph.louvain` does not handle empty graphs well

### ISSUE THREAD

**Issue by eriknw** [rapidsai/cugraph#3804]
### Version

22.10 (dev)

### Which installation method(s) does this occur on?

Source

### Describe the bug.

`cugraph.louvain` is very, very slow for empty input graphs. I would expect this condition to be detected and handled quickly.

I handled this in `cugraph-nx` here: https://github.com/rapidsai/cugraph/pull/3803/files#diff-506c93446829d8794348fa8b6773e7326ede87b095ac120c9c47fed46e56c699R31-R33

### Minimum reproducible example

```python
import sys
import networkx as nx
import cugraph

G = nx.Graph()
G.add_nodes_from(range(5))
# G = cugraph.utilities.ensure_cugraph_obj_for_nx(G)  # Optional
cugraph.louvain(G, sys.maxsize)  # Runs for a very long time
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by BradReesWork** [comment]
@eriknw I cannot reproduce

**Comment by rlratzel** [comment]
@BradReesWork I'm able to reproduce this.  I think the important arg to remember is `sys.maxsize`, did you use that?
