### ISSUE TITLE
[FEA] OpenCypher: Graph Database Object

### ISSUE THREAD

**Issue by jwyles** [rapidsai/cugraph#385]
To enable OpenCypher querying we need to have a C++ object to hold the database and a python wrapper to allow manipulation of it in python.

The object needs to encapsulate the data model of two tables and a dictionary:

To represent the data we will use a dictionary and two tables along with multiple indices on those tables. The dictionary encodes the values of items into numerical ids, the tables store only encoded numerical ids. The first table represents relationships along with node labels and properties. The second table stores relationship properties. The first table has four columns: ‘begin vertex id’, ‘end vertex id’, ‘relationship type’, and ‘relationship id’. The second table has three columns: ‘relationship id’, ‘property name’, ‘property value’. To represent labels on a node we store them as a relationship in the first table. The ‘begin vertex id’ is the node with the label, the ‘relationship type’ has a value of “HasLabel”, the ‘end vertex id’ has the value of “label name”, and the ‘relationship id’ is null. Properties of nodes are represented similarly: The ‘begin vertex id’ is the node with the property, the ‘relationship type’ has a value of “HasProperty:propertyname”, the ‘end vertex id’ has the value of “property value”, and the ‘relationship id’ is null. To represent a real relationship: ‘begin vertex id’ is the id of the first node, ‘end vertex id’ is the id of the second node, ‘relationship type’ is the type of the relationship, and ‘relationship id’ is a uniquely assigned id to describe the relationship in the second table.

CSR style indices (with redirection) should be added for both tables on each column.

**Comment by jwyles** [comment]
Please assign to me. I am working on it.

**Comment by afender** [comment]
Should this be closed by #416?

**Comment by jwyles** [comment]
This can be closed it's finished.

**Comment by afender** [comment]
#416
