### ISSUE TITLE
Several Possible Errors in Leiden Implementation

### ISSUE THREAD

**Issue by fantaosha** [rapidsai/cugraph#3850]
Thanks for your great work! However, after reading the code of Leiden, I'm afraid that there are probably several errors in [refine_impl.cuh](https://github.com/rapidsai/cugraph/blob/branch-23.10/cpp/src/community/detail/refine_impl.cuh).

1. In the computation of [well-connected vertices](https://github.com/rapidsai/cugraph/blob/98324acc83a55618f1fa41313b4bd2ec32079215/cpp/src/community/detail/refine_impl.cuh#L247),  I think the correct implementation should be 
```c
return wcut > (resolution * wdeg * (louvain_volume - wdeg)) / total_edge_weight;
```
According to the [paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-019-41695-z/MediaObjects/41598_2019_41695_MOESM1_ESM.pdf), Eq. (A4) rather than Eq. (A5) is used in the algorithms and proofs. Note that Eq. (A4) is CPM while Eq. (A5) is modularity. Therefore, if modularity is used, there should be a division of `total_edge_weight`. This also applies to the computation of [well connected communities](https://github.com/rapidsai/cugraph/blob/98324acc83a55618f1fa41313b4bd2ec32079215/cpp/src/community/detail/refine_impl.cuh#L91), which should be
```c
bool is_dst_leiden_cluster_well_connected =
      dst_leiden_cut_to_louvain > resolution * dst_leiden_volume * 
             (louvain_cluster_volume - dst_leiden_volume) / total_edge_weight;
```

2. I think the computation of [modularity gain](https://github.com/rapidsai/cugraph/blob/98324acc83a55618f1fa41313b4bd2ec32079215/cpp/src/community/detail/refine_impl.cuh#L102) should be
```c
mod_gain = aggregated_weight_to_neighboring_leiden_cluster -
                   resolution * src_weighted_deg * dst_leiden_volume / total_edge_weight;
```
since the vertex has not been merged into `dst_leiden_cluster`.

**Comment by naimnv** [comment]
Thank you. It somehow slipped my mind for a while. After quite some debugging we fixed those errors.
