### ISSUE TITLE
[DOC]: Broken documentation (list of algorithms)

### ISSUE THREAD

**Issue by tnnandi** [rapidsai/cugraph#3915]
### How would you describe the priority of this documentation request

Critical (currently preventing usage)

### Please provide a link or source to the relevant docs

https://github.com/rapidsai/cugraph/blob/branch-23.10/readme_pages/algorithms.md

### Describe the problems in the documentation

Documentation severely broken, e.g., the page supposed to contain the list of algorithms lead to nowhere: https://github.com/rapidsai/cugraph/blob/branch-23.10/readme_pages/algorithms.md

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by nv-rliu** [comment]
Hi @tnnandi 
Thanks for raising this issue. I'll take a look into this. What source directed you to use the link you mentioned above to `algorithms.md`? 

In the meantime, [here](https://docs.rapids.ai/api/cugraph/nightly/graph_support/algorithms/#supported-algorithms) is a list of supported algorithms in our official docs. Hope this helps

**Comment by tnnandi** [comment]
HI @nv-rliu I was directed to that broken link from the table of content in the readme file.

**Comment by nv-rliu** [comment]
Thank you @tnnandi for bringing the broken links to our attention! Those will be fixed shortly.
