### ISSUE TITLE
[QST]: How to accurately count the execution time of a cuGraph program？

### ISSUE THREAD

**Issue by whuLames** [rapidsai/cugraph#3921]
### What is your question?

I count the runtime of cuGraph program as the following code:
`t1 = time.time()`
`cugraph.pagerank(G)`
`t2 = time.time()`
`all_time = t2 - t1`
I'm not sure if this is the right way to do it, because I know that cuGraph is cuda programming underneath, and I'm not sure if this way of counting would be subject to cuda asynchronous
**And** when i add the following code: `torch.cuda.synchronize()` after the code `cugraph.pagerank(G)`,the runtime has increased a lot

**So, I would like to know how to accurately count the runtime of cuGraph**
Thank you !!!

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by ChuckHastings** [comment]
This should be a valid way of timing cugraph (as with all things python, there are many ways).

Since you are executing the single GPU code path (the default behavior), the cugraph calls exposed in our python API are synchronous.  When control returns to the python layer in the call stack, all of cugraph's outstanding CUDA calls have been synchronized and are complete.

**Comment by BradReesWork** [comment]
The one thin I would note is that there is some lazy execution happening and that a Graph at the C/CUDA layer is not actually created until the first time an algorithms is called.  So the first call to cugraph.pagerank(G) will be slightly slower that the next call.

**Comment by whuLames** [comment]
> The one thing I would note is that there is some lazy execution happening and that a Graph at the C/CUDA layer is not actually created until the first time an algorithms is called. So the first call to cugraph.pagerank(G) will be slightly slower that the next call.

Thank you for your answer ! But，I still have two question：
1. What does lazy execution mean at the C/CUDA level? Is it the time it takes to get the graph data from CPU to GPU? Or is it the time to do some special optimization processing on the graph? If I want to compare with other frameworks like Gunrock, should I use the time of the first execution to compare?

2.I noticed that when cuGraph reads in the graph data, there is a parameter, `store_transposed`, for PageRank, recording the transposed matrix information can speed up the execution, but this is equivalent to recording double matrix information (adjacency matrix and its transposed matrix), if other graph frameworks only record one of the matrix information for computation, rigorously speaking, is it possible to record the execution time of cuGraph with `store_transposed = False`

Thank you !!

**Comment by ChuckHastings** [comment]
I think you've misinterpreted what Brad said.

The lazy execution is in the python layer (potentially).  You've given us a snippet of python to analyze, it's possible it isn't actually affecting you.

When you create a graph in the python API, you add edges from a cuDF data frame.  This adds the edges to the python data structure, but it does not automatically trigger the creation of our graph data structures in the C/CUDA layer.  If you never do anything with the graph, it will never actually create the graph data structures in the C/CUDA layer.  The first time you execute a python function that requires the C/CUDA data structures to be  created we will pay the execution cost of creating them.

So if you create the graph object, add edges from a data frame, call pagerank, and then call pagerank a second time, you should see something like this:
* Inside the first pagerank call the python code will discover that we haven't created the C/CUDA data structures, so it will make calls into the C/CUDA library to create them.  Then we will run pagerank.
* Inside the second pagerank call the python code will discover that the C/CUDA data structures already exist, so it will just run pagerank.

The consequence of this will be that the cost of the first pagerank call will be higher than the cost of the second one, or any subsequent calls to pagerank.


Regarding question 2, we don't currently support execution of pagerank against a graph with `store_transposed=False`.  The pagerank computation on the transposed graph is much more efficient on the GPU as we can perform it without doing atomic accumulation operations.

If you were to create the graph with `store_transposed=False` and then call pagerank from python we will react using the lazy execution description above.  We will notice that `store_transposed=False` and we will transpose the storage representation of the graph in the C/CUDA structures and then call pagerank on the transposed graph.  So your first call to pagerank on a graph that you created with `store_transposed=False` will include the transposition cost.

**Comment by kingmesal** [comment]
Please reopen if this does not address the question
