### ISSUE TITLE
[BUG] Fix and review 0.9 doc 

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#393]
I suspect that the refactoring removed some features (such as `renumber`) from the nightly doc : https://docs.rapids.ai/api/cugraph/nightly/. The cause is unknown as the content is in the python file and the doc of other files is visible. 

We need to check that all functions are there and re-add the missing ones.

**Comment by seunghwak** [comment]
I guess the api.rst file is out of sync (https://github.com/rapidsai/cugraph/blob/branch-0.9/docs/source/api.rst).

renumber(), from_cudf_edgelist() should be added.

nvLouvain and nvJaccard are renamed and weighted version of Jaccard is missing.

overlap coefficient and  triangle_count are missing.

**Comment by seunghwak** [comment]
Fixing this issue should be quick and I will do this today, but our documentation has multiple issues.

Indentations & line changes affect formatting in automatic document generation, but our python docstrings are not written properly considering this. This leads to odd formatting in multiple places.

And the first sentence in the docstring should be a "short" description of a function, but it is lengthy in multiple places, and this leads to horizontal scrolling in the generated tables.

@afender @BradReesWork  Should I fix these all together (this will require making changes to nearly every python file) or should we work on this in the code refactoring phase?
