### ISSUE TITLE
Update python/dask cugraph implementation to use new PLC features from #3947

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3948]
When #3947 is closed, the cugraph python code for MG graphs needs to be updated.
There are three updates here, and I can create separate issues if that's better.

### Remove code that computes `num_edges` from a `dask_cudf` edgelist

Once #3947 is closed, the `num_edges` arg to the PLC MGGraph is optional and no longer needs to be computed. This will allow the python code to bypass the need to persist/compute the distributed edgelist.

### Remove code that combines (and modifies) the copied input `dask_cudf` edgelist

Once #3947 is closed, the code that combines the src/dst columns from each partition can be removed.  This should greatly simplify the MG graph creation code.

### Re-enable MG tests in CI

Once the above changes are made, MG tests in CI should pass reliably.

**Comment by BradReesWork** [comment]
closed by PR #3941
