### ISSUE TITLE
[BUG]: `plc.hits` does not raise after not converging after reaching max iterations

### ISSUE THREAD

**Issue by eriknw** [rapidsai/cugraph#3972]
### Version

23.12 dev

### Describe the bug.

Unlike other power iteration methods, HITS does not raise upon reaching the maximum number of iterations without converging.

See here that it does not check the convergence criteria and raise if necessary:
https://github.com/rapidsai/cugraph/blob/f4bcdc2667a15e2e5031987550322a9d29d8f713/cpp/src/link_analysis/hits_impl.cuh#L176-L192

For an example of expected behavior, here's Katz centrality:
https://github.com/rapidsai/cugraph/blob/f4bcdc2667a15e2e5031987550322a9d29d8f713/cpp/src/centrality/katz_centrality_impl.cuh#L163-L168

### Minimum reproducible example

```shell
Call with `max_iterations=1`.
```

### Other/Misc.

Not having this behavior makes it difficult for `nx-cugraph` to match NetworkX.

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by ChuckHastings** [comment]
Good catch.  Will try to fix along with #3971.
