### ISSUE TITLE
[FEA] [MG] RMM support

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#401]
Need to check the status of RMM support for SPMG and test dask-cugraph with different configurations.

Some extra work / debugging may be needed.

There is some related work in cuML where it's supported to the extent that the individual cudfs backing the dask cudf inputs use RMM. The cuML handle API contains a device allocator API and it has an implementation for RMM.
Correy had some ideas about using [void chunk_to_device](https://github.com/rapidsai/cuml/blob/branch-0.8/cpp/src/ml_mg_utils.h#L40) to take a cuml handle and then use "handl.getImpl().getDeviceAllocator()->allocate(*ptr, size, steam);

**Comment by seunghwak** [comment]
I guess this one is dependent on https://github.com/rapidsai/rmm/pull/106.

**Comment by afender** [comment]
Should we mark this issue as blocked then?

**Comment by seunghwak** [comment]
I think so :-)

**Comment by afender** [comment]
RMM PR will not be merged for 0.9 because they are not ready to move CFFI --> Cython for 0.9

**Comment by BradReesWork** [comment]
#rapidis/rmm/106 was merged in 0.11.   Since we use RMM locally per GPU - similar to cuML, this is no longer an issue with OPG
