### ISSUE TITLE
[FEA] core.py should be in rapidsai/raft

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#402]
This file has been borrowed from dask-cuML. It is quite advanced and subject to frequent updates. Hence, we should share a single file instead of duplicating maintenance. 

https://github.com/rapidsai/raft has been created for this purpose. `core.py` should go in raft repo and both dask-cuml and dask-cugraph should get it from there.

**Comment by afender** [comment]
probably for 0.11

**Comment by BradReesWork** [comment]
marking as BLOCKED until cuML is ready to start RAFT
