### ISSUE TITLE
[FEA] Support int weights in SSSP

### ISSUE THREAD

**Issue by pgera** [rapidsai/cugraph#408]
Currently, BFS uses int32 for distances whereas SSSP uses floats or doubles for weights and distances. If the graph is unweighted, SSSP creates unit float weights (1.0f). In such cases, SSSP should fall back to BFS since BFS would be more efficient (more so for undirected graphs due to bottom up optimisations). Further, floats have limited precision for this use case which would be better served by int types. 

In order to do that, SSSP needs to support int weights at the API level first, so that it can seamlessly call BFS. It would be straightforward to add support for int types, but we need to think through some over/underflow issues before adding it. Since SSSP relies on edge relaxations, we want to avoid int over or under flows. One option is to add a conservative check at the beginning that checks that the weights in the graph are in the range (int_min/(|V|-1), int_max/(|V|-1) so that even in the worst case with a path of length |V|-1, we would not have over/under flow issues.

**Comment by Iroy30** [comment]
addressed in PR #481. Instead of supporting int weights in sssp, we internally call bfs if the graph is unweighted for sssp. This roughly gives an improvement of 2.25x for a 3GB input csv
