### ISSUE TITLE
[BUG] [MG] Improve the wait mechanism after dask csv reader

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#409]
It seems that, by default, the reader is lazy and exits before finishing reading. This resulted in longer PageRank runtime since we waited for dask tasks to complete before calling CUDA functions. To bypass that problem and have accurate timings we added a way to wait for the csv reader before entering  cugraph.dask.pagerank. The current solution does :
```
    ddf = dask_cudf.read_csv(...)
    y = ddf.to_delayed()
    x = client.compute(y)
    wait(x)
    pr = dcg.pagerank(x, ...)
```

I wish there was a parameter in dask / dask_cudf or a sync function. So that we would just call: 
```
    ddf = dask_cudf.read_csv(...)
    pr = dcg.pagerank(ddf, ...)
```

**Comment by Iroy30** [comment]
This is addressed in #420. A conditional check is added in pagerank.py and if the read_csv is already computed, it doesn't recompute it, thus separating read_csv time from actual pagerank algorithm time. 
It can work both as:  
    ddf = dask_cudf.read_csv(...)
    y = ddf.to_delayed()
    x = client.compute(y)
    wait(x)
    pr = dcg.pagerank(x, ...)
or:
    ddf = dask_cudf.read_csv(...)
    pr = dcg.pagerank(ddf, ...)
