### ISSUE TITLE
[BUG]: Not able to install Cugraph in Conda

### ISSUE THREAD

**Issue by anuj1501** [rapidsai/cugraph#4151]
### Version

22.02

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

Hi community,

I am struggling to install cugraph 22.04 on my conda environment. I am able to install CuDf 22.04 without any issue. Upon installing Cugraph, conda throws multiple dependency conflicts. So what can I do here?

Possible Solutions:

1. Resolve dependencies one by one (quite cumbersome)
2. Can you help me with the correct versions compatible with each other.

Systems Specs:

- Python: 3.9.2
- CUDA Driver: 11.4
- Ubuntu 20

![image](https://github.com/rapidsai/cugraph/assets/49569619/6587101e-032e-49b9-ae1e-c80c277208ab)

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by BradReesWork** [comment]
@anuj1501 can you try installing release 23.12?    Release 22.04 is several years old 

https://docs.rapids.ai/install?_gl=1*6t8cuf*_ga*MTg4OTAyNTQzOS4xNjk2ODc1NzUw*_ga_RKXFW6CM42*MTcwNzc3Mjk1Ni44LjAuMTcwNzc3Mjk1Ni42MC4wLjA.

**Comment by rlratzel** [comment]
Hi @anuj1501 , sorry for the delay in responding.

The environment you've set up seems like it should be supported, but I'm wondering about the python you're using.  These lines in particular seem troubling:
```
Package python_abi conflicts for:
python=3.9.4 -> python_abi=3.9[build=*_cp39]
```
Did you also have that when you tried installing 23.12?  Can you include the output of the conda command that's failing for 23.12 too?
