### ISSUE TITLE
cuGraph: CUDA 12 testing

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cugraph#4208]
Currently CUDA 12 testing on some cuGraph packages is skipped

https://github.com/rapidsai/cugraph/blob/0a2a2454c349f5375938ddd2fddff0e9c417b52e/ci/test_wheel_cugraph-pyg.sh#L48

https://github.com/rapidsai/cugraph/blob/cc4199d86da520b6e6d92bd97e0110fb1c83b2a8/.github/workflows/test.yaml#L79

Would be interested in understanding why that is the case and figuring out how we can enable testing here

**Comment by alexbarghi-nv** [comment]
We can add CUDA 12 testing, just have to manually specify the index URL.  Hopefully we will move towards an environment where that isn't required after we finish the `edge_index` changes which should remove the need for those additional packages in CI.

**Comment by jakirkham** [comment]
Thanks Alex! 🙏 

Where is the `edge_index` work being tracked?

**Comment by alexbarghi-nv** [comment]
https://github.com/rapidsai/cugraph/issues/4051

**Comment by alexbarghi-nv** [comment]
These tests are only skipped on arm64 now due to pytorch issues.
