### ISSUE TITLE
Update pre-commit for cugraph python pacakges to match nx-cugraph

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#4234]
nx-cugraph has several more linters and formatters than the other python projects in cugraph.  
It would be nice to update `pre-commit` to run the same linters and formatters (with the same or newer versions) as nx-cugraph.

@eriknw - Do we then remove the `lint.yaml` and the `make lint` target from nx-cugraph to ensure everything stays current together?

**Comment by eriknw** [comment]
> @eriknw - Do we then remove the lint.yaml and the make lint target from nx-cugraph to ensure everything stays current together?

No need to answer this question right now. Let's update pre-commit first. We may not want everything that nx-cugraph has in lint.yaml.
