### ISSUE TITLE
[FEA] cuGraph graph to Gunrock

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#427]
#328 should be addressed first

Cugraph and Gunrock use the same internal representation (coo/csr). The first step is to identify if/how we can add a feature that natively wraps cugraph data in a gunrock graph. Ideally, that should not involve duplicating anything. We can consider contributing one or two functions in gunrock if needed. 
That option would allow leveraging all cuGraph features on the graph while transparently running gunrock based analytics without any extra cost.

Another option is to convert/copy the edge list stored in cugraph using gunrock’s `FromCoo` in order to create a gunrock graph. That would duplicate everything (ie. reduce the largest size we can run) be redundant with the existing structure and make gunrock-based analytics slow at the python algorithm call level. 

gunrock structure: https://github.com/gunrock/gunrock/tree/master/gunrock/graph

**Comment by ogreen** [comment]
It looks like Gunrock's COO2CSR process is on the GPU, so the performance cost of using it might not be very high in comparison with the cost of the analytic itself (at least not for subgraph matching). But I agree with your point on increasing the memory footprint.

**Comment by BradReesWork** [comment]
Marking as closed.  We have on-going interacts with GunRock and have worked out a data exchange process where they access data directly on the GPU
