### ISSUE TITLE
[QST]: How to Identify Subgraphs Based on Non-Connectivity in cuGraph

### ISSUE THREAD

**Issue by Ibrahim25-ai** [rapidsai/cugraph#4354]
### How to Identify Subgraphs Based on Non-Connectivity in cuGraph

Hello,

I'm working with cuGraph and trying to segment a graph into subgraphs based on non-connectivity of vertices. i found this one `cugraph::connected_components` but it requires a legacy CSR format.

Here is how I've set up and created my graph:

```cpp
#include <cugraph/graph.hpp>
#include <rmm/device_uvector.hpp>
#include <raft/handle.hpp>

raft::handle_t handle;
cudaStream_t stream = handle.get_stream();

rmm::device_uvector<int64_t> d_edge_srcs(srcs.size(), stream);
rmm::device_uvector<int64_t> d_edge_dsts(dsts.size(), stream);
raft::update_device(d_edge_srcs.data(), srcs.data(), srcs.size(), handle.get_stream());
raft::update_device(d_edge_dsts.data(), dsts.data(), dsts.size(), handle.get_stream());

std::optional<rmm::device_uvector<double>> d_edge_weights{std::nullopt};

cugraph::graph_properties_t properties{.is_symmetric = false, .is_multigraph = true};
bool renumber = true;
cugraph::graph_t<int64_t, int64_t, false, false> graph(handle);

std::tie(graph, std::ignore, std::ignore, std::ignore, renumber_map) = cugraph::create_graph_from_edgelist<int64_t, int64_t, double>(
    handle,
    std::nullopt,
    std::move(d_edge_srcs),
    std::move(d_edge_dsts),
    std::move(d_edge_weights),
    std::nullopt,
    std::nullopt,
    properties,
    renumber,
    true
);
    
     how do I use the connected_components function to identify and extract these non-connected subgraphs?

Any guidance or examples would be greatly appreciated!

Thank you!

**Comment by Ibrahim25-ai** [comment]
thank you!
i just have one more question,Can i transform my graph to a lagacy::graphCSR ?

**Comment by ChuckHastings** [comment]
You can currently construct a `legacy::GraphCSRView`, which is what's used by the legacy algorithms.  Here's an example of some of our code that does this: https://github.com/rapidsai/cugraph/blob/d7d479ba26ee45af96ff82c70d110a353753111a/cpp/src/c_api/legacy_spectral.cpp#L119

I would consider this an unsupported feature.  The `cugraph::graph_t` object supports this solely for the purpose of supporting our legacy algorithms.  Once we have ported all of our legacy algorithms to use the new graph primitives (there are only a few stragglers remaining), support for this feature will likely be phased out.  It only works on single GPU algorithms, and requires us to use a simple CSR structure internally to represent the graph.  We want to be able to support other implementations (especially to support dynamic graphs), so in the long run we will probably drop support for this feature.

Is there a particular motivation for wanting access directly to the internal CSR representation?

**Comment by Ibrahim25-ai** [comment]
No , just because when i try to impliment this cugraph::connected_components it demands a csr input ,
i have a question after building the graph is there any method that gives you all the predecessors of each vertex .

**Comment by ChuckHastings** [comment]
Closing this.  Thanks for your question!

Please post a new issue if you have a new question, or if you have follow-ups to this question either create a new issue or reopen this one with your follow-up question.
