### ISSUE TITLE
Update C uniform_neighbor_sampling to skip invalid starting vertices

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#4378]
Update C API (and C++ API/implementation) to support an option (defaulting to True) that will skip invalid starting vertices.

**Comment by alexbarghi-nv** [comment]
Can you hold off on implementing this?  It may not be needed.

**Comment by ChuckHastings** [comment]
Kicking out to 24.08.  Let me know if you think we can drop this @alexbarghi-nv
