### ISSUE TITLE
[QST]: BFS/SSSP Implementation

### ISSUE THREAD

**Issue by omdano** [rapidsai/cugraph#4445]
### What is your question?

Can you tell me what implementation of BFS and SSSP are being utilized in CuGraph's cugraph.bfs and cugraph.sssp?
I doubt its the standard BFS/SSSP implementation, so can you refer me to the relevant sources of the algorithms?

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by alexbarghi-nv** [comment]
These algorithms are implemented using our primitives.  You can view our C++ source code, which is part of this repository.
