### ISSUE TITLE
[QST]: cuGraph `shortest_path` vs. NetworkX shortes_path difference?

### ISSUE THREAD

**Issue by pacificoceanmist** [rapidsai/cugraph#4446]
### What is your question?

I looked at the [documentation ](https://docs.rapids.ai/api/cugraph/nightly/api_docs/api/cugraph/cugraph.shortest_path/#cugraph.shortest_path) for cuGraph `shorts_path()' and noticed that it's different from NetworkX `[shortest_path()](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path.html#networkx.algorithms.shortest_paths.generic.shortest_path)`.  When I specify the target parameter for `short_path(),` it gives me `TypeError: shortest_path() got an unexpected keyword argument target`.

What are their differences? What would be equivalent to NetworkX shortest_path for the cuGraph version?

My code below:
```
import os
import cudf
import cugraph
import dask_cudf
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
import cugraph.dask.comms.comms as Comms
import cugraph.dask as dask_cugraph

# Define the columns to read
columns_to_read = ['subject', 'object', 'predicate']

# Read the TSV file using Dask cuDF with specific columns
df = dask_cudf.read_csv('graph.tsv', sep='\t', usecols=columns_to_read)

# Renaming columns to match cuGraph requirements
df = df.rename(columns={'subject': 'src', 'object': 'dst'})

# Add a default weight column
df['weight'] = 1.0

# Create graph from input data
G = cugraph.Graph(directed=True)
G.from_dask_cudf_edgelist(df, source='src', destination='dst', edge_attr='weight')

# List of nodes for BFS
node_lst = ['PU:7045767', 'GO:0007271', 'G:0035249', 'G:0005947', 'G:0004129', 
            'CH:26519', 'UM:C0132173', 'G:0018393', 'G:0006979', 'H:0025464', 'G:0007613', 
            'CH:64645', 'P:000010173', 'G:0014055', 'G:0061535', 'G:0150076', 'MO:0001152', 
            'H:0002185', 'MO:0004975', 'E:0005816', 'C:60425']

# Initialize an empty list to collect BFS results
bfs_results = []

# Perform BFS for each node in the list and collect results
for start_node in node_lst:
    try:
        bfs_result = dask_cugraph.bfs(G, start=start_node)
        bfs_results.append(bfs_result)
    except ValueError as e:
        print(f"Skipping invalid node {start_node}: {e}")

# Concatenate all BFS results into a single DataFrame
if bfs_results:
    final_bfs_df = dask_cudf.concat(bfs_results)
    # Drop duplicates to ensure unique rows (optional based on your use case)
    final_bfs_df = final_bfs_df.drop_duplicates()
else:
    final_bfs_df = None
    print("No valid nodes found for BFS traversal.")

# Find the shortest paths using BFS results
shortest_paths = []

if final_bfs_df is not None:
    for i in range(len(node_lst)):
        for j in range(i + 1, len(node_lst)):
            src = node_lst[i]
            dst = node_lst[j]
            try:
                # Find the shortest path
                path_df = cugraph.shortest_path(G, source=src, target=dst)
                shortest_paths.append(path_df)
            except ValueError as e:
                print(f"Could not find path from {src} to {dst}: {e}")

# Concatenate all shortest path results into a single DataFrame
if shortest_paths:
    final_shortest_paths_df = dask_cudf.concat(shortest_paths)
    final_shortest_paths_df = final_shortest_paths_df.drop_duplicates()
else:
    final_shortest_paths_df = None
    print("No shortest paths found.")

# Display the shortest path result
if final_shortest_paths_df is not None:
    print(final_shortest_paths_df.compute())
else:
    print("No shortest paths to display.")


# Shutdown comms
Comms.shutdown()
client.close()
```
Thank you. 

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by alexbarghi-nv** [comment]
@pacificoceanmist I think what you want is https://docs.rapids.ai/api/cugraph/nightly/api_docs/api/cugraph/cugraph.shortest_path_length/

**Comment by alexbarghi-nv** [comment]
You may also want to consider using `nx-cuGraph` which is a plugin for NetworkX that enables cuGraph acceleration with no code change.  https://github.com/rapidsai/cugraph/blob/branch-24.06/python/nx-cugraph/README.md

**Comment by pacificoceanmist** [comment]
> @pacificoceanmist I think what you want is https://docs.rapids.ai/api/cugraph/nightly/api_docs/api/cugraph/cugraph.shortest_path_length/

Thanks for the suggestion but SSSP, or Shortest path, does not support unweighted graph; I used BFS instead.

**Comment by ChuckHastings** [comment]
@pacificoceanmist - yes, our SSSP does not support an unweighted graph, BFS should be used instead.

I'm going to close this issue as it appears you were able to resolve it.  If you have any further issues please create a new issue.
