### ISSUE TITLE
[FEA]: clarify cugraph-equivariant's src vs dst semantics in weight-sharing bidirectionaly message passing

### ISSUE THREAD

**Issue by DejunL** [rapidsai/cugraph#4459]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

High

### Please provide a clear description of problem this feature solves

In cugraph-equivariant's `FullyConnectedTensorProductConv` layer (FCTPConv), the 1st layer of the underlying MLP is decomposed into edge embedding, src and dst scalar weight blocks in that order (see code [here](https://github.com/rapidsai/cugraph/blob/ee4cbb7ffea4394fef4367cc02782657a0e94c16/python/cugraph-equivariant/cugraph_equivariant/nn/tensor_product_conv.py#L232-L236)). In one of our applications, DiffDock-PP, the same FCTPConv layer is called bidirectionally, sharing the same set of MLP weights (see the original code [here](https://github.com/ketatam/DiffDock-PP/blob/25a28900736c0730821e45265ee8e409751c358a/src/model/diffusion.py#L327) for one direction and [here](https://github.com/ketatam/DiffDock-PP/blob/25a28900736c0730821e45265ee8e409751c358a/src/model/diffusion.py#L348) for another.) Note that these links point to the code that hasn't been replaced with FCTPConv but imagine that situation once they are using FCTPConv: one of the two directions would have to violate the src vs dst assignment if the two directions keep sharing the same set of weights. 

The crux here is cugraph-equivariant's FCTPConv layer is inherently single-directional even though the user could shoehorn it into a bidirectionaly usage case by paying attentions to how the underlying MLP computation is carried out, e.g.:
```python
# first direction
a2b_edge_emb = torch.hstack([edge_emb, a_scalars, b_scalars])
cross_conv(a_node_attrs, edge_sh, a2b_edge_emb, (a2b_edge_index, (size_a, size_b)))

# second direction sharing the same weight as the first direction
b2a_edge_index = a2b_edge_index.flip(dims=(0,))
cross_conv(b_node_attrs, edge_sh, a2b_edg_emb, (b2a_edge_index, (size_b, size_a)))
```
where the semantic violation can be seen `a2b_edg_emb` being used in the case of a `b->a` convolution

### Describe your ideal solution

Not sure if there is any

### Describe any alternatives you have considered

A not-so-ideal solution would be to clarify in the documentation how the underlying MLP is being decomposed into the blocks and how `src_scalars` and `dst_scalars` are being indexed and broadcasted using the` edge_index[0]` and `edge_index[1]` respectively to at least warn the user of potential semantic violation

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by DejunL** [comment]
@tingyu66

**Comment by tingyu66** [comment]
We have two modes in the layer:
1). users pass in concatenated `edge_emb` that is going to be consumed by MLP
or 2). users pass in a_scalars, b_scalars, edge_scalars separately to allow for smaller GEMMs

For the bidirectional use case mentioned above, mode 1 should work just fine since the same `edge_emb` can be used in the calls for both directions (despite being not elegant).
Mode 2 is problematic because of the way we split the weights: 
```
                w_edge, w_src, w_dst = torch.split(
                    self.mlp[0].weight,
                    (edge_emb_size, src_scalars_size, dst_scalars_size),
                    dim=-1,
                )
```
src nodes in one direction become dst nodes in the other one, causing the inconsistency in the MLP.
The root cause is really that we don't have rich node type information from the graph structure to allow proper weight sharing. Instead of denoting with `w_src`, we could have used `w_protein` or `w_ligand` given a heterogeneous graph (ex. HeteroData in PyG). That simplifies the bookkeeping work we need otherwise.

**Comment by DejunL** [comment]
>  1). users pass in concatenated edge_emb that is going to be consumed by MLP

> For the bidirectional use case mentioned above, mode 1 should work just fine since the same edge_emb can be used in the calls for both directions (despite being not elegant).

Yes, the computation would work but the user would have to make a choice by looking at the cugraph-equivariant source code to figure out the correct usage as I show in the example. For this matter, is there anything we can do to the documentation of the forward function to clarify the handling of `edge_emb` w.r.t. src vs dst node type handling in [these lines](https://github.com/rapidsai/cugraph/blob/31f01ca6fd770b0c1a14b4608c52a4908dc46f17/python/cugraph-equivariant/cugraph_equivariant/nn/tensor_product_conv.py#L169-L170)?

I also agree that the lack of node type annotation is the root cause. Perhaps another layer of complexity is how the MLP[0].weight block is sliced and how the later GEMM results are broadcasted use `edge_index[0]` vs `edge_index[1]` is not totally obvious to the user so they have to rely on the name of the "src_" vs "dst_scalars" to figure out what arguments to give there and hence could hit the pitfall in the bidirectional case

**Comment by tingyu66** [comment]
Just to clarify, is the ask here to better document the caveat when using mode 2, right?

With mode 1, edge_emb could be constructed in arbitrary ways, and I don't see any issue with the following snippet:
```python
# first direction
edge_emb = ...
cross_conv(a_node_attrs, edge_sh, edge_emb, (a2b_edge_index, (size_a, size_b)))

# second direction sharing the same weight as the first direction
b2a_edge_index = a2b_edge_index.flip(dims=(0,))
cross_conv(b_node_attrs, edge_sh, edge_emb, (b2a_edge_index, (size_b, size_a)))
```
