### ISSUE TITLE
[BUG]: Nx-cuGraph caching not working with documentation example

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cugraph#4466]
### Version

24.06

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

When I ran the documentation example multiple times, I expected performance to be significantly better the second time with caching enabled. Instead, performance was the same and the CPU to GPU conversion was happening every time.

### Minimum reproducible example

```python
%env NETWORKX_BACKEND_PRIORITY=cugraph
%env CACHE_CONVERTED_GRAPH=True

import pandas as pd
import networkx as nx

url = "https://data.rapids.ai/cugraph/datasets/cit-Patents.csv"
df = pd.read_csv(url, sep=" ", names=["src", "dst"], dtype="int32")

G = nx.from_pandas_edgelist(df, source="src", target="dst")
env: NETWORKX_BACKEND_PRIORITY=cugraph
env: CACHE_CONVERTED_GRAPH=True


%time result = nx.betweenness_centrality(G, k=10)
CPU times: user 18.1 s, sys: 1.69 s, total: 19.8 s
Wall time: 20.7 s

%time result = nx.betweenness_centrality(G, k=10)
CPU times: user 19.6 s, sys: 859 ms, total: 20.4 s
Wall time: 20.6 s
```

```python
%%snakeviz

result = nx.betweenness_centrality(G, k=10)
```
<img width="835" alt="Screenshot 2024-06-05 at 5 36 54 PM" src="https://github.com/rapidsai/cugraph/assets/8457388/8289ac6e-6a14-4fb1-bf91-79e54c4a4c4c">

### Environment details

```shell
!conda list | grep "cugraph\|networkx"

cugraph                   24.06.00a94     cuda12_py310_240604_g1667f7a43_94    rapidsai-nightly
libcugraph                24.06.00a94     cuda12_240604_g1667f7a43_94    rapidsai-nightly
libcugraph_etl            24.06.00a94     cuda12_240604_g1667f7a43_94    rapidsai-nightly
libcugraphops             24.06.00a24     cuda12_240603_gac69d0a6_24    rapidsai-nightly
networkx                  3.3                pyhd8ed1ab_1    conda-forge
nx-cugraph                24.06.00a94            py310_94    rapidsai-nightly
pylibcugraph              24.06.00a94     cuda12_py310_240604_g1667f7a43_94    rapidsai-nightly
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by beckernick** [comment]
It looks like [our docs](https://docs.rapids.ai/api/cugraph/nightly/nx_cugraph/nx_cugraph/) are wrong. We should be using `NETWORKX_CACHE_CONVERTED_GRAPHS` not `CACHE_CONVERTED_GRAPH` to configure caching behavior.

<img width="795" alt="Screenshot 2024-06-05 at 6 22 25 PM" src="https://github.com/rapidsai/cugraph/assets/8457388/05bfc583-b931-43c5-ad4a-eee6c1bf3572">

**Comment by rlratzel** [comment]
Thanks @beckernick for finding this.  I've submitted [this PR](https://github.com/rapidsai/cugraph/pull/4478) to fix those docs.
