### ISSUE TITLE
[BUG]: variable cannot appear in its own initializer

### ISSUE THREAD

**Issue by YvanMokwinski** [rapidsai/cugraph#4734]
### Version

24.10

### Which installation method(s) does this occur on?

Source

### Describe the bug.

This line of code is a non-sense:

https://github.com/rapidsai/cugraph/blob/branch-24.12/cpp/src/c_api/core_number.cpp#L79

### Relevant log output

core_number.cpp:79:75: error: variable 'degree_type' declared with deduced type 'auto' cannot appear in its own initializer
   79 |       auto degree_type = reinterpret_cast<cugraph::k_core_degree_type_t>(degree_type)

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by ChuckHastings** [comment]
Thanks for this bug report.  Will fix.
