### ISSUE TITLE
[QST]: is_isomorphic

### ISSUE THREAD

**Issue by roitberg** [rapidsai/cugraph#4768]
### What is your question?

Has is_isomorphic from NetworkX been ported to the cuda frontend ?

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by rlratzel** [comment]
> Has is_isomorphic from NetworkX been ported to the cuda frontend ?

Hi @roitberg , cuGraph does not have an implementation for `is_isomorphic` yet.

When you say "cuda frontend", do you mean in the cugraph Python package, or the cuGraph backend for NetworkX ([nx-cugraph](https://github.com/rapidsai/nx-cugraph))?  Knowing this will help us prioritize which library to add it to first.  Also, any details about your application and/or use case can help us ensure we understand the requirements.

**Comment by rlratzel** [comment]
Hi again @roitberg .  I'll be closing this issue now, but please reopen it if you have any additional questions about `is_isomorphic` or information to clarify the original question.
