### ISSUE TITLE
[QST]: BFS timer for execution

### ISSUE THREAD

**Issue by kaanolgu** [rapidsai/cugraph#4787]
### What is your question?

I have this example from the repository : 
```
def cugraph_call(M):

    gdf = cudf.DataFrame()
    gdf['src'] = M.row
    gdf['dst'] = M.col
    
    print('\tcuGraph Solving... ')
    
    G = cugraph.Graph(directed=True)
    G.from_cudf_edgelist(gdf, source='src', destination='dst', renumber=False)
    t1 = time.time()
    df = cugraph.bfs(G, 1)
    t2 = (time.time() - t1) * 1000  # Convert to milliseconds
    
    return t2
```
I would like to capture the execution time of while loop here only, not for the whole init stage : 

https://github.com/rapidsai/cugraph/blob/f4c519ec7b8ae430fe0832e5ad68c1b7f07c1943/cpp/src/traversal/bfs_impl.cuh#L201

Is there a way to achieve this ? 

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open issues](https://github.com/rapidsai/cugraph/issues) and have found no duplicates for this question

**Comment by ChuckHastings** [comment]
We don't provide any timing information for the internal implementations of the algorithms at this point.  This hasn't been a feature that's been requested, so we don't have any current plans to add that mechanism.

If you need timing detail for BFS (or any algorithm) at that level you could update the C++ source code and build from source.  But that's probably the only way you could accomplish that exactly.

I haven't tried this, but glancing through the code... you might get a good approximation of the overhead costs by running your traversal with a depth limit of 0.  There doesn't appear to be any fast failure if the depth limit is 0.  That would take you through all of the before and after overhead.  Unfortunately, as the loop is written it will also take you through the first iteration of the while loop.  So it won't be exactly what you're looking for... but it would be very close.

**Comment by kaanolgu** [comment]
Thank you for the quick reply, OK I will modify the C++ source code and build from the source

**Comment by kaanolgu** [comment]
Hi @ChuckHastings , I tried to construct your suggestion from the Python code but it seems like not working as expected
```
    for _ in range(18):
        # Measure time for cugraph.bfs(G, source_node, 0)
        start_0 = time.monotonic()
        df_0 = cugraph.bfs(G, source_node, 0)
        end_0 = time.monotonic()
        time_0 = (end_0 - start_0) * 1000  # Convert to milliseconds

        # Measure time for cugraph.bfs(G, source_node)
        start_1 = time.monotonic()
        bfs_result = cugraph.bfs(G, source_node)  # Reuse bfs_result
        end_1 = time.monotonic()
        time_1 = (end_1 - start_1) * 1000  # Convert to milliseconds

        # Calculate the time difference
        t2 = time_1 - time_0
        print(f"{_} iteration, t2 is {t2}")
```

The execution times are varying a lot and sometimes it is minus :
```
0 iteration, t2 is 14.865966979414225
1 iteration, t2 is 1.0754046961665154
2 iteration, t2 is 12.134073302149773
3 iteration, t2 is 11.349649634212255
4 iteration, t2 is -6.9432128220796585
5 iteration, t2 is 16.537054907530546
6 iteration, t2 is -8.001524023711681
7 iteration, t2 is -26.730888057500124
8 iteration, t2 is -18.34333874285221
9 iteration, t2 is -17.298993188887835
10 iteration, t2 is 10.098983533680439
11 iteration, t2 is -3.134199883788824
12 iteration, t2 is 26.668859645724297
13 iteration, t2 is 0.48283766955137253
14 iteration, t2 is 12.394406832754612
15 iteration, t2 is 7.249013055115938
16 iteration, t2 is 17.00076600536704
17 iteration, t2 is 8.981176652014256
```

**Comment by kaanolgu** [comment]
OK, adding the timer to c++ source code worked and provides reliable results after first iteration (warmup) Thanks!
