### ISSUE TITLE
[BUG]: 24.12 nightly wheel tests failing with SSL certificate issues

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/cugraph#4818]
### Version

24.12

### Describe the bug.

Many nightly wheel tests are failing on 24.12. I see dozens of failures, in two broad categories.

Stuff like this:

> FAILED python/cugraph/cugraph/tests/traversal/test_sssp.py::test_sssp_data_type_conversion[1-graph_file0] - KeyError: "results for {'algo': 'single_source_dijkstra_path_length', 'graph_dataset': 'karate', 'graph_directed': 'True', 'source': '1', 'test': 'data_type_conversion', 'resultset_name': 'traversal'} not found"

And stuff like this:

> FAILED python/cugraph/cugraph/tests/utils/test_dataset.py::test_download[dataset0] - urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

([build link](https://github.com/rapidsai/cugraph/actions/runs/12235138888/job/34144089538))

These failures only occur on the CUDA 11.8.0, Python 3.10 wheels test jobs.

### Minimum reproducible example

```shell
See CI links above.
```

### Relevant log output

```shell
See CI links above.
```

### Environment details

```shell
See CI links above.
```

### Other/Misc.

Because they looked network-related, I did try manually re-running these failed jobs... they failed in exactly the same way.

I know that `cugraph` tests do some downloading of externally-hosted datasets... maybe one of those sites hosting that data had an outage or changed some configuration?

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
I'm wondering if the solution [here](https://github.com/rapidsai/graph_dl/pull/656) is relevant for these SSL errors.

**Comment by nv-rliu** [comment]
Can this be closed now?

**Comment by jameslamb** [comment]
I think so, yes.

The latest 24.12 test run did fail: https://github.com/rapidsai/cugraph/actions/runs/12349459995

As did the latest 25.02 test run: https://github.com/rapidsai/cugraph/actions/runs/12372518014

Neither looks like this exact issue though. Let's close it. You may want to watch https://github.com/rapidsai/ci-imgs/pull/218. Once it goes out, it might be possible to rever the changes from #4825 or some subset of them.
