### ISSUE TITLE
[BUG]: cugraph relies on `cudf._lib.transform`, which no longer exists

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/cugraph#4823]
### Version

25.02

### Describe the bug.

On #4805, noticed `cugraph` pytests failing like this:

```text
AttributeError: module 'cudf._lib' has no attribute 'transform'
```

([build link](https://github.com/rapidsai/cugraph/actions/runs/12242819477/job/34200391264?pr=4805))

### Minimum reproducible example

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Environment details

```shell
N/A
```

### Other/Misc.

This is probably a result of https://github.com/rapidsai/cudf/pull/17505

Besides just fixing this, think it'd be worth talking with @mroeschke about the plans for other changes to `cudf._lib` in this release cycle, so `cugraph` can get out ahead of them.

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mroeschke** [comment]
This should be closed by https://github.com/rapidsai/cugraph/pull/4758

(Throughout cugraph, this is the only usage of `cudf._lib` that I found)

**Comment by jameslamb** [comment]
oooooh I hadn't made the connection between this and that PR!

Thanks for re-targeting that to 25.02.
