### ISSUE TITLE
[FEA] Support graphs with more than 2.1B edges

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#484]
The 32-bit integer type limits the number of edges we can store.

To do:
- [ ] The number of vertices should be stored in a 64-bit integer everywhere 
- [ ] Offsets in the adjacency list should be 64-bits integers
- [ ] All the code using the data above needs to be updated (from API, to structures, to kernels, to third party library calls). 
- [ ] Documentation should be upgraded
- [ ] Tests should be upgraded.

**Comment by BradReesWork** [comment]
This is being closed.  The 2D partitioned MNMG code being developed in 0.16 and beyond all exceed the 2B limit
