### ISSUE TITLE
[BUG] Missing arch flag in CMakelists for T4

### ISSUE THREAD

**Issue by kaatish** [rapidsai/cugraph#494]
Cmake needs to be updated with the correct arch for T4 (compute capability 7.5) [here](https://github.com/rapidsai/cugraph/blob/0fc0f57213a439b73dba5645698b04c303e3acd9/cpp/CMakeLists.txt#L76).

As of now `__CUDA_ARCH__` does not correctly identify the compute capability of T4 in kernel code.

**Comment by afender** [comment]
closed by #495
