### ISSUE TITLE
Processing a batch of graphs

### ISSUE THREAD

**Issue by BestSonny** [rapidsai/cugraph#517]
@afender @BradReesWork  I want to know whether there is any implementation supporting processing a mini-batch of graphs (e.g., 32 graphs). The current cugraph seems to have to sequentially process these graphs. Any help is appreciated

**Comment by BestSonny** [comment]
@afender @BartleyR  I tried to wrap a list of graphs in Cython and pass it to f BatchSpectralBalancedCutClustering(graphs,
                                    num_clusters,
                                    num_eigen_vects=2,
                                    evs_tolerance=.00001,
                                    evs_max_iter=100,
                                    kmean_tolerance=.00001,
                                    kmean_max_iter=100):
    """
    Call gdf_balancedCutClustering_nvgraph
    """
    cdef int num_gragh
    num_gragh = len(graphs)
    df_list = []
    cdef uintptr_t graph
    cdef gdf_graph *g_ptr
    cdef gdf_graph** graph_ptr = <gdf_graph**>malloc(num_gragh * sizeof(gdf_graph*))
    cdef gdf_column** cluster_col_ptr = <gdf_column**>malloc(num_gragh * sizeof(gdf_column*))
    cdef gdf_column c_cluster_col
    cdef gdf_column c_identifier_col
    cdef int i

    for i in range(num_gragh):

        graph = <uintptr_t> graphs[i].graph_ptr
        
        g_ptr = <gdf_graph*> graph

        graph_ptr[i] = g_ptr
        
        # Ensure that the graph has CSR adjacency list
        err = gdf_add_adj_list(g_ptr)
        libcudf.cudf.check_gdf_error(err)

        # we should add get_number_of_vertices() to gdf_graph (and this should be
        # used instead of g.adjList.offsets.size - 1)
        num_verts = g_ptr.adjList.offsets.size - 1

        # Create the output dataframe
        df = cudf.DataFrame()
        df['vertex'] = cudf.Series(np.zeros(num_verts, dtype=np.int32))
        cc_identifier_col = get_gdf_column_view(df['vertex'])
        df['cluster'] = cudf.Series(np.zeros(num_verts, dtype=np.int32))
        c_cluster_col = get_gdf_column_view(df['cluster'])

        # Set the vertex identifiers
        err = g_ptr.adjList.get_vertex_identifiers(&c_identifier_col)
        libcudf.cudf.check_gdf_error(err)

        cluster_col_ptr[i] = &c_cluster_col
        

    err = gdf_balancedCutClustering_nvgraph(<gdf_graph**>graph_ptr,
                                            num_clusters,
                                            num_eigen_vects,
                                            evs_tolerance,
                                            evs_max_iter,
                                            kmean_tolerance,
                                            kmean_max_iter,
                                            num_gragh,
                                            <gdf_column**>cluster_col_ptr
                                            )
    libcudf.cudf.check_gdf_error(err)

    df_list.append(df['cluster'])

    return df_list`

**Comment by BradReesWork** [comment]
That is a good question.  You are correct that currently cuGraph would process each sequentially.  One of the issues that we always fall trap to is thinking only in terms of very large graphs where sequential is the only ways since no one than one graph can be processed at a time.  We also talk about batching in the sense of streaming, which is also different.

To your question, it is something that will take some time to code, but is possible and can be added to the roadmap  We are getting ready to do some refactoring an redesign.  I will make sure that we add a batch graph type into the design (doesn't mean that it will be coded next release).

**Comment by BradReesWork** [comment]
This is being added to Release 0.11 for design discussion

**Comment by BestSonny** [comment]
@BradReesWork I tried to write it by myself.  My basic idea is to extend the cugraph python wrapper and feed a list of graphs (gdf graph). Then I tried to extend the single graph operation (e.g., gdf_balancedCutClustering_nvgraph) to a batch version with OpenMP looping over the batch size. Not sure whether it is the right direction.

**Comment by BestSonny** [comment]
@BradReesWork I think it could be a great addition if the batch processing is supported in cugraph. The deep learning community widely adopts batch training and inference. Thank you very much for your contributions.

**Comment by afender** [comment]
Betweenness centrality enabled the Multi-GPU batched processing pipeline in cuGraph #940 
https://docs.rapids.ai/api/cugraph/nightly/dask-cugraph.html#batch-processing
