### ISSUE TITLE
[BUG] module 'cugraph' has no attribute 'Graph'

### ISSUE THREAD

**Issue by jamesthegiantpeach** [rapidsai/cugraph#526]
**Describe the bug**

**To Reproduce**
1. pip install cugraph-cuda100

```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cugraph
>>> G = cugraph.Graph()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cugraph' has no attribute 'Graph'
>>> exit()

```

**Expected behavior**
I expected to be able to create a Graph object

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

This is odd too. 

```Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cugraph
>>> import cugraph.structure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cugraph.structure'
>>> 
```

**Comment by jamesthegiantpeach** [comment]
This is not an issue with the conda installation. Maybe the pip installation is not officially supported?

**Comment by afender** [comment]
Hi James, 

`pip`is not supported by RAPIDS. We recommend using our conda packages : [release](https://anaconda.org/rapidsai/) or [nightly](https://anaconda.org/rapidsai-nightly). Another option is to [build from source](https://github.com/rapidsai/cugraph/blob/branch-0.10/CONTRIBUTING.md) if you are looking at contributing.
