### ISSUE TITLE
[FEA] self loop check

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#536]
We should have a feature that identifies if a graph has self-loops. We could compute it once and store the information inside the graph structure.
Nx checks for that for features like k-core : https://github.com/rapidsai/cugraph/pull/520/files/8dc6015561d345f4deebeb91074c5172c638feac#r330361903

**Comment by BradReesWork** [comment]
We could do this at the Python layer - simple len(df.query('src == dst') )
