### ISSUE TITLE
[FEA] Input/Output Style

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#541]
We should improve consistency with C++ API in RAPIDS and libcudf in particular

The preferred style for how inputs are passed in and outputs are returned is the following:

* Inputs 
   * Expensive to copy types --- pass by constant reference
   * Inexpensive to copy types --- pass by value
* In/Outs - Pass via pointer
* Outputs - Returned by value
  * Returning outputs by value will not incur a copy in most cases. For more details, see: https://stackoverflow.com/questions/12953127/what-are-copy-elision-and-return-value-optimization

For example:

```
namespace cugraph{
graph some_function( cugraph::graph const& input_graph, cugraph::graph * input_output_graph, int size){
  graph G;
  // Do stuff to create output G
  ...
  // Return the result graph of this function
  return G;
}
}
```

And the usage would be:
```
cugraph::graph input;
cugraph::graph in_out;
int size;
cugraph::graph output = cugraph::some_function(input, &in_out, size);
```

### Multiple Return Values

Sometimes it is necessary for functions to have multiple outputs. There are a few ways this can be done in C++ (including creating a `struct` for the output). One convenient way to do this is using `std::tie` and `std::make_pair`.

```
auto return_two_outputs(void){
  cugraph::graph out0;
  cugraph::graph out1;
  ...
  // Do stuff with out0, out1
  
  // Return a std::pair of the two outputs
  return std::make_pair(out0, out1);
}


cugraph::graph out0;
cugraph::graph out1;
std::tie(out0, out1) = cugraph::return_two_outputs();
```

Note: `std::tuple` *could* be used if not for the fact that Cython does not support `std::tuple`. Therefore, cugraph APIs must use `std::pair`, and are therefore limited to return only two objects of different types. Multiple objects of the same type may be returned via a `std::vector<T>`.

**Comment by seunghwak** [comment]
We should also decide on orders to take input arguments.

e.g. Inputs first, In/Outs second, (and if we cannot return outputs, outputs third, we should avoid taking output pointers as input arguments as much as possible but just in case this is not possible).

**Comment by BradReesWork** [comment]
We should continue with the approach that return variables are passed in as arguments and that all functions are 'void'.
