### ISSUE TITLE
[FEA] Leiden Algorithm for Community Detection

### ISSUE THREAD

**Issue by abhim701** [rapidsai/cugraph#552]
I am currently trying to apply graph based community detection for one of the case studies in my organization.

I have used Louvain's Algorithm available in CUGRAPH. However it spits out lot of bigger communities ( multiple communities merged) 

Leiden algorithm seems to be a better fit as it was tested in CPU. Due to the high volume of data, we want to run this in GPU. Can we have a Leiden implementation as well in CUGRAPH ?

Let me know if it is feasible.

Leiden Algorithm for Community Detection Literature Link:
https://www.nature.com/articles/s41598-019-41695-z

**Comment by vrushang25** [comment]
Hello abhi I tried to run cugraph but it's not working on anaconda. the kernel is not producing output of simple print functino as well. I successfully installed the cugraph and cudf but output is not coming. 

In jupyter notebook it says kernel dead but in spyder nothing happens.

How did you got the output?

Regards,
Vrushang.

**Comment by AK-ayush** [comment]
Hi @vrushang25 can you provide a minimal reproducer? if this issue is still there...

**Comment by jwyles** [comment]
Main steps for Leiden Algorithm:
1. Assign all nodes to their own partition
2. Fast move nodes to improve metric
3. Refine partition
4. Aggregate graph according to refined partition
5. Assign nodes to clusters according to unrefined partition
6. Repeat steps 1-5 until no improvement can be made

**Comment by honeyve** [comment]
> https://www.nature.com/articles/s41598-019-41695-z

work is refine part ?
