### ISSUE TITLE
[BUG] Missing moderngpu source files?

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cugraph#553]
I'm attempting to build/install cugraph from source using the provided `build.sh` script.

Command:
```
git clone https://github.com/rapidsai/cugraph -b branch-0.10
cd cugraph
git submodule update --init --recursive --remote

bash build.sh libcugraph
cd /rapids/cugraph/python
python setup.py install
```
Build failure trace:
```
...
[100%] Built target GoogleTest
-- GoogleTest installed here: /rapids/cugraph/cpp/build/googletest/install
-- Google C++ Testing Framework (Google Test) found in /rapids/cugraph/cpp/build/googletest
-- NVSTRINGS: NVSTRINGS_INCLUDE set to /conda/envs/rapids/include
-- NVSTRINGS: NVSTRINGS_LIBRARY set to /conda/envs/rapids/lib/libNVStrings.so
-- NVSTRINGS: NVCATEGORY_LIBRARY set to /conda/envs/rapids/lib/libNVCategory.so
-- NVSTRINGS: NVTEXT_LIBRARY set to /conda/envs/rapids/lib/libNVText.so
-- CUDF: CUDF_LIBRARY set to /conda/envs/rapids/lib/libcudf.so
-- CUDF: CUDF_INCLUDE set to /conda/envs/rapids/include
-- RMM: RMM_LIBRARY set to /conda/envs/rapids/lib/librmm.so
-- RMM: RMM_INCLUDE set to /conda/envs/rapids/include
-- Configuring done
CMake Error at CMakeLists.txt:263 (add_library):
  Cannot find source file:

    /rapids/cugraph/thirdparty/gunrock/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:263 (add_library):
  No SOURCES given to target: cugraph


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Does moderngpu need a conda package installed, or does the CMake config possibly need to be updated?

**Comment by kaatish** [comment]
Could you try removing the --remote flag while updating the submodules?

git clone https://github.com/rapidsai/cugraph -b branch-0.10
cd cugraph
git submodule update --init --recursive

**Comment by randerzander** [comment]
That got me further, but I get c++ errors now:
```
[ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/partition.cu.o                                    [232/1883]
[ 47%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/nvgraph_cusparse.cpp.o                                       
[ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/graph_extractor.cu.o                                        [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/pagerank_kernels.cu.o                                       [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/utilities/graph_utils.cu.o                                          
[ 50%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/triangles_counting.cpp.o                                     
[ 51%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/nvgraph.cu.o                                                
[ 52%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/valued_csr_graph.cpp.o                                       [ 53%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/triangles_counting_kernels.cu.o                             
[ 54%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/widest_path.cu.o                                            [ 55%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/error_utils.cu.o         [ 56%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/test_utils.cu.o          
[ 57%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/externals/moderngpu/src/mgpucontext.cu
.o                                                                                                                         
[ 58%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/misc_utils.cu.o          
[ 60%] Building CXX object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/externals/moderngpu/src/mgpuutil.cpp.o 
[ 59%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/str_to_T.cu.o            
[ 61%] Building CUDA object CMakeFiles/cugraph.dir/src/matching/subg_match.cu.o                                            
/rapids/cugraph/cpp/src/cores/core_number.cu:27:10: fatal error: Static/CoreNumber/CoreNumber.cuh: No such file or director
y                                                                                                                          
 #include <Static/CoreNumber/CoreNumber.cuh>                                                                               
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                               
compilation terminated.                                                                                                    
CMakeFiles/cugraph.dir/build.make:244: recipe for target 'CMakeFiles/cugraph.dir/src/cores/core_number.cu.o' failed        
make[2]: *** [CMakeFiles/cugraph.dir/src/cores/core_number.cu.o] Error 1                                                   
make[2]: *** Waiting for unfinished jobs....
```

**Comment by aschaffer** [comment]
The 1st problem looks like the same error that required removing `--remote` from gunrock submodule-ing in PR#496. I'm looking into the 2nd.

**Comment by aschaffer** [comment]
This looks like a `cuhornet` missing dependency.

**Comment by kaatish** [comment]
> That got me further, but I get c++ errors now:
> 
> ```
> [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/partition.cu.o                                    [232/1883]
> [ 47%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/nvgraph_cusparse.cpp.o                                       
> [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/graph_extractor.cu.o                                        [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/pagerank_kernels.cu.o                                       [ 49%] Building CUDA object CMakeFiles/cugraph.dir/src/utilities/graph_utils.cu.o                                          
> [ 50%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/triangles_counting.cpp.o                                     
> [ 51%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/nvgraph.cu.o                                                
> [ 52%] Building CXX object CMakeFiles/cugraph.dir/src/nvgraph/valued_csr_graph.cpp.o                                       [ 53%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/triangles_counting_kernels.cu.o                             
> [ 54%] Building CUDA object CMakeFiles/cugraph.dir/src/nvgraph/widest_path.cu.o                                            [ 55%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/error_utils.cu.o         [ 56%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/test_utils.cu.o          
> [ 57%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/externals/moderngpu/src/mgpucontext.cu
> .o                                                                                                                         
> [ 58%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/misc_utils.cu.o          
> [ 60%] Building CXX object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/externals/moderngpu/src/mgpuutil.cpp.o 
> [ 59%] Building CUDA object CMakeFiles/cugraph.dir/rapids/cugraph/thirdparty/gunrock/gunrock/util/str_to_T.cu.o            
> [ 61%] Building CUDA object CMakeFiles/cugraph.dir/src/matching/subg_match.cu.o                                            
> /rapids/cugraph/cpp/src/cores/core_number.cu:27:10: fatal error: Static/CoreNumber/CoreNumber.cuh: No such file or director
> y                                                                                                                          
>  #include <Static/CoreNumber/CoreNumber.cuh>                                                                               
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                               
> compilation terminated.                                                                                                    
> CMakeFiles/cugraph.dir/build.make:244: recipe for target 'CMakeFiles/cugraph.dir/src/cores/core_number.cu.o' failed        
> make[2]: *** [CMakeFiles/cugraph.dir/src/cores/core_number.cu.o] Error 1                                                   
> make[2]: *** Waiting for unfinished jobs....
> ```

Could you paste the contents of cugraph/thirdparty and cugraph/thirdparty/gunrock/externals?

**Comment by aschaffer** [comment]
@kaatish: "that error is typically seen when cuhornet is not cloned into the repo. Looks like removing --remote does not bring in cuhornet at all."

Yep, that was my suspicion. Rick and I assumed that eliminating --remote for gunrock alone would not affect the other submodules. We were wrong, apparently. 

@rlratzel it looks like the fix in `ci/<cpu/gpu>/build.sh`  (removing `--remote` for gunrock) affects the other submodules. Although the command we use specifically targets gunrock: 

`git submodule update --init --recursive thirdparty/gunrock/`

**Comment by aschaffer** [comment]
Ok, I tried adding `git submodule update --init --recursive --remote thirdparty/cuhornet/` to the 2 `build.sh` files mentioned above. That does NOT fix the problem.

So, the PROBLEM seems to be that our builds cannot handle different ways of submoduling (1/ vs. wo/ `--remote`). Not anymore, at least. It was able to, when PR#496 was merged. @rlratzel, any idea?

**Comment by afender** [comment]
cuhornet submodule points to 8e21f9f which is outdated and causes the second error you see.

While using `--remote` is one way to get the latest version of submodules, if you couple it with `--recursive` in the same command line it will apply to submodules of submodules and bring dependencies in gunrock that they are not supported. This is what caused your first error.

Options : 
1. Disable gunrock submodule
2. Update cuhornet submodule
3. Use the fix I suggested here : https://github.com/rapidsai/faq/issues/4#issuecomment-539348062

**Comment by aschaffer** [comment]
Ok, so I got it to build (locally, I doubt this would address CI concerns):
```
$ git clone -b branch-0.10 https://github.com/aschaffer/cugraph.git # fork updated a few hours ago
$ cd cugraph/
$ git submodule update --init --recursive --remote # this gets latest of every submodule
$ git submodule update --init --recursive thirdparty/gunrock/ # this reverts gunrock's submodule to a specific branch / tag
```

**Comment by aschaffer** [comment]
@rlratzel, maybe the commands we put in `ci/<cpu/gpu>/build.sh` happen *too soon*?

**Comment by aschaffer** [comment]
> 
> 
> Ok, I tried adding `git submodule update --init --recursive --remote thirdparty/cuhornet/` to the 2 `build.sh` files mentioned above. That does NOT fix the problem.
> 
> So, the PROBLEM seems to be that our builds cannot handle different ways of submoduling (w/ vs. wo/ `--remote`). Not anymore, at least. It was able to, when PR#496 was merged. @rlratzel, any idea?

Let me try switching the order of doing the submoduling in the 2 build.sh files. (to be cont'd soon)
