### ISSUE TITLE
[BUG] CMake build fails when using -DNVG_PLUGIN=FALSE

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cugraph#56]
When trying to build cuGraph from source, I used the -DNVG_PLUGIN=FALSE argument, but CMake fails with an error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.              
Please set them or make sure they are set and tested correctly in the CMake files:                        
NVGRAPH_INCLUDE
```
It looks like the nvgraph plugin is now required? If so, the README should suggest how to set the -DNVGRAPH_INCLUDE switch

**Comment by afender** [comment]
`-DNVG_PLUGIN=FALSE` is not supported in cuGraph. 
`Readme.md` will be updated in PR #53.

**Comment by ChuckHastings** [comment]
This iNVGRAPH_INCLUDE error is a function of nvgraph not being found in the environment.

**Comment by randerzander** [comment]
No longer relevant
