### ISSUE TITLE
[BUG]Subgraph Extraction 

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#567]
**Describe the bug**
When performing a Subgraph Extraction, the returned subgraph (Graph) throws and error on any follow-on operations.  The solution is to call  "view_edge_list()" on the extracted subgraph.  The user should not have to do that.  The returned Graph should be ready to go.  

**To Reproduce**
1) create a graph  
2) run subgraph
       subG = cugraph.subgraph(G, v)
3) get the number of vertices
      subG.number_of_vertices()

**Comment by seunghwak** [comment]
@BradReesWork This succeeds now, so I guess this may get fixed during refactoring as you mentioned.

**Comment by BradReesWork** [comment]
This was fixed as part of the recent refactoring and is now working
