### ISSUE TITLE
[BUG] Setup cugraph Python API docs with Sphinx

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cugraph#57]
Now that cuGraph has its first Python bindings, we need to setup a Sphinx project for generating its API docs

**Comment by afender** [comment]
Sphinx is setup for generating its API docs (https://github.com/rapidsai/cugraph/tree/master/docs). 
However, I noticed it's broken (it's based on an old cuDF solution) so it needs to be updated.

**Comment by randerzander** [comment]
This was fixed
