### ISSUE TITLE
[BUG] Katz test assumes `RAPIDS_DATASET_ROOT_DIR` is `<path>/cugraph/datasets/`

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#571]
Katz test relies on the assumption that CI/user will download the graph dataset there and that GitHub will get the references to that same place.

2 options : 
1. use both graph input and references from the github repo (and not rely on `RAPIDS_DATASET_ROOT_DIR`). 
2. upload references to S3 and use the same reference directory structure than other algos in order to work when `RAPIDS_DATASET_ROOT_DIR` is not  `<path>/cugraph/datasets/`.

---

Also, the test should throw an error when it cannot find the reference file

**Comment by BradReesWork** [comment]
The KATZ test was updated last release to use datasets specified in the Utility class.  that removed the Katz test code from having a different view of where datasets were located.
