### ISSUE TITLE
[BUG] Subgraph Extraction - needs to return renumbering mapping

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#572]
**Describe the bug**
When running cugraph.subgraph(G, V) the returned list of vertices are renumbered.  While that is needed to reduce the size of the extracted matrix, a mapping of old vertex IDs to renumbered needs to be returned.   

**What should be returned**
  subG, df
    - the initialized subgraph
    - a dataframe with vertex ID mapping

**Comment by Iroy30** [comment]
Solved with PR #588. Issue can be closed after verifying expected working of subgraph extraction

**Comment by Iroy30** [comment]
This can be closed since we now return a subgraph which internally stores the renumber map. When the subgraph is viewed using view_edge_list(), the user notation (unrenumbered) of vertex ids is returned
