### ISSUE TITLE
[BUG] Documentation need updating

### ISSUE THREAD

**Issue by vmjersey** [rapidsai/cugraph#586]
**Describe the bug**
[https://github.com/rapidsai/cugraph/blob/branch-0.11/CONTRIBUTING.md]
under "Setting Up Your Build Environment" it does not list Cudf as a dependency.  This might seem obvious to the developers, but it can be confusing to Noobs.

**Comment by BradReesWork** [comment]
thanks.  I'll fix the documentation before 0.11 get released
