### ISSUE TITLE
[ENH] Leak test after removing C++ ownership policy

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#593]
The current C++ ownership mechanism will conflict with the Python class in the long run and won't be needed after the refactoring.
C++ should just free the C++ object wrapping the data but not the device data as it is expected to be owned by the above layer and potentially transit through other Rapids products.
C++ API clients (gtests, bindings) should be updated to properly handle the device data they get from C++.
Leak tests should be run.

**Comment by ChuckHastings** [comment]
The work to remove gdf_column and rmm allocation calls cleaned up much of this.  I suspect that we can just do leak testing at this point.

**Comment by BradReesWork** [comment]
being closed.  The move to C++ unique pointer standard removes (or greatly reduces) memory leaks
