### ISSUE TITLE
[ENH] Error messages need to be more specific

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#606]
Error messages need to be more specific.  Don't just say that one argument caused an error, be specific about which one.  Likewise, say what field and data type is wrong.  

- [ ] review all error messages and update

**Comment by lmeyerov** [comment]
@BradReesWork  Clarifying a bit on some stuff we hit:

1. We mistakingly passed in `None` and indeed took a bit to decipher what error message `"graph"` meant :)

2. Worse, our Python context hard crashed, so exception handling didn't work 😅

**Comment by BradReesWork** [comment]
done in PR #720
