### ISSUE TITLE
[FEA] Add create_using feature when creating a graph from edge list

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#617]
Instead of creating the graph before loading data into it, we should be able to directly create a graph from an edge list. We would need an option like `create_using` to specify what graph is to be created from the edge list DataFrame

For example:
`G = from_cudf_edgelist( ... , create_using=None)`
create_using (graph constructor, optional (default=cugraph.Graph)) – Graph type to create.

See also : https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html

**Comment by Iroy30** [comment]
I believe this can now be closed (#689 )
