### ISSUE TITLE
[FEA] [NV] Add Python bindings for Spectral Clustering

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#62]
Following Alex's  CUDA/C++ method for accessing nvgraph features using cugraph graph structure, wrapperSpectral Clustering  [src/plugin/nvgraph/nvgraph_gdf.cu]. 

This should cover both Modularity and min cut

Subtasks checklist:
- [ ] Pythion bindings and API
- [ ] Pytest testing against NetworkX
- [ ] Documentation
- [ ] licenses info
- [ ] Validate

**Comment by jwyles** [comment]
Please assign this to me. I am starting to work on it.
