### ISSUE TITLE
[BUG] Pytest fail when cugraph is built in debug mode

### ISSUE THREAD

**Issue by ogreen** [rapidsai/cugraph#633]
**Describe the bug**
pytest suite fails to complete successfully when cugraph is built in debug mode.

**To Reproduce**
Build cugraph with debug info as explained here:
https://github.com/rapidsai/cugraph/blob/branch-0.12/CONTRIBUTING.md
./build.sh libcugraph -g 

After that:
cd python
python setup.py build_ext --inplace
python setup.py install    # install cugraph python bindings
pytest

**Expected behavior**
All tests should pass with PASSED.

**Screenshots**
(Copy&Paste from command line)
cugraph/tests/test_balanced_cut.py FFFF................................F........                                                                                                                     [  8%]
cugraph/tests/test_bfs.py ....................                                                                                                                                                       [ 12%]
cugraph/tests/test_connectivity.py ....................                                                                                                                                              [ 16%]
cugraph/tests/test_core_number.py ........                                                       

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by ChuckHastings** [comment]
Just did a clean build of branch 0.15 with debug turned on.  All of the pytest tests passed cleanly for me.

The test that failed in Oded's example above was exercising nvgraph spectral methods.  These methods were refactored a bit during the effort to eliminate the use of gdf_column and RMM_ALLOC.  I suspect that whatever was failing before was corrected during this update.
