### ISSUE TITLE
[BUG] OOM running SCC

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#637]
100M data file is running out of memory running SCC on a 16GB GPU

**Comment by jeaton32** [comment]
Any ideas on cause? Even if we needed a extra copy for the components, should be able to run this in a few GB at most.

**Comment by BradReesWork** [comment]
Issues was caused by the number of edges being larger that what is allowed in current implementation.  Current limit is:
32GB GPU ~ 50K vertices
16GB GPU ~ 25K vertices

customer had over 100K vertices in dataset
