### ISSUE TITLE
[BUG] Remove gdf_column in the graph structure and directly related features

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#639]
Next step for #538

Apply #629 to the graph structure and related features (degree, add edge list, etc.). 

This will touch many files as we use the graph everywhere. 

1. upgrade core graph structure files under cpp/structure
2. upgrade converters (coo2csr,...) degree functions, renumbering, ... 
3. upgrade all algo files

**Comment by BradReesWork** [comment]
Closed by #722
