### ISSUE TITLE
Why kernel Dies after execution

### ISSUE THREAD

**Issue by vrushang25** [rapidsai/cugraph#648]
I installed cugraph and cudf i can call it's all functions as well. but when i run 
"df, mod = cugraph.nvLouvain(G)" my kernel dies. 

why it's happening?

Thank you so much:)

Regrds,
Vrushang.

**Comment by jwyles** [comment]
nvLouvain(G) is deprecated now you should run: df, mod = cugraph.louvain(G) that should work.

**Comment by vrushang25** [comment]
> nvLouvain(G) is deprecated now you should run: df, mod = cugraph.louvain(G) that should work.

Hello sir,

Here is my code 
import cugraph
import cudf
print("hi")
M = cudf.read_csv('karate.csv', delimiter=' ', dtype=['int32', 'int32', 'float32'], header=None)
sources = cudf.Series(M['0'])
destinations = cudf.Series(M['1'])
G = cugraph.Graph()
G.add_edge_list(sources, destinations, None)
parts, modularity_score = cugraph.louvain(G)
print(modularity_score)

and the output is like 
hi
Traceback (most recent call last):

  File "/home/new_user/Desktop/untitled0.py", line 9, in <module>
    parts, modularity_score = cugraph.louvain(G)

AttributeError: module 'cugraph' has no attribute 'louvain'

i installed cugraph by the command like 
"conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cugraph cudatoolkit=9.2
"

is it problem of version?

**Comment by BradReesWork** [comment]
That should have worked, although we are deprecating that API in favor of the newer from_cudf API (similar to how NetworkX moved to using Panda).  

Try removing rapids and reinstalled with the version specified:
conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.11 python=3.6 cudatoolkit=9.2

**Comment by vrushang25** [comment]
> That should have worked, although we are deprecating that API in favor of the newer from_cudf API (similar to how NetworkX moved to using Panda).
> 
> Try removing rapids and reinstalled with the version specified:
> conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.11 python=3.6 cudatoolkit=9.2

but sir in new anaconda i have python version 3.7 than what should i do? can you please send me the command for that one please. i have gpu version of GP102 pascal architecture.

**Comment by BradReesWork** [comment]
take a look at: https://rapids.ai/start.html  there is a nice tool for creating the install command based on versions

Also, check out the cugraph examples in notebook repo  (https://github.com/rapidsai/notebooks/tree/branch-0.12/cugraph)

**Comment by BradReesWork** [comment]
making issue as closed.  please reach out with any further questions or issues
