### ISSUE TITLE
[BUG] Verify and upgrade notebooks to reflect 0.11/0.12 changes

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#650]

**Comment by taureandyernv** [comment]
Solved in https://github.com/rapidsai/notebooks/pull/284
https://github.com/rapidsai/notebooks/pull/290
https://github.com/rapidsai/notebooks/pull/291

**Comment by BradReesWork** [comment]
moving to 0.13 branch since we need 0.12 built before the notebooks can be validarted

**Comment by BradReesWork** [comment]
This was done in PR #739
