### ISSUE TITLE
[BUG] Remove cuda toolkit dependency from setup.py

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#66]
Python bindings currently request the whole cuda toolkit only because some nvgraph functions use cuda data types.

A possible solution is to wrap the _nvGraph_ function (`a`) into a  C++ _cuGraph_ function (`b`) so that `b` exposes only simple types and do the proper cast before calling `a`. Then, the existing python bindings should be updated to call the `b` function from _cugraph_.

**Comment by afender** [comment]
@Iroy30 please take a look, I remember you are familiar with the issue.

**Comment by afender** [comment]
@Iroy30 is this going to make it in 0.6?

**Comment by BradReesWork** [comment]
Being moved to v0.7
Once nvGRAPH is opened sourced we will have have this dependency

**Comment by afender** [comment]
The bindings will still need to get rid the dependency on cuda data types which are defined in the toolkit.

**Comment by afender** [comment]
closed by #157
