### ISSUE TITLE
[FEA] Make the Hash Size in Renumbering a function argument

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#661]
Currently the hash size is hard coded. This value should be a function argument or dynamically set based on graph size.    

related to issue #243

**Comment by ChuckHastings** [comment]
I believe the renumbering work can be refactored using some cudf++ structures that will make it faster and make it possible to have this parameter be derived from the graph size.

**Comment by ChuckHastings** [comment]
Suggest closing this as OBE.  PR #963 refactors this code to use cudf functions.  The current C++ functions will no longer be used after that PR is merged.

From a performance perspective, it might be necessary to reintroduce some C++ functions, but we would build those functions in a way that would not require this parameter.

**Comment by BradReesWork** [comment]
OBE
