### ISSUE TITLE
[ENH] Accept users notation for auto multi-column renumbering/unrenumbering

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cugraph#678]
**Describe the bug**
The cugraph API supports auto multi-column renumbering with PR #666 . All cugraph algorithms use the renumbered notation for running algorithms and un-renumber the vertices in the result back to user's notation for viewing. The bindings need to be further updated to accept additional arguments(vertices in the case of multi column renumbering map) in the API as user's notation while calling algorithms and internally renumber them, for example, nstart in pagerank, source in sssp, etc. 

The following needs to be resolved:
1) Currently there are two renumbering methods implemented and in use. Identify if multi-column renumbering #636 can handle all renumbering cases and proceed with one(or both) renumbering method accordingly for further changes.
2) Auto renumber multi column vertices passed by the user in algorithms. 
3) Update (un)renumbering degree calculation and two hop neighbors in graph.py
4) Test and verify functionality of all changes

**Comment by ChuckHastings** [comment]
Working with an external customer and re-discovered this issue.   Note that jaccard is even more complicated, since it needs to renumber 2 columns in the output, and in some variations 2 columns in the input.

**Comment by BradReesWork** [comment]
part of renumbering refactoring
