### ISSUE TITLE
[ENH] SCC needs a better mechanism to handle memory requirement.

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#693]
SCC implementation currently checks the entire physical memory in the system (via calling cudaGetDeviceProperties and querying totalGlobalMem) and proceeds if this is larger than the memory requirement.

https://github.com/rapidsai/cugraph/blob/3735720a644412358b4831aee0c6717dab6a97c4/cpp/src/components/connectivity.cu#L162
https://github.com/rapidsai/cugraph/blob/3735720a644412358b4831aee0c6717dab6a97c4/cpp/src/tests/components/scc_test.cu#L162

This is insufficient as we need to check the available free memory (not the entire physical memory) and checking this can vary based on whether we're using managed memory/RMM pool or not.

And even this solution will not work if we concurrently run multiple queries on a single GPU (e.g. solving many smaller graph problems in a batch) as actual available memory can change between this query and actual memory allocation. 

SCC implementation needs to throw memory allocation failure exception like any other graph algorithms  instead of this check (and we need to investigate that SCC and other graph algorithms are exception safe).

**Comment by BradReesWork** [comment]
OBE - new SCC for MNMG will address issues
