### ISSUE TITLE
DISCUSSION: Add support for cypher query language

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cugraph#713]
I am playing with idea to expose cugraph to cypher query language:
https://www.opencypher.org/

Some python library for neo4j
https://py2neo.org/v4/

How difficult it would be to support this, or where to start in code of cugraph? Any ideas?

Additionally it will be good if vertexes/edges supports variable binding like:
string, int, list,map, etc.

**Comment by datametrician** [comment]
You're not the first to ask about this. Do you think cypher is the most used query language or are there other alternatives you think we should explore?

**Comment by archenroot** [comment]
So lets discuss, we have following langs available:
Cypher - I vote for this one as it felt most intuitive to me, but I agree some others might have other idea :-)
```
MATCH (n:Person)-[:FRIEND]-(f)
WITH count(f) as c, n
MATCH (n)-[:FRIEND]-()-[:FRIEND]-(fof)
RETURN n, c, fof
```

SPARQL
I used this one when working with RDF datasets, but I didn't like the syntax to be honest, it felt strange to use it and I had to often spent times to read manual over and over 
```
PREFIX foaf: 
SELECT ?craft ?homepage
{
  ?craft foaf:name "Apollo 7" .
  ?craft foaf:homepage ?homepage
}
```

GraphQL
Well this is defacto standard adopted by service layers in general to replace REST APIs, I like the idea, I see it as another candidate as its being adopted on non graph systems as well:
```
{
  hero {
    name
    mass
  }
}
Returns
{
  "hero": {
    "name": "Luke Skywalker",
    "mass": 77
  }
}
```

Gremlin
I think it is most variable language from all those above, but also requires some study 
```
def gt=graph.traversal();
gt.V()
.hasLabel("band")
.has("genre",within("indie","Hip Hop","Techno/EDM"))
.outE("performing_at")
.inV().path();
```
I don't like much the query language of Gremlin, but I agree its probably the most rich lang at same time...

I can imagine this job here shouldn't be materializing within this project, but something like BlazingGraph (like blazingSQL) could emerge...

**Comment by datametrician** [comment]
Only if BlazeGraph was still around...

**Comment by archenroot** [comment]
Sure, https://github.com/blazegraph/database repo is still available although quite old, but my idea was rather to follow simplified approach of blazingsql, to completely reuse their approach, just instead of cudf and sql use cugraph and cypher/gremlin

I think trying to revieve this codebase https://github.com/blazegraph/database could be bit bigger task.... I think Amazon aquired them and its now Amazon Neptune managed service.

**Comment by archenroot** [comment]
@datametrician - anyway how difficult it will be for cugraph to support storing and retreiving data on vertices and edges?

**Comment by jeaton32** [comment]
In cuGraph, since we start from a dataframe edge list, you can always
attach arbitrary edge data right there, just add as many columns as you
need for the associated data.  Alternatively, you can keep a separate
dataframe with edge id mapping to rows, and keep the associated data
there.
Same idea applies for vertex data, keep a separate dataframe with a map of
vertex id to vertex associated data.   Results from cuGraph are returned in
a dataframe, with ids from the original dataframe, so you can then merge
the results with the associated dataframes to carry forward the edge and
vertex data as results.

**Comment by BradReesWork** [comment]
We have pondered the notion of a query language for a while.  cuGraph is not a database, so what you have loaded into a DataFrame is already an extract from some data repository or file.  Once data is in RAPIDS it can be represented as a single DataFrame or as multiple DataFrames.  This allow data to be represented as Property Graph or other relational structures and support the type of queries mentioned.  The only difference is syntax
