### ISSUE TITLE
[FEA] Remove direct use of `RMM_ALLOC`/rmm::alloc

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cugraph#727]
**Is your feature request related to a problem? Please describe.**

RMM is likely to deprecate and remove the `RMM_ALLOC/rmm::alloc` and corresponding `RMM_FREE/rmm::free` APIs https://github.com/rapidsai/rmm/issues/302

**Describe the solution you'd like**
 Remove direct use of these APIs in favor of RAII constructs like `rmm::device_buffer` or `rmm::device_vector`. Alternatively, using the `device_memory_resource` directly from `get_default_resource()` and calling `allocate/deallocate`.

**Comment by seunghwak** [comment]
This is related to

https://github.com/rapidsai/cugraph/issues/459

and should be addressed at the same time.

**Comment by ChuckHastings** [comment]
In my work on the remove gdf_column epic, I have been converting many of our ALLOC_TRY calls into the RAII constructs (mostly rmm::device_vector).  I think we should use rmm::device_vector for any locally allocated memory that is no longer required when the function exits.  This RAII construct is much better for reducing memory leaks and is generally a cleaner model.  The exceptions to this, within our graph code, would be:
1. Graph construction requires allocating pointers that are returned to the python and converted into cudf columns/data frames.  In this case our code needs to allocate memory that is returned across the C++ API.
1. Algorithms that return a new graph need to allocate new arrays for the COO that will ultimately become cudf columns.
1. Algorithms that return results that are variable in length would need to return results in memory that is allocated during the call.

Most of our algorithms return a result who's size and type is known a priori.  In this case, the python code should create and initialize the column/columns that are required and then we can pass pointers into the cugraph calls directly and just populate the already allocated memory.

**Comment by ChuckHastings** [comment]
My suggestion for this issue would be the following:
1. Continue moving to RAII constructs to eliminate as much direct allocation of memory as possible
1. Modify ALLOC_TRY/ALLOC_TRY_FREE to get the default resource manager and call allocate/deallocate on the default resource manager so that things continue to work
1. After we've eliminated as many ALLOC_TRY calls as possible, this will identify which calls really need a resource allocator.  Add an optional resource allocator to the API, defaulting to the default resource allocator and replace the ALLOC_TRY calls with calls to allocate/deallocate directly

This strategy will let us conclude step 3 at our pace instead of hurrying to get that done before RMM deprecates the functions (although I think we can probably get it all done pretty quickly if that's a priority).

**Comment by jrhemstad** [comment]
> Graph construction requires allocating pointers that are returned to the python and converted into cudf columns/data frames. In this case our code needs to allocate memory that is returned across the C++ API.

RMM Python has a `DeviceBuffer` class that uses `rmm::device_buffer` under the hood. So you can just return `device_buffer`s from C++ APIs and Python can take ownership of them.

**Comment by seunghwak** [comment]
> In my work on the remove gdf_column epic, I have been converting many of our ALLOC_TRY calls into the RAII constructs (mostly rmm::device_vector). I think we should use rmm::device_vector for any locally allocated memory that is no longer required when the function exits. This RAII construct is much better for reducing memory leaks and is generally a cleaner model. The exceptions to this, within our graph code, would be:
> 
> 1. Graph construction requires allocating pointers that are returned to the python and converted into cudf columns/data frames.  In this case our code needs to allocate memory that is returned across the C++ API.
> 2. Algorithms that return a new graph need to allocate new arrays for the COO that will ultimately become cudf columns.
> 3. Algorithms that return results that are variable in length would need to return results in memory that is allocated during the call.
> 
> Most of our algorithms return a result who's size and type is known a priori. In this case, the python code should create and initialize the column/columns that are required and then we can pass pointers into the cugraph calls directly and just populate the already allocated memory.

1. If the python layer owns the memory, the C++ layer just needs to get a non-owning pointer from the python layer, if the C++ layer should pass the ownership of the memory to the python layer, we need to use just a proper ownership transfer mechanism. It is very likely that cuDF folks have already solved this problem, and I think we may better look how they handle this and follow what they do unless there is a serious issue.

2. We can at least use smart pointers but better just return device vectors (Return Value Optimization will remove unnecessary copy or move).

3. Same with 2.

We should never use raw pointers as this will lead to memory leak on exceptions.

**Comment by ChuckHastings** [comment]
Even better, thanks @jrhemstad.  We do have one special case in pagerank where we have to allocate memory locally due to a cub bug.  I have an ifdef in that has the RAII calls that would be there eventually.  But otherwise we should be able to avoid this entirely.

**Comment by seunghwak** [comment]
> Even better, thanks @jrhemstad. We do have one special case in pagerank where we have to allocate memory locally due to a cub bug. I have an ifdef in that has the RAII calls that would be there eventually. But otherwise we should be able to avoid this entirely.

@ChuckHastings Could you point out the code?

**Comment by ChuckHastings** [comment]
https://github.com/rapidsai/cugraph/blob/8283eda0bd90f176afcb562ee83133180b694a64/cpp/src/link_analysis/pagerank.cu#L218

**Comment by seunghwak** [comment]
> https://github.com/rapidsai/cugraph/blob/8283eda0bd90f176afcb562ee83133180b694a64/cpp/src/link_analysis/pagerank.cu#L218
> 
> (Your issue @seunghwak)

We can wrap cudaMalloc here with a smart pointer with a custom deleter to make this less vulnerable to exceptions (and maybe thrust::device_vector with reserve() or shrink_to_fit() may work as well as long as memory does not come from a pool).

Look for

https://github.com/seunghwak/hornet/blob/google-test/hornet/tests/rmm/rmm_test.cu#L81

as an example.

**Comment by jrhemstad** [comment]
How are we doing on this? Will this be done for 0.14 so we can remove the APIs from RMM?

**Comment by ChuckHastings** [comment]
That's the goal.  We're close.  There are PRs in review that cover most of this work.  Once they get merged we'll be able to assess what's left.  Should be small and easy to fix.

**Comment by BradReesWork** [comment]
closed by #897
