### ISSUE TITLE
[ENH] Pagerank templating cleanup

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#729]
**Describe the solution you'd like**
The latest work to create a new graph object adds the ability for the type of an edge id to be different from the type of a vertex id.  Specifically this would allow us to have > 2^31 edges (since the type today is a signed int) but still only use an int32_t to represent the vertex ids.

The API has been enhanced to support these types being different - although the only instantiated versions of the algorithm specify them as the same.

The *underlying* functions (`pagerankIteration` and `pagerankSolver`) have NOT been updated, since there are calls to CUB routines that might require adapting.

We should change these implementations to match the template definition of the API and make whatever changes are required to support that.

**Describe alternatives you've considered**

**Additional context**

**Comment by afender** [comment]
See https://github.com/rapidsai/cugraph/issues/484

**Comment by BradReesWork** [comment]
This is OBE as PageRank has shifted to using the Pattern Accelerator code
