### ISSUE TITLE
[ENH] Katz should auto-compute Alpha if not specified

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#730]
**Describe the solution you'd like**
The current default Alpha value seems to be too large and throws and error even on small files.  That value should be auto-computed if not specified

**Comment by kaatish** [comment]
If the user does specify a value of alpha that is greater than the maximum alpha required for convergence, what should be the behavior of cugraph?

Should it blindly run for the maximum number of iterations? or Should it throw an exception informing the user that the alpha is way too large along with the maximum acceptable alpha?

**Comment by BradReesWork** [comment]
If a user specifies an `alpha` then that is what is used.  If the user does not specify `alpha`  then it should be set to 1/max_degree.  The user should not need to figure out max_degree before making the call

**Comment by kaatish** [comment]
Alright, so we will not raise an exception if a value of alpha causes the maximum number of iterations to be reached.
