### ISSUE TITLE
importing data from tinkerpop 

### ISSUE THREAD

**Issue by AVSuni** [rapidsai/cugraph#732]
Thanks for all the hard work. I'm a huge admirer. 

Do you have any advice on the current gold standard for importing data from knowledge graphs? I'm working with JanusGraph. I can use the Python-Gremlin library to pull data out and then transform it to cudf. Is there a more efficient way? Thanks!

**Comment by BradReesWork** [comment]
not currently :(  You will need to extract from JanusGraph a format that RAPIDS understands, then load it into cudf and from there into cuGraph.   We have talked about connectors to various databases, but there is so much on our to-do list and connectors have not been a top priority

**Comment by AVSuni** [comment]
Thanks Brad. I completely understand. I'm glad it's on the radar. Tinkerpop compatibility would be nice. Keep up the great work!
