### ISSUE TITLE
[ENH] Jaccard API change

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#743]
**Describe the solution you'd like**
Our jaccard implementation has a different default behavior than networkx.  If you do not specify a list of vertex pairs to operate on then networkx gives you an iterator over (n)(n-1)/2 vertex pairs (upper triangular representation of the dense graph).  The caller would need to iterate over all (n)(n-1)/2 pairs to actually compute the value (the networkx iterator provides lazy evaluation of the jaccard coefficient).

This is clearly not scalable to large graphs.  No user is going to want to run an iterator over such a result if n is large (n = 100,000 would require iterating over 50 billion values to compute an answer).

Our implementation essentially runs jaccard_list over the list of adjacent vertices.  This would certainly be confusing to a novice user.  If a user really wanted that they could do this directly themselves with little effort.

The suggestion is that we **don't** implement the default interface and only implement the interface that requires a list.  We can identify in the documentation the motivation for this, and demonstrate how the user could mimic the networkx behavior - assuming they have a small enough graph or large enough memory and patience.

**Describe alternatives you've considered**
We discussed creating a sparse result - which would certainly work for a variety of real-world graphs.  However, the user could also create that result themselves if they wanted with relative ease.

**Comment by afender** [comment]
Agreed with the proposal. Sounds like it is just a doc update then? If so maybe we can try and do it this release.

**Comment by BradReesWork** [comment]
Jaccard is slated to be rewritten using graph primitives and the new Network compatability module will address these
