### ISSUE TITLE
[BUG] ECG 0.12 CUDA error iinvalid value

### ISSUE THREAD

**Issue by geoHeil** [rapidsai/cugraph#744]
**Describe the bug**
cannot execute ECG example

**To Reproduce**
https://docs.rapids.ai/api/cugraph/stable/ for ECG has the following example:
```
import cudf
import cugraph

M = cudf.read_csv('path/to/karate.csv',
                      delimiter = ' ',
                      dtype=['int32', 'int32', 'float32'],
                      header=None)
sources = cudf.Series(M['0'])
destinations = cudf.Series(M['1'])
values = cudf.Series(M['2'])
G = cugraph.Graph()
G.add_edge_list(sources, destinations, values)
parts = cugraph.ecg(G)
```

fails with:

```
/home/at/heilerg/.conda/envs/phd2-graph-econ/lib/python3.7/site-packages/cugraph/structure/graph.py:191: UserWarning: add_edge_list will be deprecated in next release. Use from_cudf_edgelist instead
  Use from_cudf_edgelist instead')

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-4b59f30e695a> in <module>
     12 G = cugraph.Graph()
     13 G.add_edge_list(sources, destinations, values)
---> 14 parts = cugraph.ecg(G)

site-packages/cugraph/community/ecg.py in ecg(input_graph, min_weight, ensemble_size)
     61     """
     62 
---> 63     parts = ecg_wrapper.ecg(input_graph, min_weight, ensemble_size)
     64 
     65     return parts

cugraph/community/ecg_wrapper.pyx in cugraph.community.ecg_wrapper.ecg()

RuntimeError: CUDA error encountered at: /conda/conda-bld/libcugraph_1580841414814/work/cpp/src/converters/COOtoCSR.cuh:163: 1 cudaErrorInvalidValue invalid argument


```

**Expected behavior**
ECG to be comuted successfully

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] centos 7
 - Browser [e.g. chrome, safari] firefox developer edition
 - Version [e.g. 22] cuGraph: 0.12 (latest stable)

**Comment by BradReesWork** [comment]
@jwyles or @Iroy30 any insight into this problem?

**Comment by BradReesWork** [comment]
@geoHeil - are you using the latest nightly build or an older version?  I'm trying to see when a change might have slipped in

**Comment by Iroy30** [comment]
@geoHeil We are looking into this. Meanwhile you could try using float64 values/weights if that works for you.

**Comment by geoHeil** [comment]
As written, I am using the latest stable - as of now, this is 0.12. And Indeed, switching to int64 values is making it work just fine.

Interesting.

**Comment by geoHeil** [comment]
But when calling cugraph with my real data (regardless of int64/int32 is used) I get:

cugraph.ecg(G)
RuntimeError: extrema failed on 2nd step: cudaErrorInvalidValue: invalid argument

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-206f064064fa> in <module>
      1 # cudf_res = cugraph.ecg(G)
      2 
----> 3 cugraph.ecg(G)

~/.conda/envs/phd2-graph-econ/lib/python3.7/site-packages/cugraph/community/ecg.py in ecg(input_graph, min_weight, ensemble_size)
     61     """
     62 
---> 63     parts = ecg_wrapper.ecg(input_graph, min_weight, ensemble_size)
     64 
     65     return parts

cugraph/community/ecg_wrapper.pyx in cugraph.community.ecg_wrapper.ecg()

cugraph/structure/graph_wrapper.pyx in cugraph.structure.graph_wrapper.add_adj_list()

RuntimeError: extrema failed on 2nd step: cudaErrorInvalidValue: invalid argument

```

**Comment by BradReesWork** [comment]
We are working on getting the code updated to handle all the data types and not crash.

**Comment by ChuckHastings** [comment]
Regarding the 'extrema' error.  That it *probably* an issue with the range of values in your vertex ids.  I would suggest the following:
- Change the add_edge_list call to the new from_cudf_edgelist
- Set the renumber parameter to True

This will renumber your vertex identifiers into a dense range from 0..n-1 (where n is the number of unique vertex ids).  This makes the memory usage more efficient, and if your vertices have a wide range of values then it will keep some of the internal data structures into a size that will fit in GPU memory.

**Comment by ChuckHastings** [comment]
Working on a fix for your other problem that should get into the 0.13 release.  Let me know if renumbering fixes your other issue.  If not, I'll need some additional information to try and track that down.

**Comment by geoHeil** [comment]
I think renumbering would not help as I manually work with pandas categories. They are indexed from 0 to n-1

**Comment by ChuckHastings** [comment]
Can you either send me a data set that fails, or describe it in some detail (how many vertices, how many edges)?  Could you be running out of GPU memory?

**Comment by geoHeil** [comment]
I think renumbering would not help as I manually work with pandas categories. They are indexed from 0 to n-1

On my real data, I already use the `from_cudf_edgelist`

**Comment by geoHeil** [comment]
Unfortunately, I cannot send you the data. However:

```
G.number_of_vertices()  #16953465
G.number_of_edges() # 125228476

```

It is a P100. Usually it is pretty explicit with CUDA for OOM failures. I do not get one of these errors here.

**Comment by geoHeil** [comment]
But what I can confirm is that by setting `renumber=true`

```
out of memory on alloc request of 2,684,354,480 elements of size 1 = 2,684,354,480 bytes
terminate called after throwing an instance of 'std::runtime_error'
```
that I run OOM then.

**Comment by ChuckHastings** [comment]
I'm going to guess you have a memory issue that is perhaps not giving you a good error message.  A P100 has either 12GB or 16GB of GPU memory.

If I'm doing the memory calculation correctly...
1. 125228476 edges, with 64-bit integers and 64-bit double weights would take 1 GB of memory for the source, destination and weights in your input data frame (3 GB combined)
1. COO2CSR (which is where your ECG error is coming from) is going to allocate another 3GB combined for the output arrays, and another 4-5 GB of temporary space for constructing the CSR.

That's a total of 10-11 GB of GPU memory being used.  It would not surprise me if you're running out of memory in a place that isn't checked properly.
