### ISSUE TITLE
[BUG] benchmark script needs improvements

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#750]
1. The current version of the script symmetrizes directed graphs. This results in the wrong interpretation of the input and 2x slow down. We need to create a DiGraph for the directed inputs: https://github.com/rapidsai/cugraph/blob/c295218da4d3b8c9aa6da6bf3a8bab20c4bdf423/python/utils/run_benchmarks.py#L114

2. `add_edge_list` function is deprecated, `from_cudf_edgelist`  should be used instead:
https://github.com/rapidsai/cugraph/blob/c295218da4d3b8c9aa6da6bf3a8bab20c4bdf423/python/utils/run_benchmarks.py#L115

3. All the ETL steps (renumber, symmetrize, coo2csr) should have been called (and timed) prior to calling the analytics. If not, the analytics might trigger them and include their time in the reported solver time by mistake.

**Comment by afender** [comment]
+ @rlratzel I think you addressed most of it already?

**Comment by rlratzel** [comment]
>     * @rlratzel I think you addressed most of it already?
Yes I believe so.  I can reopen this if I discover something is still missing.
