### ISSUE TITLE
[QST]# edges increase for undirected graph

### ISSUE THREAD

**Issue by geoHeil** [rapidsai/cugraph#757]
It seems strange to me, that the number of edges varies between directed and undirected graphs and especially, that the number of edges is increased for an undirected graph. Could it be that there is a bug?
![image](https://user-images.githubusercontent.com/1694964/76704340-9eb73f80-66d8-11ea-93da-82aa1450aff2.png)

**Comment by Iroy30** [comment]
@geoHeil I assume you are using cugraph version 0.12? The reason for increase is because in 0.12 the number of edges is calculated as the number of directed edges. This has already been updated in 0.13

**Comment by geoHeil** [comment]
exactly.
