### ISSUE TITLE
[BUG] Running python tests requires placing datasets under /datasets

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#79]
Many developers may not have write access privilege to create /datasets, but this directory path is hardcoded.

**Comment by afender** [comment]
Closing as duplicate of #65

**Comment by BradReesWork** [comment]
We are making the assumption that a user has  permissions on their server, which might not always be the case.  I am moving this to v0.7 as one of the first things to be fixed since it is not cause the system to crash

**Comment by seunghwak** [comment]
If we can agree on a right strategy to fix this, actually fixing this may not be very hard... I am thinking about overriding the default path (/datasets) if the environment variable is set (e.g. CUGRAPH_TEST_DATASET_PATH). Maybe a harder thing is to enforce some consistency across Rapids projects.

**Comment by afender** [comment]
closed by #203
