### ISSUE TITLE
[QST] How do I debug CUDA methods in cugraph? IDE integration with Eclipse / VScode / CLion

### ISSUE THREAD

**Issue by df8** [rapidsai/cugraph#794]
Dear cugraph community!

I would like to contribute to cugraph by developing a few graph algorithms in CUDA. I prefer not to write code in a vanilla notepad but rather in a sophisticated IDE such as Eclipse, Visual Studio Code or JetBrains CLion. IDEs offer visually appealing debugging, build configurations, code autocomplete and some other neat features. Unfortunately there is no instruction on how to set up the development environment specifically for cugraph. I followed the "Build from Source" instructions and successfully compiled libcugraph. The instruction contains a few shell commands which is fine for build tasks, but what about writing code?

**Can you, experienced cugraph devs, please share how your development setup looks like?** I am not biased, hence would not mind using any IDE you suggest, as long as it debugs and does not cost a fortune.
 
Do you use Debuggers? If so, how? Are you writing your CUDA kernels in an empty project first and then integrate it into cugraph? How do you set up "continuous builds" in order for the build to skip unchanged objects during compilation?

- I have successfully used Eclipse with the "Nvidia Nsight" and "CDT" plugins for other CUDA projects. However I wasn't able to make Eclipse compile and debug _cugraph_ properly. Many import commands in C++ were marked as missing libraries even though I did set up the include directories correctly. 
- JetBrains CLion officially supports CUDA in the 2020.x beta version. With cugraph the IDE detects the CMake scripts and runs cmake without errors, however the `make -j` step fails and hence I cannot run any tests.

Ideally `CONTRIBUTING.md` would be extended by a section on how to set up Eclipse or NVIDIA Nsight, with focus on having a C++ project, a Cython project and a Python project sitting side by side in one directory.

I'm running Ubuntu 18.10 64 bit.

Looking forward to your help :)

**Comment by BradReesWork** [comment]
@df8   there is no one perffered environment over another.  I use NSight when I am on a machine with GPUs and VSCode for remote development when on a laptop remoting into a workstation with GPUs.  NSight does have some nice performance tool tied in.  

I will take you suggestion and update the CONTRIBUTING.md doc to include a section on development environments.

For CI:  When you submit a PR it is run through our CI system.  If you specify [skip-ci] then the code is built.  This is typically used with the Work In Process  [WIP] tag.  Once everything is ready for compile and test, the drop the other tags and use [REVIEW]  and code reviers will dive in and provide feedback.

**Comment by afender** [comment]
**IDE**
I did a config file to automating build and test cuGraph in VSCode https://github.com/afender/cugraph-vscode
After using Sublime for years I find VScode is pretty good especially for writing code remotely. Several people like it on the team.

**Debug**
I find `cuda-memcheck` very helpful and it does not require recompiling.
https://docs.nvidia.com/cuda/cuda-memcheck/index.html

A debug launch can also be enabled in VS Code with something similar to
https://github.com/harrism/cudf-vscode/blob/master/.vscode/launch.json . 
It is actually on my to-do list on https://github.com/afender/cugraph-vscode but didn't get a chance to add it so far.
Also a good thing to add in CONTRIBUTING.md for sure.

**Comment by kaatish** [comment]
> IDEs offer visually appealing debugging, build configurations, code autocomplete and some other neat features.

I do not use an IDE. I use neovim with plugins for code exploration/auto completion such as

- [FZF](https://github.com/junegunn/fzf)(Fuzzy finder - tags, files, syntax)
- [Rg](https://github.com/BurntSushi/ripgrep) (Finding code from the command line)
- [ccls](https://github.com/MaskRay/ccls/wiki) (Language server for command completion. Works with [nvim-lsp](https://github.com/neovim/nvim-lsp))

That can make your editing really workable. For debugging unfortunately I use cuda-gdb from the command line but I hope to use nsight debugging at some point.

**Comment by BradReesWork** [comment]
@df8 I hope you can see that there is not a standard development environment.  I will be updating out documentation to  list some of the environments that we do use and links to helpful tools and plug-ins

**Comment by df8** [comment]
Thank you for sharing your options. I'm going to try out the VScode configs mentioned by @afender and give it another shot with Nsight with the documentation by @BradReesWork.

Yesterday, I also had a small breakthrough with Jetbrains CLion. The internal CMake parser picked up the CMake scripts and I was able to build and to debug line by line the test case for Betweenness Centrality in CLion. Debugger worked both in code managed by cugraph and by gunrock. I may add an instruction how to get started with cugraph in CLion, too.
