### ISSUE TITLE
[BUG][NV] CMakeLists.txt structure inconsistent with cuDF, cuML

### ISSUE THREAD

**Issue by mt-jones** [rapidsai/cugraph#8]
* The test infrastructure in `cugraph` places a `CMakeLists.txt` in every test directory.
* Gunrock is added as an external project, and it cloned to a location along-side `cugraph` rather than in a directory inside of `cugraph/build`, meaning deleting `build` does not restore the the compiled project to its initial state
* Locations for libraries like `libcudf.so` are hard-coded, rather than searched in system locations and Conda locations, etc.

**Comment by rgsl888** [comment]
I have posted a PR for this.
