### ISSUE TITLE
[FEA] target to source shortest path

### ISSUE THREAD

**Issue by aerdem4** [rapidsai/cugraph#806]
**Is your feature request related to a problem? Please describe.**
cugraph sssp implementation only takes source as input and calculates shortest path to all other nodes. I only need shortest path to a target node.

**Describe the solution you'd like**
I would like to have shortest_path_length(g, source=a, target=b) functionality similar to networkx.

**Comment by BradReesWork** [comment]
@aerdem4 getting the shortest path to just a single target vertex is just a matter of filtering the returned results down to the single path you want.  

There is a utility function to do that:  get_traversed_path(df, id):

 df = cugraph.sssp(G, start_id)
path = cugraph.util.get_traversed_path(df, target):

**Comment by aerdem4** [comment]
@BradReesWork but doesn't it do a redundant work then? Or did you suggest it as a work around?

**Comment by BradReesWork** [comment]
@aerdem4 The amount of time to do an all path SSSP is the same of a directed Source to Destination.  We could just make an API that hides that fact

**Comment by BradReesWork** [comment]
Adding the creation of a new function to the roadmap

**Comment by jsnns** [comment]
I want to start working on this. @BradReesWork, can you assign it to me?

**Comment by jpurviance** [comment]
I've been playing around with this. 

From looking at the [networkx docs](https://networkx.org/documentation/networkx-1.10/reference/generated/networkx.algorithms.shortest_paths.generic.shortest_path_length.html#networkx.algorithms.shortest_paths.generic.shortest_path_length), the api for this supports more than what was requested. How important is it for the api to match exactly. Is the goal to support duck typing as much as possible?
