### ISSUE TITLE
Failed in spectralModularityMaximizationClustering

### ISSUE THREAD

**Issue by YukeWang96** [rapidsai/cugraph#828]
I successfully make a call 
 
> **`spectralBalancedCutClustering(graph, nparts)`**

However, when I am using the same parameters to make the function call to

>  **` spectralModularityMaximizationClustering(graph, parts)`**

`cugraph `always returns me the ERROR like this.

```
File "cugraph/community/spectral_clustering_wrapper.pyx", line 137, in cugraph.community.spectral_clustering_wrapper.spectralModularityMaximizationClustering

RuntimeError: CUGRAPH failure at: /conda/conda-bld/libcugraph_1585675134832/work/cpp/src/community/nvgraph_gdf.cu:128: Invalid API parameter: edge data is NULL
```
Is there anyone can help me with this?
Thanks!

**Comment by BradReesWork** [comment]
@YukeWang96 we are looking into the issue and will have a response as quick as possible.
Do you have a code sample that you can share?

**Comment by BradReesWork** [comment]
@YukeWang96 the error indicates that your graph does not have any edge weights set.  Can you share the code for reading data and building the graph?

**Comment by YukeWang96** [comment]
ok, I see, I just passing the graph with no weight and only edge list. 
Thanks a lot!
