### ISSUE TITLE
[BUG] Python tests take too long

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#83]
Python tests take more than 30 min to run. This is blocking the testing platform for too long. Users may also think that something is not working correctly. 

We should identify what takes so long (afaik, most of the time is spent in NextworkX to get the reference result) and try to reduce the total time as much as possible.

**Comment by dantegd** [comment]
If reducing the problem sizes for speeding up networkx is not an option, why not precompute the expected results and then compare to this saved results to skip networkx long processing time?

**Comment by afender** [comment]
The problem sizes look quite small already but we can consider reducing it further. As long as it is large enough to run on multiple SMs that's good enough. 

I agree that, for tests where Nx will be identified as the bottleneck, we can generate and save some golden data. We already do that for several internal C++ tests actually.

**Comment by jwyles** [comment]
Please assign this to me. I am going to start working on it.
Plan: Swap out dblp.mtx with a smaller (but large enough to be on multiple SM) matrix in the tests. This will reduce the NetworkX overhead to a reasonable amount. Have all tests that compare series first copy data from the GPU to a numpy array for faster compares.
