### ISSUE TITLE
How to find all simple cycles in CuGraph?

### ISSUE THREAD

**Issue by shekhawatmeenu18** [rapidsai/cugraph#837]
I need to find all simple cycles in a network but I didn't see any function or package to do so in Rapids. A similar thing is available in Python under the NetworkX package.

Please help me to find the same in cugraph.

**Comment by afender** [comment]
You are correct that currently, cuGraph does not have a feature to enumerate all cycles (or elementary circuits). It is something that will take some time to code but it should be possible. There are a couple of references on accelerating this problem with GPUs in the literature.

**Comment by shekhawatmeenu18** [comment]
Thanks @afender for the reply. Could you share any references for me to look at to implement these in GPU? Or if you know any possible workaround for the same.

**Comment by afender** [comment]
The only thing I can think of as a workaround is for cycles of size 3. In this case, you can count them using cuGraph's Triangle Counting algorithm. 

The paper "Detecting Cycles in Graphs Using Parallel Capabilities of GPU" looks relevant: https://link.springer.com/chapter/10.1007/978-3-642-22027-2_17

Your request has been added to the backlog and we will be monitoring interest for it. 
We also love when people want to get involved, and if you want to add it to cuGraph, we fully encourage that. Here is more information on how to contribute:  https://github.com/rapidsai/cugraph/blob/branch-0.14/CONTRIBUTING.md
