### ISSUE TITLE
[FEA] Build infrastructure to use RAFT

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#839]
The goal is to update cugraph infra to use raft
https://github.com/rapidsai/raft

like what Dante did in cuML :
https://github.com/rapidsai/cuml/pull/2125

**Comment by dantegd** [comment]
@afender I can definitely help creating the PR here, was waiting for the review process to be done on cuML. Buf if you want someone else to pick it up to be familiar with the process that would also be fine.

**Comment by afender** [comment]
Closed by #881
