### ISSUE TITLE
[BUG] Two different approaches to import submodules

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#84]
rmm is checked out before build (git submodule update --init --remote --recursive) while gunrock is checked out during build (in CMakeLists.txt). This can be confusing to some people and also inconsistent with other RAPIDS projects (they checkout submodules before build). We need to fix the code base to checkout gunrock before build (git submodule update --init --remote --recursive) to be consistent.

**Comment by seunghwak** [comment]
Better leave this as it is. Based on slack discussion, I think this is the direction cudf is moving.

For rmm (or other RAPIDS projects we are developing in lock-steps), cugraph downloads it as a submodule and cugraph should be maintained to be compatible with the most recent version.

For non-RAPIDS modules, download those in cmake and cugraph already does this, so we'd better note change.

**Comment by BradReesWork** [comment]
resolution is to leave code as is
