### ISSUE TITLE
[BUG] build fail

### ISSUE THREAD

**Issue by dheerajsreedhar** [rapidsai/cugraph#856]
I get this build error while building from source : branch : branch-0.14

..envs/cugraph_dev/lib/libcudf.so: undefined reference to `NVCategory::get_values(int*, bool)'
..envs/cugraph_dev/lib/libcudf.so: undefined reference to `NVCategory::create_from_categories(std::vector<NVCategory*, std::allocator<NVCategory*> >&)'
..envs/cugraph_dev/lib/libcudf.so: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.10.1'

Following the same procedure as listed in the git
using gcc v 6.2 and cuda - 10.1

**Comment by BradReesWork** [comment]
@dheerajsreedhar  Did you also pull down, or build, the latest cuDF?

**Comment by seunghwak** [comment]
Those are functions in libNVCategory.so and libnvrtc.so, and in ../envs/cugraph_dev/lib could you type ldd libcudf.so and share the output?

**Comment by dheerajsreedhar** [comment]
ldd libcudf.so output :
        linux-vdso.so.1 =>  (0x00007ffc408c2000)
        libNVCategory.so => ../envs/cugraph_dev/lib/././libNVCategory.so (0x00007f577af0e000)
        libNVStrings.so => ../envs/cugraph_dev/lib/././libNVStrings.so (0x00007f5775a45000)
        librmm.so => ../envs/cugraph_dev/lib/././librmm.so (0x00007f57757c3000)
        libnvrtc.so.10.1 => ../envs/cugraph_dev/lib/././libnvrtc.so.10.1 (0x00007f5774052000)
        libcudart.so.10.1 => ../envs/cugraph_dev/lib/././libcudart.so.10.1 (0x00007f5773dd3000)
        libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f5772bcd000)
        libz.so.1 => ../envs/cugraph_dev/lib/././libz.so.1 (0x00007f57ae73c000)
        libboost_filesystem.so.1.70.0 => ../envs/cugraph_dev/lib/././libboost_filesystem.so.1.70.0 (0x00007f57ae71b000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f57729b1000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f57727ad000)
        libstdc++.so.6 => ../envs/cugraph_dev/lib/././libstdc++.so.6 (0x00007f57ae5a6000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f57724ab000)
        libgcc_s.so.1 => ../envs/cugraph_dev/lib/././libgcc_s.so.1 (0x00007f57ae592000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f57720dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f57ae549000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f5771ed5000)
../ before /envs/ is the miniconda location 

@BradReesWork , i did not pull the latest cuDF it is from conda install cudf=0.14.*

**Comment by seunghwak** [comment]
OK, it seems like libNVCategory.so and libnvrtc.so are properly installed, and could you also run ```make VERBOSE=1``` and post the output?

**Comment by dheerajsreedhar** [comment]
@seunghwak 
[outfile.txt](https://github.com/rapidsai/cugraph/files/4609117/outfile.txt)

**Comment by seunghwak** [comment]
```
/usr/bin/ld: warning: libNVCategory.so, needed by PWD/scratch/miniconda3_x86/envs/cugraph_dev/lib/libcudf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libNVStrings.so, needed by PWD/scratch/miniconda3_x86/envs/cugraph_dev/lib/libcudf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnvrtc.so.10.1, needed by PWD/scratch/miniconda3_x86/envs/cugraph_dev/lib/libcudf.so, not found (try using -rpath or -rpath-link)
```
The above in the outfile.txt suggests that libNVCategory.so, libNVStrings.so, and libnvrtc.so.10.1 are not found and this matches with the build error.

Could you try a few things?

1) Could you double check your conda environment is activated? (i.e. conda activate cugraph_dev)
2) Could you print your LD_LIBRARY_PATH and add the path to the libraries above. (i.e. echo $LD_LIBRARY_PATH then export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:PWD/scratch/miniconda3_x86/envs/cugraph_dev/lib)
