### ISSUE TITLE
[BUG] BC crashes / CUDA error 700: an illegal memory access was encountered

### ISSUE THREAD

**Issue by df8** [rapidsai/cugraph#857]
**Describe the bug**
Executing Betweenness centrality on a medium sized graph leads to crash of the jupyter kernel.

**To Reproduce**
1. Download the dataset file `facebook_combined.txt` from [this repo](https://github.com/Adam27X/hybrid_BC/blob/master/graphs/facebook_combined.txt). Size: 4039 nodes, 88234 edges.
1. Pull, compile and install the newest commit of cugraph according to the instruction in SOURCEBUILD.md
2. Activate the conda environment where cugraph is installed. `conda activate cugraph_dev`
3. Install `jupyter-notebook` in conda and launch `jupyter-notebook` in terminal. Keep this terminal instance running.
4. In browser, create a new blank jupyter notebook with the code snippet provided below.
5. Run this snippet. There is a python error:
`RuntimeError: CUDA error encountered at: /home/user/repos/cugraph/cpp/src/centrality/betweenness_centrality.cu:85: 700 cudaErrorIllegalAddress an illegal memory access was encountered`.
6. When I run the same python snippet a second time, my jupyter-notebook crashes with a flood of the following lines repeating over and over in terminal: 

> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_enactor.cuh, 606 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 817 @ gpu 0] data_slices[0] cudaMemcpy H2D failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_problem.cuh, 425 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 817 @ gpu 0] nodes_queued cudaMemcpy H2D failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_types.cuh, 149 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_types.cuh, 309 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 427 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_enactor.cuh, 569 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> (CUDA error 700 @ GPU 0: an illegal memory access was encountered
> (CUDA error 700 @ GPU 0: an illegal memory access was encountered
> (CUDA error 700 @ GPU 0: an illegal memory access was encountered
> (CUDA error 700 @ GPU 0: an illegal memory access was encountered

> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_enactor.cuh, 606 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 835 @ gpu 0] bc_values cudaMemcpy D2H failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_problem.cuh, 319 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] bc::frontier[0,0]::queues[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/frontier.cuh, 185 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_types.cuh, 291 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 250 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_enactor.cuh, 491 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_problem.cuh, 284 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] labels cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_problem.cuh, 122 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/bc/bc_problem.cuh, 284 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] row_offsets cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/graph/csr.cuh, 108 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [/home/user/repos/cugraph/cpp/build/cugunrock/src/cugunrock/gunrock/app/app_base.cuh, 134 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)

**Code**
```
import cugraph
import cudf
datafile = r"/home/user/repos/hybrid_BC/graphs/facebook_combined.txt" #location of the dataset
gdf = cudf.read_csv(datafile, delimiter='\t', names=['src', 'dst'], dtype=['int32', 'int32'] )
G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='src', destination='dst')
results = cugraph.betweenness_centrality(G, normalized=False)
```

**Expected behavior**
BC should run and return the centrality scores for each vertex. 

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Firefox 76
 - Python: 3.7
 - CUDA / GPU: sm61, GTX 1050 Mobile in a Lenovo consumer laptop
 - deviceQuery:
```
Device 0: "GeForce GTX 1050"
  CUDA Driver Version / Runtime Version          10.2 / 10.1
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 4042 MBytes (4238737408 bytes)
  ( 5) Multiprocessors, (128) CUDA Cores/MP:     640 CUDA Cores
  GPU Max Clock rate:                            1493 MHz (1.49 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 byteso
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.1, NumDevs = 1
Result = PASS
```

**Additional context**
In my tests with significantly smaller datasets like `datasets/dolphins.csv` betweenness_centrality() works fine. NetworkX also handles the `facebook_combined` dataset just fine.

Thank you in advance!

**Comment by afender** [comment]
Thanks for letting us know. BC is about to get a massive upgrade in the next few days. There are good chances that your issue will be addressed as part of it.

Here is the new BC PR currently being reviewed : 
https://github.com/rapidsai/cugraph/pull/817

**Comment by xcadet** [comment]
Thanks for letting us know, the upcoming BC update seems to be working fine on your dataset.

**Comment by df8** [comment]
Great, thank you for your response! Looking forward to test the update.

**Comment by afender** [comment]
Hi @df8, the new BC (#817) has been merged! It should be much faster and it comes with new features like approximating betweenness centrality from a sample of seeds :tada:  
Let us know if this addresses the problem you saw earlier. 

We are actively working on Edge BC #885 as well.

**Comment by df8** [comment]
Thank you very much for your work! Impressive results and an enormous performance upgrade. I quickly compared the numeric results of BC from NetworkX and your new implementation and there is barely any difference (mean squared error is at incredible 1e-10)
I'm closing my issue and looking forward to hack around with your implementation. Great job!
