### ISSUE TITLE
[FEA] Add new test data to CI

### ISSUE THREAD

**Issue by jwyles** [rapidsai/cugraph#86]
**Is your feature request related to a problem? Please describe.**
This is in relation to Issue #83 to make tests run faster we need a new dataset which is large enough to require more than a single SM on the GPU but small enough to not take too long for NetworkX to process. 

**Describe the solution you'd like**
Add netscience.mtx to /datasets/networks/netscience.mtx. MTX file is available at: https://sparse.tamu.edu/Newman/netscience

**Comment by afender** [comment]
@raydouglass can you please add this file to the CI platform or let us know how we can do it?

**Comment by raydouglass** [comment]
Done
