### ISSUE TITLE
[ENH] Get rid of deprecated CUDA library calls 

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#869]
CuSparse is removing a lot of functions in the next major release  https://docs.nvidia.com/cuda/cusparse/index.html. 
cuGraph should be updated in order to build with the next major CUDA Toolkit version.

Many calls are related to spectral clustering which should be refactored and moved into RAFT #868

**Comment by aschaffer** [comment]
I can switch the `SpMv` mechanism to use `raft::sparse_matrix_t::mv()`, which _should_ also cover CUDA 11, but I need a `raft::handle_t` for that. Can I create one on-the-fly in the _client_ code (i.e., `cugraph` code that calls `SpMv`, formerly `CusparseCsrMV`) ? Or, else, where do I get the raft handle from?

**Comment by aschaffer** [comment]
Also, I assume `CusparseCsrMV` is to be removed completely, correct?

**Comment by aschaffer** [comment]
It looks like the only remaining dependency is in `src/utilities/spmv_1D.cu(h)` via `src/utilities/cusparse_helper.h(cu)` on `cusparseCsrmvEx(...)`. But that does *not* seem to be deprecated. In fact, I'm not sure if I should touch that code at all. No other dependencies remain: certainly no other `cusparse` or `cublas` calls. So, then should I replace/remove the above code, and if so with what? Some clarifications would help. Thanks in advance.

**Comment by aschaffer** [comment]
Relevant PRs:

1. https://github.com/rapidsai/cugraph/pull/1019
2. https://github.com/rapidsai/raft/pull/41 (merged)

**Comment by aschaffer** [comment]
Completed. Closing.
