### ISSUE TITLE
[BUG] Improve testing  on edge list input

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#92]
Currently, several algorithms isolate the solver to test by directly running the algorithm on the `adj_list` where this `adj_list` is generated from networkX. 

We want to add tests where the input graph object contains only the `edge_list` and let the algorithm API entry do the conversion automatically. 

The following tests need to be upgraded :
- bfs
- jaccard
- louvain
- spectral clustering
- weighted jaccard

Already properly tested:
- Pagerank
- SSSP

**Comment by seunghwak** [comment]
I have a question about the purpose of this update.

So pros:
Users do not need to convert the input graph in the edge list format (COO) to the adjacency list format (CSR).

cons:
cuGraph library functions (e.g. cpdef sssp(G, source) in sssp_wrapper.pyx) implicitly modify G by adding an adjacency list and this increases the GPU memory footprint as well (now G holds both an edge list and an adjacency list).

It the pros really bigger than the cons or am I missing something?

**Comment by afender** [comment]
Absolutely.
Users are expected to provide an edge list most of the time, this is why we need to test it even if we already have the adjacency list test. Imagine that the function call to the conversion is broken for a particular algorithm, we wouldn't be able to catch it if we don't have a test for it.

**Comment by seunghwak** [comment]
So we need to test both edge list & adjacency list cases?

So in addition to adding edge list test cases to bfs, jaccard, ... we need to add adjacency list test cases to PageRank and sssp as well, correct?

**Comment by seunghwak** [comment]
If we provide only edge list test cases, users taking these as examples may consider these cases as more desirable (for really large graphs, converting a graph in the CPU memory and providing in the adjacency list format to the cugraph function is more desirable to fit the graph to the GPU memory).

**Comment by seunghwak** [comment]
OK, I think I got the point... converting in CPU can be slow as well... so this trade-offs converting time and GPU memory footprint... I can replace adjacency list test cases with edge list test cases or can provide both... Let me know which is more desirable.

**Comment by afender** [comment]
No need to remove existing tests or add adjacency list tests.
This task is about making sure that the most common use case (edge list) is properly covered.

**Comment by BradReesWork** [comment]
here is sample code from the cuGraph notebooks

datafile='../data/networks/karate-data.csv'
# Read the data file
cols = ["src", "dst"]

dtypes = OrderedDict([
        ("src", "int32"), 
        ("dst", "int32")
        ])

gdf = cudf.read_csv(datafile, names=cols, delimiter='\t', dtype=list(dtypes.values()) )
# create a Graph 
G1 = cugraph.Graph()
G1.add_edge_list(gdf["src"], gdf["dst"])

# Call an algorithm
df1 = cugraph.<xxx>(G1)

**Comment by jwyles** [comment]
I am starting on this now. @seunghwak let me know if you have any work started on this.

**Comment by seunghwak** [comment]
I haven't touched this problem, yet.

**Comment by BradReesWork** [comment]
closed by PR #137
