### ISSUE TITLE
[ENH] doc whether renumber preserves edge order

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cugraph#922]
**Describe the solution you'd like**
Docs clarify whether renumbering preserves edge orders. 

(Ideally they do, because this simplifies then plugging in different edge weights without manually swizzling.)

**Additional context**
Encountered in various `renumber` calls in 0.13, e.g.: 
https://docs.rapids.ai/api/cugraph/stable/api.html?highlight=renumber#cugraph.structure.renumber.renumber_from_cudf

**Comment by ChuckHastings** [comment]
FYI - it does preserve the ordering.

I am updating this code in 0.15, I will add this to the documentation.

**Comment by ChuckHastings** [comment]
Let me change my answer.

In version 0.14 and prior single column integer renumbering preserved ordering.  Single column non-integer and Multi column renumbering did not guarantee that the order was preserved.

The new renumbering in 0.15 does not guarantee to preserve ordering of the input.  This is documented in the new python API methods.

If ordering matters, you can add an extra column to the input Dataframe numbering the rows.  The output of the 0.15 numbering is always a data frame and preserves the contents of the original Dataframe that aren't part of the source or destination definitions.  You can then use sort_values on the extra column you added to reconstruct the original order.

I considered making that part of the implementation, but sorting is expensive and in most cases unnecessary.

**Comment by lmeyerov** [comment]
Maybe make `sorted=False` a parameter?

cc @kkraus14  as you felt the pain of tickets stemming from similar design decisions here in cudf

My reasoning:
* A lot of usage will be sorted, so make typical cases easy: have df, use cugraph to enrich, get back df, continue
* By making an arg, makes it way easier to optimize later without breaking user code
* I'd prefer a default of `sorted=True` -- let people go faster via opt-in, but safe by default, as what's annoying-level for us is horrible for others. but i'm not spending my request points on this :)

**Comment by ChuckHastings** [comment]
Makes sense.  I will evaluate the mechanics of doing this and update the PR accordingly.

**Comment by lmeyerov** [comment]
RE:Notebook, just had some fun:

```
import cudf, cugraph, graphistry

#free account @ https://www.graphistry.com/get-started
graphistry.register(api=3, protocol='https', server='hub.graphistry.com', username='leotest', password='accountaccount')

n = 100
e = cudf.DataFrame({
    's': range(n), 
    'd':  [(x+1) % n for x in range(n)], 
    'w': cudf.Series([x/100 for x in range(n)], dtype='float32')
})
G = cugraph.from_cudf_edgelist(e, source='s', destination='d', edge_attr='w')
graphistry\
    .edges(G.view_edge_list())\
    .bind(source='src', destination='dst', edge_weight='weights')\
    .settings(url_params={'edgeInfluence': 3})\
    .plot()
```
