### ISSUE TITLE
[FEA]  Build cuGraph documentation

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#93]
Should we have automated builds of cuGraph's documentation (ie. the `docs` directory)?

That would allow checking that the documentation is building properly and keep https://cugraph.readthedocs.io up-to-date.

**Comment by raydouglass** [comment]
cc @randerzander

**Comment by BradReesWork** [comment]
we should have automated builds of the documentation.  The main page has a link to the most recent doc which currently points to:  https://cugraph.readthedocs.io/en/latest/ - 404 error

**Comment by BradReesWork** [comment]
this is being tracked by OPS as https://github.com/rapidsai/ops/issues/54
