### ISSUE TITLE
[BUG] module 'cugraph' has no attribute 'device_of_gpu_pointer'

### ISSUE THREAD

**Issue by tjwkfla123** [rapidsai/cugraph#949]
**Describe the bug**
I tried to build and install rapidsai packages through source codes, and run distributed pagerank with GPUs. For the pagerank, I implemented several versions based on the doc, and also tried to run the example apap of the repository:/cugraph/python/cugraph/tests/dask/test_karate_csv.py

However, I got the error with the msg "module 'cugraph' has no attribute 'device_of_gpu_pointer'"

I suspected my installation and so, I tried to install through conda and test it again.
(https://rapids.ai/start.html)
I tested 0.14 and 0.15 full packages of both stable and nightly versions.
I still got that errors. I am using python 3.7, and cuda 10.2.

It seems like device_of_gpu_pointer() was removed between 0.13 and 0.14. 
But, the dask still tries to call this function.
Could you give any instructions on this issue?

**To Reproduce**
1. Go to $CUGRAPH_HOME/python/cugraph/tests/dask/test_karate_csv.py
2. Run it with multiple GPUs (I tried to use 4 GPUs)
3. See error

**Expected behavior**
Got pageranks for each nodes without error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/64513607/84729275-e90abf80-af58-11ea-9460-6194dbdc0d72.png)
![image](https://user-images.githubusercontent.com/64513607/84729291-f6c04500-af58-11ea-82de-023cf8878ff7.png)
![image](https://user-images.githubusercontent.com/64513607/84729328-0b9cd880-af59-11ea-83f2-7d1b70cd910b.png)
** Note that the red marked codes are the results of cugraph/dask/pagerank/pagerank.py:66, who_has.values().

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: bash shell
 - Version: cugraph/cudf 0.14, python 3.7, cuda 10.2

**Comment by afender** [comment]
Hi, 

Thanks for your feedback! 

The single-node multi-GPU Pagerank implementation has been deprecated during 0.14 due to software incompatibilities. 
Multi-GPU Pagerank remains one of our top priorities. In fact, we are actively working on an enhanced **multi-node** PageRank (work in progress in PRs #944 and #947). I'd recommend keeping 0.13 release for a couple more weeks before upgrading to the multi-node version from 0.15 nightly.

**Comment by tjwkfla123** [comment]
Thank you for your explanation.
I will use 0.13 release until you release the new version. You can freely close the issue.
