### ISSUE TITLE
[ENH] Use RAFT error handling mechanism

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#951]
**Describe the solution you'd like**
RAFT error handling macros are updated (https://github.com/rapidsai/raft/pull/15). We need to use this instead of redefining our own (our CUGRAPH_EXPECTS and CUGRAPH_FAIL need to be updated to use the RAFT mechanism).

**Comment by afender** [comment]
So should we just use RAFT_EXPECTS/RAFT_FAIL until we have a use case for a cugraph specific error macros? 
We will just keep reconciling them otherwise. 
IIRC the only difference is the "raft" vs "cugraph" string in the error message

**Comment by afender** [comment]
Let's also upgrade the RAFT git tag in the cmake to get the latest RAFT version that contains rapidsai/raft#15

**Comment by afender** [comment]
And there are many redefined warnings (CUDA_TRY, CUDA_CHECK, THROW). They need to be deleted from cuGraph

**Comment by seunghwak** [comment]
> So should we just use RAFT_EXPECTS/RAFT_FAIL until we have a use case for cugraph specific error macros?
> We will just keep reconciling them otherwise.
> IIRC the only difference is the "raft" vs "cugraph" string in the error message

CUGRAPH_EXPECTS(FAIL) will throw cugraph::logic_error while RAFT_EXPECTS(FAIL) will throw raft::logic_error in addition to the difference in error message.

And cuDF uses CUDF_EXPECTS (cuML currently uses ASSERT but I guess they will switch to CUML_EXPECTS) and I think we'd better use CUGRAPH_EXPECTS(FAIL) and use this for now.

**Comment by seunghwak** [comment]
I assigned this to myself. This will be a quick fix.
