### ISSUE TITLE
[BUG] Bottom-up BFS on Volta appears to have issues

### ISSUE THREAD

**Issue by pgera** [rapidsai/cugraph#960]
**Describe the bug**
Bottom-up BFS on Volta (V100 in my case) seems to be broken. It works as expected on Pascal. This issue is unrelated to the type support issue/pr. You should be able to reproduce this with current master using the included cpp tests.

While debugging, I have narrowed it down to some corruption in bottom_up_large_degree_kernel that causes some threads to exit in the middle of the kernel. There is no return statement in the kernel. So this should not happen. Each thread should reach the end of the kernel. 

**To Reproduce**
1. Add __syncthreads(); at the end of bottom_up_large_degree_kernel before the closing brace.
2. Trigger the bottom up flow. Note that current cugraph cpp tests do not test for bottom up. The cpp test file always passes a pointer to sp_counters. So bottom up is never tested. You need to pass a nullptr to sp_counters to trigger bottom up. Any of the included small graphs are fine for triggering the behaviour. karate.mtx works fine for this test.
3. On Volta, this hangs. On Pascal, it works fine.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.04, cuda 10.2, 418.126.02, 4.15.0-101-generic

**Comment by BradReesWork** [comment]
The BFS code is being completely refactored.  This issues is being put on hold until that work is completed in release 0.16, at which time it will be re-evaluated to see if the new version addresses the quastion

**Comment by BradReesWork** [comment]
closed by 1270
