### ISSUE TITLE
[BUG] Rename "master" branch.

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cugraph#965]
Decades from now, will history students wonder why an entire industry decided to rename a core part of its infrastructure, or will they wonder why it was named that way to begin with?

Let's rename the "master" branch.

rapidsai/cudf#5560

**Comment by mike-wendt** [comment]
As mentioned in rapidsai/cudf#5560 there is a coordinated effort for this that is still in progress. Once approved a new issue with steps for each repo will be created here and the necessary PRs for the transition in the next few weeks.
