### ISSUE TITLE
[ENH] Extend Jaccard and Overlap Coefficient to handle DiGraphs

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#973]
The Jaccard And Overlap Coefficent analytics should accept and process as-is DiGraphs.  

If the user wants the data processed as an undirected symmeterized graph, then it is easy enough to call the conversion function

**Comment by afender** [comment]
I think we should have a cugraph wide decision on what to do when DiGraph are passed to analytics that operates only on undirected graphs.

**Comment by BradReesWork** [comment]
This issue is being closed and the functionality pushed to the refactoring of Jaccard and Overlap for MNMG
