### ISSUE TITLE
[BUG] cugraph-style check fails

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#98]
`FAILED: flake8 style check;`
100+ errors and warnings in `cugraph/python/...`

See for instance: https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/WIP%2Fcugraph-prb%2Fcugraph-style/detail/cugraph-style/13/pipeline

**Comment by seunghwak** [comment]
Could you assign this to me? It will be much more productive to fix this before working on other issues assigned to me.
