### ISSUE TITLE
[BUG] BFS finds paths that do not exist

### ISSUE THREAD

**Issue by mnienow** [rapidsai/cugraph#982]
BFS finds paths that do not exist and path that is not relevant to the request

[Notebook to reproduce](https://github.com/mnienow/cugraph_tests/blob/master/BFS_Bug.ipynb)
Expected that in this case (on screenshot), the BFS will not find any paths, but:
![BFS bug](https://user-images.githubusercontent.com/46624207/86006021-0e4e0200-ba1e-11ea-8df6-106a031fdda9.jpg)

**Comment by afender** [comment]
Hi @mnienow, the problem causing this bug should be the same as the one described here:  https://github.com/rapidsai/cugraph/issues/981#issuecomment-651414822
#983 should have fixed it.
