### ISSUE TITLE
[QST] Number of iterations PageRank does to convergence

### ISSUE THREAD

**Issue by dkoutsou** [rapidsai/cugraph#986]
Hey everybody,

I built and installed cugraph and I am running the benchmarks. 
I run the command:
```pytest -v -s -k "pagerank"```
Here is my output:
```
------------------------------------------------------------------------------------------------- benchmark: 16 tests --------------------------------------------------------------------------------------------------
Name (time in ms)                                                                             Min                   Max                  Mean              StdDev            Outliers          GPU mem            Rounds
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_pagerank[ds=../datasets/csv/directed/cit-Patents.csv,mm=False,pa=True]              67.0418 (1.0)         68.5635 (1.0)         67.7290 (1.0)        0.4844 (2.54)          6;0  0      16
bench_pagerank[ds=../datasets/csv/directed/cit-Patents.csv,mm=True,pa=True]               67.2661 (1.00)        68.8220 (1.00)        67.9975 (1.00)       0.4254 (2.23)          4;0  0      14
bench_pagerank[ds=../datasets/csv/directed/cit-Patents.csv,mm=False,pa=False]             78.3745 (1.17)        79.7178 (1.16)        78.9080 (1.17)       0.4091 (2.15)          6;1  83,886,080      14
bench_pagerank[ds=../datasets/csv/directed/cit-Patents.csv,mm=True,pa=False]             125.1966 (1.87)       129.8017 (1.89)       127.7185 (1.89)       1.4693 (7.71)          2;0  134,217,728       9
bench_pagerank[ds=../datasets/csv/undirected/hollywood.csv,mm=False,pa=True]             278.7432 (4.16)       279.1541 (4.07)       278.9225 (4.12)       0.1977 (1.04)          1;0  0       4
bench_pagerank[ds=../datasets/csv/undirected/hollywood.csv,mm=True,pa=True]              279.2566 (4.17)       279.7883 (4.08)       279.5289 (4.13)       0.2461 (1.29)          2;0  0       4
bench_pagerank[ds=../datasets/csv/undirected/hollywood.csv,mm=False,pa=False]            300.9447 (4.49)       301.2933 (4.39)       301.1093 (4.45)       0.1905 (1.0)           0;0  31,457,280       4
bench_pagerank[ds=../datasets/csv/undirected/hollywood.csv,mm=True,pa=False]             430.3472 (6.42)       431.2199 (6.29)       430.8358 (6.36)       0.4456 (2.34)          1;0  134,217,728       3
bench_pagerank[ds=../datasets/csv/directed/soc-LiveJournal1.csv,mm=False,pa=True]        569.8313 (8.50)       570.3266 (8.32)       570.0201 (8.42)       0.2678 (1.41)          1;0  0       3
bench_pagerank[ds=../datasets/csv/directed/soc-LiveJournal1.csv,mm=True,pa=True]         570.3941 (8.51)       570.9039 (8.33)       570.5861 (8.42)       0.2772 (1.45)          1;0  0       3
bench_pagerank[ds=../datasets/csv/directed/soc-LiveJournal1.csv,mm=False,pa=False]       592.0562 (8.83)       595.9166 (8.69)       593.4068 (8.76)       2.1757 (11.42)         1;0  104,857,600       3
bench_pagerank[ds=../datasets/csv/directed/soc-LiveJournal1.csv,mm=True,pa=False]        703.7634 (10.50)      708.2587 (10.33)      705.4452 (10.42)      2.4520 (12.87)         1;0  165,675,008       3
bench_pagerank[ds=../datasets/csv/undirected/europe_osm.csv,mm=False,pa=True]            769.8207 (11.48)      779.1473 (11.36)      773.3208 (11.42)      5.0799 (26.66)         1;0  0       3
bench_pagerank[ds=../datasets/csv/undirected/europe_osm.csv,mm=True,pa=True]             771.6507 (11.51)      781.4870 (11.40)      774.9793 (11.44)      5.6364 (29.58)         1;0  0       3
bench_pagerank[ds=../datasets/csv/undirected/europe_osm.csv,mm=False,pa=False]           875.4707 (13.06)      877.3766 (12.80)      876.2067 (12.94)      1.0244 (5.38)          1;0  1,027,604,480       3
bench_pagerank[ds=../datasets/csv/undirected/europe_osm.csv,mm=True,pa=False]          1,464.6072 (21.85)    2,399.0647 (34.99)    2,008.5737 (29.66)    485.7661 (>1000.0)       1;0  1,080,033,280       3
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

However, I can't really explain the results. I didn't find anywhere where I can print the number of iterations PageRank needs to converge. Trying to randomly change max_iter everywhere I could find it in the source code, didn't change the execution time at all as well. Is there a way to see how many iterations PageRank does until convergence for every one of these benchmarks?

Thank you very much for your time!

**Comment by BradReesWork** [comment]
@dkoutsou  currently PageRank does not return the number of iterations.  You can set the _**max_iter**_ to stop PageRank at that point, and you will be notified that it did reach the iteration limit rather than converging.  

You can recompile the code from source with the VERBOSE flag turned on.  That might give you what you are looking for.  
Or make a request to add an option to return the number of iterations

**Comment by dkoutsou** [comment]
Thanks for your answer @BradReesWork !

> You can set the _**max_iter**_ to stop PageRank at that point, and you will be notified that it did reach the iteration limit rather than converging.
Although I have done this in all page rank related files meaning:
```
python/cugraph/link_analysis/pagerank.py
python/cugraph/link_analysis/pagerank_wrapper.pyx
```
I don't see any changes in the running time. Do I have to recompile?

Also in the `pytest.ini` file in `benchmarks` there is the `iterations` options. Is this the number of iterations for PageRank or am I looking at something else?

**Comment by ChuckHastings** [comment]
I think you have several options here:

1. Modify python/cugraph/tests/test_pagerank.py to specify max_iter in the call to:  `cugraph_call` and run pytest as you did above.  You can make multiple runs with different values of max_iter to converge on your solution.
1. Use the python code in test_pagerank.py (or one of the pagerank notebooks) to develop your own python script and modify max_iter in the call.  You could, in this case, for each test do some sort of binary search on max_iter to find the number of iterations where the convergence happens.
1. Modify the file cpp/src/link_analysis/pagerank.cu, before the line `#ifdef DEBUG` you can add the line: `#define DEBUG`.  Then compile the entire package (follow the instructions in SOURCEBUILD.md) and run the pytest pointing at the newly compiled code.  Add a -s to the pytest call and it will display the debug output.  This will tell you in one call how many iterations it takes to converge.

**Comment by dkoutsou** [comment]
Thanks for your answer @ChuckHastings 
1 didn't work as the time returned by pytest didn't change when changing the number of iterations.
2 did the trick in the end, although I don't understand why the package returns an error when the algorithm hasn't converged. Shouldn't it return a warning and output the running time anyway?
I didn't want to use 3 as I am doing some benchmark and I don't want to run in debug mode.

**Comment by ChuckHastings** [comment]
I'm glad you got what you needed.

Not sure why 1 didn't work, but I imagined 2 would be a better solution (less annoying to use).

I believe the intention of raising an exception is based on the following assumption:  If we return a warning and the partial answer when the algorithm doesn't converge,  *most* users will not check the return value and will use the result of the algorithm thinking that everything was fine.
