### ISSUE TITLE
[BUG] [CI Local] - Misleading README - Conda "solving environment" step fails

### ISSUE THREAD

**Issue by df8** [rapidsai/cugraph#994]
**Describe the bug**
I wanted to setup a fresh local CI environment on my machine, so I cloned the cugraph 0.15 branch with the newest commit as of writing this.

Then I followed this instruction: 
[https://github.com/rapidsai/cugraph/blob/branch-0.15/ci/local/README.md](https://github.com/rapidsai/cugraph/blob/branch-0.15/ci/local/README.md)

When I don't use the -i option and only run `bash build.sh -r ~/rapids/cugraph`, the environment defaults to the `"gpuci/rapidsai:0.15-cuda10.1-devel-ubuntu16.04-py3.7"` container and the entire CI runs perfectly fine and compiles the sources.

However, if I choose a custom container from this [page](https://hub.docker.com/r/gpuci/rapidsai-base/tags) as linked in the README, the conda environment fails to find all packages. 

And this is where I noticed a small difference between the default and the custom docker container:

While the README instruction directs me to this page:
[https://hub.docker.com/r/gpuci/rapidsai-base/tags](https://hub.docker.com/r/gpuci/rapidsai-base/tags)
The default container actually comes from this page (notice the missing "-base").
[https://hub.docker.com/r/gpuci/rapidsai/tags](https://hub.docker.com/r/gpuci/rapidsai/tags)

My guess is, the rapidsai-base images are not supposed to work for local CI, even though the example in README is explicitly using `rapidsai-base`.

As I was not aware of that, I used the following lines to try out different image versions:

- `bash build.sh -r ~/rapids/cugraph -i gpuci/rapidsai-base:cuda10.2-ubuntu16.04-gcc5-py3.7`
- `bash build.sh -r ~/rapids/cugraph -i gpuci/rapidsai-base:cuda10.2-ubuntu18.04-gcc7-py3.7`

These containers seem to boot correctly. Here is the `env` output for 16.04:
```
PARALLEL_LEVEL=4
HOSTNAME=ecfcc9cfd499
NVIDIA_REQUIRE_CUDA=cuda>=10.2 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419
TERM=xterm
CUDA_REL=10.2
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
OLDPWD=/rapids/cugraph
WORKSPACE=/rapids/cugraph
CUDA_HOME=/usr/local/cuda
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute,utility
GIT_DESCRIBE_TAG=v0.15.0a-448-g8f01380
PATH=/conda/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
CUDAHOSTCXX=/usr/bin/g++-5
PWD=/rapids/cugraph
MINOR_VERSION=0.15
CUDA_PKG_VERSION=10-2=10.2.89-1
CUDA_VERSION=10.2.89
CXX=/usr/bin/g++-5
HOME=/rapids/cugraph
SHLVL=2
NCCL_VERSION=2.5.6
DEBIAN_FRONTEND=noninteractive
CC=/usr/bin/gcc-5
_=/usr/bin/env
```

When Conda tries to load all packages, apparently there is a serious conflict, because even after 40 minutes there was still this looping animation while conda is trying to find compatible package versions:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
/ (keeps looping)
```
As I stumbled upon this, others may do too, so it would be helpful to fix the README. :) 
Thank you for looking into this!

**Expected behavior**
CI launches, downloads all conda dependencies, runs the unit tests and terminates.

**Environment overview**
Host system: Ubuntu 18.04, nvidia-driver 450.51.05, cuda-11.0, docker v19.03.12

**Comment by df8** [comment]
Addition:
Inside my CI container environment, the compilation stopped with an error and the terminal returned to the container shell. Now it would be nice to know the command for relaunching the tests. Please add some instruction to the README section "[Where The User is Dumped](https://github.com/rapidsai/cugraph/tree/branch-0.15/ci/local#where-the-user-is-dumped)" on **how to re-start the test suite from within the container terminal** after applying some code changes.

**Comment by BradReesWork** [comment]
@df8 sorry for the slow response,  I somehow missed this issue when it first came in.
Thank you for identifying the error and we are fixing the README
